### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by wuyangniubi** [open-mmlab/mmdetection3d#1013]
dear author,thanks for your great job!When I installed related tools and tried to run creat_data.py,I met this strange error and I don't know why.
`(open-mmlab) root@6176eab7a0d7577b936fb9cf:~/mmdetection3d# python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
Traceback (most recent call last):
  File "tools/create_data.py", line 11, in <module>
    from data_converter import kitti_converter as kitti
  File "/root/mmdetection3d/tools/data_converter/kitti_converter.py", line 8, in <module>
    from mmdet3d.core.bbox import box_np_ops
  File "/root/mmdetection3d/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/root/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 2, in <module>
    from mmcv.ops import nms_match
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv`
I'm sure I have installed mmcv by 'pip install mmcv-full'.I'm looking forward to any suggestion.Thanks!

**Comment by Tai-Wang** [comment]
Close due to inactivity.
