### ISSUE TITLE
Change kitti_pcd_data to my_pcd_data

### ISSUE THREAD

**Issue by ggomac** [open-mmlab/mmdetection3d#1028]
This error occurs when we change the kitti_pcd_data to our pcd_data only and run ```train.py```. 
Before the pcd_data change, the training was well done.

```
2021-11-04 14:17:03,713 - mmdet - INFO - workflow: [('train', 1)], max: 40 epochs
Traceback (most recent call last):
  File "tools/train.py", line 224, in <module>
    main()
  File "tools/train.py", line 220, in main
    meta=meta)
  File "/home/s/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/dataset_wrappers.py", line 154, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/s/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 357, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/s/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 154, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/s/mmdetection3d/mmdet3d/datasets/pipelines/transforms_3d.py", line 314, in __call__
    gt_bboxes_3d.tensor.numpy(), gt_labels_3d, img=None)
  File "/home/s/mmdetection3d/mmdet3d/datasets/pipelines/dbsampler.py", line 229, in sample_all
    avoid_coll_boxes)
  File "/home/s/mmdetection3d/mmdet3d/datasets/pipelines/dbsampler.py", line 298, in sample_class_v2
    sp_boxes = np.stack([i['box3d_lidar'] for i in sampled], axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

**Comment by ggomac** [comment]
I think there was an error because the label and  pcd_data were different.
So I try to change the label and reopen this issue.

**Comment by ggomac** [comment]
I changed the label to match the pcd_data. But the same error still occurs.

**Comment by MrZhouWenBo** [comment]
Has the problem been solved？ I have the same erro when i run train.py with my own dataset.

**Comment by yypark21** [comment]
> Has the problem been solved？ I have the same erro when i run train.py with my own dataset.

yes, I solve this problem. This is a problem that occurs when there is no data to train. Maybe your label has the wrong information about the 3D.

**Comment by SahilChachra** [comment]
> > Has the problem been solved？ I have the same erro when i run train.py with my own dataset.
> 
> yes, I solve this problem. This is a problem that occurs when there is no data to train. Maybe your label has the wrong information about the 3D.

Hey. Even I am facing the same issue.
Can you please elaborate this message - "Maybe your label has the wrong information about the 3D."

**Comment by SahilChachra** [comment]
> Has the problem been solved？ I have the same erro when i run train.py with my own dataset.

Were you able to solve the issue?
