### ISSUE TITLE
Error training smoke model on kitti dataset

### ISSUE THREAD

**Issue by 24werewolf** [open-mmlab/mmdetection3d#1040]
hi, I run the script in v1.0.0.dev0：
python tools/train.py configs/smoke/smoke_dla34_pytorch_dlaneck_gn-all_8x4_6x_kitti-mono3d.py

but I got the following error:

Traceback (most recent call last):
  File "tools/train.py", line 224, in <module>
    main()
  File "tools/train.py", line 220, in main
    meta=meta)
  File "/home/code/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/code/mmdetection3d/mmdet3d/models/detectors/single_stage_mono3d.py", line 69, in forward_train
    attr_labels, gt_bboxes_ignore)
  File "/home/code/mmdetection3d/mmdet3d/models/dense_heads/base_mono3d_dense_head.py", line 64, in forward_train
    outs = self(x)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/code/mmdetection3d/mmdet3d/models/dense_heads/smoke_mono3d_head.py", line 91, in forward
    return multi_apply(self.forward_single, feats)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/code/mmdetection3d/mmdet3d/models/dense_heads/smoke_mono3d_head.py", line 103, in forward_single
    super().forward_single(x)
  File "/home/code/mmdetection3d/mmdet3d/models/dense_heads/anchor_free_mono3d_head.py", line 361, in forward_single
    clone_cls_feat = conv_cls_prev_layer(clone_cls_feat)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
    x = self.conv(x)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [256, 64, 3, 3], but got 3-dimensional input of size [64, 96, 320] instead

**Comment by ZCMax** [comment]
Change the code like #1029

**Comment by ZCMax** [comment]
PR #1029 has been merged, you can update your code an run.

**Comment by 24werewolf** [comment]
it is work, thank you very much.
