### ISSUE TITLE
I tried to run the demo,OSError:  is not a checkpoint file

### ISSUE THREAD

**Issue by alukade** [open-mmlab/mmdetection3d#1048]
(second3) root@alukade-System-Product-Name:/home/alukade/mmdetection3d/demo# python3.7 pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --device 0
Use load_from_local loader
Traceback (most recent call last):
  File "pcd_demo.py", line 44, in <module>
    main()
  File "pcd_demo.py", line 29, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/home/alukade/mmdetection3d/mmdet3d/apis/inference.py", line 60, in init_model
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "/home/alukade/anaconda3/envs/second3/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/alukade/anaconda3/envs/second3/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/alukade/anaconda3/envs/second3/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/alukade/anaconda3/envs/second3/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 260, in load_from_local
    raise IOError(f'{filename} is not a checkpoint file')
OSError: checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth is not a checkpoint file

The checkpoint file is download from the model_zoo,how to fix it?Thanks a lot.

**Comment by 24werewolf** [comment]
Maybe, you should download the pth.  https://github.com/open-mmlab/mmdetection3d/blob/master/configs/second/README.md

**Comment by Wuziyi616** [comment]
As pointed out by the error message, you need to put the pth file in the `checkpoint` folder.
