### ISSUE TITLE
OSError: symbolic link privilege not held

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection3d#1063]
```
  mmcv                    1.3.16
  mmdet                   2.17.0
  mmsegmentation          0.19.0
  Python 3.7.11
  win11
```

When will windows  be supported
什么时候支持win版本

----------------------------------------------

cd mmdetection3d
pip install -v -e .

```

Requirement already satisfied: argon2-cffi in e:\anaconda3\envs\openmmlab\lib\site-packages (from notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (21.1.0)
Requirement already satisfied: Send2Trash>=1.8.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in e:\anaconda3\envs\openmmlab\lib\site-packages (from notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (0.12.1)
Requirement already satisfied: prometheus-client in e:\anaconda3\envs\openmmlab\lib\site-packages (from notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (0.12.0)
Requirement already satisfied: jinja2 in e:\anaconda3\envs\openmmlab\lib\site-packages (from notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (3.0.3)
Requirement already satisfied: pywinpty>=1.1.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from terminado>=0.8.3->notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (1.1.6)
Requirement already satisfied: cffi>=1.0.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from argon2-cffi->notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (1.15.0)
Requirement already satisfied: pycparser in e:\anaconda3\envs\openmmlab\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from jinja2->notebook->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (2.0.1)
Requirement already satisfied: pandocfilters>=1.4.1 in e:\anaconda3\envs\openmmlab\lib\site-packages (from nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (1.5.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (0.5.9)
Requirement already satisfied: jupyterlab-pygments in e:\anaconda3\envs\openmmlab\lib\site-packages (from nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (0.1.2)
Requirement already satisfied: bleach in e:\anaconda3\envs\openmmlab\lib\site-packages (from nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (4.1.0)
Requirement already satisfied: defusedxml in e:\anaconda3\envs\openmmlab\lib\site-packages (from nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (0.7.1)
Requirement already satisfied: testpath in e:\anaconda3\envs\openmmlab\lib\site-packages (from nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (0.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in e:\anaconda3\envs\openmmlab\lib\site-packages (from nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (0.8.4)
Requirement already satisfied: webencodings in e:\anaconda3\envs\openmmlab\lib\site-packages (from bleach->nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (0.5.1)
Requirement already satisfied: packaging in e:\anaconda3\envs\openmmlab\lib\site-packages (from bleach->nbconvert->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (21.0)
Requirement already satisfied: pytz>=2017.3 in e:\anaconda3\envs\openmmlab\lib\site-packages (from pandas->lyft_dataset_sdk->mmdet3d==0.17.2) (2021.3)
Requirement already satisfied: tenacity>=6.2.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from plotly->lyft_dataset_sdk->mmdet3d==0.17.2) (8.0.1)
Requirement already satisfied: py>=1.8.2 in e:\anaconda3\envs\openmmlab\lib\site-packages (from pytest->lyft_dataset_sdk->mmdet3d==0.17.2) (1.11.0)
Requirement already satisfied: toml in e:\anaconda3\envs\openmmlab\lib\site-packages (from pytest->lyft_dataset_sdk->mmdet3d==0.17.2) (0.10.2)
Requirement already satisfied: iniconfig in e:\anaconda3\envs\openmmlab\lib\site-packages (from pytest->lyft_dataset_sdk->mmdet3d==0.17.2) (1.1.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in e:\anaconda3\envs\openmmlab\lib\site-packages (from pytest->lyft_dataset_sdk->mmdet3d==0.17.2) (1.0.0)
Requirement already satisfied: atomicwrites>=1.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from pytest->lyft_dataset_sdk->mmdet3d==0.17.2) (1.4.0)
Requirement already satisfied: qtpy in e:\anaconda3\envs\openmmlab\lib\site-packages (from qtconsole->jupyter->nuscenes-devkit->mmdet3d==0.17.2) (1.11.2)
Requirement already satisfied: PyWavelets>=1.1.1 in e:\anaconda3\envs\openmmlab\lib\site-packages (from scikit-image->mmdet3d==0.17.2) (1.1.1)
Requirement already satisfied: imageio>=2.3.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from scikit-image->mmdet3d==0.17.2) (2.9.0)
Requirement already satisfied: tifffile>=2019.7.26 in e:\anaconda3\envs\openmmlab\lib\site-packages (from scikit-image->mmdet3d==0.17.2) (2021.10.12)
Requirement already satisfied: absl-py>=0.4 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (1.0.0)
Requirement already satisfied: protobuf>=3.6.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (3.19.1)
Requirement already satisfied: werkzeug>=0.11.15 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (2.0.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (0.4.6)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (1.8.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (2.3.3)
Requirement already satisfied: requests<3,>=2.21.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (2.26.0)
Requirement already satisfied: wheel>=0.26 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (0.37.0)
Requirement already satisfied: grpcio>=1.24.3 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (1.42.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (0.6.1)
Requirement already satisfied: markdown>=2.6.8 in e:\anaconda3\envs\openmmlab\lib\site-packages (from tensorboard->mmdet3d==0.17.2) (3.3.4)
Requirement already satisfied: rsa<5,>=3.1.4 in e:\anaconda3\envs\openmmlab\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard->mmdet3d==0.17.2) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in e:\anaconda3\envs\openmmlab\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard->mmdet3d==0.17.2) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->mmdet3d==0.17.2) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in e:\anaconda3\envs\openmmlab\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->mmdet3d==0.17.2) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in e:\anaconda3\envs\openmmlab\lib\site-packages (from requests<3,>=2.21.0->tensorboard->mmdet3d==0.17.2) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda3\envs\openmmlab\lib\site-packages (from requests<3,>=2.21.0->tensorboard->mmdet3d==0.17.2) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from requests<3,>=2.21.0->tensorboard->mmdet3d==0.17.2) (2.0.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\anaconda3\envs\openmmlab\lib\site-packages (from requests<3,>=2.21.0->tensorboard->mmdet3d==0.17.2) (1.26.7)
Requirement already satisfied: oauthlib>=3.0.0 in e:\anaconda3\envs\openmmlab\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->mmdet3d==0.17.2) (3.1.1)
Installing collected packages: mmdet3d
  Running setup.py develop for mmdet3d
    Running command 'E:\anaconda3\envs\openmmlab\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'F:\\mmdetection3d\\setup.py'"'"'; __file__='"'"'F:\\mmdetection3d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "F:\mmdetection3d\setup.py", line 191, in <module>
        add_mim_extention()
      File "F:\mmdetection3d\setup.py", line 178, in add_mim_extention
        os.symlink(src_relpath, tar_path)
    OSError: symbolic link privilege not held
ERROR: Command errored out with exit status 1: 'E:\anaconda3\envs\openmmlab\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'F:\\mmdetection3d\\setup.py'"'"'; __file__='"'"'F:\\mmdetection3d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

pip install -r  requirements.txt
```
ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-3-0 (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset-tf-2-3-0
```

**Comment by ZCMax** [comment]
@monkeycc I'm sorry but some packages used in mmdetection3d only support linux or mac. For example, waymo-open-dataset only pre-compiled the package for Python 3.7, 3.8, 3.9 for Linux. The support for Windows is now not in our short-term plan,

**Comment by wangruohui** [comment]
windows上普通用户没有symlink权限，用管理员权限开命令行再执行 pip install 应该就可以了
