### ISSUE TITLE
IndexError: list index out of range when training pointpillars using existing configs

### ISSUE THREAD

**Issue by 24spiders** [open-mmlab/mmdetection3d#1069]
**Describe the bug**
A fatal error occurs when training pointpillars using the included config files. A few epochs are able to train successfully but this error always occurs in the third epoch. This error also occurs when a checkpoint epoch that has been saved is used to test.

**Reproduction**
1. What command or script did you run?

```
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py

```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

The config was slightly modified to path it to the new dataset. That is, the only value that was changed (and also in __base__/datasets/kitti-3d-car.py) was the data_root. More information on the dataset below.

3. What dataset did you use?

The dataset used was a custom dataset. This dataset consists of only examples of one class (Car). The dataset exists in KITTI format and aspects of the dataset have been verified using the visualization tools included in this package, as well as kitti-vis. When browsing the dataset, boxes line up properly on the pointcloud, and everything is projected correctly.

**Environment**

```
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3070
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.5.3
MMCV: 1.3.9
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.0+26ab7ff
```

**Error traceback**
If applicable, paste the error trackback here.

```
.
.
.
2021-11-22 20:59:48,412 - mmdet - INFO - Epoch [1][300/330]	lr: 1.018e-03, eta: 2:00:53, time: 0.292, data_time: 0.189, memory: 1510, loss_cls: 0.6473, loss_bbox: 4.6854, loss_dir: 0.0899, loss: 5.4227, grad_norm: 22.3700
2021-11-22 20:59:56,680 - mmdet - INFO - Saving checkpoint at 1 epochs
2021-11-22 21:00:16,091 - mmdet - INFO - Epoch [2][50/330]	lr: 1.029e-03, eta: 1:57:13, time: 0.387, data_time: 0.292, memory: 1517, loss_cls: 0.7195, loss_bbox: 4.5933, loss_dir: 0.1056, loss: 5.4184, grad_norm: 23.2532
2021-11-22 21:00:30,774 - mmdet - INFO - Epoch [2][100/330]	lr: 1.037e-03, eta: 1:58:10, time: 0.294, data_time: 0.204, memory: 1517, loss_cls: 0.7259, loss_bbox: 5.5094, loss_dir: 0.1025, loss: 6.3378, grad_norm: 21.7552
2021-11-22 21:00:46,459 - mmdet - INFO - Epoch [2][150/330]	lr: 1.046e-03, eta: 1:59:46, time: 0.314, data_time: 0.219, memory: 1517, loss_cls: 0.6109, loss_bbox: 4.6946, loss_dir: 0.0938, loss: 5.3992, grad_norm: 18.0382
2021-11-22 21:00:59,375 - mmdet - INFO - Epoch [2][200/330]	lr: 1.056e-03, eta: 1:58:46, time: 0.258, data_time: 0.169, memory: 1517, loss_cls: 0.5838, loss_bbox: 5.4819, loss_dir: 0.0885, loss: 6.1542, grad_norm: 16.6104
2021-11-22 21:01:09,678 - mmdet - INFO - Epoch [2][250/330]	lr: 1.067e-03, eta: 1:55:58, time: 0.206, data_time: 0.124, memory: 1517, loss_cls: 0.6356, loss_bbox: 4.3978, loss_dir: 0.0970, loss: 5.1304, grad_norm: 22.4648
2021-11-22 21:01:22,053 - mmdet - INFO - Epoch [2][300/330]	lr: 1.079e-03, eta: 1:54:59, time: 0.247, data_time: 0.155, memory: 1517, loss_cls: 0.4925, loss_bbox: 4.2361, loss_dir: 0.0843, loss: 4.8129, grad_norm: 17.1448
2021-11-22 21:01:29,889 - mmdet - INFO - Saving checkpoint at 2 epochs
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "tools/train.py", line 224, in <module>
    main()
  File "tools/train.py", line 220, in main
    meta=meta)
  File "/home/liam/Desktop/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 220, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 19, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 311, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/liam/Desktop/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 329, in evaluate
    result_files, tmp_dir = self.format_results(results, pklfile_prefix)
  File "/home/liam/Desktop/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 270, in format_results
    if not isinstance(outputs[0], dict):
IndexError: list index out of range
```

**Comment by ZCMax** [comment]
@24spiders  It seems that the result list is empty, can you print the result of https://github.com/open-mmlab/mmdetection3d/blob/0cd000bf5b04057234d67af476118984bc29ed10/mmdet3d/models/detectors/voxelnet.py#L104 while evaluation?

**Comment by 24spiders** [comment]
Hi, and thanks for the response! I have modified mmdetection3d/mmdet3d/models/detectors/voxelnet.py with the following lines:

```
    def simple_test(self, points, img_metas, imgs=None, rescale=False):
        """Test function without augmentaiton."""
        x = self.extract_feat(points, img_metas)
        outs = self.bbox_head(x)
        bbox_list = self.bbox_head.get_bboxes(
            *outs, img_metas, rescale=rescale)
        print('####### Printing bbox_results from voxelnet.py ######\n')
        bbox_results = [
            bbox3d2result(bboxes, scores, labels)
            for bboxes, scores, labels in bbox_list
        ]
        print(bbox_results)
        print('######################################\n')
        return bbox_results
```
Testing returns
```
python tools/test.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py work_dirs/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car/latest.pth --show --show-dir ./out/
Use load_from_local loader
completed: 0, elapsed: 0s
```
Training now returns
```
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py

2021-11-23 15:55:28,003 - mmdet - INFO - Saving checkpoint at 1 epochs
2021-11-23 15:55:47,514 - mmdet - INFO - Epoch [2][50/330]	lr: 1.029e-03, eta: 1:57:30, time: 0.388, data_time: 0.293, memory: 1517, loss_cls: 0.7542, loss_bbox: 4.5000, loss_dir: 0.1032, loss: 5.3574, grad_norm: 18.0595
2021-11-23 15:56:03,114 - mmdet - INFO - Epoch [2][100/330]	lr: 1.037e-03, eta: 1:59:21, time: 0.312, data_time: 0.215, memory: 1517, loss_cls: 0.7220, loss_bbox: 5.2945, loss_dir: 0.1002, loss: 6.1167, grad_norm: 22.0276
2021-11-23 15:56:18,783 - mmdet - INFO - Epoch [2][150/330]	lr: 1.046e-03, eta: 2:00:48, time: 0.313, data_time: 0.227, memory: 1517, loss_cls: 0.6552, loss_bbox: 4.7795, loss_dir: 0.1035, loss: 5.5382, grad_norm: 18.9457
2021-11-23 15:56:31,760 - mmdet - INFO - Epoch [2][200/330]	lr: 1.056e-03, eta: 1:59:45, time: 0.260, data_time: 0.180, memory: 1517, loss_cls: 0.6096, loss_bbox: 5.1960, loss_dir: 0.0861, loss: 5.8917, grad_norm: 14.1318
2021-11-23 15:56:41,858 - mmdet - INFO - Epoch [2][250/330]	lr: 1.067e-03, eta: 1:56:43, time: 0.202, data_time: 0.127, memory: 1517, loss_cls: 0.6042, loss_bbox: 4.3805, loss_dir: 0.0985, loss: 5.0832, grad_norm: 21.6161
2021-11-23 15:56:54,156 - mmdet - INFO - Epoch [2][300/330]	lr: 1.079e-03, eta: 1:55:37, time: 0.246, data_time: 0.161, memory: 1517, loss_cls: 0.5177, loss_bbox: 4.2423, loss_dir: 0.0842, loss: 4.8442, grad_norm: 15.6692
2021-11-23 15:57:01,907 - mmdet - INFO - Saving checkpoint at 2 epochs
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "tools/train.py", line 224, in <module>
    main()
  File "tools/train.py", line 220, in main
    meta=meta)
  File "/home/liam/Desktop/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 220, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 19, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/liam/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 311, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/liam/Desktop/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 329, in evaluate
    result_files, tmp_dir = self.format_results(results, pklfile_prefix)
  File "/home/liam/Desktop/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 270, in format_results
    if not isinstance(outputs[0], dict):
IndexError: list index out of range
```
Same error as before

**Comment by 24spiders** [comment]
Update: issue has been resolved. Turned out to be a formatting issue with the way I created the `trainval.txt` and `val.txt` ImageSets files.
