### ISSUE TITLE
TypeError: ball_query_wrapper(): incompatible function arguments.

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#107]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
3dssd is not working.

**Reproduction**
1. What command or script did you run?
```
bash tools/dist_train.sh configs/3dssd/configs/3dssd/3dssd_kitti-3d-car.py 1
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
```
No
```
3. What dataset did you use?
```
Kitti
```

**Environment**

```
sys.platform: linux
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce RTX 2080
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.2.0
MMCV: 1.1.2
MMDetection: 2.4.0
MMDetection3D: 0.5.0+84efe00
MMDetection3D Compiler: GCC 7.4
MMDetection3D CUDA Compiler: 10.1
```

**Error traceback**
If applicable, paste the error trackback here.
```
2020-09-15 07:19:30,524 - mmdet - INFO - Start running, host: root@06957c40f73a, work_dir: /opt/project/work_dirs/3dssd_kitti-3d-car
2020-09-15 07:19:30,524 - mmdet - INFO - workflow: [('train', 1)], max: 150 epochs
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 234, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/project/mmdet3d/models/detectors/base.py", line 57, in forward
    return self.forward_train(**kwargs)
  File "/opt/project/mmdet3d/models/detectors/votenet.py", line 55, in forward_train
    x = self.extract_feat(points_cat)
  File "/opt/project/mmdet3d/models/detectors/single_stage.py", line 61, in extract_feat
    x = self.backbone(points)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/project/mmdet3d/models/backbones/pointnet2_sa_msg.py", line 146, in forward
    sa_xyz[i], sa_features[i])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/project/mmdet3d/ops/pointnet_modules/point_sa_module.py", line 162, in forward
    new_features = self.groupers[i](points_xyz, new_xyz, features)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/project/mmdet3d/ops/group_points/group_points.py", line 65, in forward
    points_xyz, center_xyz)
  File "/opt/project/mmdet3d/ops/ball_query/ball_query.py", line 38, in forward
    sample_num, center_xyz, xyz, idx)
TypeError: ball_query_wrapper(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: int, arg2: int, arg3: float, arg4: int, arg5: at::Tensor, arg6: at::Tensor, arg7: at::Tensor) -> int

Invoked with: 4, 16384, 4096, 0, 0.2, 32, tensor([[[ 14.6247,   0.6191,  -1.5952],
         [ 71.1641, -14.7686,   1.3168],
         [ 39.3636, -22.2427,  -0.4247],
         ...,
         [ 17.1308, -14.4069,   0.5405],
         [ 14.5145,   0.6062,  -0.9683],
         [ 10.7840, -12.4140,  -1.1146]],

        [[ 39.8580,  15.7912,   0.3416],
         [ 42.9790, -52.6905,   1.7571],
         [ 12.7742, -19.7523,  -0.4086],
         ...,
         [ 10.0640,   0.1943,  -0.6353],
         [ 25.5652, -20.7948,  -0.4865],
         [ 10.2695,  -0.3202,  -1.6072]],

        [[  2.7051,   5.4570,   0.1379],
         [ 64.5348,  15.0966,   1.6975],
         [ 32.3205,  19.6773,   1.4677],
         ...,
         [ 29.6612,  14.8161,   0.1343],
         [ 32.3370,  18.7930,   1.4533],
         [ 12.1497,   9.6993,  -0.8875]],

        [[ 25.8298,  -0.9123,  -1.7159],
         [ 46.9165,  51.1561,   1.2508],
         [ 68.9729,   0.5307,  -0.3507],
         ...,
         [  7.1650,  -1.1334,  -1.4412],
         [ 10.4670,  22.2042,  -1.0417],
         [ 12.0158,  -0.2317,  -1.3502]]], device='cuda:0'), tensor([[[ 14.6247,   0.6191,  -1.5952],
         [  2.2351,  -5.3085,  -1.8268],
         [  7.6207,  -2.1482,  -1.7090],
         ...,
         [  6.5514,  -4.4366,  -1.7079],
         [  8.7897,   3.7034,  -0.5568],
         [  7.4799,  -3.2524,  -1.6927]],

        [[ 39.8580,  15.7912,   0.3416],
         [ 14.7809,  -1.8044,  -1.6292],
         [ 25.9592, -11.7795,  -1.5613],
         ...,
         [ 12.2489,   4.9562,  -1.4914],
         [  6.7188,   0.1678,  -1.7031],
         [ 29.8278, -23.2363,  -1.6951]],

        [[  2.7051,   5.4570,   0.1379],
         [  5.8451,   3.7107,  -1.5497],
         [ 10.1879,   6.4211,  -1.5263],
         ...,
         [  8.1591,   4.1461,  -1.5110],
         [  4.8407,   6.4939,  -0.4685],
         [  6.4560,   1.0064,  -1.0010]],

        [[ 25.8298,  -0.9123,  -1.7159],
         [ 13.0339,   4.5968,  -1.3455],
         [  4.2728,   7.3933,  -1.5368],
         ...,
         [  9.2533,   6.9935,  -1.5087],
         [ 24.1863,  37.2038,  -0.1566],
         [ 20.1692,  35.7954,  -0.3835]]], device='cuda:0'), tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]], device='cuda:0', dtype=torch.int32)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/3dssd/3dssd_kitti-3d-car.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by filaPro** [comment]
Sorry, used incorrect `mmdetection3d` version while building `docker` container.
