### ISSUE TITLE
mono_det_demo.py Assertion Error

### ISSUE THREAD

**Issue by clepz** [open-mmlab/mmdetection3d#1077]
- running using container.
- Mmdetection code: master branch
- mmcv : 1.3.18
- mmdet version : 2.18.1
- mmseg : 0.14.1

```
root@eb88bd085713:/mmdetection3d# python demo/mono_det_demo.py --help
Traceback (most recent call last):
  File "demo/mono_det_demo.py", line 4, in <module>
    from mmdet3d.apis import (inference_mono_3d_detector, init_model,
  File "/mmdetection3d/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/mmdetection3d/mmdet3d/apis/inference.py", line 11, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes,
  File "/mmdetection3d/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/opt/conda/lib/python3.7/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/opt/conda/lib/python3.7/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/opt/conda/lib/python3.7/site-packages/mmdet/core/bbox/samplers/__init__.py", line 10, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/opt/conda/lib/python3.7/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: assign_score_withk_forward miss in module _ext
```

**Comment by ZCMax** [comment]
@clepz I think you it's mmcv compile problem, seems that you didn't install mmcv-full successfully.
