### ISSUE TITLE
MVXNet OOM regardless of GPU

### ISSUE THREAD

**Issue by 24spiders** [open-mmlab/mmdetection3d#1081]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
How much memory does MVXNet require to train? I had issues on my 8 GB card so have since gotten access to a 16 GB card - MVXNet still expands until all memory is full and then training crashes

**Reproduction**
1. What command or script did you run?

```
python tools/train.py configs/mvxnet/mvxnet-cfg.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

The following was changed in the config:
`point_cloud_range` was changed from `[0, -40, -3, 70.4, 40, 1]` to `[0, -20, -20, 85, 20, 20,]`
`samples_per_gpu` and `workers_per_gpu` were both changed to `1`

3. What dataset did you use?

A custom dataset that has been verified to be formatted correctly using the visualization tools that come with this package

**Environment**

```
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2: NVIDIA Tesla V100-PCIE-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1
OpenCV: 4.5.4
MMCV: 1.3.18
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.2+c06c018
```

**Error traceback**
If applicable, paste the error trackback here.

```
2021-11-28 21:03:44,298 - mmdet - INFO - workflow: [('train', 1)], max: 40 epochs
2021-11-28 21:03:44,298 - mmdet - INFO - Checkpoints will be saved to /home/jupyter-team./mmdetection3d/work_dirs/mvxnet by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 216, in main
    meta=meta)
  File "/home/jupyter-team./mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/jupyter-team./mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/jupyter-team./mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 274, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/jupyter-team./mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/jupyter-team./mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 55, in extract_pts_feat
    voxels, coors, points, img_feats, img_metas)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/jupyter-team./mmdetection3d/mmdet3d/models/voxel_encoders/voxel_encoder.py", line 274, in forward
    img_metas)
  File "/home/jupyter-team./.conda/envs/mmcv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jupyter-team./mmdetection3d/mmdet3d/models/fusion_layers/point_fusion.py", line 223, in forward
    img_pts = self.obtain_mlvl_feats(img_feats, pts, img_metas)
  File "/home/jupyter-team./mmdetection3d/mmdet3d/models/fusion_layers/point_fusion.py", line 264, in obtain_mlvl_feats
    mlvl_img_feats = torch.cat(mlvl_img_feats, dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 3.06 GiB (GPU 0; 15.78 GiB total capacity; 10.33 GiB already allocated; 1.82 GiB free; 12.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by ZCMax** [comment]
@24spiders Hi! I think maybe you can first keep point_cloud_range `z` from [-20, 20] to [-3, 3], seeing whether the model could be trained well. Besides, point density should also be considered.
