### ISSUE TITLE
AttributeError: 'SUNRGBDInstance' object has no attribute 'l'

### ISSUE THREAD

**Issue by dk-liang** [open-mmlab/mmdetection3d#1098]
When  I run 
`python tools/create_data.py sunrgbd --root-path /data/dkliang/projects/synchronous/datasets/sunrgbd_mm/ --out-dir  /data/dkliang/projects/synchronous/datasets/sunrgbd_mm/ --extra-tag sunrgbd. `

It shows the following error:

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
train sample_idx: 5051
train sample_idx: 5052
train sample_idx: 5053
train sample_idx: 5054
.....................................
train sample_idx: 10334
train sample_idx: 10335
Traceback (most recent call last):
  File "tools/create_data.py", line 289, in <module>
    workers=args.workers)
  File "tools/create_data.py", line 140, in sunrgbd_data_prep
    root_path, info_prefix, out_dir, workers=workers)
  File "/data/dkliang/projects/synchronous/mmdetection3d-1.0.0.dev0/tools/data_converter/indoor_converter.py", line 54, in create_indoor_info_file
    num_workers=workers, has_label=True)
  File "/data/dkliang/projects/synchronous/mmdetection3d-1.0.0.dev0/tools/data_converter/sunrgbd_data_utils.py", line 222, in get_infos
    return list(infos)
  File "/home/dkliang/miniconda3/envs/open-mmlab/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/dkliang/miniconda3/envs/open-mmlab/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/dkliang/miniconda3/envs/open-mmlab/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/dkliang/miniconda3/envs/open-mmlab/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/dkliang/projects/synchronous/mmdetection3d-1.0.0.dev0/tools/data_converter/sunrgbd_data_utils.py", line 196, in process_single_scene
    [obj.l, obj.w, obj.h] for obj in obj_list
  File "/data/dkliang/projects/synchronous/mmdetection3d-1.0.0.dev0/tools/data_converter/sunrgbd_data_utils.py", line 197, in <listcomp>
    if obj.classname in self.cat2label.keys()
AttributeError: 'SUNRGBDInstance' object has no attribute 'l'

Could you tell me how to solve this?

**Comment by stanleyshly** [comment]
I am also getting this error

**Comment by wHao-Wu** [comment]
Hi, @dk-liang , @stanleyshly 

We suppose that you created the SUN RGB-D data with v1.0.0 branch. We found that there is something wrong when creating .pkl file with v1.0.0 branch. We will fix this problem asap.
