### ISSUE TITLE
[Visualization] RuntimeError: operation does not have an identity

### ISSUE THREAD

**Issue by Comverser** [open-mmlab/mmdetection3d#1112]
**Describe the bug**
- Run the visualization code below produces the error
```bash
python tools/test.py configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --show --show-dir data/kitti/show_dir/
```
- The error message
```
load checkpoint from local path: checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
[                                                  ] 0/3, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 217, in <module>
    main()
  File "tools/test.py", line 187, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/s/dev/mmdetection3d/mmdet3d/apis/test.py", line 52, in single_gpu_test
    score_thr=show_score_thr)
  File "/home/s/dev/mmdetection3d/mmdet3d/models/detectors/base.py", line 126, in show_results
    pred_labels=pred_labels)
  File "/home/s/dev/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 109, in show_result
    0, 255, size=(pred_labels.max() + 1, 3)) / 256
RuntimeError: operation does not have an identity.
```

**Reproduction**
1. Download checkpoints
```bash
mkdir checkpoints
wget https://download.openmmlab.com/mmdetection3d/v0.1.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth -P ./checkpoints/
```
2. Download Kitti dataset sample

3. dataset preparation
```bash
python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
```
4. Run the visualization script
```bash
python tools/test.py configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --show --show-dir data/kitti/show_dir/
```
5. Did you make any modifications on the code or config? Did you understand what you have modified? No
6. What dataset did you use? Kitti dataset
7. Although the demo works
```bash
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --show
```

**Environment**
- OS: Ubuntu 20.04 and 18.04 tested for all combinations of my settings
- CUDA/PyTorch: 11.1.1/1.8.0 and 11.3/1.8.1 tested
- GPU: NVIDIA GeFroce RTX 3080 and NVIDIA GeFroce RTX 2080 tested
- Conda: Anaconda3-2021.11-Linux-x86_64 and Anaconda3-2019 tested
- pycocotools==2.0.1 only (as upper version produces error)
- mmcv, mmdetection, mmsegmentation versions as shown below
```bash
# install mmcv (1.4.0)
pip install mmcv-full
# install mmdetection (2.19.0)
pip install git+https://github.com/open-mmlab/mmdetection.git
# install mmsegmentation (0.19.0)
pip install git+https://github.com/open-mmlab/mmsegmentation.git
```
- Also tested below
```
mmcv-full==1.3.13
mmdet==2.14.0
mmsegmentation==0.14.1
```
- Furthermore, the "A from-scratch setup script" tested

**Comment by Comverser** [comment]
I solved this issue by using source file of "MMDetection3D V0.17.0 Release" instead of cloning master branch. It may be related to downgrade of MMDetection3D version (0.17.3 -> 0.17.0).
