### ISSUE TITLE
TypeError: show_results() got an unexpected keyword argument 'show'

### ISSUE THREAD

**Issue by hufangjian** [open-mmlab/mmdetection3d#1119]
I run：
 python tools/test.py configs/centerpoint/centerpoint_01voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.py work_dir/centerpoint/centerpoint_01voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.pth --show --show-dir eval_results/

get this error:
Traceback (most recent call last):
  File "tools/test.py", line 217, in <module>
    main()
  File "tools/test.py", line 187, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/hufangjian/research/mmdetection3d/mmdet3d/apis/test.py", line 52, in single_gpu_test
    score_thr=show_score_thr)
TypeError: show_results() got an unexpected keyword argument 'show

**Comment by ZCMax** [comment]
Thanks for your feedback. We will fix it soon. For now, maybe you can remove the show keyword in https://github.com/open-mmlab/mmdetection3d/blob/30ad1aae13fe78e5b91d6d6f9eee835c1c086612/mmdet3d/apis/test.py#L51 when you are using CenterPoint.

**Comment by nikhil-nakhate** [comment]
Is this error solved? I am getting the same error on detr3d

**Comment by iceriver97** [comment]
where is the code of show_results(),  I am getting the same error on VoxFormer.

**Comment by Huxwell** [comment]
Seems that it's still not fixed.
The docs clearly state, that '--show' is required for visualisation: https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html
