### ISSUE TITLE
Training Part A^2 Error

### ISSUE THREAD

**Issue by Mahdi-Moalla** [open-mmlab/mmdetection3d#1141]
Checklist
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

Bug:
I am trying to train Part A^2 on kitti dataset.
I was able to train SECOND and Point Pillars for few epochs without problems. 

Reproduction

```
python tools/train.py configs/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.py --work-dir work/kiti_parta2
```

I am using kitti dataset. I did not make any modification to the initial scripts.

Environment

```
sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce GTX TITAN X
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2
OpenCV: 4.5.4
MMCV: 1.4.1
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMDetection: 2.19.1
MMSegmentation: 0.20.1
MMDetection3D: 0.17.3+30ad1aa
```

Error traceback

```
.
.
.
.
/opt/conda/conda-bld/pytorch_1607370172916/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [850,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1607370172916/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [850,0,0], thread: [60,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1607370172916/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [850,0,0], thread: [61,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1607370172916/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [850,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1607370172916/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [850,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 209, in main
    train_model(
  File "/media/work/mmdetection3d/mmdet3d/apis/train.py", line 28, in train_model
    train_detector(
  File "/media/work/mmdetection/mmdet/apis/train.py", line 203, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/media/work/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/media/work/mmcv/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/media/work/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/media/work/mmcv/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/mahdi/.conda/envs/mmenv/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/mahdi/.conda/envs/mmenv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
  File "/home/mahdi/.conda/envs/mmenv/lib/python3.8/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/media/work/mmdetection3d/mmdet3d/ops/spconv/functional.py", line 32, in backward
    input_bp, filters_bp = ops.indice_conv_backward(
  File "/media/work/mmdetection3d/mmdet3d/ops/spconv/ops.py", line 150, in indice_conv_backward
    return sparse_conv_ext.indice_conv_backward_fp32(
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by ZCMax** [comment]
It might be the class number of your network output doesn't match the label class number.

**Comment by Mahdi-Moalla** [comment]
I do not think so. I am using the script configs/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.py as it is without any modification. I am also having issue with the car-only script also. The latter produces an error in the roi_head. I am not sure what is happening. It might be related to my environment. However, I am able to train SECOND and Point Pillars without any problem.

**Comment by luca-b94** [comment]
I second this. I cannot train PartA2 on KTTI due to the same problem. Also, training SECOND on all 3 KITTI classes gives me the same problem. To be clear, I am using the default config files without modification. 
I have also another question, the code provided in this repository for PartA2 refers to the anchor-based version and not the anchor-free, am I right?

**Comment by Runjian-Chen** [comment]
Hello, I think I met the same problem with yours @luca-b94 @Mahdi-Moalla . I could train SECOND on KITTI but failed to train PartA2 on KITTI before. I use 3090 and have to install CUDA 11.1.

In my case, building PyTorch 1.6.0 from source deals with this problem and now I can train both models on KITTI.

**Comment by ZwwWayne** [comment]
This is because pytorch 1.6 does not support the arch of 3090. You can use a higher version of PyTorch, like PyTorch 1.7+
