### ISSUE TITLE
Demo  no attribute 'node'

### ISSUE THREAD

**Issue by Baboom-l** [open-mmlab/mmdetection3d#1144]
Hi, I got the following error while running Demo.py.

(base) ➜  mmdetection3d git:(master)  python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py ck/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
load checkpoint from local path: ck/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
/environment/miniconda3/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 44, in <module>
    main()
  File "demo/pcd_demo.py", line 40, in main
    task='det')
  File "/home/featurize/mmdetection3d/mmdet3d/apis/inference.py", line 481, in show_result_meshlab
    show, snapshot)
  File "/home/featurize/mmdetection3d/mmdet3d/apis/inference.py", line 333, in show_det_result_meshlab
    snapshot=snapshot)
  File "/home/featurize/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 145, in show_result
    osp.join(result_path, f'{filename}_pred.obj'))
  File "/home/featurize/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 68, in _write_oriented_bbox
    mesh_list = trimesh.util.concatenate(scene.dump())
  File "/environment/miniconda3/lib/python3.7/site-packages/trimesh-2.35.39-py3.7.egg/trimesh/scene/scene.py", line 499, in dump
  File "/environment/miniconda3/lib/python3.7/site-packages/trimesh-2.35.39-py3.7.egg/trimesh/caching.py", line 88, in get_cached
  File "/environment/miniconda3/lib/python3.7/site-packages/trimesh-2.35.39-py3.7.egg/trimesh/scene/transforms.py", line 224, in nodes_geometry
AttributeError: 'EnforcedForest' object has no attribute 'node'

My environment is as follows.
torch 1.10.0+cu113
mmdet3d                      0.17.3
mmdet                        2.14.0
mmcv-full                    1.4.0
mmsegmentation               0.14.1

**Comment by ZCMax** [comment]
What's your networkx version? Did you pip install 'networkx>=2.2,<2.3' before installing trimesh

**Comment by Baboom-l** [comment]
I checked the environment and my networkx ==2.6.3

**Comment by ZCMax** [comment]
You should downgrade your networkx version to meet the requirements.

**Comment by Baboom-l** [comment]
Now my networkx == 2.2,But the return is as follows

(base) ➜  mmdetection3d git:(master) python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py ck/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
load checkpoint from local path: ck/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
/environment/miniconda3/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

**Comment by Tai-Wang** [comment]
It seems just a warning from pytorch, so you should have successfully run the demo.

**Comment by Baboom-l** [comment]
Thank you for the timely reply, it has successfully generated two obj files.
