### ISSUE TITLE
Excuse me, when running the demo, the following errors occurred. I don't know why.请（问各位，运行demo指令时，出现错误，不知道原因。）

### ISSUE THREAD

**Issue by zzzzzz-ddddd** [open-mmlab/mmdetection3d#1155]
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
Use load_from_local loader
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 44, in <module>
    main()
  File "demo/pcd_demo.py", line 31, in main
    result, data = inference_detector(model, args.pcd)
  File "/home/zzz/mmdetection3d/mmdet3d/apis/inference.py", line 116, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/home/zzz/anaconda3/envs/mm3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzz/anaconda3/envs/mm3d/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/zzz/mmdetection3d/mmdet3d/models/detectors/base.py", line 61, in forward
    return self.forward_test(**kwargs)
  File "/home/zzz/mmdetection3d/mmdet3d/models/detectors/base.py", line 42, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/home/zzz/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 100, in simple_test
    x = self.extract_feat(points, img_metas)
  File "/home/zzz/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 42, in extract_feat
    voxels, num_points, coors = self.voxelize(points)
  File "/home/zzz/anaconda3/envs/mm3d/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zzz/anaconda3/envs/mm3d/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 184, in new_func
    return old_func(*args, **kwargs)
  File "/home/zzz/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 57, in voxelize
    res_voxels, res_coors, res_num_points = self.voxel_layer(res)
  File "/home/zzz/anaconda3/envs/mm3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzz/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 138, in forward
    self.deterministic)
  File "/home/zzz/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 65, in forward
    deterministic)
TypeError: hard_voxelize(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: List[float], arg5: List[float], arg6: int, arg7: int, arg8: int) -> int

Invoked with: tensor([[ 2.1554e+01,  2.8000e-02,  9.3800e-01,  3.4000e-01],
        [ 2.1240e+01,  9.4000e-02,  9.2700e-01,  2.4000e-01],
        [ 2.1056e+01,  1.5900e-01,  9.2100e-01,  5.3000e-01],
        ...,
        [ 6.3150e+00, -3.1000e-02, -1.6490e+00,  2.9000e-01],
        [ 6.3090e+00, -2.1000e-02, -1.6470e+00,  2.9000e-01],
        [ 6.3110e+00, -1.0000e-03, -1.6480e+00,  3.2000e-01]], device='cuda:0'), tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        ...,

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], device='cuda:0'), tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], device='cuda:0', dtype=torch.int32), tensor([0, 0, 0,  ..., 0, 0, 0], device='cuda:0', dtype=torch.int32), [0.05, 0.05, 0.1], [0, -40, -3, 70.4, 40, 1], 5, 40000, 3, True

**Comment by ZCMax** [comment]
Have you made any modifications in your code or config file? and which branch ( master or v1.0.0.dev0)  code are you using?

**Comment by zzzzzz-ddddd** [comment]
Neither the code nor the configuration file was modified. I used git checkout v0.17.0.

**Comment by ZCMax** [comment]
It's a problem existing in v0.17.0 branch, I suggest you to change to master branch, where the bug has been fixed.

**Comment by ZCMax** [comment]
I check it again, and maybe you compile the voxelization op in master branch, but then you switch to v0.17.0 branch. That will cause the problem.

**Comment by Tai-Wang** [comment]
Close due to inactivity.

**Comment by rebeccamart** [comment]
Hello! I have a similar problem.
Some idea how to resolve it? Thanks in advance.

I haven't changed anything in the code and I run this command:
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-3class_20200620_230238-9208083a.pth --out-dir ./output

I get this error:
![image](https://user-images.githubusercontent.com/103591525/166639375-f33f68aa-98aa-4066-834f-b95bd39b681a.png)
![image](https://user-images.githubusercontent.com/103591525/166639663-498debac-99bd-4f42-8031-ef5b93501161.png)
