### ISSUE TITLE
RuntimeError: Index put requires the source and destination dtypes match.

### ISSUE THREAD

**Issue by tuhlnaa** [open-mmlab/mmdetection3d#1161]
**Describe the bug**

RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Int for the source.

**Reproduction**

Use KITTI dataset.
```
python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti --workers 6
```
![screenshot01](https://user-images.githubusercontent.com/60013373/148556244-c4421323-15cf-460e-9985-056888478d9e.png)

```
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
```
RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Int for the source.

**Environment**
windows 10
```
sys.platform: win32
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1080
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
NVCC: Not Available
GCC: n/a
PyTorch: 1.9.0+cu102
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.10.0+cu102
OpenCV: 4.5.4
MMCV: 1.4.2
MMCV Compiler: MSVC 192930037
MMCV CUDA Compiler: 10.2
MMDetection: 2.19.1
MMSegmentation: 0.20.2
MMDetection3D: 0.17.3+unknown
```
**Error traceback**

```
2022-01-07 22:02:21,412 - mmdet - INFO - workflow: [('train', 1)], max: 80 epochs
2022-01-07 22:02:21,412 - mmdet - INFO - Checkpoints will be saved to C:\Users\Lab515\source\repos\PythonApplication3\PythonApplication3\work_dirs\hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 209, in main
    train_model(
  File "c:\users\lab515\source\repos\pythonapplication3\pythonapplication3\mmdet3d\apis\train.py", line 28, in train_model
    train_detector(
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmdet\apis\train.py", line 203, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmdet\models\detectors\base.py", line 248, in train_step
    losses = self(**data)
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "c:\users\lab515\source\repos\pythonapplication3\pythonapplication3\mmdet3d\models\detectors\base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "c:\users\lab515\source\repos\pythonapplication3\pythonapplication3\mmdet3d\models\detectors\voxelnet.py", line 94, in forward_train
    losses = self.bbox_head.loss(
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "c:\users\lab515\source\repos\pythonapplication3\pythonapplication3\mmdet3d\models\dense_heads\anchor3d_head.py", line 339, in loss
    cls_reg_targets = self.anchor_target_3d(
  File "c:\users\lab515\source\repos\pythonapplication3\pythonapplication3\mmdet3d\models\dense_heads\train_mixins.py", line 71, in anchor_target_3d
    neg_inds_list) = multi_apply(
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmdet\core\utils\misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "c:\users\lab515\source\repos\pythonapplication3\pythonapplication3\mmdet3d\models\dense_heads\train_mixins.py", line 146, in anchor_target_3d_single
    anchor_targets = self.anchor_target_single_assigner(
  File "c:\users\lab515\source\repos\pythonapplication3\pythonapplication3\mmdet3d\models\dense_heads\train_mixins.py", line 273, in anchor_target_single_assigner
    assign_result = bbox_assigner.assign(anchors, gt_bboxes,
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmdet\core\bbox\assigners\max_iou_assigner.py", line 120, in assign
    assign_result = self.assign_wrt_overlaps(overlaps, gt_labels)
  File "C:\Users\Lab515\.conda\envs\Py3-8-Pytorch1-9-cuda10-2\lib\site-packages\mmdet\core\bbox\assigners\max_iou_assigner.py", line 207, in assign_wrt_overlaps
    assigned_labels[pos_inds] = gt_labels[
RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Int for the source.
```
[Error traceback.txt](https://github.com/open-mmlab/mmdetection3d/files/7829267/Error.traceback.txt)

**Bug fix**
```
\mmdet\core\bbox\assigners\max_iou_assigner.py
[line 207] gt_labels[assign_gt_inds[pos_inds] - 1].long()

\mmdet3d\models\dense_heads\train_mixins.py
[line 305] gt_labels[sampling_result.pos_assigned_gt_inds].long()
```

**Comment by ZCMax** [comment]
hello, I think you can refer to https://github.com/open-mmlab/mmdetection/issues/6706 for solution, we'll check the problem ASAP.

**Comment by tuhlnaa** [comment]
> 您好，我想您可以參考[open-mmlab/mmdetection#6706](https://github.com/open-mmlab/mmdetection/issues/6706)的解決方案，我們會盡快檢查問題。

Thank you.The problem has been solved.

**Bug fix**
```
\mmdet\core\bbox\assigners\max_iou_assigner.py
[line 207] gt_labels[assign_gt_inds[pos_inds] - 1].long()

\mmdet3d\models\dense_heads\train_mixins.py
[line 305] gt_labels[sampling_result.pos_assigned_gt_inds].long()
```
