### ISSUE TITLE
Reduce pillar size nuScenes

### ISSUE THREAD

**Issue by carranza96** [open-mmlab/mmdetection3d#1172]
Hello,
I am using the default hv_pointpillars_fpn_nus.py configuration to train nuscenes. The default pillar value is [0.25, 0.25, 8].

I want to experiment reducing the pillar size, for instance to 0.2, but it gives an error and does not start training. Even if I try with 0.24, any value below 0.25 fails. I have also been playing with the point cloud range, increasing and decreasing it, but no success so far.

The error is the following:

Traceback (most recent call last):
  File "./tools/train.py", line 224, in <module>
    main()
  File "./tools/train.py", line 213, in main
    train_model(
  File "/home/manuelg/mmdetection3d/mmdet3d/apis/train.py", line 28, in train_model
    train_detector(
  File "/home/manuelg/torch/lib/python3.8/site-packages/mmdet/apis/train.py", line 177, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/manuelg/torch/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/manuelg/torch/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/manuelg/torch/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/manuelg/torch/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/manuelg/torch/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/home/manuelg/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/manuelg/torch/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/manuelg/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/manuelg/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 301, in forward_train
    img_feats, pts_feats = self.extract_feat(
  File "/home/manuelg/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 235, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/manuelg/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 226, in extract_pts_feat
    x = self.pts_middle_encoder(voxel_features, coors, batch_size)
  File "/home/manuelg/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/manuelg/torch/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/manuelg/mmdetection3d/mmdet3d/models/middle_encoders/pillar_scatter.py", line 34, in forward
    return self.forward_batch(voxel_features, coors, batch_size)
  File "/home/manuelg/mmdetection3d/mmdet3d/models/middle_encoders/pillar_scatter.py", line 83, in forward_batch
    this_coors = coors[batch_mask, :]

Any idea what could solve the issue? I don't know if some requirement in the PillarFeatureNet is not met, but I am just using the default conf, only reducing pillar size.

Thank you!

**Comment by luca-b94** [comment]
Did you modify also the output_shape of 'PointPillarsScatter' in the config? I think there's a mismatch between the number of pillars used to build the sparse image and the voxel size/point cloud range. If I understood correctly the number of pillars can be computed by dividing the point cloud range and the voxel size. For example, if you have a point_cloud_range = [-50, -50, -5, 50, 50, 3] and a voxel size [0.2, 0.2, 8] as yours, your output_shape would be [500, 500].  I had a similar issue when training PointPillars with KITTI data and this solved the problem.  Let me know if this is of any help :)

P.S.: For training nuScenes why you don't use hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py, I think  hv_pointpillars_fpn_nus.py contains only the definition of the model and nothing else.

**Comment by carranza96** [comment]
> Did you modify also the output_shape of 'PointPillarsScatter' in the config? I think there's a mismatch between the number of pillars used to build the sparse image and the voxel size/point cloud range. If I understood correctly the number of pillars can be computed by dividing the point cloud range and the voxel size. For example, if you have a point_cloud_range = [-50, -50, -5, 50, 50, 3] and a voxel size [0.2, 0.2, 8] as yours, your output_shape would be [500, 500]. I had a similar issue when training PointPillars with KITTI data and this solved the problem. Let me know if this is of any help :)

Thank you very much for the hint. It does work but if I put output_shape [512,512]. I found it by chance because I saw those number in other configs. So it is not so clear to me what is the rule to make it work? 

> P.S.: For training nuScenes why you don't use hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py, I think hv_pointpillars_fpn_nus.py contains only the definition of the model and nothing else.

Sorry, yes I am using that one. I just cited the other one to make clear the model architecture I was using.

**Comment by luca-b94** [comment]
I thought that to compute the output_shape you would have to divide the point cloud range by the voxel size. For example, if my point cloud limits are x_min, x_max, y_min, y_max and voxels sizes vx, vy I computed the output shape like this: [(x_max - x_min)/vx, (y_max - y_min)/vy]. 
If you say that [512, 512] works with point cloud range [-50,-50,-3,50,50,8] I guess that my assumption are incorrect

**Comment by carranza96** [comment]
Thanks again!
I have trying and your assumption is correct in same cases. Considering always the range to be 100.
With pillar size 0.25 (default conf) -> 100/0.25 = [400, 400]  works
With pillar size 0.1 -> 100/0.1 -> [1000, 1000] works
With pillar size 0.2 -> 100/0.25 = [500, 500] does not work, needs [512,512]

Do you have any idea why this may happen? Maybe something related to padding due to uneven divisions?
Thanks!

**Comment by luca-b94** [comment]
Unfortunately I have no idea why sometimes it works and others not. As you are saying maybe is related to some padding, I am clueless as you are right now

**Comment by Tai-Wang** [comment]
@luca-b94 @carranza96 Yes, your solution is correct. You can also refer to issue [#135](https://github.com/open-mmlab/mmdetection3d/issues/135). As for the case [500, 500] does not work, it is possibly because of some uneven division problems or some subtle problems caused by division implementations. Maybe a more detailed error log is required for locating that problem.

**Comment by Tai-Wang** [comment]
Please feel free to reopen this issue if you have any updates about the remaining questions.
