### ISSUE TITLE
IndexError: too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by SoftFeta** [open-mmlab/mmdetection3d#1202]
Hello! I tried to test PAConv on the S3DIS dataset. I ran the following command:
`python tools/test.py configs/paconv/paconv_cuda_ssg_8x8_cosine_200e_s3dis_seg-3d-13class.py checkpoints/paconv_cuda_ssg_8x8_cosine_200e_s3dis_seg-3d-13class_20210802_171802-e5ea9bb9.pth --eval mAP --eval-options 'show=True' 'out_dir=./data/s3dis/show_results'`

and got the following error:

```
+---------+---------+--------+--------+--------+--------+--------+--------+--------+--------+--------+----------+--------+---------+--------+--------+---------+
| classes | ceiling | floor  | wall   | beam   | column | window | door   | table  | chair  | sofa   | bookcase | board  | clutter | miou   | acc    | acc_cls |
+---------+---------+--------+--------+--------+--------+--------+--------+--------+--------+--------+----------+--------+---------+--------+--------+---------+
| results | 0.9800  | 0.9822 | 0.9552 | 0.8991 | 0.9016 | 0.9537 | 0.9600 | 0.9244 | 0.9674 | 0.9547 | 0.9683   | 0.9557 | 0.9251  | 0.9483 | 0.9792 | 0.9754  |
+---------+---------+--------+--------+--------+--------+--------+--------+--------+--------+--------+----------+--------+---------+--------+--------+---------+
Traceback (most recent call last):
  File "tools/test.py", line 238, in <module>
    main()
  File "tools/test.py", line 234, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/mnt/c/mmdetection3d/mmdet3d/datasets/custom_3d_seg.py", line 345, in evaluate
    self.show(pred_sem_masks, out_dir, pipeline=pipeline)
  File "/mnt/c/mmdetection3d/mmdet3d/datasets/s3dis_dataset.py", line 287, in show
    pred_sem_mask = result['semantic_mask'].numpy()
IndexError: too many indices for tensor of dimension 1
```

I'm using the `master` branch of `mmdetection3d`.
Any ideas? Thanks!

**Comment by SoftFeta** [comment]
I printed out `result` from `s3dis_dataset.py` and it looked like this:
```
tensor([ 0,  0,  0,  ..., 12,  2, 12])
```

**Comment by Tai-Wang** [comment]
We will fix this issue in #1457 .
