### ISSUE TITLE
Can't visualize some data with MVX-Net model

### ISSUE THREAD

**Issue by Comverser** [open-mmlab/mmdetection3d#1205]
# Issue: can't visualize some data with MVX-Net model
It can show about 10 data among 20 data, but it suddenly fail for the remaining data.

## Command used
```bash
python tools/misc/visualize_results.py configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py \
    --result data/kitti/results_mvxnet.pkl --show-dir data/kitti/show_results_mvxnet/
```
## Error message
```bash
Qt: Session management error: Could not open network socket
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
Traceback (most recent call last):
  File "tools/misc/visualize_results.py", line 49, in <module>
    main()
  File "tools/misc/visualize_results.py", line 39, in main
    dataset.show(results, args.show_dir, pipeline=eval_pipeline)
  File "/home/s/dev/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 745, in show
    show=show)
  File "/home/s/dev/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 276, in show_multi_modality_result
    color=pred_bbox_color)
  File "/home/s/dev/mmdetection3d/mmdet3d/core/visualizer/image_vis.py", line 106, in draw_lidar_bbox3d_on_img
    corners_3d = bboxes3d.corners
  File "/home/s/dev/mmdetection3d/mmdet3d/core/bbox/structures/lidar_box3d.py", line 74, in corners
    assert len(self.tensor) != 0
AssertionError
```

**Comment by ZCMax** [comment]
We will fix the bug ASAP.

**Comment by Comverser** [comment]
> The bug should be fixed in #1209, besides, what's the branch you are using?

I am using your latest version of develop branch.

There is something that I should provide. The custom KITTI dataset includes annotations that is outside of FoV.

For example,
Car 0.00 0 -1.37 **0 0 0 0** 1.60 1.88 5.28 -6.45 1.16 1.28 -0.04  **<-- Outside of FoV**
Car 0.00 1 0.26 1048.20 561.57 1593.11 767.63 2.10 3.26 5.73 3.42 1.88 12.82 -0.24
Car 0.00 0 0.70 **0 0 0 0** 2.08 2.18 5.26 2.60 1.42 3.09 -1.57   **<-- Not fusioned**

**Comment by Tai-Wang** [comment]
Sorry for the late reply. Do you still have the same bug after #1209 is merged?

**Comment by hyunduk0206** [comment]
What I can remember is I was using your latest version of develop branch at that time (Feb 2).
