### ISSUE TITLE
waymo dataset prepration: ValueError: file not exist: training/velodyne/0000000.bin

### ISSUE THREAD

**Issue by MinWang1997** [open-mmlab/mmdetection3d#1206]
Hi,

I followed the [ tutorials about the usage of MMDetection3D for waymo dataset](https://mmdetection3d.readthedocs.io/en/v0.15.0/datasets/waymo_det.html)
however, after running `python tools/create_data.py waymo --root-path ./data/waymo/ --out-dir ./data/waymo/ --workers 128 --extra-tag waymo
`
It raises the following error:

```
Traceback (most recent call last):
  File "tools/create_data.py", line 294, in <module>
    max_sweeps=args.max_sweeps)
  File "tools/create_data.py", line 197, in waymo_data_prep
    kitti.create_waymo_info_file(out_dir, info_prefix, max_sweeps=max_sweeps)
  File "/misc/data/private/m142_lidar/MinWang/SST/tools/data_converter/kitti_converter.py", line 184, in create_waymo_info_file
    max_sweeps=max_sweeps)
  File "/misc/data/private/m142_lidar/MinWang/SST/tools/data_converter/kitti_data_utils.py", line 445, in get_waymo_image_info
    return list(image_infos)
  File "/usrhomes/s1413/miniconda3/envs/sst_cuda11.3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usrhomes/s1413/miniconda3/envs/sst_cuda11.3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usrhomes/s1413/miniconda3/envs/sst_cuda11.3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usrhomes/s1413/miniconda3/envs/sst_cuda11.3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/misc/data/private/m142_lidar/MinWang/SST/tools/data_converter/kitti_data_utils.py", line 320, in map_func
    idx, path, training, relative_path, use_prefix_id=True)
  File "/misc/data/private/m142_lidar/MinWang/SST/tools/data_converter/kitti_data_utils.py", line 70, in get_velodyne_path
    relative_path, exist_check, use_prefix_id)
  File "/misc/data/private/m142_lidar/MinWang/SST/tools/data_converter/kitti_data_utils.py", line 33, in get_kitti_info_path
    raise ValueError('file not exist: {}'.format(file_path))
ValueError: file not exist: training/velodyne/0000000.bin
```
and then when I check the folder structure, there is no file in velodyne folder.

Do you know which step is missing? I used [pre-compiled pip/pip3 packages for Linux](https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md) as you suggested in [docs](https://mmdetection3d.readthedocs.io/en/v0.15.0/datasets/waymo_det.html)

Thanks!

**Comment by ZCMax** [comment]
So no file is in velodyne folder: `kitti-format/training/velodyne`? In fact, it should be generated by https://github.com/open-mmlab/mmdetection3d/blob/b4240bd665686b062e987a61ff33c4d5a57242cd/tools/create_data.py#L173.

**Comment by mazen44** [comment]
Make sure you unzipped the tar files. This usually happens when the script can't find .tfrecord files

**Comment by MinWang1997** [comment]
> Make sure you unzipped the tar files. This usually happens when the script can't find .tfrecord files

Thank you for your reminder!


> So no file is in velodyne folder: `kitti-format/training/velodyne`? In fact, it should be generated by
> 
> https://github.com/open-mmlab/mmdetection3d/blob/b4240bd665686b062e987a61ff33c4d5a57242cd/tools/create_data.py#L173
> 
> .
