### ISSUE TITLE
 name 'init_detector' is not defined

### ISSUE THREAD

**Issue by LucyXH** [open-mmlab/mmdetection3d#1234]
I am running the `inference_demo.ipynb` and I did not make any edits.

Run `python mmdet3d/utils/collect_env.py` outputs:
```
sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-16GB
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1+cu111
OpenCV: 4.5.1
MMCV: 1.3.13
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMDetection: 2.19.0
MMSegmentation: 0.20.1
MMDetection3D: 0.18.1+dabe3ff
```

The error is at this line of code `model = init_detector(config_file, checkpoint_file, device='cuda:0')`:
```
NameError: name 'init_detector' is not defined
```
Thank you!

**Comment by ZCMax** [comment]
It's bug, and it should be changed to `init_model`, we will fix it ASAP.

**Comment by LucyXH** [comment]
Thank you so much! I have another question. Do you support the split Nuscenes-mini in your code? I ran into this error:
```
AssertionError: Database version not found: ./data/nuscenes/v1.0-trainval
```
it seems like I cannot test on Nuscenes-mini?

**Comment by ZCMax** [comment]
We have supported nuscenes-mini datasets, please refer to https://github.com/open-mmlab/mmdetection3d/issues/1011, feel free to leave comments if you still have any questions.

**Comment by LucyXH** [comment]
Thank you for the reply. Now I can run the demo test on Nuscenes_mini. I went into another question. When I run 
```
python3 tools/test.py configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d.py checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_20210715_235813-4bed5239.pth --out fcos_nuscenes.pkl --eval mAP 
```
I get this error:
```
Traceback (most recent call last):
  File "tools/test.py", line 238, in <module>
    main()
  File "tools/test.py", line 176, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/ubuntu/mmdetection3d/mmdet3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: NuScenesMonoDataset: 'FileClient' object has no attribute 'get_local_path'
```
Do you know how I can fix this?

**Comment by ZCMax** [comment]
What's you mmcv version? You should update the mmcv version to satisfy the requirements in our doc.

**Comment by LucyXH** [comment]
Thank you for your reply. Here are the collect_env.py outputs:
```
sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-16GB
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1+cu111
OpenCV: 4.5.1
MMCV: 1.3.13
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMDetection: 2.19.0
MMSegmentation: 0.20.1
MMDetection3D: 0.18.1+dabe3ff
```
Which version should I update to?

**Comment by ZCMax** [comment]
Refer to our doc: https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/getting_started.md

**Comment by LucyXH** [comment]
Hi,

I have checked the versions of the 3 libraries and they satisfy the requirements on the first row of the table. 
mmdet>=2.19.0, <=3.0.0 | mmseg>=0.20.0, <=1.0.0 | mmcv-full>=1.3.8, <=1.5.0

Can you look at the error and see what else might be the reason? Thank you!

**Comment by ZCMax** [comment]
update mmcv >=1.3.16,  you can install the latest mmcv version directly.

**Comment by LucyXH** [comment]
Thank you so much! I updated mmcv to the newest version and get this error:
```
Traceback (most recent call last):
  File "tools/test.py", line 13, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/home/ubuntu/mmdetection3d/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/home/ubuntu/mmdetection3d/mmdet3d/apis/inference.py", line 11, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes,
  File "/home/ubuntu/mmdetection3d/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/ubuntu/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/mmdet/core/bbox/samplers/__init__.py", line 10, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: assign_score_withk_forward miss in module _ext
```
What might be the problem now?

**Comment by ZCMax** [comment]
Did you install mmcv-full? refer to https://github.com/open-mmlab/mmdetection/issues/6703

**Comment by LucyXH** [comment]
Yes, I did. I will try to reinstall mmcv-full like the post tomorrow and get back to you.

**Comment by LucyXH** [comment]
Thank you. Reinstalling mmcv-full works.

**Comment by SandeepMenonKodiak** [comment]
I am getting this error and reinstalling is not working
This is my trace
```
Traceback (most recent call last):
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/vehicle/source/offboard/ml/third_party/bevfusion/tools/test_dataloader.py", line 11, in <module>
    from mmdet.core import DistEvalHook
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmdet/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmdet/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmdet/site-packages/mmdet/core/bbox/samplers/__init__.py", line 10, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmdet/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmcv/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmcv/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmcv/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/external/python3_8_x86_64-unknown-linux-gnu/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

Any mmdet.core import is failing with this error.
I am using python 3.8 and cuda 11.7. Installing using a requirements file
```
mmcv == 1.4.0
mmcv-full == 1.4.0
mmdet == 2.20.0
```
