### ISSUE TITLE
Recieved key error:3 while training PointPillar on colab for kitti dataset

### ISSUE THREAD

**Issue by sparshgarg23** [open-mmlab/mmdetection3d#1253]
As per dataset preparations,I was able to obtain the pkl files for kitti dataset along with the reduced point cloud.
However during training,I got the following log message
```
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/mmdet/datasets/dataset_wrappers.py", line 178, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/content/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 357, in __getitem__
    data = self.prepare_train_data(idx)
  File "/content/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 150, in prepare_train_data
    input_dict = self.get_data_info(index)
  File "/content/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 114, in get_data_info
    info = self.data_infos[index]
KeyError: 3
```
I inspected the data obtained after loading  the pkl file and a random entry inside the pkl file looks like this
```
{'image': {'image_idx': 9,
  'image_path': 'training/image_2/000009.png',
  'image_shape': array([ 375, 1242])},
 'point_cloud': {'num_features': 4,
  'velodyne_path': 'training/velodyne/000009.bin'},
 'calib': {'P0': array([[721.5377,   0.    , 609.5593,   0.    ],
         [  0.    , 721.5377, 172.854 ,   0.    ],
         [  0.    ,   0.    ,   1.    ,   0.    ],
         [  0.    ,   0.    ,   0.    ,   1.    ]]),
  'P1': array([[ 721.5377,    0.    ,  609.5593, -387.5744],
         [   0.    ,  721.5377,  172.854 ,    0.    ],
         [   0.    ,    0.    ,    1.    ,    0.    ],
         [   0.    ,    0.    ,    0.    ,    1.    ]]),
  'P2': array([[7.215377e+02, 0.000000e+00, 6.095593e+02, 4.485728e+01],
         [0.000000e+00, 7.215377e+02, 1.728540e+02, 2.163791e-01],
         [0.000000e+00, 0.000000e+00, 1.000000e+00, 2.745884e-03],
         [0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00]]),
  'P3': array([[ 7.215377e+02,  0.000000e+00,  6.095593e+02, -3.395242e+02],
         [ 0.000000e+00,  7.215377e+02,  1.728540e+02,  2.199936e+00],
         [ 0.000000e+00,  0.000000e+00,  1.000000e+00,  2.729905e-03],
         [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]]),
  'R0_rect': array([[ 0.9999239 ,  0.00983776, -0.00744505,  0.        ],
         [-0.0098698 ,  0.9999421 , -0.00427846,  0.        ],
         [ 0.00740253,  0.00435161,  0.9999631 ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  1.        ]]),
  'Tr_velo_to_cam': array([[ 7.533745e-03, -9.999714e-01, -6.166020e-04, -4.069766e-03],
         [ 1.480249e-02,  7.280733e-04, -9.998902e-01, -7.631618e-02],
         [ 9.998621e-01,  7.523790e-03,  1.480755e-02, -2.717806e-01],
         [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]]),
  'Tr_imu_to_velo': array([[ 9.999976e-01,  7.553071e-04, -2.035826e-03, -8.086759e-01],
         [-7.854027e-04,  9.998898e-01, -1.482298e-02,  3.195559e-01],
         [ 2.024406e-03,  1.482454e-02,  9.998881e-01, -7.997231e-01],
         [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])},
 'annos': {'name': array(['Car', 'Car', 'Car', 'DontCare', 'DontCare'], dtype='<U8'),
  'truncated': array([ 0.,  0.,  0., -1., -1.]),
  'occluded': array([ 0,  2,  0, -1, -1], dtype=int64),
  'alpha': array([ -1.5 ,   1.75,   1.78, -10.  , -10.  ]),
  'bbox': array([[601.96, 177.01, 659.15, 229.51],
         [600.14, 177.09, 624.65, 193.31],
         [574.98, 178.64, 598.45, 194.01],
         [710.6 , 167.73, 736.68, 182.35],
         [758.52, 156.27, 782.52, 179.23]]),
  'dimensions': array([[ 3.2 ,  1.61,  1.66],
         [ 3.66,  1.44,  1.61],
         [ 3.37,  1.41,  1.53],
         [-1.  , -1.  , -1.  ],
         [-1.  , -1.  , -1.  ]]),
  'location': array([[ 7.000e-01,  1.760e+00,  2.388e+01],
         [ 2.400e-01,  1.840e+00,  6.637e+01],
         [-2.190e+00,  1.960e+00,  6.825e+01],
         [-1.000e+03, -1.000e+03, -1.000e+03],
         [-1.000e+03, -1.000e+03, -1.000e+03]]),
  'rotation_y': array([ -1.48,   1.76,   1.75, -10.  , -10.  ]),
  'score': array([0., 0., 0., 0., 0.]),
  'index': array([ 0,  1,  2, -1, -1]),
  'group_ids': array([0, 1, 2, 3, 4]),
  'difficulty': array([ 0, -1, -1, -1, -1]),
  'num_points_in_gt': array([215,   4,   1,  -1,  -1])}}
```

Any idea what I can do  to rectify the issue.I changed the number of workers from 4 to 2 but that didn't help the issue.

**Comment by sparshgarg23** [comment]
I was able to resolve the above issue by ensuring that my directory structure was similar to the one mentioned in getting started.md,but now I am getting another error 
When doing evaluation on the 2nd epoch,I ran into the following error
```
 File "tools/train.py", line 235, in <module>
    main()
  File "tools/train.py", line 231, in main
    meta=meta)
  File "/content/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/test.py", line 25, in single_gpu_test
    PALETTE = dataset.PALETTE
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError
```
System configuration is as follows
```
sys.platform: linux
Python: 3.7.12 (default, Jan 15 2022, 18:48:18) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla P100-PCIE-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu111
OpenCV: 4.1.2
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.21.0
MMSegmentation: 0.21.1
MMDetection3D: 0.18.1+86cc487
```
Any help in what could be the probable cause for this?

**Comment by sparshgarg23** [comment]
i am trying to train second on kitti 3 class to see if the same error happens.

**Comment by ZCMax** [comment]
Sorry for the late reply. What training command has been used? Have ever made any modifications? Which branch you are using?

**Comment by sparshgarg23** [comment]
I am using the latest branch.I haven't made any modifications in the code,and the training command is as follows
!python tools/train.py /content/mmdetection3d/configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py
The error is within mmdet which I am installing through pip.
```
File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/test.py", line 25, in single_gpu_test
    PALETTE = dataset.PALETTE
```

Hope that helps
