### ISSUE TITLE
Attribute error  while training PointPillar and SECOND on KITTI

### ISSUE THREAD

**Issue by sparshgarg23** [open-mmlab/mmdetection3d#1259]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help. Yes,I was able to trace the bug,and figure out the cause,and would like your opinion on how to resolve it on my end.
2. The bug has not been fixed in the latest version.

**Describe the bug**
While training SECOND/Point Pillar on KITTI3D when single_gpu_test.py is executed,an attribute error is raised.Inside the single_gpu_test.py there is a line 
```
 PALETTE = dataset.PALETTE
```
which is raising the error.

I looked at MMDetection version 2.19 and the specific line which is causing the error is not mentioned .As such ,I would like some help in figuring out which version of MMDet,MMSeg and MMDetection3d should I install,so that the above issue doesn't happen.

I tried training HRNet using MMSeg on ADE and there was no issues,same for SOLO.In both scenarios I used the master branch.

**Reproduction**
1. What command or script did you run?
```
python tools/train.py /content/mmdetection3d/configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? No modifications were made in the code,I am just testing it to get an idea of how the training process looks like.Once that's done,then I will customize the configurations.
3. What dataset did you use? KITTI 3D

**Environment**
Using colab
Enviroment/system config
```
sys.platform: linux
Python: 3.7.12 (default, Jan 15 2022, 18:48:18) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla P100-PCIE-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
 
  - CuDNN 8.0.5
  - Magma 2.5.2
  -

TorchVision: 0.11.1+cu111
OpenCV: 4.1.2
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.21.0
MMSegmentation: 0.21.1
MMDetection3D: 0.18.1+86cc487
```
1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] No I am using colab 
  

**Error traceback**
If applicable, paste the error trackback here.
```
File "tools/train.py", line 235, in <module>
    main()
  File "tools/train.py", line 231, in main
    meta=meta)
  File "/content/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/test.py", line 25, in single_gpu_test
    PALETTE = dataset.PALETTE
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError
```
```


**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
I think that I am not installing the correct version of MMDetection,because the master branch includes a term called PALETTE with the dataset but the branch 2.19 doesn't include the pallete term.
The problem is that when I install MMDetection via pip,it seems that pip ends up installing the master branch which causes an error when I run the training script on KITTI 3D.

**Comment by Tai-Wang** [comment]
Which codebase does the `PALETTE = dataset.PALETTE` report the error? I do not find it in MMDetection3D. You might enter an incorrect single_gpu_test of other codebase.

**Comment by yujmo** [comment]
2022-02-23 10:00:19,232 - mmdet - INFO - Epoch [1][1000/1238]   lr: 1.901e-03, eta: 11:16:26, time: 0.829, data_time: 0.006, memory: 5373, loss_cls: 0.2808, los122, loss: 1.2952, grad_norm: 2.0715
2022-02-23 10:01:00,468 - mmdet - INFO - Epoch [1][1050/1238]   lr: 1.912e-03, eta: 11:15:17, time: 0.825, data_time: 0.006, memory: 5373, loss_cls: 0.2808, los119, loss: 1.3017, grad_norm: 2.2219
2022-02-23 10:01:41,923 - mmdet - INFO - Epoch [1][1100/1238]   lr: 1.923e-03, eta: 11:14:20, time: 0.829, data_time: 0.006, memory: 5373, loss_cls: 0.2664, los101, loss: 1.2568, grad_norm: 2.1070
2022-02-23 10:02:23,130 - mmdet - INFO - Epoch [1][1150/1238]   lr: 1.934e-03, eta: 11:13:14, time: 0.824, data_time: 0.005, memory: 5373, loss_cls: 0.2641, los106, loss: 1.2316, grad_norm: 2.0202
2022-02-23 10:03:04,773 - mmdet - INFO - Epoch [1][1200/1238]   lr: 1.946e-03, eta: 11:12:28, time: 0.833, data_time: 0.006, memory: 5373, loss_cls: 0.2656, los123, loss: 1.2588, grad_norm: 2.1586
Traceback (most recent call last):
  File "tools/train.py", line 235, in <module>
    main()
  File "tools/train.py", line 231, in main    meta=meta)
  File "/home/autolab/moyujian/mmdetection3d/mmdetection3d_code/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/home/autolab/moyujian/mmdetection3d/mmdetection3d_code/mmdetection/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/autolab/moyujian/mmdetection3d/mmdetection3d_code/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/autolab/moyujian/mmdetection3d/mmdetection3d_code/mmcv/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/autolab/moyujian/mmdetection3d/mmdetection3d_code/mmcv/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/autolab/moyujian/mmdetection3d/mmdetection3d_code/mmcv/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/autolab/moyujian/mmdetection3d/mmdetection3d_code/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/autolab/moyujian/mmdetection3d/mmdetection3d_code/mmdetection/mmdet/apis/test.py", line 25, in single_gpu_test
    PALETTE = dataset.PALETTE
AttributeError: 'KittiDataset' object has no attribute 'PALETTE'

**Comment by yujmo** [comment]
![image](https://user-images.githubusercontent.com/23295281/155254556-c623c275-b13f-4174-aa1b-ccde8790cb78.png)

**Comment by sparshgarg23** [comment]
@Tai-Wang  The palette line is mentioned in mmdetection.apis.test
The script is executed when the eval_hook is launched.
Basically the order of execution is as follows
1.Train .py->MMDetection3D
2.Epoch _based_runner.py->MMCV
3.after_train_epoch hook
4.eval_hook
5.single_gpu_test ->MMDET.apis
Enclosed is the screenshot
![mmdet](https://user-images.githubusercontent.com/34626942/155263094-56dce65e-2a09-4ef0-a017-f141b243641f.png)

If needed ,shall I raise the same issue on MMdetection also.,

**Comment by yujmo** [comment]
https://github.com/open-mmlab/mmdetection/pull/7085

**Comment by sparshgarg23** [comment]
@yujmo  thanks,based on https://github.com/open-mmlab/mmdetection/pull/7085/files ,I should be installing the dev version of mmdet right?

**Comment by sparshgarg23** [comment]
@yujmo  try installing mmdet version 2.20,doing so does not raise any error

**Comment by yujmo** [comment]
> @yujmo try installing mmdet version 2.20,doing so does not raise any error

我修改了一下源代码。
![image](https://user-images.githubusercontent.com/23295281/155310505-2c119a6f-2a2a-4e02-9121-98f0509909cd.png)

我根据这个issue猜测dataset.PALETTE的目的是为了可视化。然后就直接将dataset.PALETTE设置为none。

https://github.com/open-mmlab/mmdetection/pull/7085

我使用second方法在kitti 3d数据集上自己训练了一下模型。目前这个问题是暂时解决了。训练过程中也能看到不同 Epoch 的结果。比如：
Result is saved to /tmp/tmp9bae6xqt/results.pkl.
2022-02-23 19:22:59,278 - mmdet - INFO - 
Car AP@0.70, 0.70, 0.70:
bbox AP:93.7786, 87.2924, 84.5486
bev  AP:88.6267, 82.8863, 78.7006
3d   AP:70.0678, 61.8733, 59.4702
aos  AP:93.40, 86.35, 83.09
Car AP@0.70, 0.50, 0.50:
bbox AP:93.7786, 87.2924, 84.5486
bev  AP:94.4477, 89.4506, 88.9558
3d   AP:94.3279, 89.0527, 88.4276
aos  AP:93.40, 86.35, 83.09

**Comment by shinya7y** [comment]
`PALETTE = getattr(dataset, 'PALETTE', None)` of the PR should have the same effect as the fix with `try` and `except` by @yujmo.
https://docs.python.org/3/library/functions.html#getattr

**Comment by sparshgarg23** [comment]
ok will look into it.

**Comment by Tai-Wang** [comment]
It seems like an issue related to upstream mmdet and mmseg, and I will just keep this issue open for several days for further feedback. (Currently I guess there should be a solution in the above discussion.)
