### ISSUE TITLE
CalledProcessError when evaluating on waymo dataset

### ISSUE THREAD

**Issue by QYChan** [open-mmlab/mmdetection3d#1271]
I got some error when evaluating on waymo dataset . I have generate `compute_detection_metrics_main` . 
``` [>>>>>>>>>>>>>>>>>>>>>>>>] 39987/39987, 6.4 task/s, elapsed: 6247s, ETA:     0s
Converting prediction to KITTI format
[>>>>>>>>>>>>>>>>>>>>>>>] 39987/39987, 383.4 task/s, elapsed: 104s, ETA:     0s
Result is saved to ./work_dirs/sst/results.pkl.
0 tfrecords found.
Start converting ...
completed: 0, elapsed: 0s

Finished ...
terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_filebuf::underflow error reading the file: iostream error
Aborted (core dumped)
Traceback (most recent call last):
  File "tools/train.py", line 230, in <module>
    main()
  File "tools/train.py", line 220, in main
    train_model(
  File "/data1/cqy/code/SST/mmdet3d/apis/train.py", line 27, in train_model
    train_detector(
  File "/opt/anaconda3/envs/SST/lib/python3.8/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/anaconda3/envs/SST/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/anaconda3/envs/SST/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/opt/anaconda3/envs/SST/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/anaconda3/envs/SST/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/opt/anaconda3/envs/SST/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 19, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/opt/anaconda3/envs/SST/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 361, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/data1/cqy/code/SST/mmdet3d/datasets/waymo_dataset.py", line 301, in evaluate
    ret_bytes = subprocess.check_output(
  File "/opt/anaconda3/envs/SST/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/anaconda3/envs/SST/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mmdet3d/core/evaluation/waymo_utils/compute_detection_metrics_main ./work_dirs/sst/results.bin data/waymo/waymo_format/gt.bin' returned non-zero exit status 134.

**Comment by ZCMax** [comment]
Have you ever test the success of compute_detection_metrics_main.so compilation?

**Comment by QYChan** [comment]
I just follow the guidance of [https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md#use-pre-compiled-pippip3-packages](url) and the mmdet3d official docs. For the test, do you mean to run the command line `bazel-bin/waymo_open_dataset/metrics/tools/compute_detection_metrics_main
waymo_open_dataset/metrics/tools/fake_predictions.bin
waymo_open_dataset/metrics/tools/fake_ground_truths.bin`?

**Comment by QYChan** [comment]
I trained pointpillar on waymo datatset. It seems to work properly.
I have a few questions about evaluation
1、Whether the tfrecord file used in evaluation?
2、I noticed that some files can not file in evaluation. It would influence the evaltaion results?
```[>                              ] 8/202, 0.0 task/s, elapsed: 862s, ETA: 20898s1071051 not found.
1084006 not found. 
[>>>>>>>>>>                   ] 71/202, 0.0 task/s, elapsed: 1890s, ETA:  3487s1074156 not found.
1074159 not found.
[>>>>>>>>>>>>>>>>>>          ] 131/202, 0.0 task/s, elapsed: 3041s, ETA:  1648s1191047 not found.
[>>>>>>>>>>>>>>>>>>>>>>      ] 159/202, 0.0 task/s, elapsed: 3701s, ETA:  1001s1185198 not found.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 202/202, 0.1 task/s, elapsed: 3842s, ETA:     0s

Finished ...
39986 examples found.

OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 0.677858] [mAPH 0.672234]
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0.596672] [mAPH 0.591624]


> I have solved the previous problem and retrain the model. But the evaluation results are all mAP0.
> 
> ```
> Converting prediction to KITTI format
> [>>>>>>>>>>>>>>>>>>>>>>>] 39987/39987, 355.6 task/s, elapsed: 112s, ETA:     0s
> Result is saved to ./work_dirs/225/results.pkl.
> 0 tfrecords found.
> Start converting ...
> completed: 0, elapsed: 0s
> 
> Finished ...
> 39950 examples found.
> 
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_SIGN_LEVEL_1: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_SIGN_LEVEL_2: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
> 
> 2022-02-27 03:26:39,977 - mmdet - INFO - Exp name: sst_waymoD5_1x_ped_cyc_8heads_3f.py
> 2022-02-27 03:26:40,001 - mmdet - INFO - Epoch(val) [12][39987]	Vehicle/L1 mAP: 0.0000, Vehicle/L1 mAPH: 0.0000, Vehicle/L2 mAP: 0.0000, Vehicle/L2 mAPH: 0.0000, Pedestrian/L1 mAP: 0.0000, Pedestrian/L1 mAPH: 0.0000, Pedestrian/L2 mAP: 0.0000, Pedestrian/L2 mAPH: 0.0000, Sign/L1 mAP: 0.0000, Sign/L1 mAPH: 0.0000, Sign/L2 mAP: 0.0000, Sign/L2 mAPH: 0.0000, Cyclist/L1 mAP: 0.0000, Cyclist/L1 mAPH: 0.0000, Cyclist/L2 mAP: 0.0000, Cyclist/L2 mAPH: 0.0000, Overall/L1 mAP: 0.0000, Overall/L1 mAPH: 0.0000, Overall/L2 mAP: 0.0000, Overall/L2 mAPH: 0.0000
> ```

**Comment by Tai-Wang** [comment]
- The formatting process should involve the raw tfrecord files.
- If there are not detected objects, no prediction files would be generated. That would not influence the evaluation. The printout message is just an indicator.
