### ISSUE TITLE
Error while training pointrcnn

### ISSUE THREAD

**Issue by konyul** [open-mmlab/mmdetection3d#1279]
training command : python3 tools/train.py configs/point_rcnn/point_rcnn_2x8_kitti-3d-3classes.py

when I train pointrcnn there is an error saying

Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/dataset_wrappers.py", line 176, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/spalab/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 361, in __getitem__
    data = self.prepare_train_data(idx)
  File "/spalab/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 155, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/spalab/mmdetection3d/mmdet3d/datasets/pipelines/transforms_3d.py", line 944, in __call__
    'Sampling based on distance is only applicable for CAM coord'
AssertionError: Sampling based on distance is only applicable for CAM coord

So I changed coord_type LIDAR To CAMERA and the the following error occurs
Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/dataset_wrappers.py", line 176, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/spalab/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 361, in __getitem__
    data = self.prepare_train_data(idx)
  File "/spalab/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 155, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/spalab/mmdetection3d/mmdet3d/datasets/pipelines/transforms_3d.py", line 348, in __call__
    points = points.cat([sampled_points, points])
  File "/spalab/mmdetection3d/mmdet3d/core/points/base_points.py", line 369, in cat
    assert all(isinstance(points, cls) for points in points_list)
AssertionError

**Comment by wHao-Wu** [comment]
Thanks for your attention. We will fix this problem asap.
