### ISSUE TITLE
python setup.py develop fail

### ISSUE THREAD

**Issue by huangxiaoxiao-5** [open-mmlab/mmdetection3d#1288]
running develop
running egg_info
writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing requirements to mmdet3d.egg-info/requires.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cpp' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.cu' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.h' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.cc' under directory 'mmdet3d/.mim/ops'
adding license file 'LICENSE'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
building 'mmdet3d.ops.spconv.sparse_conv_ext' extension
Emitting ninja build file /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/7] /usr/lcoal/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/reordering_cuda.cu -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering_cuda.o 
/usr/lcoal/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/reordering_cuda.cu -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
/bin/sh: 1: /usr/lcoal/cuda-10.1/bin/nvcc: not found
[2/7] /usr/lcoal/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/indice_cuda.cu -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice_cuda.o 
/usr/lcoal/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/indice_cuda.cu -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
/bin/sh: 1: /usr/lcoal/cuda-10.1/bin/nvcc: not found
[3/7] /usr/lcoal/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/maxpool_cuda.cu -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool_cuda.o 
/usr/lcoal/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/maxpool_cuda.cu -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
/bin/sh: 1: /usr/lcoal/cuda-10.1/bin/nvcc: not found
[4/7] c++ -MMD -MF /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o.d -pthread -B /home/hxx/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/all.cc -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o 
c++ -MMD -MF /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o.d -pthread -B /home/hxx/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/all.cc -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/all.cc:15:30: fatal error: cuda_runtime_api.h: 没有那个文件或目录
compilation terminated.
[5/7] c++ -MMD -MF /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool.o.d -pthread -B /home/hxx/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/maxpool.cc -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool.o 
c++ -MMD -MF /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool.o.d -pthread -B /home/hxx/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/maxpool.cc -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/hxx/mmdetection3d/mmdet3d/ops/spconv/include/spconv/maxpool.h:17:0,
                 from /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/maxpool.cc:15:
/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include/tensorview/tensorview.h:16:30: fatal error: cuda_runtime_api.h: 没有那个文件或目录
compilation terminated.
[6/7] c++ -MMD -MF /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o.d -pthread -B /home/hxx/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o 
c++ -MMD -MF /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o.d -pthread -B /home/hxx/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/hxx/mmdetection3d/mmdet3d/ops/spconv/include/spconv/geometry.h:18:0,
                 from /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc:15:
/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include/tensorview/tensorview.h:16:30: fatal error: cuda_runtime_api.h: 没有那个文件或目录
compilation terminated.
[7/7] c++ -MMD -MF /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering.o.d -pthread -B /home/hxx/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/reordering.cc -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering.o 
c++ -MMD -MF /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering.o.d -pthread -B /home/hxx/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/lcoal/cuda-10.1/include -I/home/hxx/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/reordering.cc -o /home/hxx/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/hxx/mmdetection3d/mmdet3d/ops/spconv/include/spconv/reordering.h:17:0,
                 from /home/hxx/mmdetection3d/mmdet3d/ops/spconv/src/reordering.cc:15:
/home/hxx/mmdetection3d/mmdet3d/ops/spconv/include/tensorview/tensorview.h:16:30: fatal error: cuda_runtime_api.h: 没有那个文件或目录
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 315, in <module>
    zip_safe=False)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/hxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by ZCMax** [comment]
Please run python mmdet3d/utils/collect_env.py to collect necessary environment infomation and paste it here. It seems to be the nvcc problem

**Comment by huangxiaoxiao-5** [comment]
> 请运行 python`mmdet3d/utils/collect_env.py`收集必要的环境信息并粘贴到这里。好像是nvcc的问题

i run pythonmmdet3d/utils/collect_env.py    but
Traceback (most recent call last):
  File "mmdet3d/utils/collect_env.py", line 6, in <module>
    import mmdet3d
ModuleNotFoundError: No module named 'mmdet3d'

**Comment by huangxiaoxiao-5** [comment]
> Please run python `mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here. It seems to be the nvcc problem

run python mmdet3d/utils/collect_env.py   but
Traceback (most recent call last):
  File "mmdet3d/utils/collect_env.py", line 6, in <module>
    import mmdet3d
ModuleNotFoundError: No module named 'mmdet3d'

**Comment by chenxu93** [comment]
I meet the same problem, did you solved it? @huangxiaoxiao-5

**Comment by Tai-Wang** [comment]
We need other printouts for your environment information instead of only the traceback error because it seems your machine does not have a suitable cuda configuration. Or you can basically run the mmdet collect_env.py.

**Comment by huangxiaoxiao-5** [comment]
> I meet the same problem, did you solved it? @huangxiaoxiao-5

yes ，I reinstall the CUDA
