### ISSUE TITLE
spconv headers not found

### ISSUE THREAD

**Issue by nullkatar** [open-mmlab/mmdetection3d#1312]
Hello mmdetection3d team! Thanks a lot for you great job! 

I wanted to install your package and faced an issue. Here what I did:
```
pip install mmdet3d
```
And here is the output which I get: 

```
   <whole output was not captured due to my terminal settings>
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/7] c++ -MMD -MF /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/maxpool.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/maxpool.cc -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/maxpool.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1
    FAILED: /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/maxpool.o
    c++ -MMD -MF /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/maxpool.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/maxpool.cc -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/maxpool.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1
    /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/maxpool.cc:15:10: fatal error: spconv/maxpool.h: No such file or directory
     #include <spconv/maxpool.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    [2/7] c++ -MMD -MF /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/indice.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/indice.cc -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1
    FAILED: /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/indice.o
    c++ -MMD -MF /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/indice.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/indice.cc -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1
    /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/indice.cc:15:10: fatal error: spconv/geometry.h: No such file or directory
     #include <spconv/geometry.h>
              ^~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [3/7] c++ -MMD -MF /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/reordering.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/reordering.cc -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/reordering.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1
    FAILED: /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/reordering.o
    c++ -MMD -MF /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/reordering.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/reordering.cc -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/reordering.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1
    /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/reordering.cc:15:10: fatal error: spconv/reordering.h: No such file or directory
     #include <spconv/reordering.h>
              ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [4/7] c++ -MMD -MF /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/all.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/all.cc -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1
    FAILED: /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/all.o
    c++ -MMD -MF /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/all.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/all.cc -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1
    /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/all.cc:16:10: fatal error: spconv/fused_spconv_ops.h: No such file or directory
     #include <spconv/fused_spconv_ops.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [5/7] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/reordering_cuda.cu -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/reordering_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_72,code=sm_72
    FAILED: /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/reordering_cuda.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/reordering_cuda.cu -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/reordering_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_72,code=sm_72
    /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/reordering_cuda.cu:16:10: fatal error: spconv/mp_helper.h: No such file or directory
     #include <spconv/mp_helper.h>
              ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [6/7] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/indice_cuda.cu -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/indice_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_72,code=sm_72
    FAILED: /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/indice_cuda.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/indice_cuda.cu -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/indice_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_72,code=sm_72
    /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/indice_cuda.cu:16:10: fatal error: spconv/indice.cu.h: No such file or directory
     #include <spconv/indice.cu.h>
              ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [7/7] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/maxpool_cuda.cu -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/maxpool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_72,code=sm_72
    FAILED: /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/maxpool_cuda.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/include -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/maxpool_cuda.cu -o /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/build/temp.linux-aarch64-3.6/mmdet3d/ops/spconv/src/maxpool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_72,code=sm_72
    /tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/mmdet3d/ops/spconv/src/maxpool_cuda.cu:16:10: fatal error: spconv/maxpool.h: No such file or directory
     #include <spconv/maxpool.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
        env=env)
      File "/usr/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/setup.py", line 315, in <module>
        zip_safe=False)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.6/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
        build_ext.build_extensions(self)
      File "/usr/local/lib/python3.6/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-51jh8ofo/mmdet3d_4313784293374002a310ea2a51eed22f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a67h4nhb/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/docker_centerpoint_gnn/.local/include/python3.6m/mmdet3d Check the logs for full command output.

```

Here is the output of `collect_env.py` where `mmdet3d` is commented out as sson as I cant install it. 

```
sys.platform: linux
Python: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
CUDA available: True
GPU 0: Xavier
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.0
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, USE_CUDA=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.7.0a0+78ed10c
OpenCV: 4.5.5
MMCV: 1.4.7
MMCV Compiler: n/a
MMCV CUDA Compiler: n/a
MMDetection: 2.22.0
MMSegmentation: 0.22.1
```
I doubt that environment  variables can help with this spconv issue, but I will also paste them here. 

```
PYTHONPATH=/home/docker_centerpoint_gnn/catkin_ws/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/docker_centerpoint_gnn/catkin_ws/src/centerpoint_gnn/src

LD_LIBRARY_PATH=/home/docker_centerpoint_gnn/catkin_ws/devel/lib:/opt/ros/noetic/lib:/usr/local/cuda/lib64:/usr/local/cuda-10.2/targets/aarch64-linux/lib:/usr/local/lib

PATH=/opt/ros/noetic/bin:/usr/local/cuda/bin:/usr/local/cuda-10.2/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Every other package was installed using pip. 

Thanks in advance for your help!

**Comment by nullkatar** [comment]
I resolved this issue. It was failing to build llvmlite due to too old version of LLVM.

**Comment by zzy-ucas** [comment]
@nullkatar Hi, I have met the same error. I have run `apt-get install llvm`, but it did not work for me. Do you remember how to resolve it? Thanks in advance!

**Comment by zhenjiaa** [comment]
> I resolved this issue. It was failing to build llvmlite due to too old version of LLVM.

hello, do you remember what the version of LLVM do you install.

**Comment by zzy-ucas** [comment]
> hello, do you remember what the version of LLVM do you install.

Hi, I have solved this problem. It was fixed by updating the mmdet3d's version. Thanks a lot!

**Comment by fire2323** [comment]
> > hello, do you remember what the version of LLVM do you install.
> 
> Hi, I have solved this problem. It was fixed by updating the mmdet3d's version. Thanks a lot!

please eleborate which version.

**Comment by reskipper** [comment]
I resolved it by running `git clone` and then `pip install -v -e` .
