### ISSUE TITLE
ImportError: /root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/ops/ball_query/ball_query_ext.cpython-38-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by zyrant** [open-mmlab/mmdetection3d#1323]
environment：
device: titan xp
torch:1.9.0+cu111
torchvision:1.9.0+cu111
cuda:11.1
mmcv: 1.4.6
mmdet: 2.22.0
mmseg: 0.21.0

issue： hello, I follow the [INSTALLATION](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation) to get a start of mmdet3d， when I try torch 1.7.0+cu11.0 to run `python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth`  all is ok.
but when I try torch:1.9.0+cu111, it gets a problem as follows:

`(base) root@container-7e5111a40c-dd4add68:~/autodl-tmp/mmdetection3d/mmdetection3d# python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 4, in <module>
    from mmdet3d.apis import inference_detector, init_model, show_result_meshlab
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/apis/inference.py", line 12, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes, Coord3DMode,
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/core/bbox/__init__.py", line 3, in <module>
    from .coders import DeltaXYZWLHRBBoxCoder
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/core/bbox/coders/__init__.py", line 6, in <module>
    from .fcos3d_bbox_coder import FCOS3DBBoxCoder
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/core/bbox/coders/fcos3d_bbox_coder.py", line 7, in <module>
    from ..structures import limit_period
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/core/bbox/structures/__init__.py", line 2, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/core/bbox/structures/base_box3d.py", line 8, in <module>
    from mmdet3d.ops import points_in_boxes_all, points_in_boxes_part
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/ops/__init__.py", line 6, in <module>
    from .ball_query import ball_query
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/ops/ball_query/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/ops/ball_query/ball_query.py", line 5, in <module>
    from . import ball_query_ext
ImportError: /root/autodl-tmp/mmdetection3d/mmdetection3d/mmdet3d/ops/ball_query/ball_query_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv`

how can i solve it?

**Comment by Qi-Zhangyang** [comment]
How can you solve this problem?

**Comment by zyrant** [comment]
rebuild the project.

**Comment by 1j10** [comment]
Which version of mmdetection3d are you using？help，I meet the same problem.
