### ISSUE TITLE
Getting Error at validation process, AttributeError: 'DataContainer' object has no attribute 'copy'

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection3d#1395]
I am using the model SECOND with config file **hv_second_secfpn_6x8_80e_kitti-3d-car.py**  and using the  **/mmdetection3d/tools/train.py** file for starting the workflow. After the training epoch, I get the below error as the process starts to run on the validation epoch. Secondly, regarding the GPU usage, the GPU utilization remains between 40-60%, is there anything that should be considered for optimal usage of GPU. 

```
  File "/workspace/mmdetection3d/tools/train.py", line 263, in <module>
    main()
  File "/workspace/mmdetection3d/tools/train.py", line 252, in main
    train_model(
  File "/workspace/mmdetection3d/mmdet3d/apis/train.py", line 64, in train_model
    train_detector(
  File "/workspace/mmdetection/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/workspace/mmcv/mmcv/runner/epoch_based_runner.py", line 128, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/workspace/mmcv/mmcv/runner/epoch_based_runner.py", line 55, in train
    self.call_hook('after_train_epoch')
  File "/workspace/mmcv/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/workspace/mmcv/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/workspace/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/workspace/mmdetection/mmdet/apis/test.py", line 27, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 359, in __getitem__
    return self.prepare_test_data(idx)
  File "/workspace/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 173, in prepare_test_data
    example = self.pipeline(input_dict)
  File "/workspace/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/workspace/mmdetection3d/mmdet3d/datasets/pipelines/test_time_aug.py", line 106, in __call__
    data = self.transforms(_results)
  File "/workspace/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/workspace/mmdetection/mmdet/datasets/pipelines/transforms.py", line 699, in __call__
    results[key] = mmcv.imnormalize(results[key], self.mean, self.std,
  File "/workspace/mmcv/mmcv/image/photometric.py", line 21, in imnormalize
    img = img.copy().astype(np.float32)
AttributeError: 'DataContainer' object has no attribute 'copy'
```
Below is the environmental details:
```
Python: 3.8.12 [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3080
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0
OpenCV: 4.5.5
MMCV: 1.4.7
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.3
MMDetection: 2.22.0
MMSegmentation: 0.22.1
MMDetection3D: 1.0.0rc0+6210e38
```

**Comment by ammaryasirnaich** [comment]
After looking into the type of `img` variable of `imnormalize() ` method , its of 'mmcv.parallel.data_container.DataContainer'. So tried to convert it into `img.data.numpy()` which removed the error but got stuck into `imnormalize_()`  method inside the  `image/photometric.py` giving the below error:
```
  File "/workspace/mmcv/mmcv/image/photometric.py", line 50, in imnormalize_
    cv2.subtract(img, mean, img)  # inplace
cv2.error: OpenCV(4.5.5) /io/opencv/modules/core/src/arithm.cpp:647: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
```

**Comment by ammaryasirnaich** [comment]
The issue was resolved there was a mistake in the configuration file corresponding to the `test_pipeline`
