### ISSUE TITLE
ValueError: cannot reshape array of size ... into shape (..)

### ISSUE THREAD

**Issue by tjdgus6255** [open-mmlab/mmdetection3d#1513]
Hello.

"python ./demo/pc_seg_demo.py ./bin_folder/model.bin configs/pointnet2/pointnet2_ssg_16x2_cosine_200e_scannet_seg-3d-20class.py work_dirs/pointnet2_ssg_16x2_cosine_200e_scannet_seg-3d-20class/latest.pth --device cuda:0 --out-dir ./demo_result --show --snapshot"

When I run above command, I got an Error like 

Traceback (most recent call last):
  File "./demo/pc_seg_demo.py", line 42, in <module>
    main()
  File "./demo/pc_seg_demo.py", line 29, in main
    result, data = inference_segmentor(model, args.pcd)
  File "/media/unstruct/T7/mmdetection3d/mmdet3d/apis/inference.py", line 313, in inference_segmentor
    data = test_pipeline(data)
  File "/media/unstruct/T7/mmdetection3d/mmdet3d/datasets/pipelines/compose.py", line 48, in __call__
    data = t(data)
  File "/media/unstruct/T7/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 422, in __call__
    points = points.reshape(-1, self.load_dim)
ValueError: cannot reshape array of size 4162240 into shape (6)

Using test .bin file(scene0000_00.bin), it works well. 

But, with my .bin file, it doesn't work.

I got my .bin file through the following process (point cloud -> .pcd -> .bin)

**Comment by tjdgus6255** [comment]
To add to that, I got .pcd file.
just run the command "rosrun pcl_ros pointcloud_to_pcd input:={**point cloud topic**} _binary:=true

**Comment by Tai-Wang** [comment]
Please check the point cloud dimension in your pcd file and make it consistent with the demo file.
Or you can change the corresponding setting in the config file.
