### ISSUE TITLE
TypeError: show_result() missing 2 required positional arguments: 'out_dir' and 'filename'

### ISSUE THREAD

**Issue by PengboLi1998** [open-mmlab/mmdetection3d#1527]
hello,when i run the pcd_demo.py to test my trained model.It throws the following errors,could you please help me ?
Use load_from_local loader
Traceback (most recent call last):
  File "/media/ketizu/086C03DE086C03DE/project1/fcaf3d-master/demo2.py", line 12, in <module>
    show_result_meshlab(data, result, out_dir)
  File "/media/ketizu/086C03DE086C03DE/project1/fcaf3d-master/mmdet3d/apis/inference.py", line 481, in show_result_meshlab
    file_name = show_det_result_meshlab(data, result, out_dir, score_thr,
  File "/media/ketizu/086C03DE086C03DE/project1/fcaf3d-master/mmdet3d/apis/inference.py", line 324, in show_det_result_meshlab
    show_result(
TypeError: show_result() missing 2 required positional arguments: 'out_dir' and 'filename'

Process finished with exit code 1

**Comment by Tai-Wang** [comment]
What command did you run? Please follow the [documentation](https://mmdetection3d.readthedocs.io/en/latest/demo.html) to provide corresponding variable to related arguments.
