### ISSUE TITLE
KeyError: 'pts_filename' when running demo on mini-nuscenes in colab 

### ISSUE THREAD

**Issue by tnezam** [open-mmlab/mmdetection3d#1549]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I ran tools/train.py configs/centerpoint/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py 
and successfully saved the latest.pth file. 
when trying to run demo the mentioned error occured

**Reproduction**
1. What command or script did you run?
!python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_mono3d.coco.json configs/centerpoint/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py work_dirs/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus/latest.pth

A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I just modified max_epochs to 1 in /configs/_base_/schedules/cyclic_20e.py
and also changed the v1-0.mini in the nuscenes/data folder to v1.0-trainval


4. What dataset did you use?
mini-nuscenes
**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
  sys.platform: linux
Python: 3.7.13 (default, Apr 24 2022, 01:04:09) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: x86_64-linux-gnu-gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.1.2
MMCV: 1.5.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.25.0
MMSegmentation: 0.25.0
MMDetection3D: 1.0.0rc2+14c5ded
spconv2.0: True
   

**Error traceback**
If applicable, paste the error trackback here.

/content/mmdetection/mmdetection3d/mmdet3d/models/backbones/mink_resnet.py:10: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  'Please follow `getting_started.md` to install MinkowskiEngine.`')
load checkpoint from local path: work_dirs/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus/latest.pth
The model and loaded state dict do not match exactly

size mismatch for pts_middle_encoder.conv_input.0.weight: copying a param with shape ('pts_middle_encoder.conv_input.0.weight', torch.Size([5, 16, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([16, 3, 3, 3, 5]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.0.conv1.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer1.0.conv1.weight', torch.Size([16, 16, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([16, 3, 3, 3, 16]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.0.conv2.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer1.0.conv2.weight', torch.Size([16, 16, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([16, 3, 3, 3, 16]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.1.conv1.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer1.1.conv1.weight', torch.Size([16, 16, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([16, 3, 3, 3, 16]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.1.conv2.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer1.1.conv2.weight', torch.Size([16, 16, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([16, 3, 3, 3, 16]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.2.0.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer1.2.0.weight', torch.Size([16, 32, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([32, 3, 3, 3, 16]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.0.conv1.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer2.0.conv1.weight', torch.Size([32, 32, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([32, 3, 3, 3, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.0.conv2.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer2.0.conv2.weight', torch.Size([32, 32, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([32, 3, 3, 3, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.1.conv1.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer2.1.conv1.weight', torch.Size([32, 32, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([32, 3, 3, 3, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.1.conv2.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer2.1.conv2.weight', torch.Size([32, 32, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([32, 3, 3, 3, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.2.0.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer2.2.0.weight', torch.Size([32, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.0.conv1.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer3.0.conv1.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.0.conv2.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer3.0.conv2.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.1.conv1.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer3.1.conv1.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.1.conv2.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer3.1.conv2.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.2.0.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer3.2.0.weight', torch.Size([64, 128, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([128, 3, 3, 3, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer4.0.conv1.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer4.0.conv1.weight', torch.Size([128, 128, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([128, 3, 3, 3, 128]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer4.0.conv2.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer4.0.conv2.weight', torch.Size([128, 128, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([128, 3, 3, 3, 128]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer4.1.conv1.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer4.1.conv1.weight', torch.Size([128, 128, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([128, 3, 3, 3, 128]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer4.1.conv2.weight: copying a param with shape ('pts_middle_encoder.encoder_layers.encoder_layer4.1.conv2.weight', torch.Size([128, 128, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([128, 3, 3, 3, 128]).
size mismatch for pts_middle_encoder.conv_out.0.weight: copying a param with shape ('pts_middle_encoder.conv_out.0.weight', torch.Size([128, 128, 3, 1, 1])) from checkpoint,the shape in current model is torch.Size([128, 3, 1, 1, 128]).
Traceback (most recent call last):
  File "demo/mono_det_demo.py", line 46, in <module>
    main()
  File "demo/mono_det_demo.py", line 33, in main
    result, data = inference_mono_3d_detector(model, args.image, args.ann)
  File "/content/mmdetection/mmdetection3d/mmdet3d/apis/inference.py", line 272, in inference_mono_3d_detector
    data = test_pipeline(data)
  File "/content/mmdetection/mmdetection3d/mmdet3d/datasets/pipelines/compose.py", line 48, in __call__
    data = t(data)
  File "/content/mmdetection/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 420, in __call__
    pts_filename = results['pts_filename']
KeyError: 'pts_filename'
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZCMax** [comment]
for point cloud 3d detector like centerpoint, you need to use `pcd_demo.py` instead of `mono_det_demo.py`, which is used for image-based monocular 3d detector.
