### ISSUE TITLE
cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query'

### ISSUE THREAD

**Issue by Chenzixi1** [open-mmlab/mmdetection3d#156]
Thanks for your nice work at first. Some errors in installing here.

**Install setting**
cuda = 9.2
torch = 1.5.0
mmcv-full = 1.1.4
mmdet = 2.4.0
mmdet3d = 0.6.0

**ERROR**
 File "/home/czx/mmdet2.4.0/mmdetection3d/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query' (/home/czx/mmdet2.4.0/mmdetection3d/mmdet3d/ops/ball_query/__init__.py)

**Other**
before this error, I solved pycocotools problem by this issue
https://github.com/open-mmlab/mmdetection/issues/3761

I am hard to find the solution, hope your help, thanks you.

**Comment by ZwwWayne** [comment]
Does your torch support CUDA-9.2? Did you run `python setup.py develop` in the root of MMDetection3d?

**Comment by Chenzixi1** [comment]
Hi, my torch support CUDA-9.2 and I have successfully used mmdetection before.

When run 'python setup.py develop', i got error:

writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing requirements to mmdet3d.egg-info/requires.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'mmdet3d/ops/**/*.cpp'
warning: no files found matching 'mmdet3d/ops/**/*.cu'
warning: no files found matching 'mmdet3d/ops/**/*.h'
warning: no files found matching 'mmdet3d/ops/**/*.cc'
warning: no files found matching 'mmdet3d/VERSION'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
 File "/home/czx/anaconda3/envs/open-mmlab3d/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/czx/anaconda3/envs/open-mmlab3d/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/czx/anaconda3/envs/open-mmlab3d/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/czx/anaconda3/envs/open-mmlab3d/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/czx/anaconda3/envs/open-mmlab3d/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/czx/anaconda3/envs/open-mmlab3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/czx/anaconda3/envs/open-mmlab3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/czx/anaconda3/envs/open-mmlab3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by Chenzixi1** [comment]
> Does your torch support CUDA-9.2? Did you run `python setup.py develop` in the root of MMDetection3d?

It support and successfully use MMdetection (2d), but failed when `python setup.py develop`

**Comment by ZwwWayne** [comment]
Your compilation failed. `No files matching` means the files are not found. Maybe you could try git clone a new complete mmdet3d and then compile it in the root directory.

**Comment by yan888t888** [comment]
so have you done wtih this bug? I get the same trouble, and have no idea on it, wish your help,plz.

**Comment by ginobilinie** [comment]
I encounter the same compiling error and tried to git clone a new copy for a 2nd compilation, while the error remains there.

**Comment by sisrfeng** [comment]
> Maybe you could try git clone a new complete mmdet3d and then compile it in the root directory.

I have tried several times:

>python setup.py develop

Then I get :


running develop
running egg_info
writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing requirements to mmdet3d.egg-info/requires.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'mmdet3d/ops/**/*.cpp'
warning: no files found matching 'mmdet3d/ops/**/*.cu'
warning: no files found matching 'mmdet3d/ops/**/*.h'
warning: no files found matching 'mmdet3d/ops/**/*.cc'
warning: no files found matching 'mmdet3d/VERSION'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
building 'mmdet3d.ops.spconv.sparse_conv_ext' extension
Emitting ninja build file /root/mmdetection/mmdetection3d/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /root/mmdetection/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/indice.o.d -pthread -B /root/anaconda3/compi
ler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/root/mmdetection/mmdetection3d/mm
det3d/ops/spconv/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/t
orch/csrc/api/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/lib/python3.8/site-packages/torch/include/T
HC -I/usr/local/cuda/include -I/root/anaconda3/include/python3.8 -c -c /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc -o /root/m
mdetection/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSI
ON_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /root/mmdetection/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/indice.o
c++ -MMD -MF /root/mmdetection/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/indice.o.d -pthread -B /root/anaconda3/compiler_co
mpat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/root/mmdetection/mmdetection3d/mmdet3d/
ops/spconv/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/torch/c
src/api/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/
usr/local/cuda/include -I/root/anaconda3/include/python3.8 -c -c /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc -o /root/mmdetec
tion/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAM
E=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/include/torch_utils.h:17:0,
                 from /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/include/spconv/spconv_ops.h:22,
                 from /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc:17:
/root/anaconda3/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: 没有那个文件或目录
 #include <cublas_v2.h>


compilation terminated.
[2/2] c++ -MMD -MF /root/mmdetection/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/all.o.d -pthread -B /root/anaconda3/compiler
_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/root/mmdetection/mmdetection3d/mmdet
3d/ops/spconv/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/torc
h/csrc/api/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/lib/python3.8/site-packages/torch/include/THC
-I/usr/local/cuda/include -I/root/anaconda3/include/python3.8 -c -c /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/src/all.cc -o /root/mmdetec
tion/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=s
parse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /root/mmdetection/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/all.o
c++ -MMD -MF /root/mmdetection/mmdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/all.o.d -pthread -B /root/anaconda3/compiler_compa
t -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/root/mmdetection/mmdetection3d/mmdet3d/ops
/spconv/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc
/api/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/usr
/local/cuda/include -I/root/anaconda3/include/python3.8 -c -c /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/src/all.cc -o /root/mmdetection/m
mdetection3d/build/temp.linux-x86_64-3.8/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_
conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/include/torch_utils.h:17:0,
                 from /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/include/spconv/fused_spconv_ops.h:22,
                 from /root/mmdetection/mmdetection3d/mmdet3d/ops/spconv/src/all.cc:16:
/root/anaconda3/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: 没有那个文件或目录
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "/root/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 139, in <module>
    setup(
  File "/root/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/root/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/root/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/root/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/root/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/root/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/root/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 473, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Thx!

**Comment by jhkim-spa** [comment]
did you solved this probloem?

**Comment by wHao-Wu** [comment]
There may be a solution:

If you pull some updates from any of mmcv, mmdet or mmdet3d, please remove the ./build folder in mmdetection3d:

```shell
pip uninstall mmdet3d
rm -rf ./build
find . -name "*.so" | xargs rm
```

Then recompiling from scratch as described in the instructions: https://mmdetection3d.readthedocs.io/en/latest/getting_started.html

**Comment by Liaoqing-up** [comment]
the same error！Have you solved it ?

**Comment by lyp19** [comment]
the same error！Have you solved it ?

**Comment by Light--** [comment]
same error here

**Comment by Jayden9912** [comment]
For my case, I pip install -e mmcv, mmsegmentation, mmdet under the same folder. 
-> home/Documents/mmcv
-> home/Documents/mmsegmentation
-> home/Documents/mmdetection

When you run python setup.py develop, the mmdetection3d folder should be under the same parent folder, meaning
-> home/Documents/mmdetection3d

This solves the error for my case. Hope this helps!

**Comment by ShaneCan** [comment]
> For my case, I pip install -e mmcv, mmsegmentation, mmdet under the same folder. -> home/Documents/mmcv -> home/Documents/mmsegmentation -> home/Documents/mmdetection
> 
> When you run python setup.py develop, the mmdetection3d folder should be under the same parent folder, meaning -> home/Documents/mmdetection3d
> 
> This solves the error for my case. Hope this helps!

hello, i have tried ur method , i download these repos and used  'pip install -e'  one by one, but the errors still,could you tell me the detail what you have done? 

i still have these:
    warning: no files found matching 'mmdet3d/ops/**/*.cpp'
    warning: no files found matching 'mmdet3d/ops/**/*.cu'
    warning: no files found matching 'mmdet3d/ops/**/*.h'
    warning: no files found matching 'mmdet3d/ops/**/*.cc'
    warning: no files found matching 'mmdet3d/VERSION'
    warning: no files found matching 'mmdet3d/model_zoo.yml'
    warning: no files found matching 'mmdet3d/configs/*/*.py'
    warning: no files found matching 'mmdet3d/configs/*/*.yml'
    warning: no files found matching 'mmdet3d/tools/*.py'
    warning: no files found matching 'mmdet3d/tools/*.sh'
    warning: no files found matching 'mmdet3d/tools/*/*.py'
    warning: no files found matching 'mmdet3d/demo/*/*'
    writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/new/mmdetection3d-0.13.0/setup.py", line 254, in <module>
        zip_safe=False)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 378, in build_extensions
        self._check_abi()
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 734, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/home/new/anaconda3/envs/mmd3d/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
    [end of output]

**Comment by Xutian-Ming** [comment]
just run python setup.py develop guys
