### ISSUE TITLE
Modify FCOS3D input size to 704x256, but it throws 'None type' error while test phase

### ISSUE THREAD

**Issue by erwangccc** [open-mmlab/mmdetection3d#1585]
I wonder know how to modify input size to 704x256 correctly. I change the input size to smaller size, but the training phase is weird.The loss go to zero at the beginning and go to normal later. However it will throw 'None type' error while test phase.

I add 'resize' dict into train_pipeline and test_pipeline to change image size before training, it looks like:

`dict(type='Resize', img_scale=img_size, keep_ratio=False),`

The error is:

> 2022-06-25 17:49:53,176 - mmdet - INFO - Saving checkpoint at 2 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 486/486, 8.8 task/s, elapsed: 55s, ETA:     0s
Formating bboxes of img_bbox
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 486/486, 54.6 task/s, elapsed: 9s, ETA:     0s
Results writes to /tmp/tmp3iivxrc2/results/img_bbox/results_nusc.json
Evaluating bboxes of img_bbox
Traceback (most recent call last):                                                                                                                                                                                          
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 252, in main
    train_model(
  File "/home/wangshaochang.wsc/wsc/workspace/code/mmdetection3d/mmdet3d/apis/train.py", line 344, in train_model
    train_detector(
  File "/home/wangshaochang.wsc/wsc/workspace/code/mmdetection3d/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 56, in train
    self.call_hook('after_train_epoch')
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 63, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 363, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/home/wangshaochang.wsc/wsc/workspace/code/mmdetection3d/mmdet3d/datasets/nuscenes_mono_dataset.py", line 703, in evaluate
    ret_dict = self._evaluate_single(result_files[name])
  File "/home/wangshaochang.wsc/wsc/workspace/code/mmdetection3d/mmdet3d/datasets/nuscenes_mono_dataset.py", line 586, in _evaluate_single
    nusc_eval = NuScenesEval(
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/nuscenes/eval/detection/evaluate.py", line 94, in __init__
    self.pred_boxes = filter_eval_boxes(nusc, self.pred_boxes, self.cfg.class_range, verbose=verbose)
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 219, in filter_eval_boxes
    class_field = _get_box_class_field(eval_boxes)
  File "/home/wangshaochang.wsc/anaconda3/envs/openmmlab/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 283, in _get_box_class_field
    raise Exception('Error: Invalid box type: %s' % box)
Exception: Error: Invalid box type: None

Do i miss something? Thanks in advance.

**Comment by erwangccc** [comment]
Maybe mmdet3d have no "Resize3D" for now. waiting for this feature.
