### ISSUE TITLE
Evaluate on NuScenes test set

### ISSUE THREAD

**Issue by Shiming94** [open-mmlab/mmdetection3d#1616]
hey, I tried to evaluate the performance of a pretrained PointPillars model on the NuScenes test set. I followed the instruction in the tutorial and changed the path like this:

https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/nus-3d.py#L132

However, I got the error as follows:
```
load checkpoint from local path: ./outputs/pointpillars_nuscenes_default/epoch_24.pth
[                                                  ] 0/6008, elapsed: 0s, ETA:/Data/Ubuntu_Default/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6008/6008, 4.1 task/s, elapsed: 1481s, ETA:     0s[[B^[[B^[[B^[[B^[[B^[[B^[[B
Formating bboxes of pts_bbox
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6008/6008, 46.0 task/s, elapsed: 131s, ETA:     0s
Results writes to /tmp/tmpyvjypall/results/pts_bbox/results_nusc.json
Evaluating bboxes of pts_bbox
Traceback (most recent call last):
  File "tools/test.py", line 260, in <module>
    main()
  File "tools/test.py", line 256, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/shimingwang/workspace/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 509, in evaluate
    ret_dict = self._evaluate_single(result_files[name])
  File "/home/shimingwang/workspace/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 403, in _evaluate_single
    eval_set=eval_set_map[self.version],
KeyError: 'v1.0-test'
```

Do you know how to solve this?

**Comment by Joaovsky** [comment]
Could you tell me how did you solve it? I want to use the same dataset for testing, but data_annotations.json file for v1.0-test has just an empty array inside, like this: []
