### ISSUE TITLE
Lyft Test Fail with KeyErr

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/mmdetection3d#1666]
I was running test.py on lyft data. My folder struict is as;
```
├── lyft_infos_test.pkl
├── lyft_infos_train.pkl
├── lyft_infos_val.pkl
├── test.txt
├── train.txt
├── v1.01-test -> images  lidar  maps  v1.01-test
├── v1.01-train -> images  lidar  maps  v1.01-train
└── val.txt
```
With command;

```
python tools/test.py configs/centerpoint/centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_lyft.py work_dirs/centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_lyft/latest.pth  --eval bbox
```
I got ;
```
Traceback (most recent call last):        
  File "tools/test.py", line 260, in <module>
    main()                                
  File "tools/test.py", line 256, in main 
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/capoom/mmdetection3d/mmdet3d/datasets/lyft_dataset.py", line 410, in evaluate
    ret_dict = self._evaluate_single(result_files[name])
  File "/home/capoom/mmdetection3d/mmdet3d/datasets/lyft_dataset.py", line 302, in _evaluate_single
    eval_set_map[self.version], output_dir, logger)
KeyError: 'v1.01-test'
```

I'm suspecting this [line](https://github.com/open-mmlab/mmdetection3d/blob/eb5a5a2d166d2d60dfbdffe63b925cb37a6541e3/mmdet3d/datasets/lyft_dataset.py#L298)

**Comment by Tai-Wang** [comment]
We do not support centerpoint on the Lyft for now. Do you modify the config by yourself to make it compatible with Lyft?
