### ISSUE TITLE
When I run the demo,error occurs as follows

### ISSUE THREAD

**Issue by X-ray0214** [open-mmlab/mmdetection3d#1687]
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 28, in <module>
    main()
  File "demo/pcd_demo.py", line 20, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home1/ugv/autodriving/BEVFusion-main/mmdet3d/apis/inference.py", line 51, in init_detector
    model = build_detector(config.model, train_cfg=None, test_cfg=config.get('test_cfg'))
  File "/home1/ugv/autodriving/BEVFusion-main/mmdet3d/models/builder.py", line 48, in build_detector
    return DETECTORS.build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/mnt/EXOS_AUTO/JIANG_FOLDER/anoconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
TypeError: build_model_from_cfg() got multiple values for argument 'registry'

Who can help me?

**Comment by Tai-Wang** [comment]
Please follow the template for re-implementation problems to provide more information about this issue.

**Comment by X-ray0214** [comment]
> Please follow the template for re-implementation problems to provide more information about this issue.
Hello, I just simply run the example:   python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

Maybe I need to modify "return self.build_func(*args, **kwargs, registry=self)" in registry.py?
