### ISSUE TITLE
Same validation and test configuration

### ISSUE THREAD

**Issue by holtvogt** [open-mmlab/mmdetection3d#1691]
Why is the test configuration in, e.g. [kitti-3d-car](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/kitti-3d-car.py) and [kitti-3d-3class](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/kitti-3d-3class.py) using the same pickle file, split and pipeline as the validation configuration? Shouldn't the test configuration be using the test pickle file and test split?

- Validation in kitti-3d-car:
  https://github.com/open-mmlab/mmdetection3d/blob/c8347b7ed933d70fcfbfb73a3541046b8c8e8f5e/configs/_base_/datasets/kitti-3d-car.py#L118

- Test in kitti-3d-car:
  https://github.com/open-mmlab/mmdetection3d/blob/c8347b7ed933d70fcfbfb73a3541046b8c8e8f5e/configs/_base_/datasets/kitti-3d-car.py#L129

**Comment by ZCMax** [comment]
If you want to run the model on test dataset, you need to change `kitti_infos_val.pkl` to `kitti_infos_test.pkl`, then just follow the instructions in https://mmdetection3d.readthedocs.io/en/latest/datasets/kitti_det.html.

**Comment by holtvogt** [comment]
Thanks! Won't I need to change the `split` parameter to `testing` as well? Or what's the meaning behind this parameter? Does it affect the data preparation?

**Comment by ZCMax** [comment]
yes, you need to change it to `testing` as well, `split` means split of input data. KITTI dataset is divided into `testing` and `training` part after data preparation, you can find the data directory in our doc.

**Comment by holtvogt** [comment]
By doing so, I receive this after using the testing command:

Command:
```shell
python tools/test.py <config.py> <checkpoint.pth> --eval mAP
```

Error:
```
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 31/31, 19.3 task/s, elapsed: 2s, ETA:     0s
Converting prediction to KITTI format
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 31/31, 9838.3 task/s, elapsed: 0s, ETA:     0s
Result is saved to /tmp/tmphn8c_znk/results.pkl.
Traceback (most recent call last):
  File "tools/test.py", line 260, in <module>
    main()
  File "tools/test.py", line 256, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/ws/x/Dokumente/Repositories/mmdetection3d/mmdet3d/datasets/itiv_dataset.py", line 201, in evaluate
    gt_annos = [info['annos'] for info in self.data_infos]
  File "/home/ws/x/Dokumente/Repositories/mmdetection3d/mmdet3d/datasets/itiv_dataset.py", line 201, in <listcomp>
    gt_annos = [info['annos'] for info in self.data_infos]
KeyError: 'annos'
```

Could that be related to a wrong data preparation (implementation)? Really don't know how to tackle this issue.

My config file (derived from PointPillars):
```python
model = dict(
    type='VoxelNet',
    voxel_layer=dict(
        max_num_points=32,
        point_cloud_range=[-1, -3, -3, 3, 1, 2],
        voxel_size=[0.16, 0.16, 4],
        max_voxels=(16000, 40000)),
    voxel_encoder=dict(
        type='PillarFeatureNet',
        in_channels=4,
        feat_channels=[64],
        with_distance=False,
        voxel_size=[0.16, 0.16, 4],
        point_cloud_range=[-1, -3, -3, 3, 1, 2]),
    middle_encoder=dict(
        type='PointPillarsScatter', in_channels=64, output_shape=[496, 432]),
    backbone=dict(
        type='SECOND',
        in_channels=64,
        layer_nums=[3, 5, 5],
        layer_strides=[2, 2, 2],
        out_channels=[64, 128, 256]),
    neck=dict(
        type='SECONDFPN',
        in_channels=[64, 128, 256],
        upsample_strides=[1, 2, 4],
        out_channels=[128, 128, 128]),
    bbox_head=dict(
        type='Anchor3DHead',
        num_classes=1,
        in_channels=384,
        feat_channels=384,
        use_direction_classifier=True,
        assign_per_class=True,
        anchor_generator=dict(
            type='AlignedAnchor3DRangeGenerator',
            ranges=[[-1, -3, -3, 3, 1, 2]],
            sizes=[[0.8, 0.6, 1.73]],
            rotations=[0, 1.57],
            reshape_out=True),
        diff_rad_by_sin=True,
        bbox_coder=dict(type='DeltaXYZWLHRBBoxCoder'),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=2.0),
        loss_dir=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.2)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            iou_calculator=dict(type='BboxOverlapsNearest3D'),
            pos_iou_thr=0.5,
            neg_iou_thr=0.35,
            min_pos_iou=0.35,
            ignore_iof_thr=-1),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        use_rotate_nms=True,
        nms_across_levels=False,
        nms_thr=0.01,
        score_thr=0.1,
        min_bbox_size=0,
        nms_pre=100,
        max_num=50))
dataset_type = 'ItivDataset'
data_root = 'data/itiv/'
class_names = ['Pedestrian']
input_modality = dict(use_lidar=True, use_camera=False)
file_client_args = dict(backend='disk')
db_sampler = dict(
    data_root='data/itiv/',
    info_path='data/itiv/itiv_dbinfos_train.pkl',
    rate=1.0,
    prepare=dict(
        filter_by_difficulty=[-1], filter_by_min_points=dict(Pedestrian=10)),
    classes=['Pedestrian'],
    sample_groups=dict(Pedestrian=20))
train_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=4,
        use_dim=4,
        file_client_args=dict(backend='disk')),
    dict(
        type='LoadAnnotations3D',
        with_bbox_3d=True,
        with_label_3d=True,
        file_client_args=dict(backend='disk')),
    dict(
        type='ObjectSample',
        db_sampler=dict(
            data_root='data/itiv/',
            info_path='data/itiv/itiv_dbinfos_train.pkl',
            rate=1.0,
            prepare=dict(
                filter_by_difficulty=[-1],
                filter_by_min_points=dict(Pedestrian=10)),
            classes=['Pedestrian'],
            sample_groups=dict(Pedestrian=20))),
    dict(
        type='ObjectNoise',
        num_try=100,
        translation_std=[1.0, 1.0, 0.5],
        global_rot_range=[0.0, 0.0],
        rot_range=[-0.78539816, 0.78539816]),
    dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
    dict(
        type='GlobalRotScaleTrans',
        rot_range=[-0.78539816, 0.78539816],
        scale_ratio_range=[0.95, 1.05]),
    dict(type='PointsRangeFilter', point_cloud_range=[-1, -3, -3, 3, 1, 2]),
    dict(type='ObjectRangeFilter', point_cloud_range=[-1, -3, -3, 3, 1, 2]),
    dict(type='PointShuffle'),
    dict(type='DefaultFormatBundle3D', class_names=['Pedestrian']),
    dict(type='Collect3D', keys=['points', 'gt_bboxes_3d', 'gt_labels_3d'])
]
test_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=4,
        use_dim=4,
        file_client_args=dict(backend='disk')),
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1333, 800),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(
                type='GlobalRotScaleTrans',
                rot_range=[0, 0],
                scale_ratio_range=[1.0, 1.0],
                translation_std=[0, 0, 0]),
            dict(type='RandomFlip3D'),
            dict(
                type='PointsRangeFilter',
                point_cloud_range=[-1, -3, -3, 3, 1, 2]),
            dict(
                type='DefaultFormatBundle3D',
                class_names=['Pedestrian'],
                with_label=False),
            dict(type='Collect3D', keys=['points'])
        ])
]
eval_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=4,
        use_dim=4,
        file_client_args=dict(backend='disk')),
    dict(
        type='DefaultFormatBundle3D',
        class_names=['Pedestrian'],
        with_label=False),
    dict(type='Collect3D', keys=['points'])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='RepeatDataset',
        times=4,
        dataset=dict(
            type='ItivDataset',
            data_root='data/itiv/',
            ann_file='data/itiv/itiv_infos_train.pkl',
            split='training',
            pts_prefix='velodyne',
            pipeline=[
                dict(
                    type='LoadPointsFromFile',
                    coord_type='LIDAR',
                    load_dim=4,
                    use_dim=4,
                    file_client_args=dict(backend='disk')),
                dict(
                    type='LoadAnnotations3D',
                    with_bbox_3d=True,
                    with_label_3d=True,
                    file_client_args=dict(backend='disk')),
                dict(
                    type='ObjectSample',
                    db_sampler=dict(
                        data_root='data/itiv/',
                        info_path='data/itiv/itiv_dbinfos_train.pkl',
                        rate=1.0,
                        prepare=dict(
                            filter_by_difficulty=[-1],
                            filter_by_min_points=dict(Pedestrian=10)),
                        classes=['Pedestrian'],
                        sample_groups=dict(Pedestrian=20))),
                dict(
                    type='ObjectNoise',
                    num_try=100,
                    translation_std=[1.0, 1.0, 0.5],
                    global_rot_range=[0.0, 0.0],
                    rot_range=[-0.78539816, 0.78539816]),
                dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
                dict(
                    type='GlobalRotScaleTrans',
                    rot_range=[-0.78539816, 0.78539816],
                    scale_ratio_range=[0.95, 1.05]),
                dict(
                    type='PointsRangeFilter',
                    point_cloud_range=[-1, -3, -3, 3, 1, 2]),
                dict(
                    type='ObjectRangeFilter',
                    point_cloud_range=[-1, -3, -3, 3, 1, 2]),
                dict(type='PointShuffle'),
                dict(type='DefaultFormatBundle3D', class_names=['Pedestrian']),
                dict(
                    type='Collect3D',
                    keys=['points', 'gt_bboxes_3d', 'gt_labels_3d'])
            ],
            modality=dict(use_lidar=True, use_camera=False),
            classes=['Pedestrian'],
            test_mode=False,
            box_type_3d='LiDAR')),
    val=dict(
        type='ItivDataset',
        data_root='data/itiv/',
        ann_file='data/itiv/itiv_infos_val.pkl',
        split='training',
        pts_prefix='velodyne',
        pipeline=[
            dict(
                type='LoadPointsFromFile',
                coord_type='LIDAR',
                load_dim=4,
                use_dim=4,
                file_client_args=dict(backend='disk')),
            dict(
                type='MultiScaleFlipAug3D',
                img_scale=(1333, 800),
                pts_scale_ratio=1,
                flip=False,
                transforms=[
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0, 0],
                        scale_ratio_range=[1.0, 1.0],
                        translation_std=[0, 0, 0]),
                    dict(type='RandomFlip3D'),
                    dict(
                        type='PointsRangeFilter',
                        point_cloud_range=[-1, -3, -3, 3, 1, 2]),
                    dict(
                        type='DefaultFormatBundle3D',
                        class_names=['Pedestrian'],
                        with_label=False),
                    dict(type='Collect3D', keys=['points'])
                ])
        ],
        modality=dict(use_lidar=True, use_camera=False),
        classes=['Pedestrian'],
        test_mode=True,
        box_type_3d='LiDAR'),
    test=dict(
        type='ItivDataset',
        data_root='data/itiv/',
        ann_file='data/itiv/itiv_infos_test.pkl',
        split='testing',
        pts_prefix='velodyne',
        pipeline=[
            dict(
                type='LoadPointsFromFile',
                coord_type='LIDAR',
                load_dim=4,
                use_dim=4,
                file_client_args=dict(backend='disk')),
            dict(
                type='MultiScaleFlipAug3D',
                img_scale=(1333, 800),
                pts_scale_ratio=1,
                flip=False,
                transforms=[
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0, 0],
                        scale_ratio_range=[1.0, 1.0],
                        translation_std=[0, 0, 0]),
                    dict(type='RandomFlip3D'),
                    dict(
                        type='PointsRangeFilter',
                        point_cloud_range=[-1, -3, -3, 3, 1, 2]),
                    dict(
                        type='DefaultFormatBundle3D',
                        class_names=['Pedestrian'],
                        with_label=False),
                    dict(type='Collect3D', keys=['points'])
                ])
        ],
        modality=dict(use_lidar=True, use_camera=False),
        classes=['Pedestrian'],
        test_mode=True,
        box_type_3d='LiDAR'))
evaluation = dict(
    interval=10,
    pipeline=[
        dict(
            type='LoadPointsFromFile',
            coord_type='LIDAR',
            load_dim=4,
            use_dim=4,
            file_client_args=dict(backend='disk')),
        dict(
            type='DefaultFormatBundle3D',
            class_names=['Pedestrian'],
            with_label=False),
        dict(type='Collect3D', keys=['points'])
    ])
lr = 0.000125
optimizer = dict(
    type='AdamW', lr=0.000125, betas=(0.95, 0.99), weight_decay=0.01)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='cyclic',
    target_ratio=(10, 0.0001),
    cyclic_times=1,
    step_ratio_up=0.4)
momentum_config = dict(
    policy='cyclic',
    target_ratio=(0.8947368421052632, 1),
    cyclic_times=1,
    step_ratio_up=0.4)
runner = dict(type='EpochBasedRunner', max_epochs=80)
checkpoint_config = dict(interval=1)
log_config = dict(
    interval=50,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = '/home/ws/x/Dokumente/Repositories/mmdetection3d/checkpoints/itiv/pointpillars'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
gpu_ids = [0]
```

My dataset implementation:
```python
import os
import tempfile
from os import path as osp

import mmcv
import numpy as np
from mmcv import print_log

from mmdet3d.core.evaluation import kitti_eval
from .builder import DATASETS
from .custom_3d import Custom3DDataset
from .pipelines import Compose
from ..core import show_result, Coord3DMode, CameraInstance3DBoxes
from ..core.bbox import (Box3DMode, LiDARInstance3DBoxes)


@DATASETS.register_module()
class ItivDataset(Custom3DDataset):
    r"""ITIV Dataset.

    Args:
        data_root (str): Path of dataset root.
        ann_file (str): Path of annotation file.
        split (str): Split of input data.
        pts_prefix (str, optional): Prefix of points files.
            Defaults to 'velodyne'.
        pipeline (list[dict], optional): Pipeline used for data processing.
            Defaults to None.
        classes (tuple[str], optional): Classes used in the dataset.
            Defaults to None.
        modality (dict, optional): Modality to specify the sensor data used
            as input. Defaults to None.
        box_type_3d (str, optional): Type of 3D box of this dataset.
            Based on the `box_type_3d`, the dataset will encapsulate the box
            to its original format then converted them to `box_type_3d`.
            Defaults to 'LiDAR' in this dataset. Available options includes
            - 'LiDAR': Box in LiDAR coordinates.
            - 'Depth': Box in depth coordinates, usually for indoor dataset.
            - 'Camera': Box in camera coordinates.
        filter_empty_gt (bool, optional): Whether to filter empty GT.
            Defaults to True.
        test_mode (bool, optional): Whether the dataset is in test mode.
            Defaults to False.
        pcd_limit_range (list, optional): The range of point cloud used to
            filter invalid predicted boxes.
            Default: [-1, -3, -3, 3, 1, 2].
    """

    CLASSES = ['pedestrian']

    def __init__(
            self,
            data_root,
            ann_file,
            split,
            pts_prefix='velodyne',
            pipeline=None,
            classes=None,
            modality=None,
            box_type_3d='LiDAR',
            filter_empty_gt=True,
            test_mode=False,
            pcd_limit_range=[-1, -3, -3, 3, 1, 2],
            **kwargs
    ):
        super().__init__(
            data_root=data_root,
            ann_file=ann_file,
            pipeline=pipeline,
            classes=classes,
            modality=modality,
            box_type_3d=box_type_3d,
            filter_empty_gt=filter_empty_gt,
            test_mode=test_mode,
            **kwargs)

        self.split = split
        self.root_split = os.path.join(self.data_root, split)
        assert self.modality is not None
        self.pcd_limit_range = pcd_limit_range
        self.pts_prefix = pts_prefix

    def _get_pts_filename(self, index):
        """Get point cloud filename according to the given index.

        Args:
            index (int): Index of the point cloud file to get.

        Returns:
            str: Name of the point cloud file.
        """

        pts_filename = osp.join(self.root_split, self.pts_prefix, f'{str(index)}.bin')
        return pts_filename

    def get_data_info(self, index):
        """Get data info according to the given index.

        Args:
            index (int): Index of the sample data to get.

        Returns:
            dict: Data information that will be passed to the data
                preprocessing pipelines. It includes the following keys:

                - sample_idx (str): Sample index.
                - pts_filename (str): Filename of point clouds.
                - ann_info (dict): Annotation info.
        """

        info = self.data_infos[index]
        sample_idx = info['image']['image_idx']
        pts_filename = self._get_pts_filename(sample_idx)
        input_dict = dict(sample_idx=sample_idx, pts_filename=pts_filename)

        if not self.test_mode:
            annotations = self.get_ann_info(index)
            input_dict['ann_info'] = annotations

        return input_dict

    def get_ann_info(self, index):
        """Get annotation info according to the given index.

        Args:
            index (int): Index of the annotation data to get.

        Returns:
            dict: annotation information consists of the following keys:
                - gt_bboxes_3d (:obj:`LiDARInstance3DBoxes`): 3D ground truth bboxes.
                - gt_labels_3d (np.ndarray): Labels of ground truths.
                - gt_names (list[str]): Class names of ground truths.
        """

        # Use index to get the annotations, thus the evalhook could also use this api
        info = self.data_infos[index]
        annotations = info['annos']
        loc = annotations['location']
        dims = annotations['dimensions']
        rots = annotations['rotation_y']
        gt_names_3d = annotations['name']

        gt_bboxes_3d = np.concatenate([loc, dims, rots[..., np.newaxis]], axis=1).astype(np.float32)
        # Convert gt_bboxes_3d to velodyne coordinates
        gt_bboxes_3d = CameraInstance3DBoxes(gt_bboxes_3d) \
            .convert_to(self.box_mode_3d, np.linalg.inv(np.identity(4) @ np.identity(4)))

        gt_labels_3d = []
        for category in gt_names_3d:
            if category in self.CLASSES:
                gt_labels_3d.append(self.CLASSES.index(category))
            else:
                gt_labels_3d.append(-1)
        gt_labels_3d = np.array(gt_labels_3d).astype(np.int64)

        annotation_results = dict(
            gt_bboxes_3d=gt_bboxes_3d,
            gt_labels_3d=gt_labels_3d,
            gt_names=gt_names_3d,
        )

        return annotation_results

    def evaluate(
            self,
            results,
            metric=None,
            logger=None,
            pklfile_prefix=None,
            submission_prefix=None,
            show=False,
            out_dir=None,
            pipeline=None
    ):
        """Evaluation in KITTI protocol.

        Args:
            results (list[dict]): Testing results of the dataset.
            metric (str | list[str], optional): Metrics to be evaluated.
                Default: None.
            logger (logging.Logger | str, optional): Logger used for printing
                related information during evaluation. Default: None.
            pklfile_prefix (str, optional): The prefix of pkl files, including
                the file path and the prefix of filename, e.g., "a/b/prefix".
                If not specified, a temp file will be created. Default: None.
            submission_prefix (str, optional): The prefix of submission data.
                If not specified, the submission data will not be generated.
                Default: None.
            show (bool, optional): Whether to visualize.
                Default: False.
            out_dir (str, optional): Path to save the visualization results.
                Default: None.
            pipeline (list[dict], optional): raw data loading for showing.
                Default: None.

        Returns:
            dict[str, float]: Results of each evaluation metric.
        """

        result_files, tmp_dir = self.format_results(results, pklfile_prefix)
        gt_annos = [info['annos'] for info in self.data_infos]

        ap_result_str, ap_dict = kitti_eval(gt_annos, result_files, self.CLASSES)
        print_log('\n' + ap_result_str, logger=logger)

        if tmp_dir is not None:
            tmp_dir.cleanup()

        if show or out_dir:
            self.show(results, out_dir, show=show, pipeline=pipeline)

        return ap_dict

    def format_results(self, outputs, pklfile_prefix=None, submission_prefix=None):
        """Format the results to pkl file.

        Args:
            outputs (list[dict]): Testing results of the dataset.
            pklfile_prefix (str): The prefix of pkl files. It includes
                the file path and the prefix of filename, e.g., "a/b/prefix".
                If not specified, a temp file will be created. Default: None.
            submission_prefix (str): The prefix of submitted files. It
                includes the file path and the prefix of filename, e.g.,
                "a/b/prefix". If not specified, a temp file will be created.
                Default: None.

        Returns:
            tuple: (result_files, tmp_dir), result_files is a dict containing
                the json filepaths, tmp_dir is the temporal directory created
                for saving json files when jsonfile_prefix is not specified.
        """
        if pklfile_prefix is None:
            tmp_dir = tempfile.TemporaryDirectory()
            pklfile_prefix = osp.join(tmp_dir.name, 'results')
        else:
            tmp_dir = None

        result_files = self.bbox2result_kitti(outputs, self.CLASSES, pklfile_prefix)
        return result_files, tmp_dir

    def bbox2result_kitti(self, net_outputs, class_names, pklfile_prefix=None):
        """Convert 3D detection results to kitti format for evaluation and test submission.

        Args:
            net_outputs (list[np.ndarray]): List of array storing the inferenced bounding boxes and scores.
            class_names (list[String]): A list of class names.
            pklfile_prefix (str): The prefix of pkl file.

        Returns:
            list[dict]: A list of dictionaries with the kitti format.
        """

        assert len(net_outputs) == len(self.data_infos), 'invalid list length of network outputs'

        det_annos = []
        print('\nConverting prediction to KITTI format')
        for idx, pred_dicts in enumerate(mmcv.track_iter_progress(net_outputs)):
            annos = []
            info = self.data_infos[idx]
            box_dict = self.convert_valid_bboxes(pred_dicts, info)
            anno = {
                'name': [],
                'truncated': [],
                'occluded': [],
                'alpha': [],
                'bbox': [],
                'dimensions': [],
                'location': [],
                'rotation_y': [],
                'score': []
            }
            if len(box_dict['box3d_lidar']) > 0:
                box_preds = box_dict['box3d_camera']
                box_preds_lidar = box_dict['box3d_lidar']
                scores = box_dict['scores']
                label_preds = box_dict['label_preds']

                for box, box_lidar, score, label in zip(box_preds, box_preds_lidar, scores, label_preds):
                    anno['name'].append(class_names[int(label)])
                    anno['truncated'].append(0.0)
                    anno['occluded'].append(0)
                    anno['alpha'].append(-np.arctan2(-box_lidar[1], box_lidar[0]) + box[6])
                    anno['bbox'].append([0.0, 0.0, 0.0, 0.0])
                    anno['dimensions'].append(box[3:6])
                    anno['location'].append(box[:3])
                    anno['rotation_y'].append(box[6])
                    anno['score'].append(score)

                anno = {k: np.stack(v) for k, v in anno.items()}
                annos.append(anno)
            else:
                anno = {
                    'name': np.array([]),
                    'truncated': np.array([]),
                    'occluded': np.array([]),
                    'alpha': np.array([]),
                    'bbox': np.zeros([0, 4]),
                    'dimensions': np.zeros([0, 3]),
                    'location': np.zeros([0, 3]),
                    'rotation_y': np.array([]),
                    'score': np.array([]),
                }
                annos.append(anno)

            det_annos += annos

        if pklfile_prefix is not None:
            if not pklfile_prefix.endswith(('.pkl', '.pickle')):
                out = f'{pklfile_prefix}.pkl'
            mmcv.dump(det_annos, out)
            print(f'Result is saved to {out}.')

        return det_annos

    def convert_valid_bboxes(self, box_dict, info):
        """Convert the predicted boxes into valid ones.

        Args:
            box_dict (dict): Box dictionaries to be converted.
                - boxes_3d (:obj:`LiDARInstance3DBoxes`): 3D bounding boxes.
                - scores_3d ()
                - labels_3d (torch.Tensor): Class labels of boxes.
            info (dict): Data info.

        Returns:
            dict: Valid predicted boxes.
                - box3d_camera (np.ndarray): 3D bounding boxes in camera coordinate.
                - box3d_lidar (np.ndarray): 3D bounding boxes in LiDAR coordinate.
                - scores (np.ndarray): The score.
                - label_preds (np.ndarray): Class label predictions.
                - sample_idx (int): Sample index.
        """

        box_preds = box_dict['boxes_3d']
        scores = box_dict['scores_3d']
        labels = box_dict['labels_3d']
        sample_idx = info['image']['image_idx']
        box_preds.limit_yaw(offset=0.5, period=np.pi * 2)

        if len(box_preds) == 0:
            return dict(
                box3d_camera=np.zeros([0, 7]),
                box3d_lidar=np.zeros([0, 7]),
                scores=np.zeros([0]),
                label_preds=np.zeros([0, 4]),
                sample_idx=sample_idx
            )

        box_preds_camera = box_preds.convert_to(Box3DMode.CAM)

        # Check box_preds
        limit_range = box_preds.tensor.new_tensor(self.pcd_limit_range)
        valid_pcd_inds = ((box_preds.center > limit_range[:3]) & (box_preds.center < limit_range[3:]))
        valid_inds = valid_pcd_inds.all(-1)

        if valid_pcd_inds.sum() > 0:
            return dict(
                box3d_camera=box_preds_camera[valid_inds].tensor.numpy(),
                box3d_lidar=box_preds[valid_inds].tensor.numpy(),
                scores=scores[valid_inds].numpy(),
                label_preds=labels[valid_inds].numpy(),
                sample_idx=sample_idx
            )
        else:
            return dict(
                box3d_camera=np.zeros([0, 7]),
                box3d_lidar=np.zeros([0, 7]),
                scores=np.zeros([0]),
                label_preds=np.zeros([0, 4]),
                sample_idx=sample_idx
            )

    def _build_default_pipeline(self):
        """Build the default pipeline for this dataset."""

        pipeline = [
            dict(
                type='LoadPointsFromFile',
                coord_type='LIDAR',
                load_dim=4,
                use_dim=4,
                file_client_args=dict(backend='disk')),
            dict(
                type='DefaultFormatBundle3D',
                class_names=self.CLASSES,
                with_label=False),
            dict(type='Collect3D', keys=['points'])
        ]
        if self.modality['use_camera']:
            pipeline.insert(0, dict(type='LoadImageFromFile'))
        return Compose(pipeline)

    def show(self, results, out_dir, show=True, pipeline=None):
        """Results visualization.

        Args:
            results (list[dict]): List of bounding boxes results.
            out_dir (str): Output directory of visualization result.
            show (bool): Whether to visualize the results online.
                Default: False.
            pipeline (list[dict], optional): raw data loading for showing.
                Default: None.
        """

        assert out_dir is not None, 'Expect out_dir, got none.'
        pipeline = self._get_pipeline(pipeline)
        for i, result in enumerate(results):
            if 'pts_bbox' in result.keys():
                result = result['pts_bbox']
            data_info = self.data_infos[i]
            pts_path = data_info['point_cloud']['velodyne_path']
            file_name = osp.split(pts_path)[-1].split('.')[0]
            points, img_metas, img = self._extract_data(i, pipeline, ['points', 'img_metas', 'img'])
            points = points.numpy()
            # For now, we convert points into depth mode
            points = Coord3DMode.convert_point(points, Coord3DMode.LIDAR, Coord3DMode.DEPTH)
            gt_bboxes = self.get_ann_info(i)['gt_bboxes_3d'].tensor.numpy()
            show_gt_bboxes = Box3DMode.convert(gt_bboxes, Box3DMode.LIDAR, Box3DMode.DEPTH)
            pred_bboxes = result['boxes_3d'].tensor.numpy()
            show_pred_bboxes = Box3DMode.convert(pred_bboxes, Box3DMode.LIDAR, Box3DMode.DEPTH)
            show_result(points, show_gt_bboxes, show_pred_bboxes, out_dir, file_name, show)

```

**Comment by Joaovsky** [comment]
I have the exact same problem... Did you solved it?

**Comment by ZCMax** [comment]
> By doing so, I receive this after using the testing command:
> 
> Command:
> 
> ```shell
> python tools/test.py <config.py> <checkpoint.pth> --eval mAP
> ```
> 
> Error:
> 
> ```
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 31/31, 19.3 task/s, elapsed: 2s, ETA:     0s
> Converting prediction to KITTI format
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 31/31, 9838.3 task/s, elapsed: 0s, ETA:     0s
> Result is saved to /tmp/tmphn8c_znk/results.pkl.
> Traceback (most recent call last):
>   File "tools/test.py", line 260, in <module>
>     main()
>   File "tools/test.py", line 256, in main
>     print(dataset.evaluate(outputs, **eval_kwargs))
>   File "/home/ws/x/Dokumente/Repositories/mmdetection3d/mmdet3d/datasets/itiv_dataset.py", line 201, in evaluate
>     gt_annos = [info['annos'] for info in self.data_infos]
>   File "/home/ws/x/Dokumente/Repositories/mmdetection3d/mmdet3d/datasets/itiv_dataset.py", line 201, in <listcomp>
>     gt_annos = [info['annos'] for info in self.data_infos]
> KeyError: 'annos'
> ```
> 
> I receive this with KITTI as well

For test dataset, we do not have annotations, you need to submit the generated results to test server.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/36950400/193049191-f559457d-c3c1-4dc9-99bc-6a150796003b.png">

**Comment by Joaovsky** [comment]
I did that, though I obtained inside results/kitti-3class the folder kitti_resultspts_bbox, a kitti_resultspts_bbox.pkl and a results_eval.pkl. 
Also, inside that folder I have 7518 .txt files (from 000000.txt to 007517.txt) that are all empty...
And both .pkl files have empty arrays and tensors

**Comment by holtvogt** [comment]
So, when using a custom, LiDAR-based dataset, MMDetection3D has no such testing functionality already implemented?

**Comment by Joaovsky** [comment]
Basically, they have unannotated data (images, point cloud). The problem is I need the annotations for the testing dataset and they don't have it. You can eitheir ask for submission to the website or do a training split and work with that new split as the test set.
