### ISSUE TITLE
ImportError: Please install petrel_client to enable PetrelBackend.

### ISSUE THREAD

**Issue by yeyang1021** [open-mmlab/mmdetection3d#170]
This error appeared when I was training nuScenes model

CUDA_VISIBLE_DEVICES=2 python tools/train.py configs/free_anchor/hv_pointpillars_regnet-3.2gf_fpn_sbn-all_free-anchor_strong-aug_4x8_3x_nus-3d.py

Traceback (most recent call last):
  File "tools/train.py", line 169, in <module>
    main()
  File "tools/train.py", line 165, in main
    meta=meta)
  File "/home/yeyang/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ImportError: Caught ImportError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 68, in __init__
    from petrel_client import client
ModuleNotFoundError: No module named 'petrel_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yeyang/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 293, in __getitem__                                                                            data = self.prepare_train_data(idx)
  File "/home/yeyang/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 150, in prepare_train_data
    example = self.pipeline(input_dict)                                                                                                                              File "/home/yeyang/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/yeyang/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 350, in __call__
    points = self._load_points(pts_filename)
  File "/home/yeyang/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 325, in _load_points
    self.file_client = mmcv.FileClient(**self.file_client_args)
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 224, in __init__
    self.client = self._backends[backend](**kwargs)
  File "/home/yeyang/anaconda3.7/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 71, in __init__
    raise ImportError('Please install petrel_client to enable '
ImportError: Please install petrel_client to enable PetrelBackend.

**Comment by Tai-Wang** [comment]
If you use local data, just comment the line 31-36 and uncomment the setting `file_client_args = dict(backend='disk')`.

**Comment by yeyang1021** [comment]
> If you use local data, just comment the line 31-36 and uncomment the setting `file_client_args = dict(backend='disk')`.

Thank you for your reply.
Which file are you referring to?

**Comment by Tai-Wang** [comment]
I refer to the modification of the config you use.

**Comment by YuriyPryyma** [comment]
Hi are there nay updates in this, Is it possible to write logs directly to s3 bucket?

**Comment by sandeepnmenon** [comment]
+1
I am also looking into ways of writing the logs directly to s3 bucket. Any updates on this?

**Comment by qishisuren123** [comment]
how to install petrel_client?When i use pip install petrel_client, i got :
ERROR: Could not find a version that satisfies the requirement petrel_client (from versions: none)
ERROR: No matching distribution found for petrel_client

**Comment by ztfmars** [comment]
any update for  petrel_client?

**Comment by 9p15p** [comment]
you can try to `pip install boto3`

**Comment by twythebest** [comment]
> 如何安装 petrel_client？当我使用 pip install petrel_client时，我收到：错误：找不到满足petrel_client要求的版本（来自版本：无）错误：找不到 petrel_client 的匹配发行版

SO What's the solution to solve this problem?

**Comment by torinchen** [comment]
petrel_client is a package inside sensetime :)
