### ISSUE TITLE
Cuda out of memory when training Point_RCNN on KITTI dataset

### ISSUE THREAD

**Issue by hu-de** [open-mmlab/mmdetection3d#1749]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.  Yes
2. The bug has not been fixed in the latest version. Yes

**Describe the bug**
Cuda out of memory when training Point_RCNN on KITTI dataset.
During training,the memory usage keeps increasing dramatically.

**Reproduction**

1. What command or script did you run?

```
python tools/train.py configs/point_rcnn/point_rcnn_2x8_kitti-3d-3classes.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? No Yes
3. What dataset did you use? KITTI

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3080
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.11.1
OpenCV: 4.3.0
MMCV: 1.6.1
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.25.1
MMSegmentation: 0.27.0
MMDetection3D: 1.0.0rc4+9556958
spconv2.0: True
**Error traceback**
If applicable, paste the error trackback here.

```
2022-08-20 09:31:36,728 - mmdet - INFO - Epoch [1][30/3712]    lr: 1.000e-03, eta: 3 days, 8:58:31, time: 0.982, data_time: 0.526, memory: 4559, bbox_loss: 2.2376, semantic_loss: 0.4257, loss_cls: 0.3434, loss_bbox: 1.9154, loss_corner: 1.0903, loss: 6.0124, grad_norm: 192.7253
2022-08-20 09:31:49,606 - mmdet - INFO - Epoch [1][60/3712]    lr: 1.000e-03, eta: 2 days, 10:11:03, time: 0.429, data_time: 0.004, memory: 4658, bbox_loss: 1.8089, semantic_loss: 0.2337, loss_cls: 0.3750, loss_bbox: 2.3162, loss_corner: 1.4340, loss: 6.1679, grad_norm: 152.6836
2022-08-20 09:32:02,101 - mmdet - INFO - Epoch [1][90/3712]    lr: 1.000e-03, eta: 2 days, 2:14:05, time: 0.417, data_time: 0.004, memory: 4757, bbox_loss: 1.6605, semantic_loss: 0.2032, loss_cls: 0.4846, loss_bbox: 0.9560, loss_corner: 2.8054, loss: 6.1097, grad_norm: 285.2393
2022-08-20 09:32:14,711 - mmdet - INFO - Epoch [1][120/3712]    lr: 1.000e-03, eta: 1 day, 22:20:11, time: 0.420, data_time: 0.004, memory: 4864, bbox_loss: 1.5899, semantic_loss: 0.1762, loss_cls: 0.4802, loss_bbox: 0.7378, loss_corner: 0.3347, loss: 3.3189, grad_norm: 13.3738
2022-08-20 09:32:27,321 - mmdet - INFO - Epoch [1][150/3712]    lr: 1.000e-03, eta: 1 day, 19:59:48, time: 0.420, data_time: 0.004, memory: 4972, bbox_loss: 1.5247, semantic_loss: 0.1608, loss_cls: 0.5067, loss_bbox: 0.4800, loss_corner: 0.1599, loss: 2.8322, grad_norm: 5.9468
2022-08-20 09:32:39,864 - mmdet - INFO - Epoch [1][180/3712]    lr: 1.000e-03, eta: 1 day, 18:24:16, time: 0.418, data_time: 0.004, memory: 5079, bbox_loss: 1.5167, semantic_loss: 0.1573, loss_cls: 0.4771, loss_bbox: 0.4534, loss_corner: 0.1550, loss: 2.7595, grad_norm: 5.4157
2022-08-20 09:32:52,541 - mmdet - INFO - Epoch [1][210/3712]    lr: 1.000e-03, eta: 1 day, 17:19:08, time: 0.423, data_time: 0.004, memory: 5187, bbox_loss: 1.4491, semantic_loss: 0.1523, loss_cls: 0.5051, loss_bbox: 0.6604, loss_corner: 0.1683, loss: 2.9351, grad_norm: 6.0194
2022-08-20 09:33:05,035 - mmdet - INFO - Epoch [1][240/3712]    lr: 1.000e-03, eta: 1 day, 16:26:28, time: 0.416, data_time: 0.004, memory: 5295, bbox_loss: 1.4505, semantic_loss: 0.1390, loss_cls: 0.4660, loss_bbox: 0.6184, loss_corner: 0.2304, loss: 2.9043, grad_norm: 6.3770
2022-08-20 09:33:17,531 - mmdet - INFO - Epoch [1][270/3712]    lr: 1.000e-03, eta: 1 day, 15:45:29, time: 0.417, data_time: 0.004, memory: 5403, bbox_loss: 1.4000, semantic_loss: 0.1447, loss_cls: 0.5298, loss_bbox: 0.5165, loss_corner: 0.1062, loss: 2.6973, grad_norm: 3.3602
2022-08-20 09:33:30,177 - mmdet - INFO - Epoch [1][300/3712]    lr: 1.000e-03, eta: 1 day, 15:15:08, time: 0.422, data_time: 0.004, memory: 5510, bbox_loss: 1.4125, semantic_loss: 0.1491, loss_cls: 0.4866, loss_bbox: 0.4681, loss_corner: 0.1748, loss: 2.6910, grad_norm: 5.2273
2022-08-20 09:33:42,847 - mmdet - INFO - Epoch [1][330/3712]    lr: 1.000e-03, eta: 1 day, 14:50:38, time: 0.422, data_time: 0.004, memory: 5618, bbox_loss: 1.3546, semantic_loss: 0.1352, loss_cls: 0.5391, loss_bbox: 0.4956, loss_corner: 0.1598, loss: 2.6842, grad_norm: 5.2620
2022-08-20 09:33:55,504 - mmdet - INFO - Epoch [1][360/3712]    lr: 1.000e-03, eta: 1 day, 14:29:59, time: 0.422, data_time: 0.004, memory: 5726, bbox_loss: 1.4116, semantic_loss: 0.1270, loss_cls: 0.5266, loss_bbox: 0.5375, loss_corner: 0.1685, loss: 2.7712, grad_norm: 7.1991
2022-08-20 09:34:08,276 - mmdet - INFO - Epoch [1][390/3712]    lr: 1.000e-03, eta: 1 day, 14:13:57, time: 0.426, data_time: 0.004, memory: 5833, bbox_loss: 1.3292, semantic_loss: 0.1290, loss_cls: 0.5563, loss_bbox: 0.4627, loss_corner: 0.1551, loss: 2.6323, grad_norm: 5.6520
2022-08-20 09:34:21,116 - mmdet - INFO - Epoch [1][420/3712]    lr: 1.000e-03, eta: 1 day, 14:00:58, time: 0.428, data_time: 0.004, memory: 5941, bbox_loss: 1.3018, semantic_loss: 0.1253, loss_cls: 0.5526, loss_bbox: 0.4271, loss_corner: 0.1642, loss: 2.5710, grad_norm: 6.1574
2022-08-20 09:34:34,077 - mmdet - INFO - Epoch [1][450/3712]    lr: 1.000e-03, eta: 1 day, 13:51:02, time: 0.432, data_time: 0.004, memory: 6049, bbox_loss: 1.2506, semantic_loss: 0.1218, loss_cls: 0.5785, loss_bbox: 0.5213, loss_corner: 0.1838, loss: 2.6560, grad_norm: 7.2216
2022-08-20 09:34:46,877 - mmdet - INFO - Epoch [1][480/3712]    lr: 1.000e-03, eta: 1 day, 13:40:38, time: 0.427, data_time: 0.004, memory: 6156, bbox_loss: 1.2416, semantic_loss: 0.1246, loss_cls: 0.5591, loss_bbox: 0.4573, loss_corner: 0.1813, loss: 2.5638, grad_norm: 6.9663
2022-08-20 09:34:59,762 - mmdet - INFO - Epoch [1][510/3712]    lr: 1.000e-03, eta: 1 day, 13:32:16, time: 0.430, data_time: 0.004, memory: 6264, bbox_loss: 1.2168, semantic_loss: 0.1192, loss_cls: 0.5640, loss_bbox: 0.4456, loss_corner: 0.1438, loss: 2.4894, grad_norm: 5.2395
2022-08-20 09:35:12,730 - mmdet - INFO - Epoch [1][540/3712]    lr: 1.000e-03, eta: 1 day, 13:25:34, time: 0.432, data_time: 0.004, memory: 6372, bbox_loss: 1.2345, semantic_loss: 0.1171, loss_cls: 0.5845, loss_bbox: 0.4180, loss_corner: 0.1463, loss: 2.5004, grad_norm: 6.9833
2022-08-20 09:35:25,688 - mmdet - INFO - Epoch [1][570/3712]    lr: 1.001e-03, eta: 1 day, 13:19:28, time: 0.432, data_time: 0.004, memory: 6480, bbox_loss: 1.2270, semantic_loss: 0.1177, loss_cls: 0.5803, loss_bbox: 0.4941, loss_corner: 0.1193, loss: 2.5383, grad_norm: 4.0356
2022-08-20 09:35:38,833 - mmdet - INFO - Epoch [1][600/3712]    lr: 1.001e-03, eta: 1 day, 13:15:29, time: 0.438, data_time: 0.004, memory: 6587, bbox_loss: 1.2127, semantic_loss: 0.1179, loss_cls: 0.5644, loss_bbox: 0.4304, loss_corner: 0.1484, loss: 2.4738, grad_norm: 5.6659
2022-08-20 09:35:51,792 - mmdet - INFO - Epoch [1][630/3712]    lr: 1.001e-03, eta: 1 day, 13:10:24, time: 0.432, data_time: 0.004, memory: 6695, bbox_loss: 1.1962, semantic_loss: 0.1167, loss_cls: 0.5997, loss_bbox: 0.4383, loss_corner: 0.1402, loss: 2.4909, grad_norm: 5.4718
2022-08-20 09:36:04,882 - mmdet - INFO - Epoch [1][660/3712]    lr: 1.001e-03, eta: 1 day, 13:06:45, time: 0.436, data_time: 0.004, memory: 6803, bbox_loss: 1.1913, semantic_loss: 0.1163, loss_cls: 0.5911, loss_bbox: 0.4789, loss_corner: 0.1291, loss: 2.5068, grad_norm: 5.8510
2022-08-20 09:36:17,722 - mmdet - INFO - Epoch [1][690/3712]    lr: 1.001e-03, eta: 1 day, 13:01:36, time: 0.428, data_time: 0.004, memory: 6911, bbox_loss: 1.1369, semantic_loss: 0.1095, loss_cls: 0.6066, loss_bbox: 0.4638, loss_corner: 0.1482, loss: 2.4650, grad_norm: 4.8240
2022-08-20 09:36:30,699 - mmdet - INFO - Epoch [1][720/3712]    lr: 1.001e-03, eta: 1 day, 12:57:49, time: 0.433, data_time: 0.004, memory: 7019, bbox_loss: 1.1352, semantic_loss: 0.1176, loss_cls: 0.6016, loss_bbox: 0.4131, loss_corner: 0.1382, loss: 2.4058, grad_norm: 3.7785
2022-08-20 09:36:43,731 - mmdet - INFO - Epoch [1][750/3712]    lr: 1.001e-03, eta: 1 day, 12:54:40, time: 0.434, data_time: 0.004, memory: 7127, bbox_loss: 1.0977, semantic_loss: 0.1064, loss_cls: 0.5898, loss_bbox: 0.3641, loss_corner: 0.1231, loss: 2.2811, grad_norm: 4.6418
2022-08-20 09:36:56,468 - mmdet - INFO - Epoch [1][780/3712]    lr: 1.001e-03, eta: 1 day, 12:49:52, time: 0.425, data_time: 0.004, memory: 7234, bbox_loss: 1.1301, semantic_loss: 0.1070, loss_cls: 0.6041, loss_bbox: 0.4201, loss_corner: 0.1224, loss: 2.3837, grad_norm: 4.7472
2022-08-20 09:37:09,487 - mmdet - INFO - Epoch [1][810/3712]    lr: 1.001e-03, eta: 1 day, 12:47:08, time: 0.434, data_time: 0.004, memory: 7342, bbox_loss: 1.0637, semantic_loss: 0.0962, loss_cls: 0.5883, loss_bbox: 0.4070, loss_corner: 0.1124, loss: 2.2676, grad_norm: 4.0467
2022-08-20 09:37:22,412 - mmdet - INFO - Epoch [1][840/3712]    lr: 1.001e-03, eta: 1 day, 12:44:02, time: 0.431, data_time: 0.004, memory: 7450, bbox_loss: 1.1050, semantic_loss: 0.1062, loss_cls: 0.5895, loss_bbox: 0.4363, loss_corner: 0.1478, loss: 2.3847, grad_norm: 4.6095
2022-08-20 09:37:35,188 - mmdet - INFO - Epoch [1][870/3712]    lr: 1.001e-03, eta: 1 day, 12:40:17, time: 0.426, data_time: 0.004, memory: 7558, bbox_loss: 1.0901, semantic_loss: 0.1021, loss_cls: 0.5900, loss_bbox: 0.4102, loss_corner: 0.1246, loss: 2.3171, grad_norm: 4.4261
2022-08-20 09:37:48,001 - mmdet - INFO - Epoch [1][900/3712]    lr: 1.001e-03, eta: 1 day, 12:36:59, time: 0.427, data_time: 0.004, memory: 7666, bbox_loss: 1.0500, semantic_loss: 0.1001, loss_cls: 0.5824, loss_bbox: 0.4249, loss_corner: 0.1201, loss: 2.2775, grad_norm: 5.9724
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 259, in main
    meta=meta)
  File "/opt/mmdetection3d/mmdet3d/apis/train.py", line 351, in train_model
    meta=meta)
  File "/opt/mmdetection3d/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/opt/mmdetection3d/mmdet3d/models/detectors/base.py", line 60, in forward
    return self.forward_train(**kwargs)
  File "/opt/mmdetection3d/mmdet3d/models/detectors/point_rcnn.py", line 105, in forward_train
    gt_labels_3d)
  File "/opt/mmdetection3d/mmdet3d/models/roi_heads/point_rcnn_roi_head.py", line 112, in forward_train
    sample_results)
  File "/opt/mmdetection3d/mmdet3d/models/roi_heads/point_rcnn_roi_head.py", line 181, in _bbox_forward_train
    bbox_results = self._bbox_forward(features, points, batch_size, rois)
  File "/opt/mmdetection3d/mmdet3d/models/roi_heads/point_rcnn_roi_head.py", line 210, in _bbox_forward
    cls_score, bbox_pred = self.bbox_head(pooled_point_feats)
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/mmdetection3d/mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py", line 227, in forward
    self.SA_modules[i](l_xyz[i], l_features[i])
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/mmdetection3d/mmdet3d/ops/pointnet_modules/point_sa_module.py", line 219, in forward
    new_features = self._pool_features(new_features)
  File "/opt/mmdetection3d/mmdet3d/ops/pointnet_modules/point_sa_module.py", line 160, in _pool_features
    features, kernel_size=[1, features.size(3)])
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/home/fusion/conda/envs/mmd/lib/python3.7/site-packages/torch/nn/functional.py", line 719, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.78 GiB total capacity; 7.32 GiB already allocated; 2.56 MiB free; 8.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZCMax** [comment]
How much is your GPU memory?

**Comment by hu-de** [comment]
> How much is your GPU memory?

The GPU memory is 10GB.

**Comment by VVsssssk** [comment]
Hi, it seems like an out-of-memory issue, and I suggest you can try to use the newest dev-1.x branch, it supports the AMP training model. You can refer to https://github.com/open-mmlab/mmengine/blob/458f6d684ea15af9898f8a4b3eb9115faa976d02/docs/zh_cn/examples/speed_up_training.md.
