### ISSUE TITLE
RuntimeError: Exporting the operator maximum to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

### ISSUE THREAD

**Issue by rockywind** [open-mmlab/mmdetection3d#1789]
Hi,
When I exported the 3D model to the ONNX model, I met the error below.
```
/dataset/PETR/projects/mmdet3d_plugin/models/detectors/petr3d.py:131: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if return_loss:
/dataset/PETR/projects/mmdet3d_plugin/models/detectors/petr3d.py:66: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if img.size(0) == 1 and img.size(1) != 1:
/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/mmcv/ops/modulated_deform_conv.py:146: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not all(map(lambda s: s > 0, output_size)):
/dataset/PETR/projects/mmdet3d_plugin/models/detectors/petr3d.py:83: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_feats_reshaped.append(img_feat.view(B, int(BN / B), C, H, W))
/dataset/PETR/projects/mmdet3d_plugin/models/dense_heads/petr_head.py:425: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert reference.shape[-1] == 3
Traceback (most recent call last):
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/CN/zizhang.wu/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/CN/zizhang.wu/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/CN/zizhang.wu/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/CN/zizhang.wu/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/CN/zizhang.wu/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/CN/zizhang.wu/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/dataset/PETR/tools/test_onnx.py", line 265, in <module>
    main()
  File "/dataset/PETR/tools/test_onnx.py", line 211, in main
    do_constant_folding=True,)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/utils.py", line 467, in _model_to_graph
    module=module)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/utils.py", line 990, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/utils.py", line 944, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/CN/zizhang.wu/anaconda3/envs/PETR_wxq/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 116, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator maximum to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

The code is that
```
    checkpoint = torch.load('/dataset/PETR/ckpts/p4_epoch_24.pth', map_location='cpu')

    state_dict = checkpoint['state_dict']
    model.load_state_dict(state_dict, strict=False)
    print("****fifth check***")
    input = torch.ones([1, 3, 512, 1408]).cuda() #.cuda('cuda:1').float()    # normal in train
    model.eval()
    torch.onnx.export(model.cuda(),
                      input,
                      "petr.onnx",
                      export_params=True,
                      opset_version=11,
                      do_constant_folding=True,)
```

**Comment by Tai-Wang** [comment]
I notice you are converting PETR models to onnx format. Please post issues to their specific repo and it may be more convenient for its authors to reach out to you. As for MMDet3D, we only support PointPillars deployment for now. More camera-only methods will be supported in the future.

**Comment by rockywind** [comment]
OK, thanks!

**Comment by HengLoveYi** [comment]
> 

So PGD is also not supported to export to ONNX, right?

**Comment by HengLoveYi** [comment]
> I notice you are converting PETR models to onnx format. Please post issues to their specific repo and it may be more convenient for its authors to reach out to you. As for MMDet3D, we only support PointPillars deployment for now. More camera-only methods will be supported in the future.

So PGD is also not supported to export to ONNX, right?
