### ISSUE TITLE
Sparse shape causing problems

### ISSUE THREAD

**Issue by holtvogt** [open-mmlab/mmdetection3d#1803]
**Reproduction**

1. What command or script did you run?

```
python tools/train.py <config.py>
```

2. Did you make any modifications on the code or config?
I cropped my point cloud range and now, adjusted the `sparse_shape` to match the new point cloud range.

Excerpt of the config:
```python
voxel_size = [0.05, 0.05, 0.1]
point_cloud_range = [-1, -3, -2.5, 3, 0.5, 1]
# sparse_shape  = [36, 70 ,80], previously: [46, 80, 60]
sparse_shape = [
    # Some rounding magic: -(-numerator // denominator) == math.ceil(numerator / denominator)
    -(-(point_cloud_range [5] - point_cloud_range [2]) // voxel_size[2]) + 1,
    (point_cloud_range [4] - point_cloud_range [1]) / voxel_size[1],
    (point_cloud_range [3] - point_cloud_range [0]) / voxel_size[0],
]

model = dict(
    type="VoxelNet",
    voxel_layer=dict(
        max_num_points=5,
        point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1],
        voxel_size=voxel_size,
        max_voxels=(16000, 40000),
    ),
    voxel_encoder=dict(type="HardSimpleVFE"),
    middle_encoder=dict(
        type="SparseEncoder",
        in_channels=4,
        # Depends on point cloud range and voxel size
        sparse_shape=sparse_shape,
        order=("conv", "norm", "act"),
    ),
    ...
```

3. What dataset did you use?
My custom dataset.

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.

```
sys.platform: linux
Python: 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) [GCC 7.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2
OpenCV: 4.6.0
MMCV: 1.6.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.1
MMSegmentation: 0.27.0
MMDetection3D: 1.0.0rc4+300425d
spconv2.0: True
```

**Error traceback**
If applicable, paste the error trackback here.

```
2022-09-02 19:43:48,666 - mmdet - INFO - workflow: [('train', 1)], max: 40 epochs
2022-09-02 19:43:48,666 - mmdet - INFO - Checkpoints will be saved to /home/ws/x/Dokumente/Repositories/dasad3d/checkpoints/itiv/second by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 298, in <module>
    main()
  File "tools/train.py", line 286, in main
    train_model(
  File "/home/ws/x/Dokumente/Repositories/dasad3d/mmdet3d/apis/train.py", line 391, in train_model
    train_detector(
  File "/home/ws/x/Dokumente/Repositories/dasad3d/mmdet3d/apis/train.py", line 363, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/ws/x/Dokumente/Repositories/dasad3d/mmdet3d/models/detectors/base.py", line 63, in forward
    return self.forward_train(**kwargs)
  File "/home/ws/x/Dokumente/Repositories/dasad3d/mmdet3d/models/detectors/voxelnet.py", line 96, in forward_train
    x = self.extract_feat(points, img_metas)
  File "/home/ws/x/Dokumente/Repositories/dasad3d/mmdet3d/models/detectors/voxelnet.py", line 49, in extract_feat
    x = self.backbone(x)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ws/x/Dokumente/Repositories/dasad3d/mmdet3d/models/backbones/second.py", line 97, in forward
    x = self.blocks[i](x)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 256, 3, 3], expected input[4, 128, 9, 10] to have 256 channels, but got 128 channels instead
```

**Comment by Tai-Wang** [comment]
This bug seems not directly related to the setting of sparse_shape. Could you please show your entire config?

**Comment by holtvogt** [comment]
My configuration:
```python
model = dict(
    type='VoxelNet',
    voxel_layer=dict(
        max_num_points=5,
        point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1],
        voxel_size=[0.05, 0.05, 0.1],
        max_voxels=(16000, 40000)),
    voxel_encoder=dict(type='HardSimpleVFE'),
    middle_encoder=dict(
        type='SparseEncoder',
        in_channels=4,
        sparse_shape=[36, 70, 80],
        order=('conv', 'norm', 'act')),
    backbone=dict(
        type='SECOND',
        in_channels=256,
        layer_nums=[5, 5],
        layer_strides=[1, 2],
        out_channels=[128, 256]),
    neck=dict(
        type='SECONDFPN',
        in_channels=[128, 256],
        upsample_strides=[1, 2],
        out_channels=[256, 256]),
    bbox_head=dict(
        type='Anchor3DHead',
        num_classes=1,
        in_channels=512,
        feat_channels=512,
        use_direction_classifier=True,
        anchor_generator=dict(
            type='Anchor3DRangeGenerator',
            ranges=[[-1, -3, -2.5, 3, 0.5, 1]],
            sizes=[[0.8, 0.6, 1.73]],
            rotations=[0, 1.57],
            reshape_out=True),
        diff_rad_by_sin=True,
        bbox_coder=dict(type='DeltaXYZWLHRBBoxCoder'),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=2.0),
        loss_dir=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.2)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            iou_calculator=dict(type='BboxOverlapsNearest3D'),
            pos_iou_thr=0.35,
            neg_iou_thr=0.2,
            min_pos_iou=0.2,
            ignore_iof_thr=-1),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        use_rotate_nms=True,
        nms_across_levels=False,
        nms_thr=0.01,
        score_thr=0.1,
        min_bbox_size=0,
        nms_pre=100,
        max_num=50))
dataset_type = 'ItivDataset'
data_root = 'data/itiv/'
class_names = ['Pedestrian']
point_cloud_range = [-1, -3, -2.5, 3, 0.5, 1]
input_modality = dict(use_lidar=True, use_camera=False)
file_client_args = dict(backend='disk')
db_sampler = dict(
    data_root='data/itiv/',
    info_path='data/itiv/itiv_dbinfos_train.pkl',
    rate=1.0,
    prepare=dict(
        filter_by_difficulty=[-1], filter_by_min_points=dict(Pedestrian=5)),
    classes=['Pedestrian'],
    sample_groups=dict(Pedestrian=15))
train_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=4,
        use_dim=4,
        file_client_args=dict(backend='disk')),
    dict(
        type='LoadAnnotations3D',
        with_bbox_3d=True,
        with_label_3d=True,
        file_client_args=dict(backend='disk')),
    dict(
        type='ObjectSample',
        db_sampler=dict(
            data_root='data/itiv/',
            info_path='data/itiv/itiv_dbinfos_train.pkl',
            rate=1.0,
            prepare=dict(
                filter_by_difficulty=[-1],
                filter_by_min_points=dict(Pedestrian=5)),
            classes=['Pedestrian'],
            sample_groups=dict(Pedestrian=15))),
    dict(
        type='ObjectNoise',
        num_try=100,
        translation_std=[1.0, 1.0, 0.5],
        global_rot_range=[0.0, 0.0],
        rot_range=[-0.78539816, 0.78539816]),
    dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
    dict(
        type='GlobalRotScaleTrans',
        rot_range=[-0.78539816, 0.78539816],
        scale_ratio_range=[0.95, 1.05]),
    dict(
        type='PointsRangeFilter', point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1]),
    dict(
        type='ObjectRangeFilter', point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1]),
    dict(type='PointShuffle'),
    dict(type='DefaultFormatBundle3D', class_names=['Pedestrian']),
    dict(type='Collect3D', keys=['points', 'gt_bboxes_3d', 'gt_labels_3d'])
]
test_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=4,
        use_dim=4,
        file_client_args=dict(backend='disk')),
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1333, 800),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(
                type='GlobalRotScaleTrans',
                rot_range=[0, 0],
                scale_ratio_range=[1.0, 1.0],
                translation_std=[0, 0, 0]),
            dict(type='RandomFlip3D'),
            dict(
                type='PointsRangeFilter',
                point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1]),
            dict(
                type='DefaultFormatBundle3D',
                class_names=['Pedestrian'],
                with_label=False),
            dict(type='Collect3D', keys=['points'])
        ])
]
eval_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=4,
        use_dim=4,
        file_client_args=dict(backend='disk')),
    dict(
        type='DefaultFormatBundle3D',
        class_names=['Pedestrian'],
        with_label=False),
    dict(type='Collect3D', keys=['points'])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=6,
    train=dict(
        type='RepeatDataset',
        times=4,
        dataset=dict(
            type='ItivDataset',
            data_root='data/itiv/',
            ann_file='data/itiv/itiv_infos_train.pkl',
            split='training',
            pts_prefix='velodyne',
            pipeline=[
                dict(
                    type='LoadPointsFromFile',
                    coord_type='LIDAR',
                    load_dim=4,
                    use_dim=4,
                    file_client_args=dict(backend='disk')),
                dict(
                    type='LoadAnnotations3D',
                    with_bbox_3d=True,
                    with_label_3d=True,
                    file_client_args=dict(backend='disk')),
                dict(
                    type='ObjectSample',
                    db_sampler=dict(
                        data_root='data/itiv/',
                        info_path='data/itiv/itiv_dbinfos_train.pkl',
                        rate=1.0,
                        prepare=dict(
                            filter_by_difficulty=[-1],
                            filter_by_min_points=dict(Pedestrian=5)),
                        classes=['Pedestrian'],
                        sample_groups=dict(Pedestrian=15))),
                dict(
                    type='ObjectNoise',
                    num_try=100,
                    translation_std=[1.0, 1.0, 0.5],
                    global_rot_range=[0.0, 0.0],
                    rot_range=[-0.78539816, 0.78539816]),
                dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
                dict(
                    type='GlobalRotScaleTrans',
                    rot_range=[-0.78539816, 0.78539816],
                    scale_ratio_range=[0.95, 1.05]),
                dict(
                    type='PointsRangeFilter',
                    point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1]),
                dict(
                    type='ObjectRangeFilter',
                    point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1]),
                dict(type='PointShuffle'),
                dict(type='DefaultFormatBundle3D', class_names=['Pedestrian']),
                dict(
                    type='Collect3D',
                    keys=['points', 'gt_bboxes_3d', 'gt_labels_3d'])
            ],
            modality=dict(use_lidar=True, use_camera=False),
            classes=['Pedestrian'],
            test_mode=False,
            box_type_3d='LiDAR')),
    val=dict(
        type='ItivDataset',
        data_root='data/itiv/',
        ann_file='data/itiv/itiv_infos_val.pkl',
        split='training',
        pts_prefix='velodyne',
        pipeline=[
            dict(
                type='LoadPointsFromFile',
                coord_type='LIDAR',
                load_dim=4,
                use_dim=4,
                file_client_args=dict(backend='disk')),
            dict(
                type='MultiScaleFlipAug3D',
                img_scale=(1333, 800),
                pts_scale_ratio=1,
                flip=False,
                transforms=[
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0, 0],
                        scale_ratio_range=[1.0, 1.0],
                        translation_std=[0, 0, 0]),
                    dict(type='RandomFlip3D'),
                    dict(
                        type='PointsRangeFilter',
                        point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1]),
                    dict(
                        type='DefaultFormatBundle3D',
                        class_names=['Pedestrian'],
                        with_label=False),
                    dict(type='Collect3D', keys=['points'])
                ])
        ],
        modality=dict(use_lidar=True, use_camera=False),
        classes=['Pedestrian'],
        test_mode=True,
        box_type_3d='LiDAR'),
    test=dict(
        type='ItivDataset',
        data_root='data/itiv/',
        ann_file='data/itiv/itiv_infos_val.pkl',
        split='training',
        pts_prefix='velodyne',
        pipeline=[
            dict(
                type='LoadPointsFromFile',
                coord_type='LIDAR',
                load_dim=4,
                use_dim=4,
                file_client_args=dict(backend='disk')),
            dict(
                type='MultiScaleFlipAug3D',
                img_scale=(1333, 800),
                pts_scale_ratio=1,
                flip=False,
                transforms=[
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0, 0],
                        scale_ratio_range=[1.0, 1.0],
                        translation_std=[0, 0, 0]),
                    dict(type='RandomFlip3D'),
                    dict(
                        type='PointsRangeFilter',
                        point_cloud_range=[-1, -3, -2.5, 3, 0.5, 1]),
                    dict(
                        type='DefaultFormatBundle3D',
                        class_names=['Pedestrian'],
                        with_label=False),
                    dict(type='Collect3D', keys=['points'])
                ])
        ],
        modality=dict(use_lidar=True, use_camera=False),
        classes=['Pedestrian'],
        test_mode=True,
        box_type_3d='LiDAR'))
evaluation = dict(
    interval=10,
    pipeline=[
        dict(
            type='LoadPointsFromFile',
            coord_type='LIDAR',
            load_dim=4,
            use_dim=4,
            file_client_args=dict(backend='disk')),
        dict(
            type='DefaultFormatBundle3D',
            class_names=['Pedestrian'],
            with_label=False),
        dict(type='Collect3D', keys=['points'])
    ])
lr = 0.0018
optimizer = dict(
    type='AdamW', lr=0.0018, betas=(0.95, 0.99), weight_decay=0.01)
optimizer_config = dict(grad_clip=dict(max_norm=10, norm_type=2))
lr_config = dict(
    policy='cyclic',
    target_ratio=(10, 0.0001),
    cyclic_times=1,
    step_ratio_up=0.4)
momentum_config = dict(
    policy='cyclic',
    target_ratio=(0.8947368421052632, 1),
    cyclic_times=1,
    step_ratio_up=0.4)
runner = dict(type='EpochBasedRunner', max_epochs=40)
checkpoint_config = dict(interval=1)
log_config = dict(
    interval=50,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = None
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
```

**Comment by ChristopheZhao** [comment]
You can try modify the in_channels of  SECOND backbone from 256 to 128.

**Comment by holtvogt** [comment]
Got this when changing to 128:

```
load checkpoint from local path: /home/ws/x/Dokumente/Repositories/dasad3d/checkpoints/itiv/second/latest.pth
The model and loaded state dict do not match exactly

size mismatch for backbone.blocks.0.0.weight: copying a param with shape torch.Size([128, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
[                                                  ] 0/188, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 306, in <module>
    main()
  File "tools/test.py", line 270, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/apis/test.py", line 47, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 51, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/detectors/base.py", line 65, in forward
    return self.forward_test(**kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/detectors/base.py", line 46, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/detectors/voxelnet.py", line 106, in simple_test
    x = self.extract_feat(points, img_metas)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/detectors/voxelnet.py", line 51, in extract_feat
    x = self.neck(x)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/ws/x/anaconda3/envs/dasad3d/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/necks/second_fpn.py", line 94, in forward
    out = torch.cat(ups, dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 9 but got size 10 for tensor number 1 in the list.
```

**Comment by 18722013889** [comment]
hello friend ,i got the same problem,have you solve this?

**Comment by holtvogt** [comment]
Nope, didn't look further into it due to time constraints
