### ISSUE TITLE
python setup.py develop failed

### ISSUE THREAD

**Issue by hjc0106** [open-mmlab/mmdetection3d#1806]
Thanks for your error report and we appreciate it a lot.
When I install mmdection3d==0.11.0, the error has been ocuurred.

My Enviroment
Python: 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) [GCC 7.5.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.4.r11.4/compiler.30521435_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.0
OpenCV: 4.6.0
MMCV: 1.4.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2

The Error traceback
running develop
/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing requirements to mmdet3d.egg-info/requires.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'mmdet3d/ops/**/*.cpp'
warning: no files found matching 'mmdet3d/ops/**/*.cu'
warning: no files found matching 'mmdet3d/ops/**/*.h'
warning: no files found matching 'mmdet3d/ops/**/*.cc'
warning: no files found matching 'mmdet3d/VERSION'
adding license file 'LICENSE'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
building 'mmdet3d.ops.spconv.sparse_conv_ext' extension
Emitting ninja build file /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -B /data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/compiler_compat -L/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib -Wl,-rpath=/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib -Wl,--no-as-needed -Wl,--sysroot=/ /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/spconv/src/all.o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/spconv/src/indice.o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/spconv/src/indice_cuda.o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/spconv/src/maxpool.o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/spconv/src/maxpool_cuda.o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/spconv/src/reordering.o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/spconv/src/reordering_cuda.o -L/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-38/mmdet3d/ops/spconv/sparse_conv_ext.cpython-38-x86_64-linux-gnu.so
building 'mmdet3d.ops.iou3d.iou3d_cuda' extension
Emitting ninja build file /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -B /data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/compiler_compat -L/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib -Wl,-rpath=/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib -Wl,--no-as-needed -Wl,--sysroot=/ /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/iou3d/src/iou3d.o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/iou3d/src/iou3d_kernel.o -L/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-38/mmdet3d/ops/iou3d/iou3d_cuda.cpython-38-x86_64-linux-gnu.so
building 'mmdet3d.ops.voxel.voxel_layer' extension
Emitting ninja build file /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/include/python3.8 -c -c /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu -o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/voxel/src/scatter_points_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=voxel_layer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/voxel/src/scatter_points_cuda.o 
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/TH -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/include/python3.8 -c -c /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu -o /data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/voxel/src/scatter_points_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=voxel_layer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign

/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(242): error: class "at::Tensor" has no member "max_values"

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: type name is not allowed

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: expected an expression

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: no instance of function template "coors_id_kernel" matches the argument list
            argument types are: (uint8_t *, <error-type>, int64_t *, const int, const int)

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: type name is not allowed

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: expected an expression

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: no instance of function template "coors_id_kernel" matches the argument list
            argument types are: (int8_t *, <error-type>, int64_t *, const int, const int)

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: type name is not allowed

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: expected an expression

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: no instance of function template "coors_id_kernel" matches the argument list
            argument types are: (int32_t *, <error-type>, int64_t *, const int, const int)

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: type name is not allowed

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: expected an expression

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: no instance of function template "coors_id_kernel" matches the argument list
            argument types are: (int64_t *, <error-type>, int64_t *, const int, const int)

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: type name is not allowed

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: expected an expression

/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: no instance of function template "coors_id_kernel" matches the argument list
            argument types are: (int16_t *, <error-type>, int64_t *, const int, const int)

16 errors detected in the compilation of "/data/chenhai-fwxz/BEVFusion-AD/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 139, in <module>
    setup(
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 473, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/data/chenhai-fwxz/anaconda3/envs/BEVFusion-AD/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Tai-Wang** [comment]
It's hard to say what is the exact reason triggering your compilation error, but I notice your Cuda version is inconsistent among nvcc, pytorch and mmcv. Maybe you can double-check your compilation environment.

Besides, we recommend you use the latest mmdet3d and it does not need the compilation of ops in mmdet3d. You can directly download the corresponding pre-compiled mmcv and it can avoid some similar potential problems.

**Comment by zjufkq** [comment]
Have you solved it? I have the same problem

**Comment by WuYanXingege** [comment]
> Have you solved it? I have the same problem
how can you solve this problem?

**Comment by Wendy1130** [comment]
**RuntimeError:
The detected CUDA version (12.4) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.**
i have the problem. However, cuda12.4 can't support mmcv,mmdet3d....

**Comment by Sidhant741** [comment]
@Wendy1130 how did you solve this problem ?
