### ISSUE TITLE
the training process not response, not just me, same as 2 friends

### ISSUE THREAD

**Issue by MengAaron** [open-mmlab/mmdetection3d#183]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
the training process is not response
2020-10-30 11:22:08,568 - mmdet - INFO - load 2207 Pedestrian database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 14357 Car database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 734 Cyclist database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 1297 Van database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 488 Truck database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 224 Tram database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 337 Misc database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 56 Person_sitting database infos
2020-10-30 11:22:08,605 - mmdet - INFO - After filter database:
2020-10-30 11:22:08,605 - mmdet - INFO - load 2207 Pedestrian database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 13509 Car database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 734 Cyclist database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 1297 Van database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 488 Truck database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 224 Tram database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 337 Misc database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 56 Person_sitting database infos
2020-10-30 11:22:14,188 - mmdet - INFO - Start running, host: mengboyu@dbcloud, work_dir: /home/mengboyu/code/mmdetection3d/work_dirs/3dssd_kitti-3d-car
2020-10-30 11:22:14,188 - mmdet - INFO - workflow: [('train', 1)], max: 150 epochs
2020-10-30 11:22:15.465922: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/
2020-10-30 11:22:08,568 - mmdet - INFO - load 224 Tram database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 337 Misc database infos
2020-10-30 11:22:08,568 - mmdet - INFO - load 56 Person_sitting database infos
2020-10-30 11:22:08,605 - mmdet - INFO - After filter database:
2020-10-30 11:22:08,605 - mmdet - INFO - load 2207 Pedestrian database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 13509 Car database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 734 Cyclist database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 1297 Van database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 488 Truck database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 224 Tram database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 337 Misc database infos
2020-10-30 11:22:08,605 - mmdet - INFO - load 56 Person_sitting database infos
2020-10-30 11:22:14,188 - mmdet - INFO - Start running, host: mengboyu@dbcloud, work_dir: /home/mengboyu/code/mmdetection3d/work_dirs/3dssd_kitti-3d-car

**Reproduction**
1. What command or script did you run?
CUDA_VISIBLE_DEVICES=7 python tools/train.py ./configs/3dssd/3dssd_kitti-3d-car.py 

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
Python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.1.6
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.5.0
MMDetection3D: 0.6.1+

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
conda, following the  official wetset of pytorch
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
No change.
**Error traceback**
no response for long time

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
Hi @MengAaron ,
It seems that you do not use distributed training. Due to the complicated input of 3D detection, distributed training is recommended. Could you use dist_train.sh and try again? Even if you only have one GPU, you can still use distributed training and testing.

**Comment by MengAaron** [comment]
when i try distributed training with  1 GPU，i meet both subprogress error and  NCCL error
    exec(code, run_globals)
  File "/home/mengboyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/mengboyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/mengboyu/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', './configs/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_4x8_cyclic_flip-tta_20e_nus.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
(open-mmlab) mengboyu@dbcloud:~/code/mmdetection3d$ Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 162, in main
    meta=meta)
  File "/home/mengboyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 80, in train_detector
    find_unused_parameters=find_unused_parameters)
  File "/home/mengboyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 333, in __init__
    self.broadcast_bucket_size)
  File "/home/mengboyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 549, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1595629403081/work/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8

**Comment by ZwwWayne** [comment]
It usually because there is some incompatibility between your hardware and NCCL, or there is something wrong with the communication between GPUS/GPU-CPU. You might need to first check whether the hardware environment is OK.

**Comment by MengAaron** [comment]
Hi, I found i don't install ncll and libncll. So i solve the NCLL error.
I refer to https://github.com/open-mmlab/mmdetection/issues/3423 to solve the subprocess error. The reason that error occur is that another student is using the master port of the default setting.
However, even using distributed training, we still meet the same circumstance as 1-gpu training: no response.
BTW, I use huawei cloud with 1*V100 runs well. So, I don't know why the problem occur.

**Comment by MengAaron** [comment]
I found that I meet pytorch dataloader deadlock. But I don't know how to solve it.

**Comment by ZwwWayne** [comment]
Then the deadlock might be caused by the hardware limitation.
You may try to reduce the number of workers since a large number of workers may cause overload.

**Comment by MengAaron** [comment]
I change mmcv-full source code, add cv2.setNumThreads(0) in every file which use cv2, and solve the problem

**Comment by hwy-202011** [comment]
> mmcv-full source cod

i have the same question, can you tell which version of mvcc-full you have changed?
