### ISSUE TITLE
FP16 training error: RuntimeError: Index put requires the source and destination dtypes match, got Half for the destination and Float for the source

### ISSUE THREAD

**Issue by wuziyou199217** [open-mmlab/mmdetection3d#1842]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I am running SMOKE with fp16 on Kitti dataset and got the error.

**Reproduction**

1. What command or script did you run?

```
bash scripts/mmdetection3d/dist_train.sh configs/mmdetection3d/smoke/smoke_dla34_pytorch_dlaneck_gn-all_32x4_6x_kitti-mono3d.py 1
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No, I've only added some nvtx markers

3. What dataset did you use?
Kitti

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) [GCC 10.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-40GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0a0+8a1a93a
PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.4  (built against CUDA 11.6)
  - Magma 2.6.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.4.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.13.0a0
OpenCV: 3.4.11
MMCV: 1.6.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.7
MMDetection: 2.25.1
MMSegmentation: 0.27.0
MMDetection3D: 1.0.0rc4+ad7b104
spconv2.0: True

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]:
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
Traceback (most recent call last):
  File "scripts/mmdetection3d/train.py", line 266, in <module>
    main()
  File "scripts/mmdetection3d/train.py", line 254, in main
    train_model(
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/apis/train.py", line 379, in train_model
    train_detector(
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/apis/train.py", line 354, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.8/site-packages/mmcv_full-1.6.0-py3.8-linux-x86_64.egg/mmcv/runner/epoch_based_runner.py", line 138, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv_full-1.6.0-py3.8-linux-x86_64.egg/mmcv/runner/epoch_based_runner.py", line 55, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv_full-1.6.0-py3.8-linux-x86_64.egg/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/conda/lib/python3.8/site-packages/mmcv_full-1.6.0-py3.8-linux-x86_64.egg/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/mmdet-2.25.1-py3.8.egg/mmdet/models/detectors/base.py", line 251, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv_full-1.6.0-py3.8-linux-x86_64.egg/mmcv/runner/fp16_utils.py", line 146, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdet-2.25.1-py3.8.egg/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/detectors/single_stage_mono3d.py", line 90, in forward_train
    losses = self.bbox_head.forward_train(x, img_metas, gt_bboxes,
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/dense_heads/base_mono3d_dense_head.py", line 68, in forward_train
    outs = self(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/dense_heads/smoke_mono3d_head.py", line 92, in forward
    return multi_apply(self.forward_single, feats)
  File "/opt/conda/lib/python3.8/site-packages/mmdet-2.25.1-py3.8.egg/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8.egg/mmdet3d/models/dense_heads/smoke_mono3d_head.py", line 112, in forward_single
    bbox_pred[:, self.ori_channel, ...] = F.normalize(vector_ori)
RuntimeError: Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 118523) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

**Bug fix**
I found the root cause of this bug is the calling of torch.nn.functional.normalize() function in mmdet3d/models/dense_heads/smoke_mono3d_head.py, which transfers the tensor dtype from torch.cuda.HalfTensor to torch.cuda.FloatTensor.

**Comment by Tai-Wang** [comment]
We do not support mixed precision training for SMOKE for now. You may need to adjust the related details by yourself to guarantee the intermediate output can be compatible
