### ISSUE TITLE
[Bug] DLL LOAD FAILED

### ISSUE THREAD

**Issue by bjw1107** [open-mmlab/mmdetection3d#1983]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

Traceback (most recent call last):
  File "mmdet3d/utils/collect_env.py", line 8, in <module>
    from mmdet3d.ops.spconv import IS_SPCONV2_AVAILABLE
  File "f:\702work\mmdetection3d\mmdet3d\ops\__init__.py", line 2, in <module>
    from mmcv.ops import (RoIAlign, SigmoidFocalLoss, get_compiler_version,
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Anaconda\envs\open-mmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的程序。

### Reproduces the problem - code sample

demo.py

### Reproduces the problem - command or script

python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

### Reproduces the problem - error message

Traceback (most recent call last):
  File "demo/pcd_demo.py", line 4, in <module>
    from mmdet3d.apis import inference_detector, init_model, show_result_meshlab
  File "f:\702work\mmdetection3d\mmdet3d\apis\__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "f:\702work\mmdetection3d\mmdet3d\apis\inference.py", line 12, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes, Coord3DMode,
  File "f:\702work\mmdetection3d\mmdet3d\core\__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "f:\702work\mmdetection3d\mmdet3d\core\anchor\__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmdet\core\bbox\__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmdet\core\bbox\samplers\__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmdet\core\bbox\samplers\score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "D:\Anaconda\envs\open-mmlab\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Anaconda\envs\open-mmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的程序。

### Additional information

cuda11.1,pytorch1.8,torchvision0.9.0

**Comment by ZCMax** [comment]
Seems you didn't install mmcv-full (not mmcv)?

**Comment by hwh1024** [comment]
I got the same problem
