### ISSUE TITLE
[Bug] `show() got multiple values for argument 'win_name'` when running `pcd_demo.py` with `--show` flag

### ISSUE THREAD

**Issue by vavanade** [open-mmlab/mmdetection3d#1990]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

```
sys.platform: win32
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1650
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
GCC: n/a
PyTorch: 1.13.0+cu117
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.0+cu117
OpenCV: 4.6.0
MMEngine: 0.3.0
MMDetection: 3.0.0rc2
MMDetection3D: 1.1.0rc1+28fe73d
spconv2.0: False
```

### Reproduces the problem - code sample

```
```

### Reproduces the problem - command or script

```shell
python demo/pcd_demo.py demo/data/kitti/000008.bin C:\\path\\to\\mmdetection3d\\configs\\second\\second_hv_secfpn_8xb6-80e_kitti-3d-car.py C:\\path\\to\\mmdetection3d\\checkpoints\\hv_second_secfpn_fp16_6x8_80e_kitti-3d-car_20200924_211301-1f5ad833.pth --show
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "C:\path\to\mmdetection3d\demo\pcd_demo.py", line 64, in <module>
    main(args)
  File "C:\path\to\mmdetection3d\demo\pcd_demo.py", line 50, in main
    visualizer.add_datasample(
  File "C:\path\to\venv\mmdetection3d\lib\site-packages\mmengine\dist\utils.py", line 346, in wrapper
    return func(*args, **kwargs)
  File "c:\path\to\mmdetection3d\mmdet3d\visualization\local_visualizer.py", line 788, in add_datasample
    self.show(
  File "C:\path\to\venv\mmdetection3d\lib\site-packages\mmengine\dist\utils.py", line 346, in wrapper
    return func(*args, **kwargs)
TypeError: show() got multiple values for argument 'win_name'
```

### Additional information

commenting out `vis_task` argument in call to `Det3DLocalVisualizer.show` in `Det3DLocalVisualizer.add_datasample` (`mmdet3d/visualization/local_visualizer.py`) fixes this:
```
        if show:
            self.show(
                #vis_task,
                save_path,
                drawn_img_3d,
                drawn_img,
                win_name=name,
                wait_time=wait_time)
```

I don't know whether this can break something else though.

**Comment by thinkthinking** [comment]
I also have this problem, and comment vis_task, it works.
```python
if show:
    self.show(
        #vis_task,
        save_path,
        drawn_img_3d,
        drawn_img,
        win_name=name,
        wait_time=wait_time)
```
