### ISSUE TITLE
[Bug] Evaluate multi-view dfm on Waymo dataset

### ISSUE THREAD

**Issue by YongtaoGe** [open-mmlab/mmdetection3d#1999]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

none

### Reproduces the problem - code sample

none

### Reproduces the problem - command or script

```
CUDA_VISIBLE_DEVICES=0,1,2,3 bash ./tools/dist_test.sh \
configs/dfm/multiview-dfm_r101-dcn_16xb2_waymoD5-3d-3class.py \
work_dirs/multiview-dfm_r101-dcn_16xb2_waymoD5-3d-3class/epoch_8.pth 4
```

### Reproduces the problem - error message

Traceback (most recent call last):
  File "./tools/test.py", line 121, in <module>
    main()
  File "./tools/test.py", line 117, in main
    runner.test()
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/mmengine/mmengine/runner/runner.py", line 1707, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/mmengine/mmengine/runner/loops.py", line 420, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/mmengine/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/mmengine/mmengine/evaluator/metric.py", line 110, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/dfm/mmdet3d/evaluation/metrics/waymo_metric.py", line 151, in compute_metrics
    classes=self.classes)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/dfm/mmdet3d/evaluation/metrics/waymo_metric.py", line 318, in format_results
    classes)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/dfm/mmdet3d/evaluation/metrics/kitti_metric.py", line 285, in format_results
    submission_prefix_)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/dfm/mmdet3d/evaluation/metrics/waymo_metric.py", line 459, in bbox2result_kitti
    box_dict = self.convert_valid_bboxes(pred_dicts, info)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/code/dfm/mmdet3d/evaluation/metrics/waymo_metric.py", line 590, in convert_valid_bboxes
    sample_idx = info['sample_id']
KeyError: 'sample_id'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2954) of binary: /mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/bin/python
Traceback (most recent call last):
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/distributed/run.py", line 692, in run
    )(*cmd_args)
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/beegfs/ssd_pool/docker/user/hadoop-automl/geyongtao/anaconda3/envs/dfm/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by ZCMax** [comment]
@lianqing01 @Tai-Wang  Please have a look at this issue

**Comment by XYAskWhy** [comment]
@YongtaoGe hi, I have the same problem with you. Had you solved this? What did you do?
It seemed like a dataset version problem. The waymo dataset version I am using is 1.2.

**Comment by YongtaoGe** [comment]
@XYAskWhy It is caused by a typo error. Changing 'sample_id' to 'sample_idx' would fix the problem.

**Comment by XYAskWhy** [comment]
> sample_idx

Thanks for your reply. Could you please tell me the waymo dataset version you are using? I have a data loading problem. 
`11/16 07:14:24 - mmengine - INFO - Result has been saved to ~~/mmdetection3d/work_dirs/test/modules_statistic_results.json
~~/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:92: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
11/16 07:14:45 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
11/16 07:15:08 - mmengine - INFO - load 4352210 Car database infos
11/16 07:15:08 - mmengine - INFO - load 2037627 Pedestrian database infos
11/16 07:15:08 - mmengine - INFO - load 49518 Cyclist database infos
11/16 07:15:17 - mmengine - INFO - After filter database:
11/16 07:15:17 - mmengine - INFO - load 4078739 Car database infos
11/16 07:15:17 - mmengine - INFO - load 2037627 Pedestrian database infos
11/16 07:15:17 - mmengine - INFO - load 49518 Cyclist database infos
Traceback (most recent call last):
  File "**/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "~~/mmdetection3d/mmdet3d/datasets/waymo_dataset.py", line 100, in __init__
    super().__init__(
  File "~~/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 65, in __init__
    super().__init__(
  File "~~/mmdetection3d/mmdet3d/datasets/det3d_dataset.py", line 115, in __init__
    super().__init__(
  File "**/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "**/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 298, in full_init
    self.data_list = self.load_data_list()
  File "~~/mmdetection3d/mmdet3d/datasets/waymo_dataset.py", line 181, in load_data_list
    data_list = super().load_data_list()
  File "**/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 435, in load_data_list
    raise TypeError(f'The annotations loaded from annotation file '
TypeError: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "**/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "**/lib/python3.8/site-packages/mmengine/dataset/dataset_wrapper.py", line 207, in __init__
    self.dataset = DATASETS.build(dataset)
  File "**/lib/python3.8/site-packages/mmengine/registry/registry.py", line 454, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "**/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `WaymoDataset` in mmdet3d/datasets/waymo_dataset.py: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "**/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "**/lib/python3.8/site-packages/mmengine/runner/loops.py", line 43, in __init__
    super().__init__(runner, dataloader)
  File "**/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "**/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1336, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "**/lib/python3.8/site-packages/mmengine/registry/registry.py", line 454, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "**/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: class `WaymoDataset` in mmdet3d/datasets/waymo_dataset.py: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~~/mmdetection3d/tools/train.py", line 124, in <module>
    main()
  File "~~/mmdetection3d/tools/train.py", line 120, in main
    runner.train()
  File "**/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1628, in train
    self._train_loop = self.build_train_loop(
  File "**/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1443, in build_train_loop
    loop = LOOPS.build(
  File "**/lib/python3.8/site-packages/mmengine/registry/registry.py", line 454, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "**/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: class `WaymoDataset` in mmdet3d/datasets/waymo_dataset.py: The annotations loaded from annotation file should be a dict, but got <class 'list'>!`

**Comment by XYAskWhy** [comment]
Thanks for your reply. Could you please tell me the waymo dataset version you are using? I have a data loading problem.  
`11/16 07:14:24 - mmengine - INFO - Result has been saved to -/mmdetection3d/work_dirs/test/modules_statistic_results.json
-/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:92: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
11/16 07:14:45 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
11/16 07:15:08 - mmengine - INFO - load 4352210 Car database infos
11/16 07:15:08 - mmengine - INFO - load 2037627 Pedestrian database infos
11/16 07:15:08 - mmengine - INFO - load 49518 Cyclist database infos
11/16 07:15:17 - mmengine - INFO - After filter database:
11/16 07:15:17 - mmengine - INFO - load 4078739 Car database infos
11/16 07:15:17 - mmengine - INFO - load 2037627 Pedestrian database infos
11/16 07:15:17 - mmengine - INFO - load 49518 Cyclist database infos
Traceback (most recent call last):
  File "--/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "-/mmdetection3d/mmdet3d/datasets/waymo_dataset.py", line 100, in __init__
    super().__init__(
  File "-/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 65, in __init__
    super().__init__(
  File "-/mmdetection3d/mmdet3d/datasets/det3d_dataset.py", line 115, in __init__
    super().__init__(
  File "--/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "--/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 298, in full_init
    self.data_list = self.load_data_list()
  File "-/mmdetection3d/mmdet3d/datasets/waymo_dataset.py", line 181, in load_data_list
    data_list = super().load_data_list()
  File "--/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 435, in load_data_list
    raise TypeError(f'The annotations loaded from annotation file '
TypeError: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "--/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "--/lib/python3.8/site-packages/mmengine/dataset/dataset_wrapper.py", line 207, in __init__
    self.dataset = DATASETS.build(dataset)
  File "--/lib/python3.8/site-packages/mmengine/registry/registry.py", line 454, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "--/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `WaymoDataset` in mmdet3d/datasets/waymo_dataset.py: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "--/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "--/lib/python3.8/site-packages/mmengine/runner/loops.py", line 43, in __init__
    super().__init__(runner, dataloader)
  File "--/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "--/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1336, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "--/lib/python3.8/site-packages/mmengine/registry/registry.py", line 454, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "--/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: class `WaymoDataset` in mmdet3d/datasets/waymo_dataset.py: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "-/mmdetection3d/tools/train.py", line 124, in <module>
    main()
  File "-/mmdetection3d/tools/train.py", line 120, in main
    runner.train()
  File "--/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1628, in train
    self._train_loop = self.build_train_loop(
  File "--/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1443, in build_train_loop
    loop = LOOPS.build(
  File "--/lib/python3.8/site-packages/mmengine/registry/registry.py", line 454, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "--/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: class `WaymoDataset` in mmdet3d/datasets/waymo_dataset.py: The annotations loaded from annotation file should be a dict, but got <class 'list'>!`

**Comment by YongtaoGe** [comment]
By the way, how to generate cam_gt.bin for the multi-view camera-only waymo dataset in dev-1.x branch?
