### ISSUE TITLE
Running inference on nuScenes samples

### ISSUE THREAD

**Issue by jpowie01** [open-mmlab/mmdetection3d#208]
I try to run inference on samples from nuScenes and use it in one of my projects. Demo script works fine with KITTI dataset samples. However, it seems not to work with nuScenes at all.

**Command:**
```bash
$ python demo/pcd_demo.py \
  data/nuscenes/sweeps/LIDAR_TOP/n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603847842.pcd.bin \
  configs/centerpoint/centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus.py \
  centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus_20200930_103722-3bb135f2.pth --device=cpu
```

**Output:**
```
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 28, in <module>
    main()
  File "demo/pcd_demo.py", line 22, in main
    result, data = inference_detector(model, args.pcd)
  File "/mmdetection3d/mmdet3d/apis/inference.py", line 73, in inference_detector
    data = test_pipeline(data)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 160, in __call__
    ts = results['timestamp']
KeyError: 'timestamp'
```

NuScenes dataset was properly preprocessed using `create_data.py` script:
```
$ ls -l data/nuscenes
total 20360
drwxr-xr-x     6 root root     192 Mar 22  2019 maps
-rw-r--r--     1 root root 3726941 Nov 24 21:36 nuscenes_dbinfos_train.pkl
drwxr-xr-x 11218 root root  358976 Nov 24 21:36 nuscenes_gt_database
-rw-r--r--     1 root root 6258122 Nov 24 21:32 nuscenes_infos_train.coco.json
-rw-r--r--     1 root root 6523618 Nov 24 21:28 nuscenes_infos_train.pkl
-rw-r--r--     1 root root 2029523 Nov 24 21:32 nuscenes_infos_val.coco.json
-rw-r--r--     1 root root 1835228 Nov 24 21:28 nuscenes_infos_val.pkl
drwxr-xr-x    15 root root     480 Nov 18 19:26 samples
drwxr-xr-x    15 root root     480 Nov 18 19:28 sweeps
drwxr-xr-x    15 root root     480 Mar 22  2019 v1.0-mini
```

Do I use this script properly? Should I modify demo script (or config file) somehow? Or maybe there is completely other way to run inference on these samples?

**Comment by ZwwWayne** [comment]
Hi @jpowie01 ,
The inference script does not support nuscenes data for now, because nuscenes data usually uses multiple sweeps, which is different from other data.
