### ISSUE TITLE
Bugs of create_gt_database

### ISSUE THREAD

**Issue by meng-zha** [open-mmlab/mmdetection3d#210]
Thanks for the wonderful codebase.

1. The 'LoadPointsFromFile' pipeline in create_groundtruth_database requires the 'coord_type' arguments.
2. The 'points' in 'example' is of type 'LiDARPoints' while 'box_np_ops.points_in_rbbox' needs numpy.ndarray.
3. 'BasePoints._ _ getitem_ _ ' wants to edit the tuple object 'item', which needs to be converted to list first.

I want to know whether these are caused by bugs or my installation problem. The try of PR has been sent, or these can be fixed by a few minutes by yourself.

**Comment by songlilucky** [comment]
Thanks for your commit #211 ,but when i create nuscenes gt, i met this 

> problem:Create GT Database of NuScenesDataset
{'type': 'NuScenesDataset', 'data_root': './data/nuscenes', 'ann_file': './data/nuscenes/nuscenes_infos_train.pkl'}
Traceback (most recent call last):
  File "tools/create_data.py", line 226, in <module>
    max_sweeps=args.max_sweeps)
  File "tools/create_data.py", line 68, in nuscenes_data_prep
    f'{out_dir}/{info_prefix}_infos_train.pkl')
  File "/mnt/luci-home/songli/mmdet3d/tools/data_converter/create_gt_database.py", line 215, in create_groundtruth_database
    dataset = build_dataset(dataset_cfg)
  File "/mnt/luci-home/songli/mmdet3d/mmdet3d/datasets/builder.py", line 37, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/mnt/3dvision-cpfs/envs/conda/envs/mmdet3d/lib/python3.6/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/luci-home/songli/mmdet3d/mmdet3d/datasets/nuscenes_dataset.py", line 127, in __init__
    test_mode=test_mode)
  File "/mnt/luci-home/songli/mmdet3d/mmdet3d/datasets/custom_3d.py", line 64, in __init__
    self.pipeline = Compose(pipeline)
  File "/mnt/luci-home/songli/mmdet/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/mnt/3dvision-cpfs/envs/conda/envs/mmdet3d/lib/python3.6/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() missing 1 required positional argument: 'coord_type'

**Comment by meng-zha** [comment]
@songlilucky I test the kitti dataset before, and I have found that the 'coord_type' should be in the ‘LoadPointsFromFile’ pipeline but not in the 'LoadPointsFromMultiSweeps' pipeline. It is a bug. I will fix it immediately.

**Comment by songlilucky** [comment]
> @songlilucky I test the kitti dataset before, and I have found that the 'coord_type' should be in the ‘LoadPointsFromFile’ pipeline but not in the 'LoadPointsFromMultiSweeps' pipeline. It is a bug. I will fix it immediately.

Thanks~
