### ISSUE TITLE
AssertionError in DockerFile

### ISSUE THREAD

**Issue by cs1488** [open-mmlab/mmdetection3d#2127]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

Not Possible because of Assertion Error
I followed your tutorial for Docker since i could not resolve my errors in #2092
Physical Hardware is the same as there.
I am using Docker Desktop and ran 
``# build an image with PyTorch 1.6, CUDA 10.1 docker build -t mmdetection3d -f docker/Dockerfile .``
and also 
``docker run --gpus all --shm-size=8g -it -v {DATA_DIR}:/mmdetection3d/data mmdetection3d``

### Reproduces the problem - code sample

once again i tried to run the example:
``python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth``

### Reproduces the problem - command or script

``python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth``

### Reproduces the problem - error message

``AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=(1, 3, 13, 0, 0, 0), <=(1, 5, 0, 0, 0, 0).```
even when i try to install 1.5 as it says it hits me with:
``AssertionError: MMCV==1.5.0 is used but incompatible. Please install mmcv>=1.5.2, <=1.7.0``

How can i escape the cycle of incompatiblities?

**Comment by Tai-Wang** [comment]
Please provide more information about your environment, like the version of mmcv, mmdet and mmdet3d. You can refer to the requirement in the documentation [here](https://mmdetection3d.readthedocs.io/en/latest/faq.html).

**Comment by cs1488** [comment]
I used the Dockerfile as described in the getting_started.md, this: [Dockerfile.txt](https://github.com/open-mmlab/mmdetection3d/files/10205555/Dockerfile.txt)
I changed the installation of MMCV to Version 1.5.0 as the error demanded, but got prompted the error above.

``mim list`` inside the container gives me: 
[mim_list.txt](https://github.com/open-mmlab/mmdetection3d/files/10206060/mim_list.txt)
``pip list`` : 
 [pip_list.txt](https://github.com/open-mmlab/mmdetection3d/files/10206070/pip_list.txt)
``conda list``:
[conda_list.txt](https://github.com/open-mmlab/mmdetection3d/files/10206075/conda_list.txt)

I can not execute ``python mmdet3d/utils/collect_env.py`` as it leads to the very error i am reporting.

**Comment by Tai-Wang** [comment]
Sorry for the late reply. You can find more information about the requirement of [mmdet](https://mmdetection.readthedocs.io/en/latest/faq.html) and [mmseg](https://mmsegmentation.readthedocs.io/en/latest/faq.html) in their documentation. There may be some conflicts in your current setup.

**Comment by tub-sgg** [comment]
I have a similar issue. I found the env is very  confusing to be created no matter the docker I use ,or  the virtual env. @cs1488  Have you solved the issue?

**Comment by tub-sgg** [comment]
root@67536afa1ca7:/mmdetection3d# python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmcv
>>> import mmdet
>>> import mmdet3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mmdetection3d/mmdet3d/__init__.py", line 5, in <module>
    import mmseg
  File "/opt/conda/lib/python3.7/site-packages/mmseg/__init__.py", line 59, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=(1, 3, 13, 0, 0, 0), <=(1, 5, 0, 0, 0, 0).
>>> exit()
it seems the pushed docker is not correct @Tai-Wang

**Comment by cs1488** [comment]
> 



> I have a similar issue. I found the env is very confusing to be created no matter the docker I use ,or the virtual env. @cs1488 Have you solved the issue?

@tub-sgg sadly not yet, i will start with the recommended FAQ next week, as until then getting this fw to run is not my top priority
