### ISSUE TITLE
运行mmdetection3d/demo/pcd_demo.py出错：当我用自己采集的点云数据推理时，预测出了结果，但可视化不成功

### ISSUE THREAD

**Issue by cxy86121** [open-mmlab/mmdetection3d#2144]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

环境是好的，就不贴在这边了

### Reproduces the problem - code sample

使用kitti的bin文件运行mmdetection3d/demo/pcd_demo.py，可以正常推理出结果并生成obj文件，可以在meshlab中查看；
但使用自己采集的PCD文件转为bin文件运行demo.py，可以出结果但没有成功生成obj文件。
我的PCD转bin文件代码为：
```python
import os
import numpy as np
import open3d as o3d

def pcd2bin2(filepath, outbinpath):
    lidar = []
    pcd = o3d.io.read_point_cloud(filepath)
    # pcd = o3d.io.read_point_cloud(filepath, format='pcd')
    points = np.array(pcd.points)
    for linestr in points:
        if len(linestr) == 3:  # only x,y,z
            linestr_convert = list(map(float, linestr))
            linestr_convert.append(0)
            lidar.append(linestr_convert)
        if len(linestr) == 4:  # x,y,z,i
            linestr_convert = list(map(float, linestr))
            linestr_convert[-1]=0
            lidar.append(linestr_convert)
    pl = np.array(lidar)
    pl = pl.reshape(-1, 4).astype(np.float32)  # x,y,z,i
    pl.tofile(outbinpath)
```
### Reproduces the problem - command or script

我自己生成的点云打印出来的点数信息为：
```python
points: [[ 4.278691 3.067762 0.56450605 79. ]
[ 4.275156 3.0890148 0.5692545 82. ]
[ 4.274995 3.1139524 0.5745565 86. ]
...
[ 2.5733821 -4.2225027 -0.44653866 9. ]
[ 2.5615246 -4.2362514 -0.4400766 3. ]
[ 2.546294 -4.246134 -0.43316403 6. ]]
```
Kitti数据集中点云信息为：
```python
points: [[ 2.1554e+01 2.8000e-02 9.3800e-01 3.4000e-01]
[ 2.1240e+01 9.4000e-02 9.2700e-01 2.4000e-01]
[ 2.1056e+01 1.5900e-01 9.2100e-01 5.3000e-01]
...
[ 6.3150e+00 -3.1000e-02 -1.6490e+00 2.9000e-01]
[ 6.3090e+00 -2.1000e-02 -1.6470e+00 2.9000e-01]
[ 6.3110e+00 -1.0000e-03 -1.6480e+00 3.2000e-01]]
```
有些不同
预测的结果也和kitti的bin数据不同，但本质应该是我这边的数据转换出现了问题。

### Reproduces the problem - error message

```python
Traceback (most recent call last):
  File "pcd_demo.py", line 45, in <module>
    main()
  File "pcd_demo.py", line 34, in main
    show_result_meshlab(
  File "/home/les/MyCode/mmdetection3d/mmdet3d/apis/inference.py", line 516, in show_result_meshlab
    file_name = show_det_result_meshlab(data, result, out_dir, score_thr,
  File "/home/les/MyCode/mmdetection3d/mmdet3d/apis/inference.py", line 360, in show_det_result_meshlab
    show_result(
  File "/home/les/MyCode/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 144, in show_result
    _write_oriented_bbox(pred_bboxes,
  File "/home/les/MyCode/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 68, in _write_oriented_bbox
    scene.add_geometry(convert_oriented_box_to_trimesh_fmt(box))
  File "/home/les/MyCode/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 60, in convert_oriented_box_to_trimesh_fmt
    box_trimesh_fmt = trimesh.creation.box(lengths, trns)
  File "/home/les/miniconda3/envs/openmmlab/lib/python3.8/site-packages/trimesh/creation.py", line 489, in box
    box.apply_transform(transform)
  File "/home/les/miniconda3/envs/openmmlab/lib/python3.8/site-packages/trimesh/base.py", line 2049, in apply_transform
    aligned_pre = triangles.windings_aligned(triangle_pre[valid_pre],
  File "/home/les/miniconda3/envs/openmmlab/lib/python3.8/site-packages/trimesh/triangles.py", line 241, in windings_aligned
    raise ValueError('Triangles must be (n,3,3)!')
ValueError: Triangles must be (n,3,3)!
```
请问有什么可以解决的方法吗？非常感谢！！！！

**Comment by JingweiZhang12** [comment]
https://github.com/open-mmlab/mmdetection3d/pull/1973/files， here is an example of converting PCD to bin format.

**Comment by cxy86121** [comment]
It's helpful， thank you very much!@JingweiZhang12

> [https://github.com/open-mmlab/mmdetection3d/pull/1973/files，](https://github.com/open-mmlab/mmdetection3d/pull/1973/files%EF%BC%8C) here is an example of converting PCD to bin format.
