### ISSUE TITLE
I got a mistake when i use centerpoint: 

### ISSUE THREAD

**Issue by huster-wugj** [open-mmlab/mmdetection3d#225]

**Comment by huster-wugj** [comment]
python demo/pcd_demo.py demo/kitti_000008.bin configs/centerpoint/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py checkpoints/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus_20201001_135205-5db91e00.pth
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 29, in <module>
    main()
  File "demo/pcd_demo.py", line 22, in main
    result, data = inference_detector(model, args.pcd)
  File "/home/wugj/projects/open-mmlab/mmdetection3d/mmdet3d/apis/inference.py", line 73, in inference_detector
    data = test_pipeline(data)
  File "/home/wugj/projects/open-mmlab/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/wugj/projects/open-mmlab/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 369, in __call__
    points = points.reshape(-1, self.load_dim)
ValueError: cannot reshape array of size 68952 into shape (5)

And can i use pcd file or ros::PointCloud2 directly?

**Comment by tianweiy** [comment]
Hi, basically each KITTI point has four features (x,y,z, reflectance) while nuScenes point has five features (x,y,z, reflectance, ring_index). Therefore, you can't use a KITTI pcd file directly with nuScenes configs.

**Comment by Tai-Wang** [comment]
Current code snippets for demo only support KITTI because we typically need multi-sweep poind cloud data on nuScenes. You could try other configs or switch the centerpoint config to KITTI. We may improve this function in the future.

**Comment by KangChou** [comment]
`mmdetection3d# python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/centerpoint/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py checkpoints/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus_20201001_135205-5db91e00.pth
Use load_from_local loader
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 44, in <module>
    main()
  File "demo/pcd_demo.py", line 28, in main
    result, data = inference_detector(model, args.pcd)
  File "/data/my_project/mmdetection3d/mmdet3d/apis/inference.py", line 104, in inference_detector
    data = test_pipeline(data)
  File "/data/my_project/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/data/my_project/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 414, in __call__
    points = points.reshape(-1, self.load_dim)
ValueError: cannot reshape array of size 68952 into shape (5)
`
