### ISSUE TITLE
assert isinstance(results, list), 'results must be a list'

### ISSUE THREAD

**Issue by enesdorukadastec** [open-mmlab/mmdetection3d#2266]
### Model/Dataset/Scheduler description

Hi, when i want to use Wanb hook, i got assert isinstance(results, list), 'results must be a list' error. However after i remove wandb hook, training finish successfully. How can i resolve??

result return Nonetype, when i remove wandbhook, everything runs correctly. i changed nothing. Furthermore, when --no-validate is running, training finished succesfully.

Finally, i recognized source of problem, mmdet/api/train.py  runner.register_hook(eval_hook(val_dataloader, **eval_cfg), priority='LOW')

* I tried default config, i downloaded official repo, i recreated conda environment but it doesnt work. 

I added wandb log config which is shown below to centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_nus config

log_config = dict(hooks=[
                    dict(type='TextLoggerHook'),
                    dict(type='MMDetWandbHook',
                        init_kwargs={'project': 'Centerpoint'},
                        interval=20,
                        log_checkpoint=True,
                        log_checkpoint_metadata=True,
                        num_eval_images=3)
                        ]
) 

checkpoint_config = dict(interval=20)
evaluation = dict(interval=20, pipeline=eval_pipeline)

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by enesdorukadastec** [comment]
I found problem, i removed    log_checkpoint_metadata=True in init kwargs dict and it works, but i dont understand source of problem

**Comment by JingweiZhang12** [comment]
Where did the error `assert isinstance(results, list), 'results must be a list' error` occur? Please provide detail logs.

**Comment by enesdorukadastec** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 252, in main
    train_model(
  File "/home/adastec/mmdetection3d/mmdet3d/apis/train.py", line 344, in train_model
    train_detector(
  File "/home/adastec/mmdetection3d/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/adastec/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/adastec/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "/home/adastec/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/adastec/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 135, in wrapper
    return func(*args, **kwargs)
  File "/home/adastec/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/core/hook/wandblogger_hook.py", line 219, in after_train_epoch
    **self._get_eval_results()
  File "/home/adastec/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/core/hook/wandblogger_hook.py", line 314, in _get_eval_results
    eval_results = self.val_dataset.evaluate(
  File "/home/adastec/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 504, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/adastec/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 443, in format_results
    assert isinstance(results, list), 'results must be a list'
AssertionError: results must be a list
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.

**Comment by enesdorukadastec** [comment]
@JingweiZhang12 but why tensorboardhook or texthook run correctly, i dont get any error

**Comment by JingweiZhang12** [comment]
Suggest that you could print or set a breakpoint to inspect the `results` in the error place.
