### ISSUE TITLE
试运行pcd_demo文件后出现报错SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by 15598003953** [open-mmlab/mmdetection3d#2292]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

mmcv       2.0.0rc4   https://github.com/open-mmlab/mmcv
mmdet      3.0.0rc5   https://github.com/open-mmlab/mmdetection
mmdet3d    1.1.0rc3   c:\users\dove\mmdetection3d
mmengine   0.5.0      https://github.com/open-mmlab/mmengine

### Reproduces the problem - code sample

mmdetection3d /demo/pcd_demo.py demo

### Reproduces the problem - command or script

mmdetection3d/ demo/pcd_demo.py demo/data/kitti/000008.bin configs/second/second_hv_secfpn_8xb6-80e_kitti-3d-car.py checkpoints/second_hv_secfpn_8xb6-80e_kitti-3d-car_20200620_230238-393f000c.pth

### Reproduces the problem - error message

Traceback (most recent call last):
  File "C:/Users/Dove/mmdetection3d/demo/pcd_demo.py", line 4, in <module>
    from mmdet3d.apis import inference_detector, init_model
  File "C:\Users\Dove\mmdetection3d\mmdet3d\apis\__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "C:\Users\Dove\mmdetection3d\mmdet3d\apis\inference.py", line 17, in <module>
    from mmdet3d.structures import Box3DMode, Det3DDataSample, get_box_type
  File "C:\Users\Dove\mmdetection3d\mmdet3d\structures\__init__.py", line 9, in <module>
    from .ops import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "C:\Users\Dove\mmdetection3d\mmdet3d\structures\ops\__init__.py", line 3, in <module>
    from .box_np_ops import (box2d_to_corner_jit, box3d_to_bbox,
  File "C:\Users\Dove\mmdetection3d\mmdet3d\structures\ops\box_np_ops.py", line 7, in <module>
    import numba
  File "D:\Anaconda3\envs\mmdet3d\lib\site-packages\numba\__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "D:\Anaconda3\envs\mmdet3d\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "D:\Anaconda3\envs\mmdet3d\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

### Additional information

请告知该如何解决此报错？

**Comment by jgoenetxea** [comment]
I had the same error on my first try. It looks like there is a problem with version 1.24.2 of Numpy. I fix the problem downgrading the version to 1.23.1.

```
$ python3 -m pip install numpy==1.23.1 --upgrade
```

Hope this helps.
