### ISSUE TITLE
[Bug] read the annotations of KITTI may be unsuccessful？

### ISSUE THREAD

**Issue by onlyonewater** [open-mmlab/mmdetection3d#2313]
### Prerequisite

- [x] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0
OpenCV: 4.7.0
MMEngine: 0.5.0
MMDetection: 3.0.0rc5
MMDetection3D: 1.1.0rc3+60d848b
spconv2.0: False

### Reproduces the problem - code sample

python -u tools/train.py configs/pgd/pgd_r101-caffe_fpn_head-gn_4xb3-4x_kitti-mono3d.py

### Reproduces the problem - command or script

srun -p my-partition -N 1 -c10 --gres=gpu:1 python -u tools/train.py configs/pgd/pgd_r101-caffe_fpn_head-gn_4xb3-4x_kitti-mono3d.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/lustre/duhao/projects/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 86, in __init__
    **kwargs)
  File "/mnt/lustre/duhao/projects/mmdetection3d/mmdet3d/datasets/det3d_dataset.py", line 138, in __init__
    **kwargs)
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 300, in full_init
    self.data_list = self.load_data_list()
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 439, in load_data_list
    raise TypeError(f'The annotations loaded from annotation file '
TypeError: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/runner/loops.py", line 43, in __init__
    super().__init__(runner, dataloader)
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/runner/base_loop.py", line 27, in __init__
    dataloader, seed=runner.seed, diff_rank_seed=diff_rank_seed)
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1333, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
TypeError: class `KittiDataset` in mmdet3d/datasets/kitti_dataset.py: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner.train()
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1657, in train
    self._train_loop)  # type: ignore
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1451, in build_train_loop
    runner=self, dataloader=self._train_dataloader))
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/cache/duhao/opt/anaconda3/envs/mmdet3d/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
TypeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `KittiDataset` in mmdet3d/datasets/kitti_dataset.py: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

### Additional information

I want to train the PGD model on the KITTI dataset, but the error seems that when loading the annotations, it reads the list-typed annotations, but the code wants to receive the dict-typed annotations. I directly copy the standard KITTI data from your official website, and when I read the .pkl file by myself, it is the list-typed annotations, so maybe this place is a bug?

**Comment by onlyonewater** [comment]
and I find that in mmengine the annotations may be the dict-typed (https://mmengine.readthedocs.io/en/latest/advanced_tutorials/basedataset.html), but in mmdetection3d, the annotations may be the list-typed (https://mmdetection3d.readthedocs.io/en/stable/tutorials/customize_dataset.html)

**Comment by JingweiZhang12** [comment]
The list-type is the old annotations in mmdet3d and the docs(https://mmdetection3d.readthedocs.io/en/stable/tutorials/customize_dataset.html), have not updated.
The new annotation is dict-typed, the same as the style in mmengine.
Maybe you should run the script `update_infos_to_v2`?

**Comment by onlyonewater** [comment]
oh, I get it, thanks!!
