### ISSUE TITLE
mmdet3d install: llvmlite & bdist_wheel error

### ISSUE THREAD

**Issue by Rango-Zhang-Hang** [open-mmlab/mmdetection3d#2347]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

torch 1.10.0
CUDA 10.2
mmcv-full 1.14.0
mmdet  2.14.0
mmseg 0.14.1
mmdet3d (trying) 0.17.1(checked)

### Reproduces the problem - code sample

mmdet3d install intructon

### Reproduces the problem - command or script

```
user$ git checkout v0.17.1 
user$ python -m pip install -v -e . 
```

### Reproduces the problem - error message

  Traceback (most recent call last):
    File "/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/ffi/build.py", line 168, in <module>
      main()
    File "/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/ffi/build.py", line 158, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/ffi/build.py", line 120, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

  error: command '/home_nfs/${user}/anaconda3/envs/fast-bev/bin/python' failed with exit code 1
  **error: subprocess-exited-with-error**
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  **note**: This error originates from a subprocess, and is likely not a problem with pip.
  **full command**: /home_nfs/${user}/anaconda3/envs/fast-bev/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /tmp/pip-wheel-utz8sx2i
  cwd: /tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
  Running command python setup.py clean
  running clean
  'build/lib.linux-x86_64-cpython-39' does not exist -- can't clean it
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.9' does not exist -- can't clean it
  removing '/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/llvmlite/__pycache__' (and everything under it)
  removing '/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/__pycache__' (and everything under it)
Failed to build llvmlite
Installing collected packages: llvmlite, ipython-genutils, fastjsonschema, executing, backcall, widgetsnbextension, websocket-client, webcolors, uri-template, traitlets, tqdm, tornado, tomli, tinycss2, threadpoolctl, tensorboard-data-server, tenacity, soupsieve, sniffio, Shapely, rsa, rfc3986-validator, rfc3339-validator, qtpy, pyzmq, python-json-logger, pyrsistent, pygments, pyflakes, pycparser, pycodestyle, pyasn1-modules, psutil, protobuf, prompt-toolkit, prometheus-client, pluggy, platformdirs, pexpect, pathspec, parso, pandocfilters, oauthlib, numpy, nest-asyncio, mypy-extensions, mccabe, MarkupSafe, jupyterlab-widgets, jupyterlab-pygments, jsonpointer, joblib, iniconfig, importlib-metadata, grpcio, fqdn, exceptiongroup, defusedxml, decorator, debugpy, click, cachetools, bleach, attrs, asttokens, absl-py, werkzeug, tifffile, terminado, stack-data, scipy, requests-oauthlib, PyWavelets, pytest, pyquaternion, plyfile, plotly, pandas, numba, networkx, matplotlib-inline, matplotlib, markdown, jupyter-core, jsonschema, jinja2, jedi, imageio, google-auth, flake8, comm, cffi, black, beautifulsoup4, arrow, anyio, trimesh, scikit-learn, scikit-image, nbformat, jupyter-server-terminals, jupyter-client, isoduration, ipython, google-auth-oauthlib, descartes, argon2-cffi-bindings, tensorboard, nbclient, lyft_dataset_sdk, ipykernel, argon2-cffi, qtconsole, nbconvert, jupyter-events, jupyter-console, ipywidgets, jupyter-server, notebook-shim, nbclassic, notebook, jupyter, nuscenes-devkit, mmdet3d
  Running command Running setup.py install for llvmlite
  running install
  /home_nfs/${user}/anaconda3/envs/fast-bev/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  got version from file /tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
  running build_ext
  /home_nfs/${user}/anaconda3/envs/fast-bev/bin/python /tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/ffi/build.py
  LLVM version... 6.0.0

  Traceback (most recent call last):
    File "/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/ffi/build.py", line 168, in <module>
      main()
    File "/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/ffi/build.py", line 158, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/ffi/build.py", line 120, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

  error: command '/home_nfs/${user}/anaconda3/envs/fast-bev/bin/python' failed with exit code 1
  **error: subprocess-exited-with-error**
  
  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  **note**: This error originates from a subprocess, and is likely not a problem with pip.
  **full command**: /home_nfs/${user}/anaconda3/envs/fast-bev/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /tmp/pip-record-axuqa84o/install-record.txt --single-version-externally-managed --compile --install-headers /home_nfs/${user}/anaconda3/envs/fast-bev/include/python3.9/llvmlite
  cwd: /tmp/pip-install-5ct900o7/llvmlite_aea4181d3a08488a8102b98f37afedd2/
  Running setup.py install for llvmlite ... error
**error**: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

### Additional information

I tried some already-existed-similar-issue methods, but these errors still exist.

**Comment by Rango-Zhang-Hang** [comment]
sloved. the cause is after u installed the mmdet, ur mmdet will install gcc 7.3. but for mmdet3d, u need gcc-5 & g++-5. reboot and not issues above.

**Comment by Rango-Zhang-Hang** [comment]
also, if above didnt work. u can try to down grade python<=3.8, cuz py3.9 will make numb error as well
