### ISSUE TITLE
[Bug] Run pre-commit error: `'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'`

### ISSUE THREAD

**Issue by OrangeSodahub** [open-mmlab/mmdetection3d#2412]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

python3.8.10
```
absl-py                         1.1.0
actionlib                       1.13.2
addict                          2.4.0
aiofiles                        22.1.0
aiohttp                         3.8.3
aiosignal                       1.2.0
aiosqlite                       0.18.0
angles                          1.9.13
annlite                         0.3.13
antlr4-python3-runtime          4.9.3
anyio                           3.6.1
appdirs                         1.4.4
apptools                        5.2.0
apturl                          0.5.2
arbotix-python                  0.11.0
argcomplete                     2.0.0
argon2-cffi                     21.3.0
argon2-cffi-bindings            21.2.0
arrow                           1.2.3
asttokens                       2.0.5
astunparse                      1.6.3
async-timeout                   4.0.2
attrs                           19.3.0
autobahn                        17.10.1
Automat                         0.8.0
Babel                           2.11.0
backcall                        0.2.0
backports.cached-property       1.0.2
backports.zoneinfo              0.2.1
base_local_planner              1.17.1
bcrypt                          3.1.7
beautifulsoup4                  4.11.1
black                           22.3.0
bleach                          5.0.0
blinker                         1.4
bondpy                          1.8.6
boto3                           1.24.31
botocore                        1.27.31
breezy                          3.0.2
Brlapi                          0.7.0
build                           0.10.0
CacheControl                    0.12.11
cachetools                      5.2.0
camera-calibration              1.16.0
camera-calibration-parsers      1.12.0
catkin                          0.8.10
catkin-pkg                      0.5.2
catkin-pkg-modules              0.5.2
cbor                            1.0.0
ccimport                        0.4.2
certifi                         2019.11.28
cffi                            1.15.0
cfgv                            3.3.1
chardet                         3.0.4
charset-normalizer              2.1.1
chrome-gnome-shell              0.0.0
cleo                            2.0.1
click                           8.0.4
cloudpickle                     2.1.0
cob-cartesian-controller        0.8.18
cob-script-server               0.6.28
cob-twist-controller            0.8.18
colorama                        0.4.3
command-not-found               0.3
commonmark                      0.9.1
ConfigArgParse                  1.5.3
configobj                       5.0.6
constantly                      15.1.0
controller-manager              0.19.5
controller-manager-msgs         0.19.5
controller-manager-tests        0.19.5
crashtest                       0.4.1
cryptography                    2.8
cumm-cu113                      0.3.7
cupshelpers                     1.0
cv-bridge                       1.16.0
cycler                          0.10.0
Cython                          0.29.14
dacite                          1.6.0
dash                            2.8.1
dash-core-components            2.0.0
dash-html-components            2.0.0
dash-table                      5.0.0
dbus-python                     1.2.16
debugpy                         1.6.0
decorator                       5.1.1
defer                           1.0.6
defusedxml                      0.6.0
Deprecated                      1.2.7
deprecation                     2.1.0
descartes                       1.1.0
det3d                           1.0rc0+a32ca1c       /home/zonlin/Openmmlab/Det3D
diagnostic-analysis             1.11.0
diagnostic-common-diagnostics   1.11.0
diagnostic-updater              1.11.0
dill                            0.3.5.1
distlib                         0.3.4
distro                          1.4.0
distro-info                     0.23ubuntu1
dlib                            19.24.0
dnspython                       2.2.1
docarray                        0.17.0
docker                          6.0.0
docker-pycreds                  0.4.0
docutils                        0.16
dulwich                         0.21.3
duplicity                       0.8.12.0
dynamic-reconfigure             1.7.2
dynamixel_sdk                   3.7.51
e2cnn                           0.2.1
easydict                        1.10
einops                          0.6.0
einsum                          0.3.0
empy                            3.3.2
entrypoints                     0.3
envisage                        7.0.1
eventlet                        0.33.1
executing                       0.8.3
fairscale                       0.4.8
fasteners                       0.14.1
fastimport                      0.9.8
fastjsonschema                  2.15.3
fiftyone                        0.16.5
fiftyone-brain                  0.8.2
fiftyone-db                     0.3.0
fiftyone-desktop                0.22.1
filelock                        3.10.7
fire                            0.4.0
flake8                          4.0.1
Flask                           2.2.2
fqdn                            1.5.1
frozenlist                      1.3.1
future                          0.18.2
fvcore                          0.1.5.post20220512
gazebo_plugins                  2.9.2
gazebo_ros                      2.9.2
gencpp                          0.6.5
geneus                          3.0.0
genlisp                         0.4.18
genmsg                          0.5.16
gennodejs                       2.0.2
genpy                           0.6.15
gitdb                           4.0.10
GitPython                       3.1.31
glob2                           0.7
google-auth                     2.8.0
google-auth-oauthlib            0.4.6
gpg                             1.13.1-unknown
graphql-core                    3.1.7
graphviz                        0.20.1
greenlet                        1.1.2
grpcio                          1.46.3
h11                             0.12.0
h2                              4.1.0
hpack                           4.0.0
html5lib                        1.0.1
httpcore                        0.15.0
httplib2                        0.14.0
httpx                           0.23.0
hydra-core                      1.2.0
hypercorn                       0.13.2
hyperframe                      6.0.1
hyperlink                       19.0.0
identify                        2.5.17
idna                            2.8
image-geometry                  1.16.0
imagecorruptions                1.1.2
imageio                         2.19.3
imgviz                          1.7.2
importlib-metadata              4.11.4
importlib-resources             5.8.0
imutils                         0.5.4
incremental                     16.10.1
iniconfig                       1.1.1
installer                       0.7.0
interactive-markers             1.12.0
iopath                          0.1.9
ipykernel                       6.15.0
ipython                         8.4.0
ipython-genutils                0.2.0
ipywidgets                      7.7.0
isoduration                     20.11.0
isort                           5.12.0
itsdangerous                    2.1.2
jaraco.classes                  3.2.3
jedi                            0.18.1
jeepney                         0.8.0
jina-hubble-sdk                 0.19.2
Jinja2                          3.1.2
jittor                          1.3.4.16
jmespath                        1.0.1
joblib                          1.1.0
joint-state-publisher           1.15.1
joint-state-publisher-gui       1.15.1
json5                           0.9.11
jsonpointer                     2.3
jsonschema                      4.17.3
jupyter                         1.0.0
jupyter_client                  8.0.2
jupyter-console                 6.4.3
jupyter_core                    5.2.0
jupyter-events                  0.5.0
jupyter_packaging               0.12.3
jupyter_server                  2.2.1
jupyter_server_fileid           0.6.0
jupyter_server_terminals        0.4.4
jupyter_server_ydoc             0.6.1
jupyter-ydoc                    0.2.2
jupyterlab                      3.6.1
jupyterlab-pygments             0.2.2
jupyterlab_server               2.19.0
jupyterlab-widgets              1.1.0
kaleido                         0.2.1
kazam                           1.4.5
keyboard                        0.13.5
keyring                         23.13.1
kiwisolver                      1.0.1
labelCloud                      0.7.9
labelme                         5.1.1
labelme2coco                    0.2.4
language-selector               0.1
lark                            1.1.5
laser_geometry                  1.6.7
launchpadlib                    1.10.13
lazr.restfulclient              0.14.2
lazr.uri                        1.0.3
llvmlite                        0.36.0
lmdb                            1.3.0
lockfile                        0.12.2
loguru                          0.6.0
louis                           3.12.0
lxml                            4.5.0
lyft-dataset-sdk                0.0.8
lz4                             3.0.2+dfsg
macaroonbakery                  1.3.1
Mako                            1.1.0
Markdown                        3.3.7
MarkupSafe                      2.1.1
matplotlib                      3.1.2
matplotlib-inline               0.1.3
mayavi                          4.8.1
mccabe                          0.6.1
message-filters                 1.15.14
mistune                         0.8.4
mmcls                           0.23.1
mmcv-full                       1.6.0
mmdet                           2.25.0               /home/zonlin/Openmmlab/SceneClassification/mmdetection-2.25.0
mmdet3d                         1.0.0rc6             /home/zonlin/Openmmlab/mmdetection3d
mmpycocotools                   12.0.3
mmsegmentation                  0.25.0
model-index                     0.1.11
mongoengine                     0.20.0
monotonic                       1.5
more-itertools                  9.1.0
motor                           2.5.1
moveit_commander                1.1.9
moveit-core                     1.1.9
moveit_ros_planning_interface   1.1.9
moveit_ros_visualization        1.1.9
mpi4py                          3.0.3
mpmath                          1.2.1
msgpack                         1.0.5
multidict                       6.0.2
mypy-extensions                 0.4.3
natsort                         8.3.1
nbclassic                       0.5.1
nbclient                        0.6.4
nbconvert                       6.5.0
nbformat                        5.5.0
ndjson                          0.3.1
nest-asyncio                    1.5.5
netifaces                       0.10.4
networkx                        2.2
ninja                           1.10.2.3
nodeenv                         1.7.0
nose                            1.3.7
notebook                        6.4.12
notebook_shim                   0.2.2
numba                           0.53.0
numpy                           1.22.4
nuscenes-devkit                 1.1.9
oauthlib                        3.1.0
objgraph                        3.5.0
olefile                         0.46
omegaconf                       2.2.2
open3d                          0.15.2
opencv-contrib-python           4.6.0.66
opencv-python                   4.7.0.68
opencv-python-headless          4.6.0.66
openmim                         0.2.0
ordered-set                     4.1.0
packaging                       21.3
pandas                          1.4.2
pandocfilters                   1.5.0
paramiko                        2.6.0
parso                           0.8.3
pathspec                        0.9.0
pathtools                       0.1.2
patool                          1.12
pccm                            0.4.4
pcdet                           0.6.0+707a861        /home/zonlin/Openmmlab/OpenPCDet
pexpect                         4.8.0
pickleshare                     0.7.5
Pillow                          9.1.1
pip                             23.0.1
pip-shims                       0.7.3
pkginfo                         1.9.6
pkgutil_resolve_name            1.3.10
platformdirs                    2.5.2
plotly                          4.14.3
pluggy                          1.0.0
plyfile                         0.7.4
poetry                          1.4.2
poetry-core                     1.5.2
poetry-plugin-export            1.3.0
portalocker                     2.5.1
pprintpp                        0.4.0
pr2_controller_manager          1.8.20
pre-commit                      3.0.1
prettytable                     3.3.0
priority                        2.0.0
prometheus-client               0.14.1
prompt-toolkit                  3.0.29
protobuf                        3.19.4
psutil                          5.5.1
ptyprocess                      0.7.0
pure-eval                       0.2.2
py                              1.11.0
py-ubjson                       0.14.0
pyasn1                          0.4.2
pyasn1-modules                  0.2.1
pyassimp                        4.1.4
pybboxes                        0.1.6
pybind11                        2.10.3
pycairo                         1.16.2
pycocotools                     2.0.4
pycodestyle                     2.8.0
pycparser                       2.21
pycrypto                        2.6.1
pycryptodomex                   3.6.1
pycups                          1.9.73
pydot                           1.4.1
pyface                          7.4.4
pyflakes                        2.4.0
PyGithub                        1.43.7
Pygments                        2.12.0
PyGObject                       3.36.0
pygraphviz                      1.5
PyHamcrest                      1.9.0
PyJWT                           1.7.1
pymacaroons                     0.13.0
pymongo                         3.12.3
PyNaCl                          1.3.0
PyOpenGL                        3.1.0
PyOpenGL-accelerate             3.1.6
pyOpenSSL                       19.0.0
pyparsing                       2.4.6
pypng                           0.0.20
pyproject_hooks                 1.0.0
PyQRCode                        1.2.1
PyQt5                           5.15.9
PyQt5-Qt5                       5.15.2
PyQt5-sip                       12.11.1
pyquaternion                    0.9.9
pyRFC3339                       1.1
pyrsistent                      0.18.1
pyserial                        3.4
PySide2                         5.15.2.1
pytest                          7.1.2
pytest-runner                   6.0.0
python-apt                      2.0.0+ubuntu0.20.4.7
python-dateutil                 2.8.2
python-debian                   0.1.36ubuntu1
python-gitlab                   2.0.1
python-gnupg                    0.4.5
python-json-logger              2.0.4
python-multipart                0.0.5
python-pcl                      0.3
python-qt-binding               0.4.4
python-snappy                   0.5.3
PyTrie                          0.2
pytz                            2022.1
pytz-deprecation-shim           0.1.0.post0
PyWavelets                      1.3.0
pyxattr                         0.6.1
pyxdg                           0.26
PyYAML                          6.0
pyzmq                           25.0.0
qt-dotgraph                     0.4.2
qt-gui                          0.4.2
qt-gui-cpp                      0.4.2
qt-gui-py-common                0.4.2
qtconsole                       5.3.1
QtPy                            2.1.0
rapidfuzz                       2.15.0
reportlab                       3.5.34
requests                        2.28.2
requests-oauthlib               1.3.1
requests-toolbelt               0.10.1
requests-unixsocket             0.2.0
resource_retriever              1.12.7
retrying                        1.3.3
rfc3339-validator               0.1.4
rfc3986                         1.5.0
rfc3986-validator               0.1.1
rich                            12.5.1
roman                           2.0.0
ros_numpy                       0.0.5
rosapi                          0.11.14
rosbag                          1.15.14
rosboost-cfg                    1.15.8
rosbridge-library               0.11.14
rosbridge-server                0.11.14
rosclean                        1.15.8
roscreate                       1.15.8
rosdep                          0.21.0
rosdep-modules                  0.21.0
rosdistro                       0.9.0
rosdistro-modules               0.9.0
rosgraph                        1.15.14
rosinstall                      0.7.8
rosinstall-generator            0.1.22
roslaunch                       1.15.14
roslib                          1.15.8
roslint                         0.12.0
roslz4                          1.15.14
rosmake                         1.15.8
rosmaster                       1.15.14
rosmsg                          1.15.14
rosnode                         1.15.14
rosparam                        1.15.14
rospkg                          1.4.0
rospkg-modules                  1.4.0
rospy                           1.15.14
rosservice                      1.15.14
rostest                         1.15.14
rostopic                        1.15.14
rosunit                         1.15.8
roswtf                          1.15.14
rqt_action                      0.4.9
rqt_bag                         0.5.1
rqt_bag_plugins                 0.5.1
rqt_console                     0.4.11
rqt-controller-manager          0.19.5
rqt_dep                         0.4.12
rqt_graph                       0.4.14
rqt_gui                         0.5.3
rqt_gui_py                      0.5.3
rqt_image_view                  0.4.16
rqt_joint_trajectory_controller 0.20.0
rqt_launch                      0.4.9
rqt_logger_level                0.4.11
rqt-moveit                      0.5.10
rqt_msg                         0.4.10
rqt_nav_view                    0.5.7
rqt_plot                        0.4.13
rqt_pose_view                   0.5.11
rqt_publisher                   0.4.10
rqt_py_common                   0.5.3
rqt_py_console                  0.4.10
rqt-reconfigure                 0.5.5
rqt-robot-dashboard             0.5.8
rqt-robot-monitor               0.5.14
rqt_robot_steering              0.5.12
rqt_runtime_monitor             0.5.9
rqt-rviz                        0.7.0
rqt_service_caller              0.4.10
rqt_shell                       0.4.11
rqt_srv                         0.4.9
rqt_tf_tree                     0.6.3
rqt_top                         0.4.10
rqt_topic                       0.4.13
rqt_web                         0.4.10
rsa                             4.8
rviz                            1.14.14
s3transfer                      0.6.0
sahi                            0.11.13
scikit-image                    0.19.3
scikit-learn                    1.1.1
scipy                           1.8.1
screen-resolution-extra         0.0.0
SecretStorage                   3.3.3
Send2Trash                      1.8.0
sensor-msgs                     1.13.1
sentinel                        0.3.0
sentry-sdk                      1.19.0
service-identity                18.1.0
setproctitle                    1.3.2
setuptools                      62.3.4
Shapely                         1.8.2
SharedArray                     3.2.2
shellingham                     1.5.0.post1
shiboken2                       5.15.2.1
simplejson                      3.16.0
sip                             4.19.21
six                             1.14.0
smach                           2.5.0
smach-ros                       2.5.0
smclib                          1.8.6
smmap                           5.0.0
sniffio                         1.2.0
sortedcontainers                2.4.0
soupsieve                       2.3.2.post1
spconv-cu113                    2.2.6
srdfdom                         0.6.3
sse-starlette                   0.10.3
sseclient-py                    1.7.2
ssh-import-id                   5.10
stack-data                      0.3.0
starlette                       0.16.0
strawberry-graphql              0.96.0
style                           1.1.0
sympy                           1.10.1
systemd-python                  234
tabulate                        0.8.10
tenacity                        8.0.1
tensorboard                     2.9.1
tensorboard-data-server         0.6.1
tensorboard-plugin-wit          1.8.1
tensorboardX                    2.5.1
termcolor                       1.1.0
terminado                       0.15.0
terminaltables                  3.1.10
tf                              1.13.2
tf-conversions                  1.13.2
tf2-geometry-msgs               0.7.5
tf2-kdl                         0.7.5
tf2-py                          0.7.5
tf2-ros                         0.7.5
threadpoolctl                   3.1.0
tifffile                        2022.5.4
timm                            0.6.7
tinycss2                        1.1.1
toml                            0.10.2
tomli                           2.0.1
tomlkit                         0.11.6
topic-tools                     1.15.14
torch                           1.11.0+cu113
torch-scatter                   2.0.9
torchaudio                      0.11.0+cu113
torchvision                     0.12.0+cu113
tornado                         6.2
tqdm                            4.64.0
traitlets                       5.9.0
traits                          6.4.1
traitsui                        7.4.3
trimesh                         2.35.39
trove-classifiers               2023.3.9
Twisted                         18.9.0
txaio                           2.10.0
typing_extensions               4.2.0
tzdata                          2022.1
tzlocal                         4.2
u-msgpack-python                2.1
ubuntu-advantage-tools          27.8
ubuntu-drivers-common           0.0.0
ufw                             0.36
unattended-upgrades             0.1
universal-analytics-python3     1.1.1
update                          0.0.1
urdfdom-py                      0.4.6
uri-template                    1.2.0
urllib3                         1.26.12
usb-creator                     0.3.7
vcstools                        0.1.42
virtualenv                      20.14.1
voxel51-eta                     0.7.1
vtk                             9.2.5
wadllib                         1.3.3
wandb                           0.14.0
wcwidth                         0.2.5
webcolors                       1.12
webencodings                    0.5.1
websocket-client                1.4.1
Werkzeug                        2.2.2
wheel                           0.37.1
widgetsnbextension              3.6.0
wrapt                           1.11.2
wsaccel                         0.6.2
wsproto                         1.1.0
wstool                          0.1.18
xacro                           1.14.13
xkit                            0.0.0
xmltodict                       0.13.0
y-py                            0.5.5
yacs                            0.1.8
yapf                            0.32.0
yarl                            1.8.1
youtube-dl                      2020.3.24
ypy-websocket                   0.8.2
zipp                            3.8.0
zope.interface                  4.7.1
```

### Reproduces the problem - code sample

None

### Reproduces the problem - command or script

```shell
pip install pre-commit
pre-commit install
pre-commit run --all-files
```

### Reproduces the problem - error message

```
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/zonlin/.cache/pre-commit/repo_6_6q3tc
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-gneorq89/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-gneorq89/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /home/zonlin/.cache/pre-commit/pre-commit.log
```

### Additional information

pre-commit.log:
```
#version information

pre-commit version: 3.0.1
git --version: git version 2.25.1
sys.version:
    3.8.10 (default, Mar 15 2022, 12:22:08) 
    [GCC 9.4.0]
sys.executable: /home/zonlin/Openmmlab/openmmlab_env/bin/python
os.name: posix
sys.platform: linux

#error information

An unexpected error has occurred: CalledProcessError: command: ('/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/zonlin/.cache/pre-commit/repo_6_6q3tc
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-gneorq89/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-gneorq89/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Traceback (most recent call last):
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/pre_commit/commands/run.py", line 436, in run
    install_hook_envs(to_install, store)
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/pre_commit/repository.py", line 239, in install_hook_envs
    _hook_install(hook)
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/pre_commit/repository.py", line 86, in _hook_install
    lang.install_environment(
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/pre_commit/languages/helpers.py", line 49, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/pre_commit/util.py", line 115, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/zonlin/.cache/pre-commit/repo_6_6q3tc
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error

      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/zonlin/.cache/pre-commit/repo_6_6q3tc/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-gneorq89/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-gneorq89/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

**Comment by sunjiahao1999** [comment]
It seem isort version wrong. We recommend using the latest version of mmdetection3d and this bug is fixed in main branch.

**Comment by OrangeSodahub** [comment]
Thanks. Previous I tryied a lot upgrading the isort in the local env, didn't know that in the `.pre-commit.yaml`. Now solved.
