### ISSUE TITLE
hi,i have got some questions on training.

### ISSUE THREAD

**Issue by guigui6666** [open-mmlab/mmdetection3d#2421]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by sunjiahao1999** [comment]
Check your keys in `nuscenes_train.pkl` and `nuscenes_dbinfos_train.pkl` and make sure your pkl file is generated correctly as shown in the tutorial.

**Comment by hankeceli** [comment]
I am in the process of building a dataset using `v1.0-mini`.

I have installed all the prerequisite libraries as described in the README.md file. Following that, I executed the `python setup.py develop` command for code base installation.

My working tree currently looks like this:

```
bevfusion
├── mmdet3d
├── tools
├── configs
├── data
│   ├── nuscenes
│   │   ├── maps
│   │   ├── samples
│   │   ├── sweeps
│   │   ├── v1.0-mini
│   │   ├── nuscenes_infos_train.pkl
│   │   ├── nuscenes_infos_val.pkl
│   │   ├── nuscenes_infos_mini_val.pkl
│   │   ├── nuscenes_infos_mini_train.pkl

```
I downloaded the .pkl files from this [link](https://github.com/open-mmlab/mmdetection3d/issues/2454#issuecomment-1517743436).
When I run the command `python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini`, I encounter a `FileNotFoundError: [Errno 2] No such file or directory: './data/nuscenes/nuscenes_infos_train.pkl'` error, unless I manually add the .pkl files shared by the author. As far as I understand, those .pkl files should automatically created, but it gives not found error during running Dataset Preparation phase [as it says here](https://github.com/open-mmlab/mmdetection3d/blob/1.0/docs/en/datasets/nuscenes_det.md#dataset-preparation).

If I add the .pkl files, I face the following error:
```
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.208 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.0 seconds.
======
total scene num: 10
exist scene num: 10
train scene: 8, val scene: 2
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 404/404, 5.9 task/s, elapsed: 69s, ETA:     0s
nuscenes
train sample: 323, val sample: 81
Create GT Database of NuScenesDataset
Traceback (most recent call last):
  File "/home/ubuntu/Documents/students/han_k/hanBev/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/ubuntu/Documents/students/han_k/bevfusion/mmdet3d/datasets/nuscenes_dataset.py", line 143, in __init__
    super().__init__(
  File "/home/ubuntu/Documents/students/han_k/bevfusion/mmdet3d/datasets/custom_3d.py", line 66, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/home/ubuntu/Documents/students/han_k/bevfusion/mmdet3d/datasets/nuscenes_dataset.py", line 203, in load_annotations
    data_infos = list(sorted(data["infos"], key=lambda e: e["timestamp"]))
KeyError: 'infos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/create_data.py", line 122, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 45, in nuscenes_data_prep
    create_groundtruth_database(
  File "/home/ubuntu/Documents/students/han_k/bevfusion/tools/data_converter/create_gt_database.py", line 252, in create_groundtruth_database
    dataset = build_dataset(dataset_cfg)
  File "/home/ubuntu/Documents/students/han_k/bevfusion/mmdet3d/datasets/builder.py", line 42, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ubuntu/Documents/students/han_k/hanBev/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "NuScenesDataset: 'infos'"
```

I also downloaded the map extension, but there are four versions of [them](https://www.nuscenes.org/download), and two of them are deprecated. Which one should be downloaded? Additionally, the directory structure for the map extensions is not described in the README.md. Should we directly extract all the files under the `maps` dir?

Thank you.

PS: It is crucial to run it on the NuScenes mini dataset. Looking forward for your solution.
