### ISSUE TITLE
mmdetection==0.17.1

### ISSUE THREAD

**Issue by dandervis** [open-mmlab/mmdetection3d#2427]
您好 我所复现的代码工程项目指定了mmdetection3d的版本必须为0.17.1，但是我按照您的方法安装mmdetection3d后只能安装最新版本的，哪怕是使用您所公布的[Customize Installation](https://github.com/openmmlab/mmdetection3d/blob/1.0/docs/en/getting_started.md#customize-installation)方式，也找不到在哪里指定0.17.1，请问我应该如何做才可以安装指定版本0.17.1的mmdetection3d呢

**Comment by Xiangxu-0103** [comment]
你可以使用 pip 指定安装 mmdetection3d，例如 `pip install mmdet3d==0.17.1`，或者clone我们的代码库后运行 `git checkout v0.17.1` 切换到 v0.17.1 版本分支。

**Comment by Xiangxu-0103** [comment]
```bash
conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge
pip install mmcv-full==1.3.8
pip install mmdet==2.14.0
pip install mmsegmentation==0.14.1
git clone https://github.com/openmmlab/mmdetection3d
cd mmdetection3d
git checkout v0.17.1
pip install -e .
```

希望能够帮助到你。

**Comment by dandervis** [comment]
我按照您给出的步骤进行安装 前面一切正常 到最后运行pip install -e .时报错
Installing collected packages: mmdet3d
    Running setup.py develop for mmdet3d
         error: subprocess-exited-with-error
         python setup.py develop did not run successfully.
         exit code : 1
         No CUDA runtime is found ,usingCUDA_HOME='/uer/local/cuda'
         ......

随后我进入python查看了torch的版本 确为1.8.1 但是使用torch.cuda.is_available()查询cuda时结果为fales，请问这看起来是否还是我11.3的cuda不匹配呢 还是说我的环境里没有读取正确路径的cuda或是其他原因？

**Comment by Xiangxu-0103** [comment]
这需要您首先将 cuda 路径手动添加到环境变量中，再进行安装。

**Comment by dandervis** [comment]
是的 我的bashrc里手动source了cuda 问题应该不是出在这里 我按照您给出的conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge安装完torch后, conda list出来的pytorch显示了[cpu_only] 我想问题可能是出现在了这里 请问是否您可以给出适配gpu的呢

**Comment by YuJiXYZ** [comment]
Hi,  https://github.com/Xiangxu-0103
谢谢您的教程，我也想安装0.17.0版本的mmdet3d。我按照您的教程，最后一步总是报错：错误如下，想请教您知道如何解决吗？感谢！


        adding license file 'LICENSE'
        writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
        running build_ext
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/ps/yuji/mmdetection3d/setup.py", line 248, in <module>
            zip_safe=False)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
            super().run_command(command)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-p
            cmd_obj.run()
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
            super().run_command(command)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
            _build_ext.run(self)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
            _build_ext.build_ext.run(self)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
            self.build_extensions()
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
            _check_cuda_version(compiler_name, compiler_version)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 382, in _check_cuda_version
            torch_cuda_version = packaging.version.parse(torch.version.cuda)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
            return Version(version)
          File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
            match = self._regex.search(version)
        TypeError: expected string or bytes-like object
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─
      EasyInstallDeprecationWarning,
    /home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    /home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    warning: no files found matching 'mmdet3d/ops/**/*.cpp'
    warning: no files found matching 'mmdet3d/ops/**/*.cu'
    warning: no files found matching 'mmdet3d/ops/**/*.h'
    warning: no files found matching 'mmdet3d/ops/**/*.cc'
    warning: no files found matching 'mmdet3d/VERSION'
    adding license file 'LICENSE'
    writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/ps/yuji/mmdetection3d/setup.py", line 248, in <module>
        zip_safe=False)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
        self.build_extensions()
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
        _check_cuda_version(compiler_name, compiler_version)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 382, in _check_cuda_version
        torch_cuda_version = packaging.version.parse(torch.version.cuda)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
        return Version(version)
      File "/home/ps/miniconda3/envs/yuji_trans/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.


谢谢！

**Comment by Xiangxu-0103** [comment]
@YuJiXYZ 你好，我这边试了下是可以正确安装的，请你检查下你的环境是否正确，例如 `conda pytorch 使用的 cuda` 与你本地的 cuda 版本是否一致，以及

**Comment by YuJiXYZ** [comment]
Ok, 我会再尝试一下，我估计是我本地的cuda版本太高导致的，感谢回复。

**Comment by Cindy0725** [comment]
hello，请问你这个问题解决了吗？我是cuda11.6， torch 1.13.0，我需要用mvcc-full 1.17，但是我每次一安装mmdet3d都是最新版本，如果我安装更低版本的mmdet3d都会报错，用最新版本又和mvcc-full 1.17版本不兼容，谢谢！

**Comment by YuJiXYZ** [comment]
你好，时间有点久了，我记得最后我换了台服务器cuda:11.3好像是可以了。
然后mmdet3d的版本可以自己设定，从历史版本中可以手动安装，而默认安装都会最新版。

**Comment by fjq-tongji** [comment]
> ```shell
> conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge
> pip install mmcv-full==1.3.8
> pip install mmdet==2.14.0
> pip install mmsegmentation==0.14.1
> git clone https://github.com/openmmlab/mmdetection3d
> cd mmdetection3d
> git checkout v0.17.1
> pip install -e .
> ```
> 
> 希望能够帮助到你。

亲测有效，非常感谢

**Comment by jackwky** [comment]
我也遇到了这个问题，但是我无法解决。
![image](https://github.com/open-mmlab/mmdetection3d/assets/126163628/664d31b7-5bca-4490-b6c2-e788d90f1bd0)
![image](https://github.com/open-mmlab/mmdetection3d/assets/126163628/8fefb67d-1c69-44d7-bc8f-72e97166575a)
我使用的是这个pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 mmcv-full==1.4.0 mmdet==2.14.0 mmsegmentation==0.14.1

**Comment by davidpengiupui** [comment]
> 我也遇到了这个问题，但是我无法解决。 ![image](https://private-user-images.githubusercontent.com/126163628/294655180-664d31b7-5bca-4490-b6c2-e788d90f1bd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTE5NjQsIm5iZiI6MTczMzg5MTY2NCwicGF0aCI6Ii8xMjYxNjM2MjgvMjk0NjU1MTgwLTY2NGQzMWI3LTViY2EtNDQ5MC1iNmMyLWU3ODhkOTBmMWJkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwNDM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTIwNTFjMDQwMjY3Nzc2OGQ0Y2M2MjFiYThhZDdiMDM1YWU5MmMzMDQ3MGRiMDA5MTExYTk3ZGNiY2I0ODIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g9MRD8M51R9YaPxgSHyZtjAphuBGwQ2-6Zl5Ig4cWF4) ![image](https://private-user-images.githubusercontent.com/126163628/294655189-8fefb67d-1c69-44d7-bc8f-72e97166575a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTE5NjQsIm5iZiI6MTczMzg5MTY2NCwicGF0aCI6Ii8xMjYxNjM2MjgvMjk0NjU1MTg5LThmZWZiNjdkLTFjNjktNDRkNy1iYzhmLTcyZTk3MTY2NTc1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwNDM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTkyMjU1ZjMzMWEzYWRlNmVjYWEyMTE1MWMyZmM2YTAxNWNjZGViYWJkNWE1YzAzZDAyOGNlMTdiMDY3ZjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4HnBdAig4MWD0ecMRwtLstrkpZjeWX5iorhgB6VS9B8) 我使用的是这个pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 mmcv-full==1.4.0 mmdet==2.14.0 mmsegmentation==0.14.1

我也是

**Comment by davidpengiupui** [comment]
> 我也遇到了这个问题，但是我无法解决。 ![image](https://private-user-images.githubusercontent.com/126163628/294655180-664d31b7-5bca-4490-b6c2-e788d90f1bd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTE5NjQsIm5iZiI6MTczMzg5MTY2NCwicGF0aCI6Ii8xMjYxNjM2MjgvMjk0NjU1MTgwLTY2NGQzMWI3LTViY2EtNDQ5MC1iNmMyLWU3ODhkOTBmMWJkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwNDM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTIwNTFjMDQwMjY3Nzc2OGQ0Y2M2MjFiYThhZDdiMDM1YWU5MmMzMDQ3MGRiMDA5MTExYTk3ZGNiY2I0ODIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g9MRD8M51R9YaPxgSHyZtjAphuBGwQ2-6Zl5Ig4cWF4) ![image](https://private-user-images.githubusercontent.com/126163628/294655189-8fefb67d-1c69-44d7-bc8f-72e97166575a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTE5NjQsIm5iZiI6MTczMzg5MTY2NCwicGF0aCI6Ii8xMjYxNjM2MjgvMjk0NjU1MTg5LThmZWZiNjdkLTFjNjktNDRkNy1iYzhmLTcyZTk3MTY2NTc1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwNDM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTkyMjU1ZjMzMWEzYWRlNmVjYWEyMTE1MWMyZmM2YTAxNWNjZGViYWJkNWE1YzAzZDAyOGNlMTdiMDY3ZjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4HnBdAig4MWD0ecMRwtLstrkpZjeWX5iorhgB6VS9B8) 我使用的是这个pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 mmcv-full==1.4.0 mmdet==2.14.0 mmsegmentation==0.14.1

请问您解决了吗？
