### ISSUE TITLE
Can't train un nuImages

### ISSUE THREAD

**Issue by salokin1997** [open-mmlab/mmdetection3d#2435]
Hallo,

I have tried to train Mask RCNN and HTC on nuImages. But in both cases it fails with the following error message:

```
$ python3 tools/train.py configs/nuimages/mask-rcnn_r50_fpn_1x_nuim.py 

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 124, in main
    runner = Runner.from_cfg(cfg)
  File "/home/labor/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/labor/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 290, in __init__
    raise ValueError(
ValueError: train_dataloader, train_cfg, and optim_wrapper should be either all None or not None, but got train_dataloader=None, train_cfg={'type': 'EpochBasedTrainLoop', 'max_epochs': 12, 'val_interval': 1}, optim_wrapper={'type': 'OptimWrapper', 'optimizer': {'type': 'SGD', 'lr': 0.02, 'momentum': 0.9, 'weight_decay': 0.0001}}.
```

I used your script to convert the Labels to COCO-format. My data directory looks like this:
```
- mmdet3d
- - data
- - - annotations
- - - - nuimages_v1.0-train.json
- - - - nuimages_v1.0-val.json
- - - samples
- - - - CAM_BACK
- - - - etc.
```

Thank you for your help!

**Comment by Xiangxu-0103** [comment]
Thanks for your feedback. We will refactor it ASAP.

**Comment by Orbis36** [comment]
Same error

**Comment by duanmushuangquan** [comment]
Same error.

**Comment by ZitengXue** [comment]
same error

**Comment by ZitengXue** [comment]
> Thanks for your feedback. We will refactor it ASAP.

Hi!,sorry to bother you, I noticed that the bug still hasn't been fixed, is there any temporary solution for the bug(no train_dataloader)？

**Comment by Mingqj** [comment]
same error

**Comment by Ruvennsiow** [comment]
same error
