### ISSUE TITLE
File corupt error when run create_data.py in nuScenes dataset

### ISSUE THREAD

**Issue by benz725** [open-mmlab/mmdetection3d#2448]
Since the nuscnes dataset is so hudge. It cost me **3 days** to untar it and cost me **3 TB storage space**.
When I run the create_data.py as the mm3d official tutorial : python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes
It threw an error like below:
------------------------error slash-----------------------------
'NoneType' object has no attribute 'shape'
  File "/home/benzlife/mmdetection3d/tools/data_converter/nuscenes_converter.py", line 373, in export_2d_annotation
    (height, width, _) = mmcv.imread(cam_info['data_path']).shape
  File "/home/benzlife/mmdetection3d/tools/create_data.py", line 85, in nuscenes_data_prep
    nuscenes_converter.export_2d_annotation(
  File "/home/benzlife/mmdetection3d/tools/create_data.py", line 250, in <module>
    nuscenes_data_prep(
AttributeError: 'NoneType' object has no attribute 'shape
------------------------error slash-------------------------------
Then I find the specific **cam_info['data_path']**, it's **'./data/nuscenes/samples/CAM_BACK/n008-2018-07-26-12-13-50-0400__CAM_BACK__1532622015687558.jpg'**, and found that this jpg file is accually corrupted.
**So question is** : I'm not sure if this file corruption is caused by my unproperly untar or something other. If my untar process has something wrong, how to find the unproperly untared file becuase I'm not tend to untar all the files again.
Or someone may have some other advices?

The whole create_data.py run log is like below:
-----------------------log slash----------------------------------
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 28.431 seconds.
======
Reverse indexing ...
Done reverse indexing in 6.3 seconds.
======
total scene num: 850
exist scene num: 850
train scene: 700, val scene: 150
[>>>>>>>>>>>>>>>>>>>>>>>] 34149/34149, 20.3 task/s, elapsed: 1678s, ETA:     0s
train sample: 28130, val sample: 6019
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 41.962 seconds.
======
Reverse indexing ...
Done reverse indexing in 6.4 seconds.
======
[>>>>                      ] 5278/28130, 7.0 task/s, elapsed: 758s, ETA:  3281sTraceback (most recent call last):
  File "tools/create_data.py", line 250, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 85, in nuscenes_data_prep
    nuscenes_converter.export_2d_annotation(
  File "/home/benzlife/mmdetection3d/tools/data_converter/nuscenes_converter.py", line 373, in export_2d_annotation
    (height, width, _) = mmcv.imread(cam_info['data_path']).shape
AttributeError: 'NoneType' object has no attribute 'shape'
-----------------------log slash----------------------------------

Thank you.

**Comment by JingweiZhang12** [comment]
@benz725 Thanks for your feedback.
1. The cause of  `'NoneType' object has no attribute 'shape'` may be the path of the image is wrong. We'll appreciate it if you could create a PR to fix this bug?
2. We'll upload the annotation files generated offline in the main branch today and you could just download the annotation file.

**Comment by benz725** [comment]
> @benz725 Thanks for your feedback.
> 
> 1. The cause of  `'NoneType' object has no attribute 'shape'` may be the path of the image is wrong. We'll appreciate it if you could create a PR to fix this bug?
> 2. We'll upload the annotation files of all 3d datasets generated offline in the main branch today and you could just download the annotation file.

Thank you.
1. There is a img file in that path, but the img is corrupted, so the return of the mmcv.imread().shape is None.
I don't understand what "PR" is as you just said. But I modified the code to record the corrupted file paths as below:
---------------------------code-----------------------------------
            **try:
                (height, width, _) = mmcv.imread(cam_info['data_path']).shape
            except:
                with open('corrupt_files.txt', 'a') as f1:
                    f1.write(cam_info['data_path']+'\n')
                print(cam_info['data_path'] + ' corrupt error.')
                continue**
----------------------------code----------------------------------
2. I'll appreciate if you remind me when I can download the offline files.
