### ISSUE TITLE
error nuscenes_infos_train.pkl

### ISSUE THREAD

**Issue by SMSajadi99** [open-mmlab/mmdetection3d#2454]
Hello, I received GitHub, I went to the folders according to your instructions, and its site is:

https://github.com/open-mmlab/mmdetection3d/blob/1.0/docs/en/datasets/nuscenes_det.md

The outputs are as follows:
![image](https://user-images.githubusercontent.com/69210109/233606449-058a40ab-8ffd-4e2b-82ff-ea693ebb87ac.png)
![image](https://user-images.githubusercontent.com/69210109/233606514-ebee6895-5b91-4945-8d32-0e7ec7097535.png)
![image](https://user-images.githubusercontent.com/69210109/233606744-6846b907-6358-411f-a12f-f2d14da91327.png)

But I encountered this error

![image](https://user-images.githubusercontent.com/69210109/233605768-eab07bbf-cfd9-49f3-a604-b01eb5016a17.png)

can you help me

**Comment by SMSajadi99** [comment]
I am working with mini data, now the problem is that it calls the error <sweeps/LIDAR_TOP> twice

**Comment by JingweiZhang12** [comment]
@SMSajadi99  We'll provide annotation files generated offline soon. You can try it first:
[nuscenes train split](https://download.openmmlab.com/mmdetection3d/data/nuscenes/nuscenes_infos_train.pkl) 
[nuscenes val split](https://download.openmmlab.com/mmdetection3d/data/nuscenes/nuscenes_infos_val.pkl) 
[nuscenes_mini train split](https://download.openmmlab.com/mmdetection3d/data/nuscenes/nuscenes_mini_infos_train.pkl) 
[nuscenes_mini val split](https://download.openmmlab.com/mmdetection3d/data/nuscenes/nuscenes_mini_infos_val.pkl)

**Comment by SMSajadi99** [comment]
Thanks so much

**Comment by SMSajadi99** [comment]
@JingweiZhang12 Hi

Thank you very much for the data you sent.

But I want to start it on my system, on data mini.
I will try to explain in detail so that we can fix the bug, thank you for your help.

nuscenes folder photo:

![image](https://user-images.githubusercontent.com/69210109/233829582-87078f6a-aeef-4ec7-9801-ebc89ee80422.png)

Installation libraries using Cuda 23.1.0 and Cuda 11.7:
`
Package                  Version
------------------------ ---------
absl-py                  1.4.0
addict                   2.4.0
anyio                    3.6.2
appdirs                  1.4.4
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    22.2.0
backcall                 0.2.0
beautifulsoup4           4.12.0
black                    23.3.0
bleach                   6.0.0
build                    0.7.0
cachetools               5.3.0
ccimport                 0.4.2
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       3.1.0
click                    8.1.3
colorama                 0.4.6
comm                     0.1.3
ConfigArgParse           1.5.3
contextlib2              21.6.0
contourpy                1.0.7
cumm-cu117               0.4.8
cycler                   0.11.0
dash                     2.9.2
dash-core-components     2.0.0
dash-html-components     2.0.0
dash-table               5.0.0
debugpy                  1.6.6
decorator                5.1.1
defusedxml               0.7.1
descartes                1.1.0
docopt                   0.6.2
exceptiongroup           1.1.1
executing                1.2.0
fastjsonschema           2.16.3
fire                     0.5.0
flake8                   6.0.0
Flask                    2.2.3
flit_core                3.8.0
fonttools                4.39.3
fqdn                     1.5.1
google-auth              2.17.1
google-auth-oauthlib     1.0.0
grpcio                   1.53.0
h5py                     3.8.0
idna                     3.4
imageio                  2.27.0
importlib-metadata       6.3.0
importlib-resources      5.12.0
iniconfig                2.0.0
inspect-it               0.3.2
ipykernel                6.22.0
ipython                  8.12.0
ipython-genutils         0.2.0
ipywidgets               8.0.6
isoduration              20.11.0
itsdangerous             2.1.2
itypes                   1.2.0
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
jsonpointer              2.3
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           8.1.0
jupyter-console          6.6.3
jupyter_core             5.3.0
jupyter-events           0.6.3
jupyter_server           2.5.0
jupyter_server_terminals 0.4.4
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.7
kiwisolver               1.4.4
lark                     1.1.5
lazy_loader              0.2
llvmlite                 0.36.0
loguru                   0.6.0
lyft-dataset-sdk         0.0.8
Markdown                 3.4.3
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.5.2
matplotlib-inline        0.1.6
mccabe                   0.7.0
mdurl                    0.1.2
mistune                  2.0.5
mkl-fft                  1.3.1
mkl-random               1.2.2
mkl-service              2.4.0
mmcv                     2.0.0
mmdet                    3.0.0
mmengine                 0.7.2
model-index              0.1.11
mpi4py                   3.0.3
msgpack                  1.0.5
msgpack-numpy            0.4.8
multimethod              1.9.1
mypy-extensions          1.0.0
nbclassic                0.5.4
nbclient                 0.7.2
nbconvert                7.2.10
nbformat                 5.7.0
nest-asyncio             1.5.6
networkx                 3.1
ninja                    1.11.1
notebook                 6.5.3
notebook_shim            0.2.2
numba                    0.53.0
numpy                    1.23.5
nuscenes-devkit          1.1.10
oauthlib                 3.2.2
olefile                  0.46
open3d                   0.17.0
opencv-python            4.7.0.72
openmim                  0.3.7
ordered-set              4.1.0
packaging                23.0
pandas                   2.0.0
pandocfilters            1.5.0
parso                    0.8.3
pathlib                  1.0.1
pathspec                 0.11.1
pccm                     0.4.6
pep517                   0.13.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.0.1
pip-tools                6.13.0
pkgutil_resolve_name     1.3.10
platformdirs             3.2.0
plotly                   5.14.1
pluggy                   1.0.0
portalocker              2.7.0
prometheus-client        0.16.0
prompt-toolkit           3.0.38
protobuf                 4.22.1
psutil                   5.9.4
pure-eval                0.2.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pybind11                 2.10.4
pycocotools              2.0.6
pycodestyle              2.10.0
pycparser                2.21
pyflakes                 3.0.1
Pygments                 2.14.0
pyparsing                3.0.9
pyquaternion             0.9.9
pyrsistent               0.19.3
pytest                   7.3.0
python-dateutil          2.8.2
python-json-logger       2.0.7
pytools                  2022.1.14
pytz                     2023.3
PyWavelets               1.4.1
pywin32                  306
pywinpty                 2.0.10
PyYAML                   6.0
pyzmq                    25.0.2
qtconsole                5.4.2
QtPy                     2.3.1
regex                    2023.3.23
requests                 2.28.2
requests-oauthlib        1.3.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rich                     13.3.4
rsa                      4.9
scikit-image             0.20.0
scikit-learn             1.2.2
scipy                    1.9.1
Send2Trash               1.8.0
setuptools               65.6.3
Shapely                  1.8.5
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.4
spconv-cu117             2.3.6
stack-data               0.6.2
tabulate                 0.9.0
tenacity                 8.2.2
tensorboard              2.12.1
tensorboard-data-server  0.7.0
tensorboard-plugin-wit   1.8.1
tensorpack               0.11
termcolor                2.2.0
terminado                0.17.1
terminaltables           3.1.10
threadpoolctl            3.1.0
tifffile                 2023.3.21
tinycss2                 1.2.1
toml                     0.10.2
tomli                    2.0.1
torch                    1.10.1
torchaudio               0.10.1
torchpack                0.3.1
torchvision              0.11.2
tornado                  6.2
tqdm                     4.65.0
traitlets                5.9.0
trimesh                  2.35.39
typing                   3.7.4.3
typing_extensions        4.4.0
tzdata                   2023.3
uri-template             1.2.0
urllib3                  1.26.15
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.5.1
Werkzeug                 2.2.3
wheel                    0.38.4
widgetsnbextension       4.0.7
win32-setctime           1.1.0
wincertstore             0.2
yapf                     0.32.0
zipp                     3.15.0
`

Now the main folder is as follows:

![image](https://user-images.githubusercontent.com/69210109/233829724-a0a48c68-0108-4638-a05c-1355cf7293a8.png)

Data folder:

![image](https://user-images.githubusercontent.com/69210109/233829747-8cf6dbd9-8739-4295-b6fe-aef49b592b5c.png)

Now I run the following code:
Of course, I have to say two things
1- In line 252 of the python creat_data file, I changed the version from `v1.0` to `v1.0-mini`.
2- I pulled out the creat_data file from the tools folder and put it in the mmdetection3d folder, because in the picture below it says that the file should be run in the tools folder, but in the file itself, it says to go to tools folder, which had this problem, in general, it ran fine with this. became.

![image](https://user-images.githubusercontent.com/69210109/233829923-d12ff09b-bfca-4544-b974-9a18200472f7.png)

Now the output is as follows:

`
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.530 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
total scene num: 10
exist scene num: 10
train scene: 8, val scene: 2
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 404/404, 13.3 task/s, elapsed: 30s, ETA:     0s
train sample: 323, val sample: 81
./data/nuscenes\nuscenes_infos_train.pkl will be modified.
Warning, you may overwriting the original data ./data/nuscenes\nuscenes_infos_train.pkl.
Reading from input file: ./data/nuscenes\nuscenes_infos_train.pkl.
C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d
################################################################
 ./data/nuscenes\nuscenes_infos_train.pkl
True
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.494 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
Start updating:
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 323/323, 8.8 task/s, elapsed: 37s, ETA:     0s
Writing to output file: ./data/nuscenes\nuscenes_infos_train.pkl.
ignore classes: set()
./data/nuscenes\nuscenes_infos_val.pkl will be modified.
Warning, you may overwriting the original data ./data/nuscenes\nuscenes_infos_val.pkl.
Reading from input file: ./data/nuscenes\nuscenes_infos_val.pkl.
C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d
################################################################
 ./data/nuscenes\nuscenes_infos_val.pkl
True
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.486 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
Start updating:
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 6.8 task/s, elapsed: 12s, ETA:     0s
Writing to output file: ./data/nuscenes\nuscenes_infos_val.pkl.
ignore classes: set()
Create GT Database of NuScenesDataset
C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d
################################################################
 ./data/nuscenes\nuscenes_infos_train.pkl
True
04/23 13:27:11 - mmengine - INFO - ------------------------------
04/23 13:27:11 - mmengine - INFO - The length of the dataset: 323
04/23 13:27:11 - mmengine - INFO - The number of instances per category in the dataset:
+----------------------+--------+
| category             | number |
+----------------------+--------+
| car                  | 5051   |
| truck                | 525    |
| trailer              | 60     |
| bus                  | 369    |
| construction_vehicle | 196    |
| bicycle              | 191    |
| motorcycle           | 212    |
| pedestrian           | 3657   |
| traffic_cone         | 1339   |
| barrier              | 2323   |
+----------------------+--------+
[                                                  ] 0/323, elapsed: 0s, ETA:C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d
################################################################
 ./data/nuscenes\samples/LIDAR_TOP\n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin
True
[                                                  ] 1/323, 1.5 task/s, elapsed: 1s, ETA:   214sC:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d
################################################################
 ./data/nuscenes\samples/LIDAR_TOP\n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402928147847.pcd.bin
True
C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d
################################################################
 ./data/nuscenes\sweeps/LIDAR_TOP\sweeps/LIDAR_TOP/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402928098063.pcd.bin
False
Traceback (most recent call last):
  File "create_data.py", line 306, in <module>
    nuscenes_data_prep(
  File "create_data.py", line 86, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, info_prefix,
  File "C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d\tools\dataset_converters\create_gt_database.py", line 241, in create_groundtruth_database
    example = dataset.pipeline(data_info)
  File "C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\lib\site-packages\mmengine\dataset\base_dataset.py", line 59, in __call__
    data = t(data)
  File "C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\lib\site-packages\mmcv\transforms\base.py", line 12, in __call__
    return self.transform(results)
  File "C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d\mmdet3d\datasets\transforms\loading.py", line 435, in transform
    points_sweep = self._load_points(
  File "C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\mmdetection3d\mmdet3d\datasets\transforms\loading.py", line 364, in _load_points
    pts_bytes = get(pts_filename, backend_args=self.backend_args)
  File "C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\lib\site-packages\mmengine\fileio\io.py", line 181, in get
    return backend.get(filepath)
  File "C:\Users\smsaj\.conda\envs\sajadi_BEVFusion_env\lib\site-packages\mmengine\fileio\backends\local_backend.py", line 37, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/nuscenes\\sweeps/LIDAR_TOP\\sweeps/LIDAR_TOP/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402928098063.pcd.bin'
`

Now I have to say two things:
1- The newly created files in the data folder are as follows:

![image](https://user-images.githubusercontent.com/69210109/233830115-2c2c120e-c38b-4508-a192-e239c44b0a89.png)


2- If you look carefully, the `path` it is referring to writes the phrase `sweeps/LIDAR_TOP` twice, so it is clear that there is a problem.

Now, if possible, check this case, what should I do?

**Comment by JingweiZhang12** [comment]
Fro the log, you could check the code of create_gt_databse. Maybe the path is repeated somewhere?

**Comment by SMSajadi99** [comment]
Hi @JingweiZhang12 
I typed the following code again with another method, but it didn't work like the files you sent me in the first question.

`python create_data.py nuscenes --root-path ./data/nuscenes --version "v1.0-mini" --out-dir ./data/nuscenes --extra-tag nuscenes`

what should i do

**Comment by SMSajadi99** [comment]
can you help me ?

**Comment by Lcl159** [comment]
Hi, I have the same problem, have you solved it yet?

**Comment by iiiiiAI** [comment]
I also encountered the same problem, which appeared on my windows system, but this error disappeared when I switched to linux system.
