### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by lehnasamia** [open-mmlab/mmdetection3d#2480]
I want to visualize my result from the test of the mvx model (kittiDataset).I am using dev-1.x branch.
I run this command to visualize : 

$ python tools/misc/visualize_results.py configs/mvxnet/mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class.py --result /home/lehna/mmdetection3d/mvx_kitti_results/pred_instances_3d.pkl --show-dir ./works_dirs

I have this error : 

Traceback (most recent call last):
  File "/home/lehna/mmdetection3d/mmengine/config/config.py", line 51, in __getattr__
    value = super().__getattr__(name)
  File "/home/lehna/.local/lib/python3.8/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/lehna/mmdetection3d/mmengine/config/config.py", line 47, in __missing__
    raise KeyError(name)
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/misc/visualize_results.py", line 51, in <module>
    main()
  File "tools/misc/visualize_results.py", line 31, in main
    cfg.data.test.test_mode = True
  File "/home/lehna/mmdetection3d/mmengine/config/config.py", line 894, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/lehna/mmdetection3d/mmengine/config/config.py", line 53, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'data'

I understand that the key is missing in the config file. I don't know what to add after "data = ..."

My environment : 
sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
CUDA_HOME: /usr/local/cuda-11.4
NVCC: Cuda compilation tools, release 11.4, V11.4.152
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.6.0
OpenCV: 4.2.0
MMEngine: 0.7.2
MMDetection: 3.0.0
MMDetection3D: 1.1.0+c0c5007
spconv2.0: True

Thank you

**Comment by JingweiZhang12** [comment]
@lehnasamia Hi, thanks for your feedback. This is caused by that the `visualize_results.py` is not refactored to be compatible with MMEngine. Could you create a PR to fix it?

**Comment by DongmingMMM** [comment]
> Thank you for your response. I created the PR to fix it but I don't know if I have done it correctly (this is the first time). Please don't hesitate to tell me if I have to change something.

Hi! Thank you so much for raising the issue and your PR. Did you fix the problem? I still encounter the same error even though your PR is merged. Thank you for your response!
