### ISSUE TITLE
KeyError: 'CAM_FRONT'

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmdetection3d#2487]
## my envy:
- mmcv                    2.0.0rc4  
- mmdet                   3.0.0
- mmdet3d                 1.1.0     
- mmengine                0.7.2     
- mmeval                  0.2.1
- mmsegmentation          1.0.0

my mmdetection3d code branch is dev-1.x

## my command:
```
python /opt/mmdetection3d/demo/multi_modality_demo.py /opt/mmdetection3d/demo/data/kitti/000008.bin /opt/mmdetection3d/demo/data/kitti/000008.png /opt/mmdetection3d/demo/data/kitti/000008.pkl /opt/mmdetection3d/configs/mvxnet/mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class.py mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class-8963258a.pth --out-dir work-dir/demo_result
```
## Traceback
```
Traceback (most recent call last):
  File "/opt/mmdetection3d/demo/multi_modality_demo.py", line 71, in <module>
    main(args)
  File "/opt/mmdetection3d/demo/multi_modality_demo.py", line 50, in main
    args.ann, args.cam_type)
  File "/opt/mmdetection3d/mmdet3d/apis/inference.py", line 225, in inference_multi_modality_detector
    img_path = data_info['images'][cam_type]['img_path']
KeyError: 'CAM_FRONT'
```

please give me some help to solve the problem, thanks !

**Comment by swaggywilliam** [comment]
> Specify `--cam-type=CAM2` on KITTI dataset.

Why is there only a demo for pcd and not for images?
