### ISSUE TITLE
Update_waymo_infos Crash

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/mmdetection3d#2572]
Preping WOD 1.4.1 with 
`python tools/create_data.py waymo --root-path /mnt/ADASTEC_STORAGE/waymo_root/ --out-dir /mnt/ADASTEC_STORAGE/waymo_root/ --workers 4 --extra-tag waymo` results:
```
...

Finished ...
Generate info. this may take several minutes.
[>>>>>>>>>>>>>>>>>>>>] 158081/158081, 107.4 task/s, elapsed: 1472s, ETA:     0s:
[>>>>>>>>>>>>>>>>>>>>] 158081/158081, 11.9 task/s, elapsed: 13244s, ETA:     0s:
Waymo info train file is saved to /mnt/ADASTEC_STORAGE/waymo_root/kitti_format/waymo_infos_train.pkl
[>>>>>>>>>>>>>>>>>>>>>>>>] 39987/39987, 78.8 task/s, elapsed: 508s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>] 39987/39987, 12.0 task/s, elapsed: 3334s, ETA:     0s
Waymo info val file is saved to /mnt/ADASTEC_STORAGE/waymo_root/kitti_format/waymo_infos_val.pkl
Waymo info trainval file is saved to /mnt/ADASTEC_STORAGE/waymo_root/kitti_format/waymo_infos_trainval.pkl
[>>>>>>>>>>>>>>>>>>>>>>>] 29647/29647, 115.9 task/s, elapsed: 256s, ETA:     0s
Waymo info test file is saved to /mnt/ADASTEC_STORAGE/waymo_root/kitti_format/waymo_infos_test.pkl
/mnt/ADASTEC_STORAGE/waymo_root/kitti_format/waymo_infos_train.pkl will be modified.
Warning, you may overwriting the original data /mnt/ADASTEC_STORAGE/waymo_root/kitti_format/waymo_infos_train.pkl.
Reading from input file: /mnt/ADASTEC_STORAGE/waymo_root/kitti_format/waymo_infos_train.pkl.
Start updating:
[>>>>>>>>>>>>>>>>>>>>>] 158081/158081, 4.1 task/s, elapsed: 38227s, ETA:     0s:
Writing to output file: /mnt/ADASTEC_STORAGE/waymo_root/kitti_format/waymo_infos_train.pkl.
ignore classes: set()
Killed
```

**Comment by JingweiZhang12** [comment]
You could set `--workers=0`

**Comment by adeebislam8** [comment]
I am having the same issue as op. setting --workers=0 leads to the following error. 
"
Traceback (most recent call last):
  File "tools/create_data.py", line 357, in <module>
    max_sweeps=args.max_sweeps)
  File "tools/create_data.py", line 204, in waymo_data_prep
    converter.convert()
  File "/mmdetection3d/tools/dataset_converters/waymo_converter.py", line 113, in convert
    self.workers)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/utils/progressbar.py", line 155, in track_parallel_progress
    pool = init_pool(nproc, initializer, initargs)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/utils/progressbar.py", line 100, in init_pool
    return Pool(process_num)
  File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
"
I have also noticed that my gpu wasn't utilized during the conversion. I checked the log and I continuously get a "cuda_error_not_initialized". I check if tensorflow can access cuda through a simple python script. and it does. SO my assumption is that the multiprocessing causes this issue. Can you please point me to the right direction to fix this issue?
