### ISSUE TITLE
[Bug] TypeError: class `DETR3D` in projects/DETR3D/detr3d/detr3d.py: class `DETR3DHead` in projects/DETR3D/detr3d/detr3d_head.py: __init__() got an unexpected keyword argument 'transformer'

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [open-mmlab/mmdetection3d#2594]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x

### Environment

sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA RTX A6000
CUDA_HOME: /usr/local/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.9.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.1+cu111
OpenCV: 4.7.0
MMEngine: 0.7.3
MMDetection: 3.0.0
MMDetection3D: 1.1.1+e753ecb
spconv2.0: False

### Reproduces the problem - code sample

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 124, in main
    runner = Runner.from_cfg(cfg)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
TypeError: class `DETR3D` in projects/DETR3D/detr3d/detr3d.py: class `DETR3DHead` in projects/DETR3D/detr3d/detr3d_head.py: __init__() got an unexpected keyword argument 'transformer'

### Reproduces the problem - command or script

python tools/train.py /home/estar/Projects/mmdetection3d/projects/DETR3D/configs/detr3d_r101_gridmask_cbgs.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 124, in main
    runner = Runner.from_cfg(cfg)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
TypeError: class `DETR3D` in projects/DETR3D/detr3d/detr3d.py: class `DETR3DHead` in projects/DETR3D/detr3d/detr3d_head.py: __init__() got an unexpected keyword argument 'transformer'

### Additional information

I have tried different versions of mmdetection3d. This problem always arises.
Would please help me , thaks very much!

**Comment by JingweiZhang12** [comment]
![image](https://github.com/open-mmlab/mmdetection3d/assets/34888372/792ffd40-4efe-457a-8c9c-6fc4b04ab1d4)
@RhythmOfTheRain-Byte The transformer head in DETR3D uses the old TransFormer structure in `mmdet`. Please mind your version of mmdet.

**Comment by RhythmOfTheRain-Byte** [comment]
Thank you very much！
I install the MMEngine/MMCV/MMDetection as the Best Practices in the Get Starte.md.
Then i try to execute mim install mmdet<=V3.0.0rc5, it shows "mmdet3d 1.1.0 requires mmdet<3.1.0,>=3.0.0, but you have mmdet 2.24.0 which is incompatible." What should i do?
Thanks!

**Comment by JingweiZhang12** [comment]
modify this line: https://github.com/open-mmlab/mmdetection3d/blob/main/mmdet3d/__init__.py#L17

**Comment by RhythmOfTheRain-Byte** [comment]
Excuse me sir, when i train the DETR3D on nuscenes dataset, another error occurred. I can't find the solution to it.
the command is : python tools/train.py  {configs_path/detr3d_r101_gridmask_cbgs.py --cfg-options load_from={pretrained_path/fcos3d.pth}
The information is as fellows: 
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 10.8 task/s, elapsed: 7s, ETA:     0s
Results writes to /tmp/tmpgcgmdm9f/results/pred_instances_3d/results_nusc.json
Evaluating bboxes of pred_instances_3d
Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner.train()
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/home/estar/Projects/mmdetection3d/mmdet3d/evaluation/metrics/nuscenes_metric.py", line 177, in compute_metrics
    ap_dict = self.nus_evaluate(
  File "/home/estar/Projects/mmdetection3d/mmdet3d/evaluation/metrics/nuscenes_metric.py", line 207, in nus_evaluate
    ret_dict = self._evaluate_single(
  File "/home/estar/Projects/mmdetection3d/mmdet3d/evaluation/metrics/nuscenes_metric.py", line 233, in _evaluate_single
    nusc = NuScenes(
  File "/home/estar/anaconda3/envs/openmmlab/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 63, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: data/nuscenes/v1.0-trainval

**Comment by RhythmOfTheRain-Byte** [comment]
What's more,I use nuscenes-mini dataset. Which contain the fellow folders:
maps  nuscenes_dbinfos_train.pkl  nuscenes_gt_database  nuscenes_infos_train.pkl  nuscenes_infos_val.pkl  samples  sweeps  v1.0-mini

**Comment by RhythmOfTheRain-Byte** [comment]
Hello, how can I deploy the trained model such as pointpillar on the car for real-time 3D target detection?

**Comment by Alicture** [comment]
@RhythmOfTheRain-Byte hi,what's version of mmdet mmcv and mmdet3d you using，i can't found a match version.

**Comment by ywfwyht** [comment]
@Alicture @JingweiZhang12 @RhythmOfTheRain-Byte 
hi, bro. I have the same error, How to solve this error？ (mmcv 2.1.0, mmdet 3.2.0, mmengine 0.10.3, mmdet3d 1.3.0)

**Comment by as754770178** [comment]
I run mmdet3d 1.4.0, what version of mmdet match?

**Comment by as754770178** [comment]
```
mmcv  2.0.1
mmdet 3.2.0
mmdet3d 1.4.0
mmengine 0.10.6
```

report error: 

```
super(DETR3DHEAD, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'transformer'
```

**Comment by BatyrbekSM** [comment]
If you want to use direct installation of mmdet from cloning its repo, do this

git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
git checkout v3.0.0rc5
pip install -v -e .

And then the right version of mmdet will be installed.

**Comment by Sstrap** [comment]
Any update on this ? 
The solution proposed by @JingweiZhang12 works but it's a bit hacky. It seems that there is no proper environement to make the detr3d project work. Or is there ? 
On my side I have 
```
  "mmdet==3.0.0.rc5",
  "mmdet3d==1.1.0",  required for Det3DDataPreprocessor signature
  "mmcv==2.0.1",
  "mmengine"==0.9.0
]
```
But with this env I have the issue `mmdet3d 1.1.0 requires mmdet<3.1.0,>=3.0.0, but you have mmdet 2.24.0 which is incompatible.`
