### ISSUE TITLE
Error while using custom Neck module,

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection3d#2639]
### What is the feature?

I have implemented a new **custom Neck module** using the votenet as a dectector, but while trainining the pipeline i am getting the below error which i can't understand where to troubleshoot the problem 
```
Traceback (most recent call last):
  File "/workspace/mmdetection3d/tools/train.py", line 136, in <module>
    main()
  File "/workspace/mmdetection3d/tools/train.py", line 132, in main
    runner.train()
  File "/workspace/mmengine/mmengine/runner/runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "/workspace/mmengine/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/workspace/mmengine/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/workspace/mmengine/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/workspace/mmengine/mmengine/model/base_model/base_model.py", line 116, in train_step
    optim_wrapper.update_params(parsed_losses)
  File "/workspace/mmengine/mmengine/optim/optimizer/optimizer_wrapper.py", line 184, in update_params
    self.backward(loss)
  File "/workspace/mmengine/mmengine/optim/optimizer/optimizer_wrapper.py", line 208, in backward
    loss.backward(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
**RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved 
tensors after calling backward.**
```

Would really appreciate if i can get help on it.

**Comment by sunjiahao1999** [comment]
This is caused by incorrect implementation of your module. Please check if the computational graph of your module is correct.

**Comment by ammaryasirnaich** [comment]
> This is caused by incorrect implementation of your module. Please check if the computational graph of your module is correct.

@sunjiahao1999 thanks for the response. I am not quite sure how to check the computational graph of my module. Is there any way to troubleshoot it ?

**Comment by ammaryasirnaich** [comment]
Issue has been solved
