### ISSUE TITLE
[Bug] ext_module.box_iou_rotated( RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by narimanmadani** [open-mmlab/mmdetection3d#2694]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.1+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.3
    - Built with CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2+cu118
OpenCV: 4.8.0
MMEngine: 0.8.4
MMDetection: 3.1.0
MMDetection3D: 1.2.0+0f9dfa9
spconv2.0: True

### Reproduces the problem - code sample

```
bash   tools/dist_train.sh   projects/BEVFusion/configs/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py   1
```

### Reproduces the problem - command or script

```
bash   tools/dist_train.sh   projects/BEVFusion/configs/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py   1
```

### Reproduces the problem - error message

```
08/17 23:28:44 - mmengine - INFO - Checkpoints will be saved to /home/ubuntu/mmdetection3d/work_dirs/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.
Traceback (most recent call last):
  File "/home/ubuntu/mmdetection3d/tools/train.py", line 135, in <module>
    main()
  File "/home/ubuntu/mmdetection3d/tools/train.py", line 131, in main
    runner.train()
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    results = self(**data, mode=mode)
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/mmdetection3d/mmdet3d/models/detectors/base.py", line 75, in forward
    return self.loss(inputs, data_samples, **kwargs)
  File "/home/ubuntu/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 294, in loss
    bbox_loss = self.bbox_head.loss(feats, batch_data_samples)
  File "/home/ubuntu/mmdetection3d/projects/BEVFusion/bevfusion/transfusion_head.py", line 761, in loss
    loss = self.loss_by_feat(preds_dicts, batch_gt_instances_3d)
  File "/home/ubuntu/mmdetection3d/projects/BEVFusion/bevfusion/transfusion_head.py", line 777, in loss_by_feat
    ) = self.get_targets(batch_gt_instances_3d, preds_dicts[0])
  File "/home/ubuntu/mmdetection3d/projects/BEVFusion/bevfusion/transfusion_head.py", line 539, in get_targets
    res_tuple = multi_apply(
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmdet/models/utils/misc.py", line 219, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/ubuntu/mmdetection3d/projects/BEVFusion/bevfusion/transfusion_head.py", line 618, in get_targets_single
    assign_result = self.bbox_assigner.assign(
  File "/home/ubuntu/mmdetection3d/projects/BEVFusion/bevfusion/utils.py", line 284, in assign
    iou = self.iou_calculator(bboxes, gt_bboxes)
  File "/home/ubuntu/mmdetection3d/mmdet3d/structures/ops/iou3d_calculator.py", line 90, in __call__
    return bbox_overlaps_3d(bboxes1, bboxes2, mode, self.coordinate)
  File "/home/ubuntu/mmdetection3d/mmdet3d/structures/ops/iou3d_calculator.py", line 176, in bbox_overlaps_3d
    return bboxes1.overlaps(bboxes1, bboxes2, mode=mode)
  File "/home/ubuntu/mmdetection3d/mmdet3d/structures/bbox_3d/base_box3d.py", line 569, in overlaps
    iou2d = box_iou_rotated(boxes1_bev, boxes2_bev)
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmcv/ops/box_iou_rotated.py", line 147, in box_iou_rotated
    ext_module.box_iou_rotated(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

### Additional information

1- When I use cuda11.8 on Nvidia H100 GPU I see the below error (it works fine with cuda11.7 on A100)
2- I have compiled Bevfusion using `python projects/BEVFusion/setup.py develop`
3- The issue seems to be related to a CUDA op **box_iou_rotated**:
`  File "/home/ubuntu/mmdetection3d/mmdet3d/structures/bbox_3d/base_box3d.py", line 569, in overlaps
    iou2d = box_iou_rotated(boxes1_bev, boxes2_bev)
  File "/home/ubuntu/.conda/envs/openmmlab/lib/python3.10/site-packages/mmcv/ops/box_iou_rotated.py", line 147, in box_iou_rotated
    ext_module.box_iou_rotated(
RuntimeError: CUDA error: no kernel image is available for execution on the device
`

**Comment by liyih** [comment]
It is because the compute capability of your GPU is not match with the projects/BEVFusion/setup.py file. In this file, it only mention:
'-gencode=arch=compute_70,code=sm_70',
'-gencode=arch=compute_75,code=sm_75',
'-gencode=arch=compute_80,code=sm_80',
'-gencode=arch=compute_86,code=sm_86',
this only match some GPUs, whose compute capability is 7.0, 7.5, 8.0, 8.6. For me, I use GTX 1080 Ti, whose compute capability is 6.1. So, I should add '-gencode=arch=compute_61,code=sm_61' in the setup.py file.

**Comment by narimanmadani** [comment]
I could resolve this issue by using CUDA 12.1

**Comment by barrydoooit** [comment]
> I could resolve this issue by using CUDA 12.1

@narimanmadani Hi there! I'm encountering the same error on H100 with CUDA/12.1.1 loaded on a slurm node. I'd like to know which version of mmcv are you using and how it is installed. I installed v2.2.0 with mim.

**Comment by barrydoooit** [comment]
> > I could resolve this issue by using CUDA 12.1
Update: I built mmcv from source and things went on smoothly :)
