### ISSUE TITLE
[Bug] Pointpillars training fails on Kitti after 2 epoch (ERROR: numba.cuda.cudadrv.driver.LinkerError and ptxas application ptx input, line 9; fatal   : Unsupported .version 7.6; current version is '7.4')

### ISSUE THREAD

**Issue by Mufan187569** [open-mmlab/mmdetection3d#2720]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1070 Ti
CUDA_HOME: /home/lw/miniconda3/envs/openmmlab
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1
OpenCV: 4.8.0
MMEngine: 0.8.4
MMDetection: 3.1.0
MMDetection3D: 1.2.0+c04831c
spconv2.0: False
Numba: 0.56.4
Numpy: 1.19.5

### Reproduces the problem - code sample

none

### Reproduces the problem - command or script

python python tools/train.py configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py

### Reproduces the problem - error message

running
python python tools/train.py configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py
on KITTI dataset
after the first epoch ends I get:

Converting 3D prediction to KITTI format
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 50/50, 895.5 task/s, elapsed: 0s, ETA:     0s
Result is saved to /tmp/tmpqdiad9q5/results/pred_instances_3d.pkl.
Traceback (most recent call last):
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 2705, in add_ptx
    driver.cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 320, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 388, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tool/train.py", line 135, in <module>
    main()
  File "tool/train.py", line 131, in main
    runner.train()
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/home/lw/LW/mmdetection3d/mmdet3d/evaluation/metrics/kitti_metric.py", line 205, in compute_metrics
    ap_dict = self.kitti_evaluate(
  File "/home/lw/LW/mmdetection3d/mmdet3d/evaluation/metrics/kitti_metric.py", line 244, in kitti_evaluate
    ap_result_str, ap_dict_ = kitti_eval(
  File "/home/lw/LW/mmdetection3d/mmdet3d/evaluation/functional/kitti_utils/eval.py", line 725, in kitti_eval
    mAP40_3d, mAP40_aos = do_eval(gt_annos, dt_annos,
  File "/home/lw/LW/mmdetection3d/mmdet3d/evaluation/functional/kitti_utils/eval.py", line 626, in do_eval
    ret = eval_class(gt_annos, dt_annos, current_classes, difficultys, 1,
  File "/home/lw/LW/mmdetection3d/mmdet3d/evaluation/functional/kitti_utils/eval.py", line 480, in eval_class
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
  File "/home/lw/LW/mmdetection3d/mmdet3d/evaluation/functional/kitti_utils/eval.py", line 384, in calculate_iou_partly
    overlap_part = bev_box_overlap(dt_boxes,
  File "/home/lw/LW/mmdetection3d/mmdet3d/evaluation/functional/kitti_utils/eval.py", line 118, in bev_box_overlap
    from .rotate_iou import rotate_iou_gpu_eval
  File "/home/lw/LW/mmdetection3d/mmdet3d/evaluation/functional/kitti_utils/rotate_iou.py", line 283, in <module>
    def rotate_iou_kernel_eval(N,
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/decorators.py", line 115, in _jit
    disp.compile(argtypes)
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/dispatcher.py", line 796, in compile
    kernel.bind()
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/dispatcher.py", line 178, in bind
    self._codelibrary.get_cufunc()
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/codegen.py", line 208, in get_cufunc
    cubin = self.get_cubin(cc=device.compute_capability)
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/codegen.py", line 181, in get_cubin
    linker.add_ptx(ptx.encode())
  File "/home/lw/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 2708, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.6; current version is '7.4'

**Comment by sunjiahao1999** [comment]
Because your version of numba doesn't work. Reinstall the appropriate version of numba

**Comment by 2001Iam** [comment]
I have a similar problem with you. Have you solved it? What version of Numba should I download？

Here are the errors I encountered：
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in CUDA_ERROR_UNSUPPORTED_PTX_VERSION
ptxas application ptx input, line 9; fatal   : Unsupported .version 8.4; current version is '8.2'
