### ISSUE TITLE
[Bug]  运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters'

### ISSUE THREAD

**Issue by yuzhenboo** [open-mmlab/mmdetection3d#2737]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

TorchVision: 0.15.1+cu117
OpenCV: 4.8.0
MMEngine: 0.8.4
MMDetection: 3.0.0
MMDetection3D: 1.2.0+0f9dfa9
spconv2.0: False

### Reproduces the problem - code sample

(pt20gpu) ljLi@sstd:~/mmdetection3d$ python demo/pcd_demo.py demo/data/kitti/000008.bin configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show
/home/ljLi/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:94: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
Loads checkpoint by local backend from path: hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth
/home/ljLi/anaconda3/envs/pt20gpu/lib/python3.9/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
/home/ljLi/anaconda3/envs/pt20gpu/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[Open3D WARNING] GLFW Error: X11: Failed to open display :0.0
[Open3D WARNING] Failed to initialize GLFW
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
Traceback (most recent call last):
  File "/home/ljLi/mmdetection3d/demo/pcd_demo.py", line 60, in <module>
    main(args)
  File "/home/ljLi/mmdetection3d/demo/pcd_demo.py", line 46, in main
    visualizer.add_datasample(
  File "/home/ljLi/anaconda3/envs/pt20gpu/lib/python3.9/site-packages/mmengine/dist/utils.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "/home/ljLi/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 1071, in add_datasample
    self.show(
  File "/home/ljLi/anaconda3/envs/pt20gpu/lib/python3.9/site-packages/mmengine/dist/utils.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "/home/ljLi/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 863, in show
    self.view_control.convert_to_pinhole_camera_parameters()  # noqa: E501
AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters'

### Reproduces the problem - command or script

python demo/pcd_demo.py demo/data/kitti/000008.bin configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show

### Reproduces the problem - error message

AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters'

**Comment by ioeddk** [comment]
Any updates? I have the same problem.

**Comment by Chuanheliu1** [comment]
yeah, encounter the same problem

**Comment by yuzhenboo** [comment]
问题还是没有解决

**Comment by sunjiahao1999** [comment]
It seems to you run this demo on remote server. You should not use "--show" when $DISPLAY is None.

**Comment by sunjiahao1999** [comment]
We will add a warning in this case.

**Comment by yuzhenboo** [comment]
就是当我没有输入--show的时候，依然没办法成功将结果输出到output中

**Comment by yuzhenboo** [comment]
> 就是当我没有输入--show的时候，依然没办法成功将结果输出到output中

**Comment by thiesymon** [comment]
some question！！！！

**Comment by yuzhenboo** [comment]
> some question！！！！

what?

**Comment by ppsychoo** [comment]
Have you solve it? I have the same question!!!

**Comment by Tzu-Hsiang-Lin** [comment]
I solved the problem by setting conda-forge as my priority installation channel before installing PyTorch. Here is the link that shows you how to set the channel: https://ostechnix.com/enable-conda-forge-channel-for-conda-package-manager/
Some of the package bugs have been fixed in the conda-forge channel but not in the default channel.

**Comment by Tzu-Hsiang-Lin** [comment]
I solved the problem by setting conda-forge as my priority installation channel before installing PyTorch. Here is the link that shows you how to do it:[ https://ostechnix.com/enable-conda-forge-channel-for-conda-package-manager/](https://ostechnix.com/enable-conda-forge-channel-for-conda-package-manager/)
Some of the package bugs have been fixed in the conda-forge channel but not in the default channel.

**Comment by Tzu-Hsiang-Lin** [comment]
I solved the problem by setting conda-forge as my priority installation channel before installing PyTorch. Here is the link that shows you how to set the channel:[ https://ostechnix.com/enable-conda-forge-channel-for-conda-package-manager/](https://ostechnix.com/enable-conda-forge-channel-for-conda-package-manager/)
Some of the package bugs have been fixed in the conda-forge channel but not in the default channel.

**Comment by caiyi4gis** [comment]
I met and fixed the same problem when Open3D calls OpenGL, possibly due to dual graphics on the laptop.
Follow these steps: 

1. Check 'nvidia-settings' for only the item < GPU 0 - Nvidia GeForce ...> . 
2.  If yes, try 'sudo prime-select nvidia'.

**Comment by samuruph** [comment]
Is it possible to run this command on WSL2?

**Comment by lin0711** [comment]
> I met and fixed the same problem when Open3D calls OpenGL, possibly due to dual graphics on the laptop. Follow these steps:
> 
> 1. Check 'nvidia-settings' for only the item < GPU 0 - Nvidia GeForce ...> .
> 2. If yes, try 'sudo prime-select nvidia'.

please speak it in detail, thanks

**Comment by hyf493** [comment]
hello，Has this problem been resolved? I encountered this issue while running tools/misc/browse_dataset.py

**Comment by AndrewSkywalker6666** [comment]
I encountered the same issue.

**Comment by yuzhenboo** [comment]
> hello，Has this problem been resolved? I encountered this issue while running tools/misc/browse_dataset.py


Sorry,I still have not resolved this question

**Comment by mhmdrz-mirdamadi** [comment]
Same problem

**Comment by YJJ1125** [comment]
请问是用的纯点云数据进行训练的吗？

**Comment by yuzhenboo** [comment]
不是，这个问题已经是差不多一年前的问题了，后来我就没有用这个算法进行检测 了




Onlyher
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月11日(星期六) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection3d] [Bug]  运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737)





 
请问是用的纯点云数据进行训练的吗？

**Comment by hyf493** [comment]
我是使用的kitti多模态数据，我当时是想进行测试可视化




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月11日(星期六) 中午12:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmdetection3d] [Bug]  运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: &#39;NoneType&#39; object has no attribute &#39;convert_to_pinhole_camera_parameters&#39; (Issue #2737)














 不是，这个问题已经是差不多一年前的问题了，后来我就没有用这个算法进行检测 了 
 
 
 
 
 Onlyher 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "open-mmlab/mmdetection3d"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年5月11日(星期六) 上午10:24 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [open-mmlab/mmdetection3d] [Bug]  运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737) 
 
 
 
 
 
   
 请问是用的纯点云数据进行训练的吗？

**Comment by hyf493** [comment]
sorry，I don't have a solution either.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月20日(星期六) 上午9:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmdetection3d] [Bug]  运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: &#39;NoneType&#39; object has no attribute &#39;convert_to_pinhole_camera_parameters&#39; (Issue #2737)














  
hello，Has this problem been resolved? I encountered this issue while running tools/misc/browse_dataset.py
  
Sorry,I still have not resolved this question

**Comment by hyf493** [comment]
抱歉，我好像是运行tools/misc/browse_dataset.py，出现的这个问题，具体是点云数据还是多模态数据，记不太清了




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月11日(星期六) 中午12:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmdetection3d] [Bug]  运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737)














 不是，这个问题已经是差不多一年前的问题了，后来我就没有用这个算法进行检测 了 
 
 
 
 
 Onlyher 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "open-mmlab/mmdetection3d"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年5月11日(星期六) 上午10:24 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [open-mmlab/mmdetection3d] [Bug]  运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737) 
 
 
 
 
 
   
 请问是用的纯点云数据进行训练的吗？

**Comment by YJJ1125** [comment]
好的 谢谢你。在排查过程种我发现 使用服务器进行点云数据读取可视化出现问题，主要是open3d无法创建窗口的问题，我还在持续跟进这个问题，再次感谢，


| |
尹嘉洁
|
|
Tel：18732049152
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年5月13日 08:49 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [open-mmlab/mmdetection3d] [Bug] 运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737) |

抱歉，我好像是运行tools/misc/browse_dataset.py，出现的这个问题，具体是点云数据还是多模态数据，记不太清了




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;;
发送时间: 2024年5月11日(星期六) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [open-mmlab/mmdetection3d] [Bug] 运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737)














不是，这个问题已经是差不多一年前的问题了，后来我就没有用这个算法进行检测 了




Onlyher
***@***.***



&amp;nbsp;




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人: "open-mmlab/mmdetection3d" ***@***.***&amp;gt;;
发送时间:&amp;nbsp;2024年5月11日(星期六) 上午10:24
***@***.***&amp;gt;;
***@***.******@***.***&amp;gt;;
主题:&amp;nbsp;Re: [open-mmlab/mmdetection3d] [Bug] 运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737)






请问是用的纯点云数据进行训练的吗？

**Comment by hyf493** [comment]
感谢，希望您尽快解决问题，有什么需要我帮助的，尽管说




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection3d] [Bug]  运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737)





 好的 谢谢你。在排查过程种我发现 使用服务器进行点云数据读取可视化出现问题，主要是open3d无法创建窗口的问题，我还在持续跟进这个问题，再次感谢，
 
 
 | |
 尹嘉洁
 |
 |
 Tel：18732049152
 ***@***.***
 |
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2024年5月13日 08:49 |
 | 收件人 | ***@***.***&gt; |
 | 抄送人 | ***@***.***&gt; ,
 ***@***.***&gt; |
 | 主题 | Re: [open-mmlab/mmdetection3d] [Bug] 运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737) |
 
 抱歉，我好像是运行tools/misc/browse_dataset.py，出现的这个问题，具体是点云数据还是多模态数据，记不太清了
 
 
 
 
 ------------------ 原始邮件 ------------------
 发件人: ***@***.***&amp;gt;;
 发送时间: 2024年5月11日(星期六) 中午12:00
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;
 主题: Re: [open-mmlab/mmdetection3d] [Bug] 运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737)
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 不是，这个问题已经是差不多一年前的问题了，后来我就没有用这个算法进行检测 了
 
 
 
 
 Onlyher
 ***@***.***
 
 
 
 &amp;amp;nbsp;
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
 发件人: "open-mmlab/mmdetection3d" ***@***.***&amp;amp;gt;;
 发送时间:&amp;amp;nbsp;2024年5月11日(星期六) 上午10:24
 ***@***.***&amp;amp;gt;;
 ***@***.******@***.***&amp;amp;gt;;
 主题:&amp;amp;nbsp;Re: [open-mmlab/mmdetection3d] [Bug] 运行mmdetection3d里面的pcd_demo.py的时候出现这个问题AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters' (Issue #2737)
 
 
 
 
 
 
 请问是用的纯点云数据进行训练的吗？

**Comment by woreom** [comment]
> Is it possible to run this command on WSL2?

I used to do it, but for some reason now I'm getting this error

**Comment by CaptainTrojan** [comment]
Same issue here.

**Comment by again-a** [comment]
pip install open3d=0.16.0

**Comment by leecyang** [comment]
> 当 Open3D 调用 OpenGL 时，我遇到并修复了同样的问题，这可能是由于笔记本电脑上的双显卡。 请执行以下步骤：
> 
>     1. 检查“nvidia-settings”，仅查看 GPU 0 - Nvidia GeForce <项 ...> .
> 
>     2. 如果是，请尝试 'sudo prime-select nvidia'。

非常感谢！您的回答解决了我的问题。我将我的处理办法附在下面：
1. 将缺失的依赖包全部通过pip安装而不止运行pip install -v -e .
2. 删去--show之后我的代码正确输出了结果，验证了我的猜想可能是ubuntu双显卡的问题。
3. 按照您的回答进行操作。
4. 重启电脑。

**Comment by 572468483** [comment]
same problem.
Have you solve it?

**Comment by DongYingwei** [comment]
不添加 --show 能在output/preds下生成一个json文件，但是vis_lidar下是空。

**Comment by hackerliang** [comment]
```bash
sudo apt-get install --reinstall libgl1-mesa-glx libgl1-mesa-dri

cd /usr/lib
sudo mkdir dri
sudo ln -s /lib/x86_64-linux-gnu/dri/swrast_dri.so swrast_dri.so

conda install -c conda-forge gcc=12.1.0
```

**Comment by anc95** [comment]
I am using WSL2, in my case, added below env helped

```
export XDG_SESSION_TYPE=x11
```

https://github.com/isl-org/Open3D/issues/6872#issuecomment-2615797521

**Comment by zhiyanxin** [comment]
> 不添加 --show 能在output/preds下生成一个json文件，但是vis_lidar下是空。

一樣的情況
