### ISSUE TITLE
[Docs] Traceback (most recent call last):   File "tools/train.py", line 135, in <module>     main()   File "tools/train.py", line 124, in main     runner = Runner.from_cfg(cfg)   File "/home/qwe/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 445, in from_cfg     runner = cls(   File "/home/qwe/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 292, in __init__     raise ValueError( ValueError: train_dataloader, train_cfg, and optim_wrapper should be either all None or not None, but got train_dataloader=None, train_cfg={'type': 'EpochBasedTrainLoop', 'max_epochs': 12, 'val_interval': 1}, optim_wrapper={'type': 'OptimWrapper', 'optimizer': {'type': 'SGD', 'lr': 0.02, 'momentum': 0.9, 'weight_decay': 0.0001}}.

### ISSUE THREAD

**Issue by duanmushuangquan** [open-mmlab/mmdetection3d#2744]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

I am in the `mmdetection3d` directory and haven't made any modifications; I directly executed the command: 

```sh
CUDA_VISIBLE_DEVICES=1 python tools/train.py mmdetection3d/configs/nuimages/cascade-mask-rcnn_r50_fpn_1x_nuim.py --work-dir res_train_1_cascade_mask_rcnn
```

But I received an error.

```sh
Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 124, in main
    runner = Runner.from_cfg(cfg)
  File "/home/qwe/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/home/qwe/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 292, in __init__
    raise ValueError(
ValueError: train_dataloader, train_cfg, and optim_wrapper should be either all None or not None, but got train_dataloader=None, train_cfg={'type': 'EpochBasedTrainLoop', 'max_epochs': 12, 'val_interval': 1}, optim_wrapper={'type': 'OptimWrapper', 'optimizer': {'type': 'SGD', 'lr': 0.02, 'momentum': 0.9, 'weight_decay': 0.0001}}.
```

**Comment by mondalanindya** [comment]
Did anyone find any fix?

**Comment by chcchc97** [comment]
@mondalanindya @duanmushuangquan Hi! Did anyone find any fix?

**Comment by chcchc97** [comment]
I have fixed it. I set train_cfg, and optim_wrapper to none and it works. @mondalanindya @duanmushuangquan

**Comment by kwonseungchan** [comment]
I have fixed this problem. I have a problem in _base_/datasets/??? because of old mmdetection code. 
`data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/aitodv2_trainval.json',
        img_prefix=data_root + 'images/trainval/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/aitodv2_test.json',
        img_prefix=data_root + 'images/test/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/aitodv2_test.json',
        img_prefix=data_root + 'images/test/',
        pipeline=test_pipeline))`
     
  ==> 

`train_dataloader = dict(
    batch_size=4,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/aitodv2_trainval.json',
        data_prefix=dict(img='images/trainval/'),
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        pipeline=train_pipeline,
        backend_args=backend_args))
val_dataloader = dict(
    batch_size=4,
    num_workers=4,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/aitodv2_test.json',
        data_prefix=dict(img='images/test/'),
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args))
test_dataloader = val_dataloader
val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/aitodv2_test.json',
    metric='bbox',
    format_only=False,
    backend_args=backend_args)
test_evaluator = val_evaluator`
