### ISSUE TITLE
No such file or directory: '/content/mmdetection3d/../_base_/datasets/kitti-3d-3class.py'

### ISSUE THREAD

**Issue by farhad-dalirani** [open-mmlab/mmdetection3d#2748]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

Google Colab, T4 GPU Runtime

### Reproduces the problem - code sample

According to [https://mmdetection3d.readthedocs.io/en/latest/get_started.html], I installed open-mmdetection3d on colab.

However, when I use 

```
from mmdet3d.apis import init_model, inference_detector

config_file = 'pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py'
checkpoint_file = 'hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth'
model = init_model(config_file, checkpoint_file)
inference_detector(model, 'demo/data/kitti/000008.bin')
```
or 
```
python demo/pcd_demo.py demo/data/kitti/000008.bin pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show
```
It gives the following error:

```
Traceback (most recent call last):
  File "/content/mmdetection3d/demo/pcd_demo.py", line 60, in <module>
    main(args)
  File "/content/mmdetection3d/demo/pcd_demo.py", line 34, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/content/mmdetection3d/mmdet3d/apis/inference.py", line 59, in init_model
    config = Config.fromfile(config)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 456, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 940, in _file2dict
    raise e
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 882, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 838, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 1651, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/mmdetection3d/../_base_/datasets/kitti-3d-3class.py'
```

I can not find ` ../_base_/datasets/kitti-3d-3class.py` in the MMdetection3D repository. What do you suggest?  

### Reproduces the problem - command or script

python demo/pcd_demo.py demo/data/kitti/000008.bin pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/content/mmdetection3d/demo/pcd_demo.py", line 60, in <module>
    main(args)
  File "/content/mmdetection3d/demo/pcd_demo.py", line 34, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/content/mmdetection3d/mmdet3d/apis/inference.py", line 59, in init_model
    config = Config.fromfile(config)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 456, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 940, in _file2dict
    raise e
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 882, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 838, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 1651, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/mmdetection3d/../_base_/datasets/kitti-3d-3class.py

**Comment by JohnFuguiWang** [comment]
Hi, I also met the same issue. Have you solved it?
