### ISSUE TITLE
[Bug] Installation errors: setuptools and torch

### ISSUE THREAD

**Issue by erivera1802** [open-mmlab/mmdetection3d#2776]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x

### Environment

Hi,
Im trying to install mmdetection3d with the default tutorial, and the following environment:
Torch 2.1
Cuda 12.1

And when I try to install the develop repository, I get an error involving setuptools, which at the end does not recognize torch (See log)

### Reproduces the problem - code sample

```
pip install -v -e .
```

### Reproduces the problem - command or script

```
pip install -v -e .
```

### Reproduces the problem - error message

Using pip 23.3 from /home/rives/environments/openmm3d/lib/python3.9/site-packages/pip (python 3.9)
Obtaining file:///home/rives/esteban/mmdetection3d
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
  Collecting wheel
    Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
  Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
  Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
  Installing collected packages: wheel, setuptools
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  openxlab 0.0.27 requires setuptools~=60.2.0, but you have setuptools 68.2.2 which is incompatible.
  Successfully installed setuptools-68.2.2 wheel-0.41.2
  WARNING: There was an error checking the latest version of pip.
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  Traceback (most recent call last):
    File "/home/rives/environments/openmm3d/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/rives/environments/openmm3d/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/rives/environments/openmm3d/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
      return hook(config_settings)
    File "/tmp/pip-build-env-3w63b2cu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 468, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
    File "/tmp/pip-build-env-3w63b2cu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-3w63b2cu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-3w63b2cu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-3w63b2cu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 9, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/rives/environments/openmm3d/bin/python3.9 /home/rives/environments/openmm3d/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_editable /tmp/tmpcuwa92f8
  cwd: /home/rives/esteban/mmdetection3d
  Getting requirements to build editable ... error
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Additional information

1. Desired result: Installed mmdetection3d
2. Doesnt apply
3. Suspected cause: setuptools is automatically upgraded to 68 by pip install

**Comment by Tombo551** [comment]
@erivera1802  Did you manage to resolve this issue?

**Comment by jacobnzw** [comment]
I'm having the same problem. Cloning the repo, creating a new python venv,  and doing `pip install -v -e .` is an endless rabbit hole of mismatched versions, missing dependencies etc. 

Unfortunately, all of this makes it virtually impossible to test and play with the model.

**Comment by lyd00116** [comment]
I encountered the same problem: No module named 'torch'
The following cmd works for me, and I successfully solved it:
python -m pip install -U pip setuptools wheel
export SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
python -m pip install -e . --no-build-isolation --config-settings editable_mode=compat

Maybe it can work for you.
