### ISSUE TITLE
[Bug] f'input should be in float32 type, got {input.dtype}' AssertionError: input should be in float32 type, got torch.float16

### ISSUE THREAD

**Issue by 1-etudiant** [open-mmlab/mmdetection3d#2777]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 1.8.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.2
OpenCV: 4.8.1
MMEngine: 0.9.0
MMDetection: 3.1.0
MMDetection3D: 1.2.0+0f9dfa9
spconv2.0: False

### Reproduces the problem - code sample

assert input.dtype == torch.float32, \
            f'input should be in float32 type, got {input.dtype}'

### Reproduces the problem - command or script

python tools/train.py configs/pointpillars/pointpillars_hv_fpn_sbn-all_8xb2-amp-2x_nus-3d.py 

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner.train()
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/runner/loops.py", line 129, in run_iter
    data_batch, optim_wrapper=self.runner.optim_wrapper)
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/model/base_model/base_model.py", line 346, in _run_forward
    results = self(**data, mode=mode)
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sh/mmdetection3d/mmdet3d/models/detectors/base.py", line 75, in forward
    return self.loss(inputs, data_samples, **kwargs)
  File "/home/sh/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 271, in loss
    batch_input_metas)
  File "/home/sh/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 246, in extract_feat
    batch_input_metas=batch_input_metas)
  File "/home/sh/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 216, in extract_pts_feat
    x = self.pts_backbone(x)
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sh/mmdetection3d/mmdet3d/models/backbones/second.py", line 93, in forward
    x = self.blocks[i](x)
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/sh/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sh/mmdetection3d/mmdet3d/models/layers/norm.py", line 124, in forward
    f'input should be in float32 type, got {input.dtype}'
AssertionError: input should be in float32 type, got torch.float16

**Comment by OttaviaBelotti** [comment]
Not a  dev here, but I had the same issue so I temporarely fixed it by adding  the following cast before the assertion line giving the error (line 124 in mmdetection3d/mmdet3d/models/layers/norm.py):
```
if input.dtype == torch.float16:
      input = input.to(torch.float32)  # casting to torch.float32
```
It seems to have fixed the problem for me since, as far as I know, the tensor's dtype can not be set in the configs, but maybe I haven't looked for it enough.

Anyway, it's still a bug that should be brought to the dev's attention.

**Comment by 1-etudiant** [comment]
> Not a dev here, but I had the same issue so I temporarely fixed it by adding the following cast before the assertion line giving the error (line 124 in mmdetection3d/mmdet3d/models/layers/norm.py):
> 
> ```
> if input.dtype == torch.float16:
>       input = input.to(torch.float32)  # casting to torch.float32
> ```
> 
> It seems to have fixed the problem for me since, as far as I know, the tensor's dtype can not be set in the configs, but maybe I haven't looked for it enough. And the cast should be pretty innocent as well in terms of data precision.
> 
> Anyway, it's still a bug that should be brought to the dev's attention.

thanks, have a nice day
