### ISSUE TITLE
Unable to run the multi modal demo for BEVFusion with only single image

### ISSUE THREAD

**Issue by zhangtingyu11** [open-mmlab/mmdetection3d#2780]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 2.0.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1+cu118
OpenCV: 4.8.1
MMEngine: 0.9.0
MMDetection: 3.1.0
MMDetection3D: 1.2.0+b0e8ece
spconv2.0: False

### Reproduces the problem - code sample

No sample.

### Reproduces the problem - command or script

```shell
python demo/multi_modality_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_FRONT__1532402927612460.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800.pkl projects/BEVFusion/configs/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py bevfusion_converted.pth --cam-type CAM_FRONT --score-thr 0.2 --show
```

### Reproduces the problem - error message

```
/home/public/zty/.conda/envs/mmdet3d_cuda11.8/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
Traceback (most recent call last):
  File "demo/multi_modality_demo.py", line 78, in <module>
    main(args)
  File "demo/multi_modality_demo.py", line 49, in main
    result, data = inference_multi_modality_detector(model, args.pcd, args.img,
  File "/home/public/zty/Project/CICV/mmdetection3d/mmdet3d/apis/inference.py", line 284, in inference_multi_modality_detector
    data_ = test_pipeline(data_)
  File "/home/public/zty/.conda/envs/mmdet3d_cuda11.8/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 60, in __call__
    data = t(data)
  File "/home/public/zty/.conda/envs/mmdet3d_cuda11.8/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/public/zty/Project/CICV/mmdetection3d/projects/BEVFusion/bevfusion/loading.py", line 134, in transform
    for _, cam_item in results['images'].items():
KeyError: 'images'
```

### Additional information

The demo run successfully with all images.

**Comment by FrozVolca** [comment]
the class `BEVLoadMultiViewImageFromFiles` needs to be rewrite to run a single cam-type prediction.
Or just for running once, we could modify the pkl file by removing other camera info and set the cam-type to --all:
`        
dict_info_images = {}
        dict_info_images["CAM_FRONT"] = {
            "img_path": cam_path,
            "cam2img": cam2img,
            "cam2ego": cam2ego,
            "timestamp": timestamp,
            "lidar2cam": lidar2cam,
        }
        data["data_list"][0]["images"] = dict_info_images`

**Comment by adduu345** [comment]
> the class `BEVLoadMultiViewImageFromFiles` needs to be rewrite to run a single cam-type prediction. Or just for running once, we could modify the pkl file by removing other camera info
> 
> ```
> dict_info_images = {}
> # Rewrite info or just remove others 
> dict_info_images["CAM_FRONT"] = {
>     "img_path": cam_path,
>     "cam2img": cam2img,
>     "cam2ego": cam2ego,
>     "timestamp": timestamp,
>     "lidar2cam": lidar2cam,
> }
> data["data_list"][0]["images"] = dict_info_images
> ```
> 
> and set `--cam-type CAM_FRONT` to `--cam-type all`

kpl文件如何生成？？
