### ISSUE TITLE
[Bug]  LoadAnnotations3D( with_bbox=True) will cause bugs results['gt_bboxes'] = results['ann_info']['gt_bboxes'] KeyError: 'gt_bboxes'

### ISSUE THREAD

**Issue by WinterCodeForEverything** [open-mmlab/mmdetection3d#2806]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

conda install Pytorch

### Reproduces the problem - code sample

train_pipeline = [
    dict(
        type='BEVLoadMultiViewImageFromFiles',
        to_float32=True,
        color_type='color',
        backend_args=backend_args),
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=5,
        use_dim=[0, 1, 2, 3, 4],
    ),
    dict(
        type='LoadPointsFromMultiSweeps',
        sweeps_num=10,
        use_dim=[0, 1, 2, 3, 4],
    ),
     dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True, with_bbox=True,
         with_label=True, with_attr_label=True),
...
]

### Reproduces the problem - command or script

bash tools/dist_train.sh projects/configs/fusion/fusion_vov.py 1

### Reproduces the problem - error message

Original Traceback (most recent call last):
  File "/home/users/sutd/1008377/.conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/users/sutd/1008377/.conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/users/sutd/1008377/.conda/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/users/sutd/1008377/mmdetection3d/mmdet3d/datasets/dataset_wrappers.py", line 153, in __getitem__
    return self.dataset[ori_index]
  File "/home/users/sutd/1008377/.conda/envs/py38/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "/home/users/sutd/1008377/mmdetection3d/mmdet3d/datasets/det3d_dataset.py", line 386, in prepare_data
    example = self.pipeline(input_dict)
  File "/home/users/sutd/1008377/.conda/envs/py38/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
    data = t(data)
  File "/home/users/sutd/1008377/.conda/envs/py38/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/users/sutd/1008377/mmdetection3d/mmdet3d/datasets/transforms/loading.py", line 1056, in transform
    results = super().transform(results)
  File "/home/users/sutd/1008377/.conda/envs/py38/lib/python3.8/site-packages/mmdet/datasets/transforms/loading.py", line 443, in transform
    self._load_bboxes(results)
  File "/home/users/sutd/1008377/mmdetection3d/mmdet3d/datasets/transforms/loading.py", line 1033, in _load_bboxes
    results['gt_bboxes'] = results['ann_info']['gt_bboxes']
KeyError: 'gt_bboxes'

### Additional information

I want to load 2D gt_box of mutli-view images in nuscenes annotations, How to do it?

**Comment by Blinkblade** [comment]
Hi, I'm meeting the same problem, did you find the way to solve it?
Thank you for any help

**Comment by WinterCodeForEverything** [comment]
nope~~
________________________________

**Comment by QasimMuhammad** [comment]
Did you find solution to it?

**Comment by QasimMuhammad** [comment]
have you found any solution to this

**Comment by joelkny97** [comment]
I am facing a similar error and I want to understand if there has been any update or if anyone using this framework have used gt_bboxes

**Comment by QasimMuhammad** [comment]
This error i think something about if pkl file when it has ampty annotations. I replaced the following two methods with following code in `mmdet3d/datasets/transforms/loading.py` and it worked. 

```
`def _load_bboxes(self, results: dict) -> None:
        """Private function to load bounding box annotations.

        The only difference is it remove the proceess for
        `ignore_flag`

        Args:
            results (dict): Result dict from :obj:`mmcv.BaseDataset`.

        Returns:
            dict: The dict contains loaded bounding box annotations.
        """

        try:
            results['gt_bboxes'] = results['ann_info']['gt_bboxes']
        except KeyError:
            results['gt_bboxes'] = np.array([[0, 0, 0, 0]])


    def _load_labels(self, results: dict) -> None:
        """Private function to load label annotations.

        Args:
            results (dict): Result dict from :obj :obj:`mmcv.BaseDataset`.

        Returns:
            dict: The dict contains loaded label annotations.
        """
        try:
            results['gt_bboxes_labels'] = results['ann_info']['gt_bboxes_labels']
        except KeyError:
            results['gt_bboxes_labels'] = np.array([-1])`
```
