### ISSUE TITLE
Can't train on nuimages[Bug] 

### ISSUE THREAD

**Issue by ZitengXue** [open-mmlab/mmdetection3d#2810]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

the lastest mmdet3d

### Reproduces the problem - code sample

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 124, in main
    runner = Runner.from_cfg(cfg)
  File "/home/xzt/miniconda3/envs/mmdet3d_120/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/xzt/miniconda3/envs/mmdet3d_120/lib/python3.8/site-packages/mmengine/runner/runner.py", line 309, in __init__
    raise ValueError(
ValueError: train_dataloader, train_cfg, and optim_wrapper should be either all None or not None, but got train_dataloader=None, train_cfg={'type': 'EpochBasedTrainLoop', 'max_epochs': 12, 'val_interval': 1}, optim_wrapper={'type': 'OptimWrapper', 'optimizer': {'type': 'SGD', 'lr': 0.02, 'momentum': 0.9, 'weight_decay': 0.0001}}.

### Reproduces the problem - command or script

bash tools/dist_train.sh configs/nuimages/mask-rcnn_r50_fpn_1x_nuim.py 2

### Reproduces the problem - error message

the dataloader for nuimages is None

**Comment by ZitengXue** [comment]
nuimages的config都没办法跑通

**Comment by Mingqj** [comment]
same error
