### ISSUE TITLE
[Feature] RuntimeError: Tensors of type TensorImpl do not have sizes

### ISSUE THREAD

**Issue by chfyyds** [open-mmlab/mmdetection3d#2811]
### What is the feature?

Please tell me why I encountered such a problem when training bevfusion. Hope to get your answer.

Traceback (most recent call last):
  File "/media/chf/新加卷/mmdetection3d/tools/train.py", line 149, in <module>
    main()
  File "/media/chf/新加卷/mmdetection3d/tools/train.py", line 145, in main
    runner.train()
  File "/media/chf/25ee13e8-f20b-4792-9213-0157bc0af688/chf/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/media/chf/25ee13e8-f20b-4792-9213-0157bc0af688/chf/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/media/chf/25ee13e8-f20b-4792-9213-0157bc0af688/chf/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/media/chf/25ee13e8-f20b-4792-9213-0157bc0af688/chf/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/media/chf/25ee13e8-f20b-4792-9213-0157bc0af688/chf/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/media/chf/25ee13e8-f20b-4792-9213-0157bc0af688/chf/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/media/chf/25ee13e8-f20b-4792-9213-0157bc0af688/chf/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/chf/新加卷/mmdetection3d/mmdet3d/models/detectors/base.py", line 75, in forward
    return self.loss(inputs, data_samples, **kwargs)
  File "/media/chf/新加卷/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 290, in loss
    feats = self.extract_feat(batch_inputs_dict, batch_input_metas)
  File "/media/chf/新加卷/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 266, in extract_feat
    img_feature = self.extract_img_feat(imgs, deepcopy(points),
  File "/media/chf/新加卷/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 154, in extract_img_feat
    x = self.view_transform(
  File "/media/chf/25ee13e8-f20b-4792-9213-0157bc0af688/chf/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/chf/新加卷/mmdetection3d/projects/BEVFusion/bevfusion/depth_lss.py", line 424, in forward
    x = super().forward(*args, **kwargs)
  File "/media/chf/新加卷/mmdetection3d/projects/BEVFusion/bevfusion/depth_lss.py", line 330, in forward
    x = self.bev_pool(geom, x)
  File "/media/chf/新加卷/mmdetection3d/projects/BEVFusion/bevfusion/depth_lss.py", line 143, in bev_pool
    x = bev_pool(x, geom_feats, B, self.nx[2], self.nx[0], self.nx[1])
  File "/media/chf/新加卷/mmdetection3d/projects/BEVFusion/bevfusion/ops/bev_pool/bev_pool.py", line 92, in bev_pool
    x = QuickCumsumCuda.apply(feats, coords, ranks, B, D, H, W)
  File "/media/chf/新加卷/mmdetection3d/projects/BEVFusion/bevfusion/ops/bev_pool/bev_pool.py", line 48, in forward
    out = bev_pool_ext.bev_pool_forward(
RuntimeError: Tensors of type TensorImpl do not have sizes

**Comment by 2460707925** [comment]
hello , do you solve this

**Comment by wrencanfly** [comment]
Reinstall package and you will be good I guess
