### ISSUE TITLE
[Bug] RuntimeError: mmcv/mmcv/ops/csrc/pytorch/cuda/sparse_indice.cu 126

### ISSUE THREAD

**Issue by six-wood** [open-mmlab/mmdetection3d#2816]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x

### Environment

System environment:
    sys.platform: linux
    Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 158802988
    GPU 0,1,2,3: Tesla V100-DGXS-32GB
    CUDA_HOME: cudatoolkit/cuda
    NVCC: Cuda compilation tools, release 11.8, V11.8.89
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 2.1.1
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.16.1
    OpenCV: 4.8.1
    MMEngine: 0.10.0

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 158802988
    Distributed launcher: none
    Distributed training: False
    GPU number: 1

### Reproduces the problem - code sample

offical code : cylinder3d_4xb4-3x_semantickitti.py

### Reproduces the problem - command or script

python tools/train.py configs/cylinder3d/cylinder3d_4xb4-3x_semantickitti.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/home/wangwenguang/liumCode/code/CrossORSeg/tools/train.py", line 135, in <module>
    main()
  File "/home/wangwenguang/liumCode/code/CrossORSeg/tools/train.py", line 131, in main
    runner.train()
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 346, in _run_forward
    results = self(**data, mode=mode)
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangwenguang/liumCode/code/CrossORSeg/mmdet3d/models/segmentors/base.py", line 102, in forward
    return self.loss(inputs, data_samples)
  File "/home/wangwenguang/liumCode/code/CrossORSeg/mmdet3d/models/segmentors/cylinder3d.py", line 100, in loss
    x = self.extract_feat(batch_inputs_dict)
  File "/home/wangwenguang/liumCode/code/CrossORSeg/mmdet3d/models/segmentors/cylinder3d.py", line 75, in extract_feat
    x = self.backbone(encoded_feats[0], encoded_feats[1],
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangwenguang/liumCode/code/CrossORSeg/mmdet3d/models/backbones/cylinder3d.py", line 466, in forward
    ret = self.down_context(ret)
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangwenguang/liumCode/code/CrossORSeg/mmdet3d/models/backbones/cylinder3d.py", line 85, in forward
    shortcut = self.conv0_0(x)
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wangwenguang/liumCode/anaconda3/envs/CrossORSeg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangwenguang/liumCode/code/CrossORSeg/mmcv/mmcv/ops/sparse_conv.py", line 157, in forward
    outids, indice_pairs, indice_pair_num = ops.get_indice_pairs(
  File "/home/wangwenguang/liumCode/code/CrossORSeg/mmcv/mmcv/ops/sparse_ops.py", line 99, in get_indice_pairs
    return get_indice_pairs_func(indices, batch_size, out_shape,
RuntimeError: /home/wangwenguang/liumCode/code/CrossORSeg/mmcv/mmcv/ops/csrc/pytorch/cuda/sparse_indice.cu 126
cuda execution failed with error 2

### Additional information

This issue does not exist in RTX4090

**Comment by six-wood** [comment]
it's due to the out of memory, because i not choose the right gpu
