### ISSUE TITLE
[Bug]Play demo: RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection3d#2818]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

```
sys.platform: linux
Python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.66
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.1.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.8.1  (built against CUDA 12.0)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.0+cu121
OpenCV: 4.8.1
MMEngine: 0.9.1
MMDetection: 3.2.0
MMDetection3D: 1.3.0+
spconv2.0: False
```

### Reproduces the problem - code sample

```
python demo/pcd_demo.py demo/data/kitti/000008.bin pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show
```

### Reproduces the problem - command or script

```
python demo/pcd_demo.py demo/data/kitti/000008.bin pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show
```

### Reproduces the problem - error message

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Additional information

```
Traceback (most recent call last):
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/demo/pcd_demo.py", line 90, in <module>
    main()
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/demo/pcd_demo.py", line 80, in main
    inferencer(**call_args)
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/mmdet3d/apis/inferencers/base_3d_inferencer.py", line 212, in __call__
    preds.extend(self.forward(data, **forward_kwargs))
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mmdet3d/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmengine/mmengine/infer/infer.py", line 296, in forward
    return self.model.test_step(inputs)
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmengine/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmengine/mmengine/model/base_model/base_model.py", line 346, in _run_forward
    results = self(**data, mode=mode)
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mmdet3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shuozhang/ProgramFiles/anaconda3/envs/mmdet3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/mmdet3d/models/detectors/base.py", line 86, in forward
    return self.predict(inputs, data_samples, **kwargs)
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/mmdet3d/models/detectors/single_stage.py", line 110, in predict
    results_list = self.bbox_head.predict(x, batch_data_samples, **kwargs)
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/mmdet3d/models/dense_heads/base_3d_dense_head.py", line 182, in predict
    predictions = self.predict_by_feat(
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/mmdet3d/models/dense_heads/base_3d_dense_head.py", line 232, in predict_by_feat
    mlvl_priors = self.prior_generator.grid_anchors(
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/mmdet3d/models/task_modules/anchor/anchor_3d_generator.py", line 114, in grid_anchors
    anchors = self.single_level_grid_anchors(
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/mmdet3d/models/task_modules/anchor/anchor_3d_generator.py", line 155, in single_level_grid_anchors
    self.anchors_single_range(
  File "/media/shuozhang/DATA/Processing/OFFICE/CodingFactory/mmWorkShop/mmdetection3d/mmdet3d/models/task_modules/anchor/anchor_3d_generator.py", line 304, in anchors_single_range
    y_centers = torch.linspace(
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

**Comment by zhongqiu1245** [comment]
Any News？

**Comment by Yunxiang-Wang** [comment]
Did you solve it? I had the same problem
