### ISSUE TITLE
[Docs] 可视化文档draw_bboxes_3d测试报错

### ISSUE THREAD

**Issue by xuyuxiang7** [open-mmlab/mmdetection3d#2828]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

 可视化文档draw_bboxes_3d测试报错。下面是报错
Traceback (most recent call last):
  File "/home/xyx/project/mmdetection3d/results/可视化demo.py", line 16, in <module>
    visualizer.draw_bboxes_3d(bboxes_3d)
  File "/home/xyx/project/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 317, in draw_bboxes_3d
    line_set.paint_uniform_color(np.array(bbox_color[i]) / 255.)
TypeError: paint_uniform_color(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cuda.pybind.geometry.LineSet, color: numpy.ndarray[numpy.float64[3, 1]]) -> open3d.cuda.pybind.geometry.LineSet

Invoked with: LineSet with 12 lines., 0.0

**Comment by guhuajun** [comment]
加油吧，我也是摸索了好多天

1. 用项目里 `docker` 文件下的Dockerfile制作镜像，避免包之间的版本冲突
2. Windows下配置好 vcXsrv, 启动时取消勾选 `Native opengl`

![image](https://github.com/open-mmlab/mmdetection3d/assets/14121694/469c9d9d-6b71-4fc3-8433-527b00fdf502)

**Comment by thelandord** [comment]
请问有解决吗，没有用docker配置环境。

**Comment by GODBENGAY** [comment]
同问

**Comment by 18722013889** [comment]
windows平台 一样的错误，解决了吗？大佬

**Comment by btn6364** [comment]
I got the same issue when running the code in the documentation. Any hint to solve this problem?
```
import torch
import numpy as np

from mmdet3d.visualization import Det3DLocalVisualizer
from mmdet3d.structures import LiDARInstance3DBoxes

points = np.fromfile('demo/data/kitti/000008.bin', dtype=np.float32)
points = points.reshape(-1, 4)
visualizer = Det3DLocalVisualizer()
# set point cloud in visualizer
visualizer.set_points(points)
bboxes_3d = LiDARInstance3DBoxes(
    torch.tensor([[8.7314, -1.8559, -1.5997, 4.2000, 3.4800, 1.8900,
                   -1.5808]]))
# Draw 3D bboxes
visualizer.draw_bboxes_3d(bboxes_3d)
visualizer.show()
```

**Comment by Wang0203** [comment]
> I got the same issue when running the code in the documentation. Any hint to solve this problem?
> 
> ```
> import torch
> import numpy as np
> 
> from mmdet3d.visualization import Det3DLocalVisualizer
> from mmdet3d.structures import LiDARInstance3DBoxes
> 
> points = np.fromfile('demo/data/kitti/000008.bin', dtype=np.float32)
> points = points.reshape(-1, 4)
> visualizer = Det3DLocalVisualizer()
> # set point cloud in visualizer
> visualizer.set_points(points)
> bboxes_3d = LiDARInstance3DBoxes(
>     torch.tensor([[8.7314, -1.8559, -1.5997, 4.2000, 3.4800, 1.8900,
>                    -1.5808]]))
> # Draw 3D bboxes
> visualizer.draw_bboxes_3d(bboxes_3d)
> visualizer.show()
> ```

Hello, did you solve the problem?

**Comment by WZWAsuna** [comment]
TypeError: paint_uniform_color(): incompatible function arguments.
The following argument types are supported:
    1. (self: open3d.cuda.pybind.geometry.LineSet, color: numpy.ndarray[numpy.float64[3, 1]]) -> open3d.cuda.pybind.geometry.LineSet
 
按照上面的描述，报错的代码应该是这个函数调用时传递的参数问题
line_set.paint_uniform_color(np.array(bbox_color[i]) / 255.)

传入的color应该是float64的numpy数组，形状是[3,1]，而draw_bboxes_3d的bbox_color参数默认值是一个Tuple[float] = (0, 1, 0)，但是这里bbox_color[i]经过索引后形状不再是[3,1]了，我把两处bbox_color[i]改成bbox_color后可以显示点云和bounding box，就是颜色有点奇怪

**Comment by WZWAsuna** [comment]
visualizer.draw_bboxes_3d(bboxes_3d,(255,0,0))
调用时传入了设置bbox颜色的元组修改了颜色

> TypeError: paint_uniform_color(): incompatible function arguments. The following argument types are supported: 1. (self: open3d.cuda.pybind.geometry.LineSet, color: numpy.ndarray[numpy.float64[3, 1]]) -> open3d.cuda.pybind.geometry.LineSet
> 
> 按照上面的描述，报错的代码应该是这个函数调用时传递的参数问题 line_set.paint_uniform_color(np.array(bbox_color[i]) / 255.)
> 
> 传入的color应该是float64的numpy数组，形状是[3,1]，而draw_bboxes_3d的bbox_color参数默认值是一个Tuple[float] = (0, 1, 0)，但是这里bbox_color[i]经过索引后形状不再是[3,1]了，我把两处bbox_color[i]改成bbox_color后可以显示点云和bounding box，就是颜色有点奇怪

![2024-03-29 10-10-24 的屏幕截图](https://github.com/open-mmlab/mmdetection3d/assets/46561667/7ae96627-1425-4c26-801c-7668e57c672e)

**Comment by hitbuyi** [comment]
I have the same problem, It is bug

**Comment by zkailinzhang** [comment]
AttributeError: 'Det3DLocalVisualizer' object has no attribute 'view_control'

**Comment by zkailinzhang** [comment]
import os
os.environ['DISPLAY'] = '1'  可以解决

**Comment by Sheharyar02** [comment]
The issue arose because of how colors were being passed and expected by **Open3D's** `paint_uniform_color `method. Here's a breakdown:
`line_set.paint_uniform_color(np.array(bbox_color[i]) / 255.)`

There was a data type mismatch as `pain_uniform_color` expects a` numpy.ndarray` with shape (3,1) while bbox_color[i] expects a tuple after slicing using bbox[i] lost its expected stucture and type.

I came up with a temporary solution based on the length of the bboxes_3d.

Using matplotlib.cm do assign dyanmic colors based on the number of bboxes.


So this is the complete change : mmdet3d--> local_visualizer.py--> Det3DLocalVisualizer--> draw__bboxes_3d;

instead of `line_set.paint_uniform_color(np.array(bbox_color[i]) / 255.)`

I did :  
   
```
            import matplotlib.cm as cm
            num_bboxes = len(bboxes_3d)
            colormap = cm.get_cmap('viridis', num_bboxes)  # Choose any colormap
            dynamic_colors = [colormap(i)[:3] for i in range(num_bboxes)]  # Extract RGB values

            
            color = np.array(dynamic_colors[i], dtype=np.float64).reshape(3, 1)
            line_set.paint_uniform_color(color)

```

![Image](https://github.com/user-attachments/assets/4ed120a0-8a6e-4d65-be4d-3ab539d10dd1)


Let me know if it works 😃
