### ISSUE TITLE
[Bug] Bevfusion Train

### ISSUE THREAD

**Issue by WuYanXingege** [open-mmlab/mmdetection3d#2844]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

correct installed

### Reproduces the problem - code sample

In the BevFusion radar branch, the original code uses a point cloud range of [-54, -54, -5, 54, 54, 3], voxel size of [0.075, 0.075, 0.2], and sparse shape of [1440, 1440, 41]. After modifying the point cloud range to [0, -30, -3, 60, 30, 1], voxel size to [0.05, 0.05, 0.1], and sparse shape to [1200, 1200, 41], you encountered an error during training, while the original code trains successfully.

### Reproduces the problem - command or script

when train bevfusion ,before modify the point range and sparss_shape,it works,but after modified,error occur

### Reproduces the problem - error message

"CUDA error: invalid configuration argument"

### Additional information

i use kitti

**Comment by WuYanXingege** [comment]
File "/home/ee615/mmdetection3d-main/projects/BEVFusion/bevfusion/ops/voxel/voxelize.py", line 142, in forward
    return voxelization(
  File "/home/ee615/mmdetection3d-main/projects/BEVFusion/bevfusion/ops/voxel/voxelize.py", line 60, in forward
    voxel_num = hard_voxelize(
RuntimeError: CUDA error: invalid configuration argument

**Comment by lxzjlu** [comment]
I have the same problem，have you solved it yet?

**Comment by lxzjlu** [comment]
In addition to the above errors, the following errors will occur. Will the same errors occur on your code?
@WuYanXingege 
`Traceback (most recent call last):                                                                                                                  File "tools/train.py", line 135, in <module>                                                                                                        main()                                                                                                                                          File "tools/train.py", line 131, in main                                                                                                            runner.train()                                                                                                                                  File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train                              model = self.train_loop.run()  # type: ignore                                                                                                   File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run                                   self.run_epoch()                                                                                                                                File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch                            self.run_iter(idx, data_batch)                                                                                                                  File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter                             outputs = self.runner.model.train_step(                                                                                                         File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step            losses = self._run_forward(data, mode='loss')  # type: ignore                                                                                   File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 346, in _run_forward          results = self(**data, mode=mode)                                                                                                               File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                        return forward_call(*input, **kwargs)                                                                                                           File "/media/data/xiaozhi_data/code_py/mmdet3D/mmdetection3d-main/mmdet3d/models/detectors/base.py", line 75, in forward                            return self.loss(inputs, data_samples, **kwargs)                                                                                                File "/media/data/xiaozhi_data/code_py/mmdet3D/mmdetection3d-main/projects/BEVFusion/bevfusion/bevfusion.py", line 290, in loss                     feats = self.extract_feat(batch_inputs_dict, batch_input_metas)                                                                                 File "/media/data/xiaozhi_data/code_py/mmdet3D/mmdetection3d-main/projects/BEVFusion/bevfusion/bevfusion.py", line 272, in extract_feat             pts_feature = self.extract_pts_feat(batch_inputs_dict)                                                                                          File "/media/data/xiaozhi_data/code_py/mmdet3D/mmdetection3d-main/projects/BEVFusion/bevfusion/bevfusion.py", line 172, in extract_pts_feat         x = self.pts_middle_encoder(feats, coords, batch_size)                                                                                          File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                        return forward_call(*input, **kwargs)                                                                                                           File "/media/data/xiaozhi_data/code_py/mmdet3D/mmdetection3d-main/projects/BEVFusion/bevfusion/sparse_encoder.py", line 132, in forward             x = self.conv_input(input_sp_tensor)                                                                                                            File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                        return forward_call(*input, **kwargs)                                                                                                           File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 138, in forward                             input = module(input)                                                                                                                           File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                        return forward_call(*input, **kwargs)                                                                                                           File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 755, in forward                                return self._conv_forward(self.training,                                                                                                        File "/home/xiaozhi/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 169, in _conv_forward                          assert input.features.shape[                                                                                                                  AssertionError: channel size mismatch  `

**Comment by lxzjlu** [comment]
In addition to the above errors, the following errors will occur. Will the same errors occur on your code?
@WuYanXingege 
`AssertionError: channel size mismatch   `
![Uploading 批注 2023-12-13 205815.png…]()

**Comment by WuYanXingege** [comment]
no，i do&nbsp; not occur your error，it just aboutCUDA error。



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 13, 2023 21:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdetection3d] [Bug] Bevfusion Train (Issue #2844)




 
In addition to the above errors, the following errors will occur. Will the same errors occur on your code?
 @WuYanXingege
 AssertionError: channel size mismatch   
 2023-12-13.205815.png (view on web)

**Comment by lxzjlu** [comment]
> no，i do&nbsp; not occur your error，it just aboutCUDA error。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Dec 13, 2023 21:00 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [open-mmlab/mmdetection3d] [Bug] Bevfusion Train (Issue #2844) In addition to the above errors, the following errors will occur. Will the same errors occur on your code? @WuYanXingege AssertionError: channel size mismatch 2023-12-13.205815.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Is it convenient to add your contact to communicate?
v 15209852118

**Comment by zql0606** [comment]
> have you solved it about cuda error？

**Comment by zql0606** [comment]
> no，i do&nbsp; not occur your error，it just aboutCUDA error。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Dec 13, 2023 21:00 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [open-mmlab/mmdetection3d] [Bug] Bevfusion Train (Issue #2844) In addition to the above errors, the following errors will occur. Will the same errors occur on your code? @WuYanXingege AssertionError: channel size mismatch 2023-12-13.205815.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;



> File "/home/ee615/mmdetection3d-main/projects/BEVFusion/bevfusion/ops/voxel/voxelize.py", line 142, in forward return voxelization( File "/home/ee615/mmdetection3d-main/projects/BEVFusion/bevfusion/ops/voxel/voxelize.py", line 60, in forward voxel_num = hard_voxelize( RuntimeError: CUDA error: invalid configuration argument
have you solved it ?

**Comment by lacie-life** [comment]
> > no，i do  not occur your error，it just aboutCUDA error。
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Wed, Dec 13, 2023 21:00 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [open-mmlab/mmdetection3d] [Bug] Bevfusion Train (Issue #2844) In addition to the above errors, the following errors will occur. Will the same errors occur on your code? @WuYanXingege AssertionError: channel size mismatch 2023-12-13.205815.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> Is it convenient to add your contact to communicate? v 15209852118

have you solved this error?

**Comment by gorkemguzeler** [comment]
@WuYanXingege , 

when you say:
> In the BevFusion radar branch

do you refer to a branch in the original BEVFusion repository? if so could you share which one you are referring? 

ah nvm, i found out it is already merged into main..
