### ISSUE TITLE
__init__() got an unexpected keyword argument 'ann_file' [Bug] 

### ISSUE THREAD

**Issue by 52THANOS** [open-mmlab/mmdetection3d#2845]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x

### Environment

TorchVision: 0.16.1+cu118
OpenCV: 4.8.1
MMEngine: 0.10.1
MMDetection: 3.2.0
MMDetection3D: 1.3.0+5c0613b
spconv2.0: False

### Reproduces the problem - code sample

_base_ = [
    '../_base_/schedules/mmdet-schedule-1x.py', '../_base_/default_runtime.py'
]
prior_generator = dict(
    type='AlignedAnchor3DRangeGenerator',
    ranges=[[-3.2, -0.2, -2.28, 3.2, 6.2, 0.28]],
    rotations=[.0])
model = dict(
    type='ImVoxelNet',
    data_preprocessor=dict(
        type='Det3DDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_size_divisor=32),
    backbone=dict(
        type='mmdet.ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=False),
        norm_eval=True,
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
        style='pytorch'),
    neck=dict(
        type='mmdet.FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=4),
    neck_3d=dict(
        type='IndoorImVoxelNeck',
        in_channels=256,
        out_channels=128,
        n_blocks=[1, 1, 1]),
    bbox_head=dict(
        type='ImVoxelHead',
        n_classes=10,
        n_levels=3,
        n_channels=128,
        n_reg_outs=7,
        pts_assign_threshold=27,
        pts_center_threshold=18,
        prior_generator=prior_generator),
    prior_generator=prior_generator,
    n_voxels=[40, 40, 16],
    coord_type='DEPTH',
    train_cfg=dict(),
    test_cfg=dict(nms_pre=1000, iou_thr=.25, score_thr=.01))

dataset_type = 'SUNRGBDDataset'
data_root = 'data/sunrgbd/'
class_names = [
    'bed', 'table', 'sofa', 'chair', 'toilet', 'desk', 'dresser',
    'night_stand', 'bookshelf', 'bathtub'
]
metainfo = dict(CLASSES=class_names)

backend_args = None

train_pipeline = [
    dict(type='LoadAnnotations3D', backend_args=backend_args),
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='RandomResize', scale=[(512, 384), (768, 576)], keep_ratio=True),
    dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
    dict(type='Pack3DDetInputs', keys=['img', 'gt_bboxes_3d', 'gt_labels_3d'])
]
test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='Resize', scale=(640, 480), keep_ratio=True),
    dict(type='Pack3DDetInputs', keys=['img'])
]

train_dataloader = dict(
    batch_size=4,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='RepeatDataset',
        times=2,
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file='sunrgbd_infos_train.pkl',
            pipeline=train_pipeline,
            test_mode=False,
            filter_empty_gt=True,
            box_type_3d='Depth',
            metainfo=metainfo,
            backend_args=backend_args)))
val_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='sunrgbd_infos_val.pkl',
        pipeline=test_pipeline,
        test_mode=True,
        box_type_3d='Depth',
        metainfo=metainfo,
        backend_args=backend_args))
test_dataloader = val_dataloader

val_evaluator = dict(
    type='IndoorMetric',
    ann_file=data_root + 'sunrgbd_infos_val.pkl',
    metric='bbox')
test_evaluator = val_evaluator

# optimizer
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        _delete_=True, type='AdamW', lr=0.0001, weight_decay=0.0001),
    paramwise_cfg=dict(
        custom_keys={'backbone': dict(lr_mult=0.1, decay_mult=1.0)}),
    clip_grad=dict(max_norm=35., norm_type=2))
param_scheduler = [
    dict(
        type='MultiStepLR',
        begin=0,
        end=12,
        by_epoch=True,
        milestones=[8, 11],
        gamma=0.1)
]

# hooks
default_hooks = dict(checkpoint=dict(type='CheckpointHook', max_keep_ckpts=1))

# runtime
find_unused_parameters = True  # only 1 of 4 FPN outputs is used

### Reproduces the problem - command or script

python tools/train.py configs/imvoxelnet/imvoxelnet_2xb4_sunrgbd-3d-10class.py

### Reproduces the problem - error message

d:\downloadproject\mmdetection3d\mmdet3d\evaluation\functional\kitti_utils\eval.py:10: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' deco
rator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_thresholds(scores: np.ndarray, num_gt, num_sample_pts=41):
Traceback (most recent call last):
  File "D:\DownloadProject\mmdetection3d\tools\train.py", line 135, in <module>
    main()
  File "D:\DownloadProject\mmdetection3d\tools\train.py", line 131, in main
    runner.train()
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\runner\runner.py", line 1742, in train
    self._val_loop = self.build_val_loop(
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\runner\runner.py", line 1562, in build_val_loop
    loop = LOOPS.build(
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\runner\loops.py", line 338, in __init__
    self.evaluator = runner.build_evaluator(evaluator)  # type: ignore
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\runner\runner.py", line 1318, in build_evaluator
    return Evaluator(evaluator)  # type: ignore
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\evaluator\evaluator.py", line 25, in __init__
    self.metrics.append(METRICS.build(metric))
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\DownloadProject\mmdetection3d\venv\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'ann_file'

**Comment by 52THANOS** [comment]
i saw this bug in September,no one is fixing bugs in mmdet3d?

**Comment by huyifan001** [comment]
Have you solved this problem yet? I seem to have encountered the same error as you.


Traceback (most recent call last):
  File "tools/train.py", line 145, in <module>
    main()
  File "tools/train.py", line 141, in main
    runner.train()
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1742, in train
    self._val_loop = self.build_val_loop(
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1562, in build_val_loop
    loop = LOOPS.build(
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 346, in __init__
    self.evaluator = runner.build_evaluator(evaluator)  # type: ignore
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1318, in build_evaluator
    return Evaluator(evaluator)  # type: ignore
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 25, in __init__
    self.metrics.append(METRICS.build(metric))
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'ann_file'

**Comment by 52THANOS** [comment]
> Have you solved this problem yet? I seem to have encountered the same error as you.
> 
> Traceback (most recent call last): File "tools/train.py", line 145, in main() File "tools/train.py", line 141, in main runner.train() File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1742, in train self._val_loop = self.build_val_loop( File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1562, in build_val_loop loop = LOOPS.build( File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build return self.build_func(cfg, *args, **kwargs, registry=self) File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg obj = obj_cls(**args) # type: ignore File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 346, in **init** self.evaluator = runner.build_evaluator(evaluator) # type: ignore File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1318, in build_evaluator return Evaluator(evaluator) # type: ignore File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 25, in **init** self.metrics.append(METRICS.build(metric)) File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build return self.build_func(cfg, *args, **kwargs, registry=self) File "/home/huyifan/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg obj = obj_cls(**args) # type: ignore TypeError: **init**() got an unexpected keyword argument 'ann_file'
you need to add argument in source file.just debug into it
