### ISSUE TITLE
[Bug] KeyError 'CAM2' when running Monocular 3D demo of FCOS3D

### ISSUE THREAD

**Issue by turtlemicro** [open-mmlab/mmdetection3d#2868]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: Tesla V100-PCIE-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0
OpenCV: 4.9.0
MMEngine: 0.10.2
MMDetection: 3.3.0
MMDetection3D: 1.4.0+0ef13b8
spconv2.0: False

### Reproduces the problem - code sample

File mono_det_demo.py
def main():
    # TODO: Support inference of point cloud numpy file.
    init_args, call_args = parse_args()

    inferencer = MonoDet3DInferencer(**init_args)
    inferencer(**call_args)

### Reproduces the problem - command or script

python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800.pkl  configs/fcos3d/fcos3d_r101-caffe-dcn_fpn_head-gn_8xb2-1x_nus-mono3d_finetune.py data/checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth  --cam-type CAM_BACK --out-dir FCOS3D/uno

### Reproduces the problem - error message

Loads checkpoint by local backend from path: data/checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth
01/08 15:46:46 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
/opt/conda/lib/python3.7/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
Traceback (most recent call last):
  File "demo/mono_det_demo.py", line 98, in <module>
    main()
  File "demo/mono_det_demo.py", line 88, in main
    inferencer(**call_args)
  File "/mmdetection3d/mmdet3d/apis/inferencers/base_3d_inferencer.py", line 204, in __call__
    ori_inputs = self._inputs_to_list(inputs, cam_type=cam_type)
  File "/mmdetection3d/mmdet3d/apis/inferencers/mono_det3d_inferencer.py", line 110, in _inputs_to_list
    img_path = data_info['images'][cam_type]['img_path']

### Additional information

I installed mmdetection3d via Docker. I only want to run the inference with a pretrained pth file. When running the official demo for inference with the PGD model and the SMOKE model on KITTI, it's running. For FCOS3D on NuScenes, this error occurs. I tried to hardcode the cam_type CAM_BACK into the files "base_3d_inferencer.py" and "mono_det3d_inferencer.py", because it seems that the CAM_BACK in the command I'm running is simply ignored. 
When doing this, the following error occurs:
"File "/mmdetection3d/mmdet3d/apis/inferencers/mono_det3d_inferencer.py", line 125, in _inputs_to_list
    lidar2img = cam2img @ lidar2cam
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)"

**Comment by Aloaml** [comment]
Hello, I encountered the same problem. Have you solved this problem?
RUNNING FCOS3D inference demo:
(openmmlab) zz@zz-Ubuntu:~/project/mmdetection3d-dev-1.x$ python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800.pkl  configs/fcos3d/fcos3d_r101-caffe-dcn_fpn_head-gn_8xb2-1x_nus-mono3d_finetune.py test_checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth --show --cam-type CAM_BACK

Error is same:
**Traceback (most recent call last):
  File "demo/mono_det_demo.py", line 98, in <module>
    main()
  File "demo/mono_det_demo.py", line 88, in main
    inferencer(**call_args)
  File "/home/zz/project/mmdetection3d-dev-1.x/mmdet3d/apis/inferencers/base_3d_inferencer.py", line 204, in __call__
    ori_inputs = self._inputs_to_list(inputs, cam_type=cam_type)
  File "/home/zz/project/mmdetection3d-dev-1.x/mmdet3d/apis/inferencers/mono_det3d_inferencer.py", line 110, in _inputs_to_list
    img_path = data_info['images'][cam_type]['img_path']
KeyError: 'CAM2'**

My thoughts are the same as yours, the program ignores the input parameters ‘--cam-type CAM_BACK’. But I dont know how to solve it.

**Comment by turtlemicro** [comment]
No, unfortunately not. I'm still waiting for help :-)

**Comment by Aloaml** [comment]
I think I have some clues. This error comes from an incorrect key in the dic 'kwargs'.
mmdet3d/apis/inferencers/base_3d_inferencer.py     line170
```python
 if cam_type != '':
            kwargs['cam_type'] = cam_type
            # kwargs['cam_type_dir'] = cam_type
``` 
Then the script will correctly read the incoming parameter 'CAM_BACK'
But another error occurs.
```
Traceback (most recent call last):
  File "/home/zz/project/mmdetection3d-dev-1.x/demo/mono_det_demo.py", line 98, in <module>
    main()
  File "/home/zz/project/mmdetection3d-dev-1.x/demo/mono_det_demo.py", line 88, in main
    inferencer(**call_args)
  File "/home/zz/project/mmdetection3d-dev-1.x/mmdet3d/apis/inferencers/base_3d_inferencer.py", line 209, in __call__
    ori_inputs = self._inputs_to_list(inputs, cam_type=cam_type)
  File "/home/zz/project/mmdetection3d-dev-1.x/mmdet3d/apis/inferencers/mono_det3d_inferencer.py", line 127, in _inputs_to_list
    lidar2img = cam2img @ lidar2cam
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)
``` 
The reason is that the number of columns of matrix cam2img is not equal to the number of rows of lidar2cam, so they cannot be multiplied.
cam2img is 3x3 and lidar2cam is 4x4, I don't know what this line of code means.
For running program, I changed **'lidar2cam'** for no reason. 
```python
  else:
      # lidar2img = cam2img @ lidar2cam
      lidar2img = cam2img @ lidar2cam[0:3]
``` 
Finally it ran, and the results were unexpectedly correct. . .Of course I don't know why, I'm just getting started.
![myplot](https://github.com/open-mmlab/mmdetection3d/assets/50262041/c283cbf5-f19f-45f8-b04d-473d0fbde1d1)

**Comment by Aloaml** [comment]
I think this program does not require lidar2cam or lidar2img because it is mono_det. So it's still normal and correct if delete all the code about lidar:
```python
                # lidar2cam = np.asarray(
                #     data_info['images'][cam_type]['lidar2cam'],
                #     dtype=np.float32)
                # if 'lidar2img' in data_info['images'][cam_type]:
                #     lidar2img = np.asarray(
                #         data_info['images'][cam_type]['lidar2img'],
                #         dtype=np.float32)
                # else:
                #     lidar2img = cam2img @ lidar2cam
                input['cam2img'] = cam2img
                # input['lidar2cam'] = lidar2cam
                # input['lidar2img'] = lidar2img
```

**Comment by Aloaml** [comment]
I think this program does not require lidar2cam or lidar2img because it is mono_det. So it's still normal and correct if delete all the code about lidar:
mmdet3d/apis/inferencers/mono_det3d_inferencer.py   line 118
```python
                # lidar2cam = np.asarray(
                #     data_info['images'][cam_type]['lidar2cam'],
                #     dtype=np.float32)
                # if 'lidar2img' in data_info['images'][cam_type]:
                #     lidar2img = np.asarray(
                #         data_info['images'][cam_type]['lidar2img'],
                #         dtype=np.float32)
                # else:
                #     lidar2img = cam2img @ lidar2cam

                input['cam2img'] = cam2img
                # input['lidar2cam'] = lidar2cam
                # input['lidar2img'] = lidar2img
```

**Comment by turtlemicro** [comment]
Thank you! I want to make the inference on other input images, have you already done that? The pictures provided in the demo are listed in the .pkl files. If the name of the input pictures differs from the one in the demo, the inference won't run.

**Comment by SajjadPSavoji** [comment]
I want to add a few notes to this discussion. As @Aloaml  mentioned mono detection should not depend on lidar2cam and lidar2img matrices. If you are not using the public datasets support so far in MMDet3D you might encounter errors as the code will try to load those matrices by default. 

So far I have not found a proper way to bypass this without changing the source code, and the same thing holds for inference codes which are called in the demo files. 

I think it calls for a bit modifications for the next release, but for now your best shot is changing the source code to ignore those matrices. 

while we are at it, maybe having a demo that runs on img arrays instead of files would be a great asset as well.

**Comment by SajjadPSavoji** [comment]
to by pass you should update the mmdet3D/apis/inferencers/mono_det3d_inferencer.py
with the following code. It will allow you to run demo on datasets that don't have lidar.

`def _inputs_to_list(self,
                        inputs: Union[dict, list],
                        cam_type='CAM2',
                        **kwargs) -> list:
        """Preprocess the inputs to a list.
        Preprocess inputs to a list according to its type:

        - list or tuple: return inputs
        - dict: the value with key 'img' is
            - Directory path: return all files in the directory
            - other cases: return a list containing the string. The string
              could be a path to file, a url or other types of string according
              to the task.

        Args:
            inputs (Union[dict, list]): Inputs for the inferencer.

        Returns:
            list: List of input for the :meth:`preprocess`.
        """
        if isinstance(inputs, dict):
            assert 'infos' in inputs
            infos = inputs.pop('infos')

            if isinstance(inputs['img'], str):
                img = inputs['img']
                backend = get_file_backend(img)
                if hasattr(backend, 'isdir') and isdir(img):
                    # Backends like HttpsBackend do not implement `isdir`, so
                    # only those backends that implement `isdir` could accept
                    # the inputs as a directory
                    filename_list = list_dir_or_file(img, list_dir=False)
                    inputs = [{
                        'img': join_path(img, filename)
                    } for filename in filename_list]

            if not isinstance(inputs, (list, tuple)):
                inputs = [inputs]

            # get cam2img, lidar2cam and lidar2img from infos
            info_list = mmengine.load(infos)['data_list']
            assert len(info_list) == len(inputs)
            for index, input in enumerate(inputs):
                data_info = info_list[index]
                img_path = data_info['images'][cam_type]['img_path']
                if isinstance(input['img'], str) and \
                        osp.basename(img_path) != osp.basename(input['img']):
                    raise ValueError(
                        f'the info file of {img_path} is not provided.')
                cam2img = np.asarray(
                    data_info['images'][cam_type]['cam2img'], dtype=np.float32)
                if 'lidar2cam' in data_info['images'][cam_type]:
                    lidar2cam = np.asarray(
                        data_info['images'][cam_type]['lidar2cam'],
                        dtype=np.float32)
                    if 'lidar2img' in data_info['images'][cam_type]:
                        lidar2img = np.asarray(
                            data_info['images'][cam_type]['lidar2img'],
                            dtype=np.float32)
                    else:
                        lidar2img = cam2img @ lidar2cam
                    input['lidar2cam'] = lidar2cam
                    input['lidar2img'] = lidar2img
                input['cam2img'] = cam2img
        elif isinstance(inputs, (list, tuple)):
            # get cam2img, lidar2cam and lidar2img from infos
            for input in inputs:
                assert 'infos' in input
                infos = input.pop('infos')
                info_list = mmengine.load(infos)['data_list']
                assert len(info_list) == 1, 'Only support single sample info' \
                    'in `.pkl`, when inputs is a list.'
                data_info = info_list[0]
                img_path = data_info['images'][cam_type]['img_path']
                if isinstance(input['img'], str) and \
                        osp.basename(img_path) != osp.basename(input['img']):
                    raise ValueError(
                        f'the info file of {img_path} is not provided.')
                cam2img = np.asarray(
                    data_info['images'][cam_type]['cam2img'], dtype=np.float32)
                if 'lidar2cam' in data_info['images'][cam_type]:
                    lidar2cam = np.asarray(
                        data_info['images'][cam_type]['lidar2cam'],
                        dtype=np.float32)
                    if 'lidar2img' in data_info['images'][cam_type]:
                        lidar2img = np.asarray(
                            data_info['images'][cam_type]['lidar2img'],
                            dtype=np.float32)
                    else:
                        lidar2img = cam2img @ lidar2cam

                    input['lidar2cam'] = lidar2cam
                    input['lidar2img'] = lidar2img
                input['cam2img'] = cam2img

        return list(inputs)
`

**Comment by muety** [comment]
Same problem here! The workaround described by @Aloaml worked, but would be cool to get this fixed permanently.

**Comment by FBarrca** [comment]
Well, I'm running the exact same code as you guys on  MMDetection3D: 1.4.0(not from source but from pip), and I'm getting the error 🥲:
```
KeyError: 'ResNet is not in the mmdet3d::model registry. Please check whether the value of `ResNet` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```
Any help would be appreciated🥺.
