### ISSUE TITLE
[Bug] Error while converting waymo into kitti

### ISSUE THREAD

**Issue by hojoonleokim** [open-mmlab/mmdetection3d#2886]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
CUDA available: False
numpy_random_seed: 2147483648
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1
OpenCV: 4.9.0
MMEngine: 0.10.2
MMDetection: 3.3.0
MMDetection3D: 1.4.0+962f093
spconv2.0: False

### Reproduces the problem - code sample

python tools/create_data.py waymo --root-path ./data/waymo/ --out-dir ./data/waymo/ --workers 128 --extra-tag waymo --version v1.4

### Reproduces the problem - command or script

python tools/create_data.py waymo --root-path ./data/waymo/ --out-dir ./data/waymo/ --workers 128 --extra-tag waymo --version v1.4

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/create_data.py", line 386, in <module>
    skip_cam_instances_infos=args.skip_cam_instances_infos)
  File "tools/create_data.py", line 252, in waymo_data_prep
    num_worker=workers).create()
  File "/home/ipa/sherlock/mmdetection3d/tools/dataset_converters/create_gt_database.py", line 592, in create
    self.dataset = DATASETS.build(dataset_cfg)
  File "/home/ipa/sherlock/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ipa/sherlock/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/ipa/sherlock/mmdetection3d/mmdet3d/datasets/waymo_dataset.py", line 126, in __init__
    **kwargs)
  File "/home/ipa/sherlock/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 88, in __init__
    **kwargs)
  File "/home/ipa/sherlock/mmdetection3d/mmdet3d/datasets/det3d_dataset.py", line 133, in __init__
    **kwargs)
  File "/home/ipa/sherlock/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/home/ipa/sherlock/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 307, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/home/ipa/sherlock/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 768, in _serialize_data
    data_bytes = np.concatenate(data_list)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

### Additional information

1. I first used waymo v1.2 dataset and gt.bin file. But  code in create_data.py requested me to use v1.4. So I downloaded "testing_3d_camera_only_detection" from 1.4.
2. I dataset was too large for my machine so I downloaded only "validation_0000.tar, training_0000.tar, testing_0000.tar, gt.bin".
3. I followed file directory guide(https://github.com/open-mmlab/mmdetection3d/blob/1.0/docs/en/datasets/waymo_det.md).
4. After code execution, 
> waymo_infos_test_cam_only.pkl, waymo_infos_test.pkl, waymo_infos_train.pkl, waymo_infos_trainval.pkl,  waymo_infos_val.pkl, image_0, image_1, image_2, image_3,  image_4,  velodyne  

was created. **waymo_gt_database** is missing
5. I followed https://mmdetection3d.readthedocs.io/en/latest/get_started.html to install mmdet3d

**Comment by friedang** [comment]
Hi, I had the same error message but solved it by installing the right version of `waymo-open-dataset-tf`.
In my case it was: `waymo-open-dataset-tf-2-1-0==1.2.0` (also mentioned in the requirement.txt). 

I can't tell which version you used but suggest an attempt for a clean re-install.
