### ISSUE TITLE
[Bug] mmdet3d 基于nuscenes-v1.0mini的可视化

### ISSUE THREAD

**Issue by GZF123** [open-mmlab/mmdetection3d#2914]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

命令行:   python projects/BEVFusion/demo/multi_modality_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin demo/data/nuscenes/ demo/data/nuscenes/n015-2018-07-24-11-22-45+0800.pkl  /home/g/mmdetection3d/mmdetection3d/work_dirs/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py /home/g/mmdetection3d/mmdetection3d/work_dirs/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d/epoch_10.pth --cam-type all --score-thr 0.2 --show
情况:出现一个黑色的图像然后就闪一下关闭了
报错内容:/home/g/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
Traceback (most recent call last):
  File "projects/BEVFusion/demo/multi_modality_demo.py", line 78, in <module>
    main(args)
  File "projects/BEVFusion/demo/multi_modality_demo.py", line 64, in main
    visualizer.add_datasample(
  File "/home/g/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/dist/utils.py", line 427, in wrapper
    return func(*args, **kwargs)
  File "/home/g/mmdetection3d/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 1031, in add_datasample
    pred_data_3d = self._draw_instances_3d(data_input,
  File "/home/g/mmdetection3d/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 707, in _draw_instances_3d
    self.draw_proj_bboxes_3d(
  File "/home/g/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/dist/utils.py", line 427, in wrapper
    return func(*args, **kwargs)
  File "/home/g/mmdetection3d/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 533, in draw_proj_bboxes_3d
    corners_2d = proj_bbox3d_to_img(bboxes_3d, input_meta)
  File "/home/g/mmdetection3d/mmdetection3d/mmdet3d/visualization/vis_utils.py", line 105, in proj_lidar_bbox3d_to_img
    lidar2img = copy.deepcopy(input_meta['lidar2img']).reshape(4, 4)
KeyError: 'lidar2img'

### Reproduces the problem - code sample

没有

### Reproduces the problem - command or script

 python projects/BEVFusion/demo/multi_modality_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin demo/data/nuscenes/ demo/data/nuscenes/n015-2018-07-24-11-22-45+0800.pkl  /home/g/mmdetection3d/mmdetection3d/work_dirs/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py /home/g/mmdetection3d/mmdetection3d/work_dirs/bevfusion_lidar_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d/epoch_10.pth --cam-type all --score-thr 0.2 --show

### Reproduces the problem - error message

/home/g/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
Traceback (most recent call last):
  File "projects/BEVFusion/demo/multi_modality_demo.py", line 78, in <module>
    main(args)
  File "projects/BEVFusion/demo/multi_modality_demo.py", line 64, in main
    visualizer.add_datasample(
  File "/home/g/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/dist/utils.py", line 427, in wrapper
    return func(*args, **kwargs)
  File "/home/g/mmdetection3d/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 1031, in add_datasample
    pred_data_3d = self._draw_instances_3d(data_input,
  File "/home/g/mmdetection3d/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 707, in _draw_instances_3d
    self.draw_proj_bboxes_3d(
  File "/home/g/miniconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/dist/utils.py", line 427, in wrapper
    return func(*args, **kwargs)
  File "/home/g/mmdetection3d/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 533, in draw_proj_bboxes_3d
    corners_2d = proj_bbox3d_to_img(bboxes_3d, input_meta)
  File "/home/g/mmdetection3d/mmdetection3d/mmdet3d/visualization/vis_utils.py", line 105, in proj_lidar_bbox3d_to_img
    lidar2img = copy.deepcopy(input_meta['lidar2img']).reshape(4, 4)
KeyError: 'lidar2img'

### Additional information

我希望是一个可以用自己模型可视化的结果

**Comment by YJJ1125** [comment]
缺少save_dir应该是 试着加上保存路径
