### ISSUE TITLE
[Bug] ImportError: DLL load failed while importing _ext: 找不到指定的程序。

### ISSUE THREAD

**Issue by apical-2** [open-mmlab/mmdetection3d#2929]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

我已经安装官网最新安装方法安装了mmdet3d，不需要使用mmcv-ful，仅用mmcv

### Reproduces the problem - code sample

python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti无法对kitti数据集生成信息文件

### Reproduces the problem - command or script

(deep_pytorch) PS D:\mmdetection3d> python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
Traceback (most recent call last):
  File "D:\mmdetection3d\tools\create_data.py", line 8, in <module>
    from tools.dataset_converters import kitti_converter as kitti
  File "c:\users\lenovo\desktop\mmdetection3d\tools\dataset_converters\kitti_converter.py", line 10, in <module>
    from mmdet3d.structures import points_cam2img
  File "c:\users\lenovo\desktop\mmdetection3d\mmdet3d\structures\__init__.py", line 2, in <module>
    from .bbox_3d import (BaseInstance3DBoxes, Box3DMode, CameraInstance3DBoxes,
  File "c:\users\lenovo\desktop\mmdetection3d\mmdet3d\structures\bbox_3d\__init__.py", line 2, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "c:\users\lenovo\desktop\mmdetection3d\mmdet3d\structures\bbox_3d\base_box3d.py", line 8, in <module>
    from mmcv.ops import box_iou_rotated, points_in_boxes_all, points_in_boxes_part
  File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

### Reproduces the problem - error message

(deep_pytorch) PS D:\mmdetection3d> python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
Traceback (most recent call last):
  File "D:\mmdetection3d\tools\create_data.py", line 8, in <module>
    from tools.dataset_converters import kitti_converter as kitti
  File "c:\users\lenovo\desktop\mmdetection3d\tools\dataset_converters\kitti_converter.py", line 10, in <module>
    from mmdet3d.structures import points_cam2img
  File "c:\users\lenovo\desktop\mmdetection3d\mmdet3d\structures\__init__.py", line 2, in <module>
    from .bbox_3d import (BaseInstance3DBoxes, Box3DMode, CameraInstance3DBoxes,
  File "c:\users\lenovo\desktop\mmdetection3d\mmdet3d\structures\bbox_3d\__init__.py", line 2, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "c:\users\lenovo\desktop\mmdetection3d\mmdet3d\structures\bbox_3d\base_box3d.py", line 8, in <module>
    from mmcv.ops import box_iou_rotated, points_in_boxes_all, points_in_boxes_part
  File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

**Comment by studentyayaya** [comment]
我又来啦，我解决了这个问题，原因在于mmcv的问题，为啥是mmcv呢，是因为这几行代码，我参照了一篇博文发现的：
`File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\ops_init_.py", line 2, in
from .active_rotated_filter import active_rotated_filter
File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in
ext_module = ext_loader.load_ext(
File "D:\deep_learning\andconda3\envs\deep_pytorch\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
ext = importlib.import_module('mmcv.' + name)`
其中都是关于mmcv相关的内容，所以我推断mmcv可能是与我torch等相关库不兼容，现在mmcv官方文档好像只给出mmcv==2.2.0对应cuda、torch相关内容，我首先已经安装好的库全部删掉了，然后通过如下程序来重新安装兼容版本，并且cuda==11.8：
`pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0+cu118 --index-url https://download.pytorch.org/whl/cu118`
`pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1.0/index.html -i https://pypi.tuna.tsinghua.edu.cn/simple
`
