### ISSUE TITLE
Help! An Error when I want to output a result pkl package.

### ISSUE THREAD

**Issue by Huleyun** [open-mmlab/mmdetection3d#2946]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

CUDA 11.1
Pytorch 1.8.1
mmcv 1.7.0
mmdet 3.0.0 
mmdet3d master 
mmseg 1.0.0

### Reproduces the problem - code sample

The official BEVFusion code. It occurs when I want to obtain a visualization pkl package for test results.

### Reproduces the problem - command or script

python tools/test.py projects/BEVFusion/configs/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py check_points/BEVFusion/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d-5239b1af.pth --cfg-options test_evaluator.pklfile_prefix='result.pkl' --show --show-dir output/ --task 'multi-modality_det'

### Reproduces the problem - error message
Traceback (most recent call last):
  File "tools/test.py", line 149, in <module>
    main()
  File "tools/test.py", line 145, in main
    runner.test()
  File "/home/huleyun/PycharmProjects/MMDetection/venv/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1816, in test
    self._test_loop = self.build_test_loop(self._test_loop)  # type: ignore
  File "/home/huleyun/PycharmProjects/MMDetection/venv/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1611, in build_test_loop
    loop = TestLoop(
  File "/home/huleyun/PycharmProjects/MMDetection/venv/lib/python3.8/site-packages/mmengine/runner/loops.py", line 421, in __init__
    self.evaluator = runner.build_evaluator(evaluator)  # type: ignore
  File "/home/huleyun/PycharmProjects/MMDetection/venv/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1318, in build_evaluator
    return Evaluator(evaluator)  # type: ignore
  File "/home/huleyun/PycharmProjects/MMDetection/venv/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 25, in __init__
    self.metrics.append(METRICS.build(metric))
  File "/home/huleyun/PycharmProjects/MMDetection/venv/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/huleyun/PycharmProjects/MMDetection/venv/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'pklfile_prefix'

### Additional information

I want to obtain a result.pkl package not result pictures.

nuScenes-mini dataset used in this project.

**Comment by Huleyun** [comment]
The command was from [this site](https://mmdetection3d.readthedocs.io/en/latest/user_guides/train_test.html).

**Comment by abadithela** [comment]
Hi @Huleyun , any updates to this?

I'm also trying to save the prediction results to a pickle file but having trouble.
