### ISSUE TITLE
Docker Installation not working with example form website

### ISSUE THREAD

**Issue by SimonTUBS** [open-mmlab/mmdetection3d#2957]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: Quadro T2000
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.9.0
MMEngine: 0.10.3
MMDetection: 3.3.0
MMDetection3D: 1.4.0+962f093
spconv2.0: False

### Reproduces the problem - code sample

None

### Reproduces the problem - command or script

1. Build Docker Image with: 
``docker build -t mmdetection3d docker/ ``
2. Run Docker Image with:
``docker run --gpus all --shm-size=8g -it -v {DATA_DIR}:/mmdetection3d/data mmdetection3d``
3. Verify Installation with:
``mim download mmdet3d --config pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car --dest .``
and 
`python demo/pcd_demo.py demo/data/kitti/000008.bin pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth`

### Reproduces the problem - error message

Traceback (most recent call last):
  File "demo/pcd_demo.py", line 90, in <module>
    main()
  File "demo/pcd_demo.py", line 79, in main
    inferencer = LidarDet3DInferencer(**init_args)
  File "/mmdetection3d/mmdet3d/apis/inferencers/lidar_det3d_inferencer.py", line 65, in __init__
    palette=palette)
  File "/mmdetection3d/mmdet3d/apis/inferencers/base_3d_inferencer.py", line 73, in __init__
    model=model, weights=weights, device=device, scope=scope)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/infer/infer.py", line 183, in __init__
    self.visualizer = self._init_visualizer(cfg)
  File "/mmdetection3d/mmdet3d/apis/inferencers/base_3d_inferencer.py", line 143, in _init_visualizer
    visualizer = super()._init_visualizer(cfg)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/infer/infer.py", line 571, in _init_visualizer
    return VISUALIZERS.build(cfg.visualizer)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/registry.py", line 451, in get
    self.import_from_location()
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/registry.py", line 376, in import_from_location
    import_module(loc)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mmdetection3d/mmdet3d/visualization/__init__.py", line 2, in <module>
    from .local_visualizer import Det3DLocalVisualizer
  File "/mmdetection3d/mmdet3d/visualization/local_visualizer.py", line 30, in <module>
    from .vis_utils import (proj_camera_bbox3d_to_img, proj_depth_bbox3d_to_img,
  File "/mmdetection3d/mmdet3d/visualization/vis_utils.py", line 7, in <module>
    import trimesh
  File "/opt/conda/lib/python3.7/site-packages/trimesh/__init__.py", line 12, in <module>
    from . import (
  File "/opt/conda/lib/python3.7/site-packages/trimesh/boolean.py", line 10, in <module>
    from . import exceptions, interfaces
  File "/opt/conda/lib/python3.7/site-packages/trimesh/interfaces/__init__.py", line 1, in <module>
    from . import blender, gmsh
  File "/opt/conda/lib/python3.7/site-packages/trimesh/interfaces/blender.py", line 4, in <module>
    from .. import resources, util
  File "/opt/conda/lib/python3.7/site-packages/trimesh/resources/__init__.py", line 5, in <module>
    from ..typed import Dict, Stream
  File "/opt/conda/lib/python3.7/site-packages/trimesh/typed.py", line 16, in <module>
    from numpy.typing import ArrayLike, NDArray
ImportError: cannot import name 'NDArray' from 'numpy.typing' (/opt/conda/lib/python3.7/site-packages/numpy/typing/__init__.py)

### Additional information

1. Expectation: Installation with Docker and successful testing with given minimal example 
2. Wuspected problem: outdated dockerfile leading to incompatible versioning

**Comment by VeeranjaneyuluToka** [comment]
I think you need to upgrade/downgrade the numpy version.

**Comment by Jane-QinJ** [comment]
Encountered the same question.
Solved by upgrade the numpy version:
`pip install numpy --upgrade`
:smile:
