### ISSUE TITLE
AttributeError: 'LiDARPoints' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by colorfulandcjy0806** [open-mmlab/mmdetection3d#2987]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

When I was preprocessing the nuscense dataset, I encountered this issue. My environment (ubuntu20.04 cuda11.4) is capable of running the KITTI dataset and successfully running the code.

Traceback (most recent call last):
  File "tools/create_data.py", line 340, in <module>
    create_groundtruth_database('NuScenesDataset', args.root_path,
  File "/mnt/2206b677-3750-478c-b7c0-489c4f8ede41/cjy/mmdetection3d/tools/dataset_converters/create_gt_database.py", line 244, in create_groundtruth_database
    points = example['points'].numpy()
AttributeError: 'LiDARPoints' object has no attribute 'numpy'

### Reproduces the problem - code sample

python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes

### Reproduces the problem - command or script

python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes

### Reproduces the problem - error message

python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes

### Additional information

When I was preprocessing the nuscense dataset, I encountered this issue. My environment (ubuntu20.04 cuda11.4) is capable of running the KITTI dataset and successfully running the code.

**Comment by colorfulandcjy0806** [comment]
It should be an environmental issue. Today, I reinstalled the MMDetection3D environment (as described in the document) and ran it again
`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --only-gt-database`
Then we can handle it correctly😭
应该是环境的问题，我今天重新安装了MMDetection3D的环境（按照文档描述），重新运行
`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --only-gt-database`
后就可以正确处理了😭
