### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'data',  KeyError: 'data'

### ISSUE THREAD

**Issue by BaroRai** [open-mmlab/mmdetection3d#3008]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: win32
Python: 3.8.19 (default, Mar 20 2024, 19:55:45) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64
GCC: n/a
PyTorch: 2.0.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 193431937
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.15.0
OpenCV: 4.10.0
MMEngine: 0.10.4
MMDetection: 3.3.0
MMDetection3D: 1.4.0+962f093
spconv2.0: False

### Reproduces the problem - code sample

I used the built in methods in following field is command:

### Reproduces the problem - command or script

python ./tools/misc/visualize_results.py ./configs/_base_/datasets/kitti-3d-3class.py --result C:\Users\danie\AppData\Local\Temp\tmpyz7mcakv\results\pred_instances_3d.pkl --show-dir ./outputs/test

### Reproduces the problem - error message

Traceback (most recent call last):
  File "E:\Conda\envs\mmdet3d_env\lib\site-packages\mmengine\config\config.py", line 109, in __getattr__
    value = super().__getattr__(name)
  File "E:\Conda\envs\mmdet3d_env\lib\site-packages\addict\addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "E:\Conda\envs\mmdet3d_env\lib\site-packages\mmengine\config\config.py", line 138, in __getitem__
    return self.build_lazy(super().__getitem__(key))
  File "E:\Conda\envs\mmdet3d_env\lib\site-packages\mmengine\config\config.py", line 105, in __missing__
    raise KeyError(name)
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/misc/visualize_results.py", line 50, in <module>
    main()
  File "./tools/misc/visualize_results.py", line 30, in main
    cfg.data.test.test_mode = True
  File "E:\Conda\envs\mmdet3d_env\lib\site-packages\mmengine\config\config.py", line 1499, in __getattr__
    return getattr(self._cfg_dict, name)
  File "E:\Conda\envs\mmdet3d_env\lib\site-packages\mmengine\config\config.py", line 113, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'data'

### Additional information

I am using dataset kitty, but I have a problems with whole visualization procedure, also when I ran test on 3dssd model, I was not able to use atrribute --show to display whats happening.

**Comment by Gaviaa** [comment]
Hello, I have encountered the same problem. Have you solved it?

**Comment by DongmingMMM** [comment]
I also encountered the error. Did you solve it? Thanks!

**Comment by Vish19-code** [comment]
Hello, I have encountered the same problem. Have you solved it?

**Comment by BaroRai** [comment]
Hello, as I remember not all models have support for visualization on pictures or so..  some of them use only lidar data not whole dataset... It was long ago, but you must go trough config file and see how is the model configured, trained and what will be the output.

**Comment by Vish19-code** [comment]
Hello,

Thank you for the information

I am already train my model in mvxnet in mmdetection3d

And browser.py is work but problem in only visualisation is there any other
way to visualise my results?

Thank you

**Comment by BaroRai** [comment]
Honestly, I dont really know, I didnt use mmdetection almost 7 months now. But if its not very Secret, I am interested in your results.
