### ISSUE TITLE
Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by oreo-lp** [open-mmlab/mmdetection3d#301]
command i ran:
from mmdet3d.apis import init_detector, inference_detector

errors:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lupeng/pycharmProjects/mmdetection3d/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import inference_detector, init_detector, show_result_meshlab
  File "/home/lupeng/pycharmProjects/mmdetection3d/mmdet3d/apis/inference.py", line 8, in <module>
    from mmdet3d.core import Box3DMode, show_result
  File "/home/lupeng/pycharmProjects/mmdetection3d/mmdet3d/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/lupeng/pycharmProjects/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 1, in <module>
    from mmdet.core.anchor import build_anchor_generator
  File "/home/lupeng/pycharmProjects/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .mask import *  # noqa: F401, F403
  File "/home/lupeng/pycharmProjects/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/lupeng/pycharmProjects/mmdetection/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
  File "/home/lupeng/anaconda3/envs/mmdetection3d/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

my environment:
cuda=10.1
pytorch=1.7
numpy=1.19.5

**Comment by oreo-lp** [comment]
我的环境：
cuda == 10.1
但是，我修改了python的版本。
原來python的版本是python==3.7，但是現在我將其修改成python==3.6.1 (conda create -n open-mmdet3d python==3.6.1)
下載pytorch==1.6 (conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch)
安装mmcv==1.2.6
但是使用pycocotools的时候出现了找不到pycocotools模块的相关问题，解决办法是
(1) pip uninstall pycocotools
(2) pip install mmpycocotools
(3) pip uninstall mmpycocotools
(4) pip install mmpycocotools
参考：https://github.com/open-mmlab/mmdetection/issues/3761

**Comment by ktro2828** [comment]
I tried
```
pip uninstall pycocotools
pip uninstall mmpycocotools
pip install mmpycocotools
```
but it doesn't work...

__My environment__

- cuda=10.2
- Python==3.8
- torch==1.7.0
- mmcv-full==1.3.0
- mmdet==2.11.0
- mmdet3d==0.12.0
- mmpycocotools==12.0.3

can anyone help me??

**Comment by oreo-lp** [comment]
改一下环境试一试？试一下我提供的环境

**Comment by ktro2828** [comment]
I found that I got error with Python==3.8.8 although got no error with Python==3.6.9
