### ISSUE TITLE
[Bug] get_flops.py throws error for Pointpillars

### ISSUE THREAD

**Issue by cadip92** [open-mmlab/mmdetection3d#3028]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35) [GCC 12.3.0]
CUDA available: False
MUSA available: False
numpy_random_seed: 2147483648
GCC: gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2+cu117
OpenCV: 4.10.0
MMEngine: 0.10.4
MMDetection: 3.3.0
MMDetection3D: 1.4.0+962f093
spconv2.0: False

### Reproduces the problem - code sample

python tools/analysis_tools/get_flops.py configs/pointpillars/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d.py --modality point

### Reproduces the problem - command or script

python tools/analysis_tools/get_flops.py configs/pointpillars/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d.py --modality point

### Reproduces the problem - error message

  warnings.warn(
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 83, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 73, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/beegfs/chandorkar/miniforge3/envs/mmdet3d/lib/python3.8/site-packages/mmcv/cnn/utils/flops_counter.py", line 107, in get_model_complexity_info
    _ = flops_model(batch)
  File "/beegfs/chandorkar/miniforge3/envs/mmdet3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/beegfs/chandorkar/projects/mmdetection3d/mmdet3d/models/detectors/base.py", line 88, in forward
    return self._forward(inputs, data_samples, **kwargs)
TypeError: _forward() takes 1 positional argument but 3 were given

### Additional information

Seems like a bug in the code. I get the same error with the config file for kitti.
configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py

**Comment by GTing31** [comment]
@cadip92 same problem. Is there anyway to fix it?

**Comment by cadip92** [comment]
I solved this issue. The problem lies in the fact that get_flops activates _forward() function which is incorrectly implemented. To fix the issue, you must modify the `mvx_two_stage.py` file in mmdet3d>models>detectors. This can be added in the existing code:

```
from torch.nn import functional as F
from mmcv.ops import Voxelization
```

Then in the __init__() function, call the Voxelization function:

```
self.voxel_layer = Voxelization(
            voxel_size = [0.2, 0.2, 8], 
            point_cloud_range = [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0], 
            max_num_points = 20
            )
```
Now, define the _forward() and voxelize() method:

```
def _forward(self, 
                 batch_inputs_dict: dict,
                 points: Optional[List[Tensor]] = None,
                 img_feats: Optional[Sequence[Tensor]] = None,
                 batch_input_metas: Optional[List[dict]] = None
                 ) -> Sequence[Tensor]:

        voxels, num_points, coors = self.voxelize(batch_inputs_dict)
        voxel_features = self.pts_voxel_encoder(voxels,
                                                num_points,
                                                coors,
                                                img_feats,
                                                batch_input_metas)

        batch_size = coors[-1, 0] + 1
        x = self.pts_middle_encoder(voxel_features, coors,
                                    batch_size)

        x = self.pts_backbone(x)

        if self.with_pts_neck:
            x = self.pts_neck(x)

        return x

    @torch.no_grad()
    def voxelize(self, points):
        """Apply hard voxelization to points."""
        voxels, coors, num_points = [], [], []
        for res in points:
            res_voxels, res_coors, res_num_points = self.voxel_layer(res)
            voxels.append(res_voxels)
            coors.append(res_coors)
            num_points.append(res_num_points)
        
        voxels = torch.cat(voxels, dim=0)
        num_points = torch.cat(num_points, dim=0)
        coors_batch = []
        
        for i, coor in enumerate(coors):
            coor_pad = F.pad(coor, (1, 0), mode='constant', value=i)
            coors_batch.append(coor_pad)
        
        coors_batch = torch.cat(coors_batch, dim=0)
        return voxels, num_points, coors_batch
```

This worked for me and generated the FLOPs for PointPillars.
**P.S**.: This method works only to generate FLOPs for nuscenes dataset. Poinpillars uses MVXFasterRCNN as the detector for nuscenes. To fetch FLOPs for kitti dataset, you must modify the `voxelnet.py` detector.

**Comment by cadip92** [comment]
@ZwwWayne @Tai-Wang @ZCMax can you please make a permanent fix for this?

**Comment by hyperccc** [comment]
same problem.

**Comment by cadip92** [comment]
> same problem.

Please try modifying the `voxelnet.py` file as mentioned above.
