### ISSUE TITLE
[Bug] nuscenes评估报错

### ISSUE THREAD

**Issue by 2000lf** [open-mmlab/mmdetection3d#3037]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

System environment:
    sys.platform: linux
    Python: 3.8.19 (default, Mar 20 2024, 19:58:24) [GCC 11.2.0]
    CUDA available: True
    MUSA available: False
    numpy_random_seed: 1514969306
    GPU 0,1: NVIDIA A30
    CUDA_HOME: /home/shiying/luofan/CUDA/cuda11.8
    NVCC: Cuda compilation tools, release 11.8, V11.8.89
    GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
    PyTorch: 2.0.0+cu118
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.15.1+cu118
    OpenCV: 4.10.0
    MMEngine: 0.10.4

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 1514969306
    Distributed launcher: pytorch
    Distributed training: True
    GPU number: 1

### Reproduces the problem - code sample

1

### Reproduces the problem - command or script

bash tools/dist_train.sh projects/BEVFusion/configs/only_lidar.py 1

### Reproduces the problem - error message

Formating bboxes of pred_instances_3d
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 13.4 task/s, elapsed: 6s, ETA:     0s
Results writes to /tmp/tmpzqmyl7iy/results/pred_instances_3d/results_nusc.json
Evaluating bboxes of pred_instances_3d
Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner.train()
  File "/home/shiying/zjx/envs/anaconda3/envs/testmb1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/shiying/zjx/envs/anaconda3/envs/testmb1/lib/python3.8/site-packages/mmengine/runner/loops.py", line 103, in run
    self.runner.val_loop.run()
  File "/home/shiying/zjx/envs/anaconda3/envs/testmb1/lib/python3.8/site-packages/mmengine/runner/loops.py", line 376, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/home/shiying/zjx/envs/anaconda3/envs/testmb1/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/home/shiying/zjx/envs/anaconda3/envs/testmb1/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/home/shiying/luofan/Testmb/mmdet3d/evaluation/metrics/nuscenes_metric.py", line 177, in compute_metrics
    ap_dict = self.nus_evaluate(
  File "/home/shiying/luofan/Testmb/mmdet3d/evaluation/metrics/nuscenes_metric.py", line 207, in nus_evaluate
    ret_dict = self._evaluate_single(
  File "/home/shiying/luofan/Testmb/mmdet3d/evaluation/metrics/nuscenes_metric.py", line 233, in _evaluate_single
    nusc = NuScenes(
  File "/home/shiying/zjx/envs/anaconda3/envs/testmb1/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: data/nuscenes/v1.0-trainval

### Additional information

I use bevfusion to train nuscenes-mini ,when finish training,it failed to evaluate.

**Comment by wuhu-auto** [comment]
what wrong

**Comment by 2000lf** [comment]
> what wrong

Error happend when val after train v1.0-mini dataset

**Comment by sinianzuishuai** [comment]
> > what wrong
> 
> Error happend when val after train v1.0-mini dataset

Hello, have you solved it? I also encountered the same problem

**Comment by Solemn-Git** [comment]
me too!
