### ISSUE TITLE
Getting "CUDA error: an illegal memory access was encountered" on MVXNet

### ISSUE THREAD

**Issue by manonthegithub** [open-mmlab/mmdetection3d#336]
**Describe the bug**
Getting "CUDA error: an illegal memory access was encountered"

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py
```
2. What dataset did you use?
I have used custom dataset converted to kitti format. Training plain kitti dataset works, but with the custom dataset I am getting the error. I have regenerated infos for my dataset.

**Environment**
```
sys.platform: linux
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
CUDA available: True
GPU 0: TITAN X (Pascal)
CUDA_HOME: /home/kirilly/cuda10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0+cu101
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.1
MMDetection: 2.9.0
MMDetection3D: 0.10.0+ac9a3e8
```

**Error traceback**

```
2021-03-04 08:35:26,752 - mmdet - INFO - Epoch [1][50/8195]     lr: 4.323e-04, eta: 1 day, 22:41:33, time: 0.513, data_time: 0.052, memory: 4503, loss_cls: 1.1683, loss_bbox: 2.4333, loss_dir: 0.1463, loss: 3.7479, grad_norm: 113.1708
2021-03-04 08:35:49,141 - mmdet - INFO - Epoch [1][100/8195]    lr: 5.673e-04, eta: 1 day, 19:43:21, time: 0.448, data_time: 0.006, memory: 4523, loss_cls: 0.9347, loss_bbox: 2.0219, loss_dir: 0.1392, loss: 3.0958, grad_norm: 19.0356
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 274, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 54, in extract_pts_feat
    voxels, coors, points, img_feats, img_metas)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/voxel_encoders/voxel_encoder.py", line 244, in forward
    voxel_mean, mean_coors = self.cluster_scatter(features, coors)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 113, in forward
    points[inds], coors[inds][:, 1:])
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 92, in forward_single
    self.point_cloud_range)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 38, in forward
    coors_range)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7fc48ce74536 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x7fc48d0b7fbe in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7fc48ce64abd in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x522fe2 (0x7fc4d4054fe2 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x523086 (0x7fc4d4055086 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: python() [0x54f146]
frame #6: python() [0x588475]
frame #7: python() [0x572b20]
frame #8: python() [0x54ee4b]
frame #9: python() [0x54ee4b]
frame #10: python() [0x588948]
frame #11: python() [0x5ad418]
frame #12: python() [0x5ad42e]
frame #13: python() [0x5ad42e]
frame #14: python() [0x5ad42e]
frame #15: python() [0x5ad42e]
frame #16: python() [0x5ad42e]
frame #17: python() [0x5ad42e]
frame #18: python() [0x56b4c6]
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7fc4e5694bf7 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```

**Bug fix**
probably related to #135, but have no idea how to change the numbers for point cloud range etc

**Comment by manonthegithub** [comment]
I have tried to change voxel size (to [0.5, 0.5, 1.0]), and right after 1 epoch passed I got: 
```
2021-03-05 00:54:53,429 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>                             ] 770/1806, 10.9 task/s, elapsed: 71s, ETA:    95sTraceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/core/evaluation/eval_hooks.py", line 144, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 61, in forward
    return self.forward_test(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 42, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 405, in simple_test
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 52, in extract_pts_feat
    voxels, coors = self.voxelize(points)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 38, in voxelize
    res_coors = self.pts_voxel_layer(res)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 113, in forward
    self.max_num_points, max_voxels)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 43, in forward
    dynamic_voxelize(points, coors, voxel_size, coors_range, 3)
RuntimeError: CUDA error: invalid configuration argument
```

**Comment by Tai-Wang** [comment]
The first error maybe just `Out of Memory`, so you can reduce the batch size (samples_per_gpu) or change voxel size to have it work. For the error after changing the voxel size, have you changed other related parameters like [this feature map shape](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py#L49)?

**Comment by manonthegithub** [comment]
@Tai-Wang did not change any other parameters except voxel size. The batch size is already very small 2, I think no point to change it.

**Comment by manonthegithub** [comment]
@Tai-Wang I guess the second error is somehow connected to the voxel size as well... as I have changed only it

**Comment by Tai-Wang** [comment]
@manonthegithub You need to change other related parameters if you change the voxel size or detection range. In your case, I guess the shape should be [5, 160, 141].

**Comment by manonthegithub** [comment]
@Tai-Wang Thanks a lot! I will try.
 how di you calculate this? Is there any description of how to do, which params to change?

**Comment by Tai-Wang** [comment]
It is just a intermediate feature map. The shape is related to the spatial discretization based on voxelization. When the voxel size is scaled up, the map should be proportionally scaled down. Similarly, when the detection range is scaled up, the map should also be proportionally scaled up.

**Comment by manonthegithub** [comment]
@Tai-Wang Changing the feature map shape to what you suggested didn't help... getting this with it:
```
2021-03-05 18:42:50,643 - mmdet - INFO - workflow: [('train', 1)], max: 40 epochs
/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/fusion_layers/point_fusion.py:309: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  in img_meta.keys() else torch.eye(3).type_as(pts).to(pts.device))
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 274, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 56, in extract_pts_feat
    x = self.pts_middle_encoder(voxel_features, feature_coors, batch_size)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/middle_encoders/sparse_encoder.py", line 116, in forward
    x = encoder_layer(x)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/spconv/conv.py", line 168, in forward
    grid=input.grid)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/spconv/ops.py", line 94, in get_indice_pairs
    int(transpose))
RuntimeError: /home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/spconv/include/tensorview/helper_launch.h 17
N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0
```


And thank you for the help!

**Comment by Tai-Wang** [comment]
@manonthegithub I guess the feature map is so small that when downsampling it, one channel is down to 0. Your voxel size is also too large. I would suggest you use "just a little larger" voxel than the original or reduce the detection range without changing the voxel size to reduce the memory costs.

**Comment by Tai-Wang** [comment]
Feel free to reopen this issue if there is further question.

**Comment by manonthegithub** [comment]
@Tai-Wang changing any of the parameters didn't help. Feels like the issue is not about out of memory, but wrong indice or something like that.

I have set the detection range to about 10 times less than it was originally set, the change of voxel size doesn't work either.
I have added a println line in the right before the failing line:
```python 
print("points shape: " + str(points.shape) + "  coors: " + str(coors.shape) + "  voxel size: " + str(voxel_size) + " coors_range: " + str(coors_range))
results = dynamic_point_to_voxel_forward(points, coors, voxel_size,
                                                 coors_range)
```

the output when it fails (the same error as before)
```
points shape: torch.Size([3519, 64])  coors: torch.Size([3519, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3855, 64])  coors: torch.Size([3855, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3519, 128])  coors: torch.Size([3519, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3855, 128])  coors: torch.Size([3855, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4437, 4])  coors: torch.Size([4437, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4316, 4])  coors: torch.Size([4316, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4437, 64])  coors: torch.Size([4437, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4316, 64])  coors: torch.Size([4316, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4437, 128])  coors: torch.Size([4437, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4316, 128])  coors: torch.Size([4316, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4014, 4])  coors: torch.Size([4014, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4462, 4])  coors: torch.Size([4462, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4014, 64])  coors: torch.Size([4014, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4462, 64])  coors: torch.Size([4462, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4014, 128])  coors: torch.Size([4014, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4462, 128])  coors: torch.Size([4462, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4315, 4])  coors: torch.Size([4315, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([743, 4])  coors: torch.Size([743, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
.... stack trace as before
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 40, in forward
    coors_range)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
```

when I am training on the original Kitti dataset I get this output (and it doesn't fail):
```
points shape: torch.Size([18971, 4])  coors: torch.Size([18971, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18345, 64])  coors: torch.Size([18345, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18971, 64])  coors: torch.Size([18971, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18345, 128])  coors: torch.Size([18345, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18971, 128])  coors: torch.Size([18971, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16896, 4])  coors: torch.Size([16896, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18199, 4])  coors: torch.Size([18199, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16896, 64])  coors: torch.Size([16896, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18199, 64])  coors: torch.Size([18199, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16896, 128])  coors: torch.Size([16896, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18199, 128])  coors: torch.Size([18199, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([15517, 4])  coors: torch.Size([15517, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16629, 4])  coors: torch.Size([16629, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([15517, 64])  coors: torch.Size([15517, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16629, 64])  coors: torch.Size([16629, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([15517, 128])  coors: torch.Size([15517, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16629, 128])  coors: torch.Size([16629, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([20288, 4])  coors: torch.Size([20288, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17393, 4])  coors: torch.Size([17393, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([20288, 64])  coors: torch.Size([20288, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17393, 64])  coors: torch.Size([17393, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([20288, 128])  coors: torch.Size([20288, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17393, 128])  coors: torch.Size([17393, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18793, 4])  coors: torch.Size([18793, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17740, 4])  coors: torch.Size([17740, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18793, 64])  coors: torch.Size([18793, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17740, 64])  coors: torch.Size([17740, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18793, 128])  coors: torch.Size([18793, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17740, 128])  coors: torch.Size([17740, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
```

can you give any clue why it may happen? seems like some bug in `scatter_points.py`

**Comment by manonthegithub** [comment]
cant reopen creating a new one
