### ISSUE TITLE
'NoneType' object has no attribute 'point_size'

### ISSUE THREAD

**Issue by Sdy344** [open-mmlab/mmdetection3d#344]
(open-mmlab) sdy@E700-G4:~/mmdet3d/mmdetection3d$ python demo/pcd_demo.py demo/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
Use load_from_local loader
[Open3D WARNING] GLFW Error: GLX: GLX version 1.3 is required
[Open3D WARNING] Failed to create window
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 28, in <module>
    main()
  File "demo/pcd_demo.py", line 24, in main
    show_result_meshlab(data, result, args.out_dir)
  File "/home/sdy/mmdet3d/mmdetection3d/mmdet3d/apis/inference.py", line 114, in show_result_meshlab
    show_result(points, None, pred_bboxes, out_dir, file_name)
  File "/home/sdy/mmdet3d/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 85, in show_result
    vis = Visualizer(points)
  File "/home/sdy/mmdet3d/mmdetection3d/mmdet3d/core/visualizer/open3d_vis.py", line 469, in __init__
    points, self.o3d_visualizer, points_size, point_color, mode)
  File "/home/sdy/mmdet3d/mmdetection3d/mmdet3d/core/visualizer/open3d_vis.py", line 35, in _draw_points
    vis.get_render_option().point_size = points_size  # set points size
AttributeError: 'NoneType' object has no attribute 'point_size'

When I follow the official installation steps to verify, why this error？

**Comment by dihuangdh** [comment]
Try to use open3d==0.11

**Comment by Sdy344** [comment]
> Try to use open3d==0.11

(open-mmlab) sdy@E700-G4:~/mmdet3d/mmdetection3d$ python demo/pcd_demo.py demo/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
Use load_from_local loader
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 28, in <module>
    main()
  File "demo/pcd_demo.py", line 24, in main
    show_result_meshlab(data, result, args.out_dir)
  File "/home/sdy/mmdet3d/mmdetection3d/mmdet3d/apis/inference.py", line 114, in show_result_meshlab
    show_result(points, None, pred_bboxes, out_dir, file_name)
  File "/home/sdy/mmdet3d/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 82, in show_result
    from .open3d_vis import Visualizer
  File "/home/sdy/mmdet3d/mmdetection3d/mmdet3d/core/visualizer/open3d_vis.py", line 7, in <module>
    import open3d as o3d
  File "/home/sdy/.conda/envs/open-mmlab/lib/python3.7/site-packages/open3d/__init__.py", line 64, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/home/sdy/.conda/envs/open-mmlab/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc++.so.1: cannot open shared object file: No such file or directory

After the version of open3d is changed to 0.11, an error is reported

**Comment by Sdy344** [comment]
> Try to use open3d==0.11

**Comment by Sdy344** [comment]
> Try to use open3d==0.11

thank you

**Comment by rockywind** [comment]
When I install open3d==0.11, the error is bellow.
My environment is in ubuntu server.
` File "/workspace/mmdet3d/mmdetection3d_02/mmdet3d/core/visualizer/open3d_vis.py", line 364, in __init__
    self.o3d_visualizer.create_window()
RuntimeError: [Open3D ERROR] GLFW Error: X11: Failed to open display :1
`

**Comment by abadithela** [comment]
I get the same error as @rockywind. Has there been a solution to this?

**Comment by wangyakunn** [comment]
I meet an error as @rockywind when I run official code in docker.
