### ISSUE TITLE
Setup issues related to the scatter_points_cuda.cu file (after pull #326)

### ISSUE THREAD

**Issue by accelaire** [open-mmlab/mmdetection3d#346]
Hello mmdetection3d team! I really would like to use your framework which seems to be really usefull but I'm facing issues on the installation process.

**Describe the bug**
The bug happen when I'm arriving on the **last setup step of the getting_started.md file**. It totally fails the installation of mmdetection3d.

**Reproduction**
It's when running the command
```
pip install -v -e .  # or "python setup.py develop"
```
All the steps before actualy works well and I've respected all specifications of version compatibility between Cuda, PyTorch and mmcv.

**Environment**
Colab with GPU enabled. In fact, two weeks ago I've succefully run the inference_demo.py after installing all the packages and dependancies in the the Colab runtime. It's works and I was able to run the inference.
Since the pull #326 (https://github.com/open-mmlab/mmdetection3d/pull/326) it's no longer possible and the error traceback is related to the file **scatter_points_cuda.cu** (see below).

**Error traceback**

```
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-a56wZI/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-a56wZI/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.7m -c mmdet3d/ops/voxel/src/scatter_points_cpu.cpp -o build/temp.linux-x86_64-3.7/mmdet3d/ops/voxel/src/scatter_points_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=voxel_layer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    In file included from /usr/local/lib/python3.7/dist-packages/torch/include/ATen/Parallel.h:149:0,
                     from /usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                     from /usr/local/lib/python3.7/dist-packages/torch/include/torch/extension.h:4,
                     from mmdet3d/ops/voxel/src/scatter_points_cpu.cpp:2:
    /usr/local/lib/python3.7/dist-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)

    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/lib/python3.7/dist-packages/torch/include -I/usr/local/lib/python3.7/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/dist-packages/torch/include/TH -I/usr/local/lib/python3.7/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.7m -c mmdet3d/ops/voxel/src/scatter_points_cuda.cu -o build/temp.linux-x86_64-3.7/mmdet3d/ops/voxel/src/scatter_points_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=voxel_layer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    /usr/local/lib/python3.7/dist-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign

    /usr/local/lib/python3.7/dist-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(239): error: class "at::Tensor" has no member "max_values"

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: type name is not allowed

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: expected an expression

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: no instance of function template "coors_id_kernel" matches the argument list
                argument types are: (uint8_t *, <error-type>, int64_t *, const int, const int)

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: type name is not allowed

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: expected an expression

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: no instance of function template "coors_id_kernel" matches the argument list
                argument types are: (int8_t *, <error-type>, int64_t *, const int, const int)

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: type name is not allowed

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: expected an expression

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: no instance of function template "coors_id_kernel" matches the argument list
                argument types are: (int32_t *, <error-type>, int64_t *, const int, const int)

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: type name is not allowed

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: expected an expression

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: no instance of function template "coors_id_kernel" matches the argument list
                argument types are: (int64_t *, <error-type>, int64_t *, const int, const int)

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: type name is not allowed

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: expected an expression

    mmdet3d/ops/voxel/src/scatter_points_cuda.cu(246): error: no instance of function template "coors_id_kernel" matches the argument list
                argument types are: (int16_t *, <error-type>, int64_t *, const int, const int)

    16 errors detected in the compilation of "mmdet3d/ops/voxel/src/scatter_points_cuda.cu".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-h89kblfp'
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/mmdetection3d/setup.py'"'"'; __file__='"'"'/content/mmdetection3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/req/req_install.py", line 851, in install
    install_options, global_options, prefix=prefix,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/req/req_install.py", line 700, in install_editable
    cwd=self.unpacked_source_directory,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/mmdetection3d/setup.py'"'"'; __file__='"'"'/content/mmdetection3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Bug fix**

**Comment by accelaire** [comment]
Ok I found out that the version of PyTorch pre installed on Colab is 1.7.0+cu102 which is incompatible with the installed version of Cuda11.

**Comment by layssi** [comment]
Hwo was this fixed? I still get this error on 1.8.0+cuda-111

**Comment by accelaire** [comment]
It seems that the framework doesn't support some functions of Pytorch since 1.7.0.
So according to this https://pytorch.org/get-started/previous-versions/ you got to downgrade your Cuda version to 10.1 or 10.2 and then reinstall Pytorch 1.6.0+cu101 or 1.6.0+cu102. 
Cuda 10.1 is preferable since the Open3d lib was designed for Cuda 10.1.

**Comment by layssi** [comment]
First fix is removing "max_values" as it is not supporterd in pytorch 1.8
It is changed to "amax"
https://github.com/pytorch/pytorch/issues/44069

That leaves you with this error:
scatter_points_cuda.cu(274): error: no instance of overloaded function "at::Tensor::index_put_" matches the argument list
            argument types are: (at::Tensor, at::Tensor)
            object type is: at::Tensor
