### ISSUE TITLE
from mmdet.core import wrap_fp16_model

### ISSUE THREAD

**Issue by tangentninety** [open-mmlab/mmdetection3d#348]
ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' (/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/__init__.py)

Hi, I got this error when i try to run the test.py How can i fix this

**Comment by tangentninety** [comment]
I change mmdet from 2.10.0 to 2.7.0 and the error is now 
`(open-mmlab) fan@fan-MS-7B61:~/mmdetection3d$ python tools/test.py configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --eval mAP
Use load_from_local loader
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3769/3769, 25.6 task/s, elapsed: 147s, ETA:     0s
Converting prediction to KITTI format
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3769/3769, 1072.9 task/s, elapsed: 4s, ETA:     0s
Result is saved to /tmp/tmpcocjxd4a/results.pkl.
Traceback (most recent call last):
  File "tools/test.py", line 153, in <module>
    main()
  File "tools/test.py", line 149, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/home/fan/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 351, in evaluate
    self.CLASSES)
  File "/home/fan/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/eval.py", line 706, in kitti_eval
    eval_types)
  File "/home/fan/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/eval.py", line 613, in do_eval
    min_overlaps)
  File "/home/fan/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/eval.py", line 479, in eval_class
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
  File "/home/fan/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/eval.py", line 382, in calculate_iou_partly
    dt_boxes).astype(np.float64)
  File "/home/fan/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/eval.py", line 116, in bev_box_overlap
    from .rotate_iou import rotate_iou_gpu_eval
  File "/home/fan/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/rotate_iou.py", line 292, in <module>
    criterion=-1):
  File "/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numba/cuda/decorators.py", line 101, in kernel_jit
    kernel.bind()
  File "/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numba/cuda/compiler.py", line 548, in bind
    self._func.get()
  File "/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numba/cuda/compiler.py", line 426, in get
    ptx = self.ptx.get()
  File "/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numba/cuda/compiler.py", line 397, in get
    **self._extra_options)
  File "/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 496, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 233, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 251, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/home/fan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 141, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (66, 23): parse expec`

**Comment by filaPro** [comment]
`wrap_fp16_model` is moved from `mmcv.core` to `mmcv.runner`. Looks like it is fixed now in [8b131f5](https://github.com/open-mmlab/mmdetection3d/commit/8b131f52b16dfbbae93af0a39155da2817560a9b).

**Comment by Tai-Wang** [comment]
Hi @tangentninety , as mentioned by @filaPro , this import problem should have been fixed in mmcv/mmdet. Please check the version of mmcv and mmdet, and then recompile mmdet3d with the latest installed mmcv and mmdet. Otherwise, the old built/compiled files may trigger errors.

**Comment by Tai-Wang** [comment]
Feel free to reopen it if there is any further question.

**Comment by houyongkuo** [comment]
wrap_fp16_model is moved from mmcv.runner
