### ISSUE TITLE
Meet RuntimeError in mmdet3d/ops/spconv/src/indice_cuda.cu

### ISSUE THREAD

**Issue by happinesslz** [open-mmlab/mmdetection3d#37]
I also meet the same bugs  with [#21](https://github.com/open-mmlab/mmdetection3d/issues/21)

**Comment by Tai-Wang** [comment]
Please follow the template for "error report" to describe your issue. We need more information to debug.

BTW, the referenced issue is simply an "out of memory" error caused by adding codes unrelated to the codebase. You can check whether there is any possibility leading to this runtime error case.

**Comment by happinesslz** [comment]
@Tai-Wang  Thanks for your reply. 

**Describe the bug**
 I can only run the pointpillar successfully without spconv. Maybe the spconv causes the error. I also try to reduce the number of "samples_per_gpu" to 1, but still get the same error.  I run the code on Titan V+CUDA 10.1+pytorch=1.5.1/1.3.1+mmcv-full=1.0.3/1.0.2. 

**Reproduction**
Did you make any modifications on the code or config? Did you understand what you have modified?
No.

**Environment**
sys.platform: linux
Python: 3.7.6 (default, Jan 8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.168
GPU 0,1: TITAN V
GCC: gcc (GCC) 5.4.0
PyTorch: 1.5.1
PyTorch compiling details: PyTorch built with:

GCC 7.3
C++ Version: 201402
Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
OpenMP 201511 (a.k.a. OpenMP 4.5)
NNPACK is enabled
CPU capability usage: AVX2
CUDA Runtime 10.1
NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
CuDNN 7.6.3
Magma 2.5.2
Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
TorchVision: 0.6.0a0+35d732a
OpenCV: 4.3.0
MMCV: 1.0.2
MMDetection: 2.3.0rc0+3c21dd0
MMDetection3D: 0.5.0+unknown
MMDetection3D Compiler: GCC 5.4
MMDetection3D CUDA Compiler: 10.1

Error traceback
```
2020-07-23 09:57:07,433 - mmdet - INFO - Start running, host: zliu@1035, work_dir: /home/zliu/mmdetection3d_1035/work_dirs/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class
2020-07-23 09:57:07,433 - mmdet - INFO - workflow: [('train', 1)], max: 40 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 162, in main
    meta=meta)
  File "/home/zliu/mmdetection3d_1035/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zliu/anaconda3/envs/mmdetection3d/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zliu/anaconda3/envs/mmdetection3d/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/zliu/anaconda3/envs/mmdetection3d/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/zliu/mmdetection3d_1035/mmdetection/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/zliu/anaconda3/envs/mmdetection3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zliu/mmdetection3d_1035/mmdet3d/models/detectors/base.py", line 60, in forward
    return self.forward_train(**kwargs)
  File "/home/zliu/mmdetection3d_1035/mmdet3d/models/detectors/mvx_two_stage.py", line 266, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/zliu/mmdetection3d_1035/mmdet3d/models/detectors/mvx_two_stage.py", line 201, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/zliu/mmdetection3d_1035/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 54, in extract_pts_feat
    x = self.pts_middle_encoder(voxel_features, feature_coors, batch_size)
  File "/home/zliu/anaconda3/envs/mmdetection3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zliu/mmdetection3d_1035/mmdet3d/models/middle_encoders/sparse_encoder.py", line 97, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/zliu/anaconda3/envs/mmdetection3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zliu/mmdetection3d_1035/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/zliu/anaconda3/envs/mmdetection3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zliu/mmdetection3d_1035/mmdet3d/ops/spconv/conv.py", line 168, in forward
    grid=input.grid)
  File "/home/zliu/mmdetection3d_1035/mmdet3d/ops/spconv/ops.py", line 94, in get_indice_pairs
    int(transpose))
RuntimeError: /home/zliu/mmdetection3d_1035/mmdet3d/ops/spconv/src/indice_cuda.cu 124
cuda execution failed with error 2
```

**Comment by Tai-Wang** [comment]
I think there is no problems in the provided information. Could you please observe the CPU/GPU memory cost when running the code? Just to confirm it is an out of memory error. Also please tell us which config you are using.

**Comment by happinesslz** [comment]
@Tai-Wang 
The config file is dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py in configs/mvxnet.

I also observe the CPU/GPU memory cost  is normal, which just costs about 6G for GPU memory. Then this error occurred. I think 12G  GPU memory is enough for running the config.  I also  reduce the number of "samples_per_gpu" to 1, but still obtain the same error.

**Comment by Tai-Wang** [comment]
I have just checked this config, and it runs well on my 2080Ti with about 8.5G for GPU memory.

Maybe you can first check whether the code still takes up the memory after the error happens. Then please try other configs using spconv, like configs with hard voxelization hv_second_secfpn_6x8_80e_kitti-3d-3class.py in the configs/second.

**Comment by happinesslz** [comment]
Other configs with spconv will meet similar bugs. Can you provide your conda environment in details?  Thanks.

**Comment by Tai-Wang** [comment]
> Other configs with spconv will meet similar bugs. Can you provide your conda environment in details? Thanks.

You can refer to this [comment](https://github.com/open-mmlab/mmdetection3d/issues/21#issuecomment-659397799) for my environment. From my experience, cuda 10.0-10.2, pytorch 1.4.0-1.5.1, python 3.7 and gcc 5.4/5.5 should be ok.

**Comment by happinesslz** [comment]
Thanks, I will have a try on RTX2080Ti.

**Comment by niezhongliang** [comment]
> Thanks, I will have a try on RTX2080Ti.

Hi, I meet the same question with you, when I run pcd_demo.py in the server.  However, I tested it on my personal desktop, it could run. Have you solved it?

**Comment by WWW2323** [comment]
> Thanks, I will have a try on RTX2080Ti.

Hi, did you run this project on Titan V or 1080Ti before? I want to figure out if it is  caused by GPU  type, because i can run this project on 2080Ti, but fail on Titan V.
