### ISSUE TITLE
dynamic voxelization : RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by panfengsu** [open-mmlab/mmdetection3d#381]
environment： cuda11.0  pytorch:1.7.0  mmdetection3D:tag v0.10.0
I run "python ./tools/train.py ./configs/dynamic_voxelization/dv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py ", then get error "RuntimeError: CUDA error: invalid configuration argument".Can you give some suggestions on this issue？Thanks

Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 155, in main
    train_detector(
  File "/opt/conda/lib/python3.8/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/conda/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 89, in forward_train
    x = self.extract_feat(points, img_metas)
  File "/home/mmdetection3d/mmdet3d/models/detectors/dynamic_voxelnet.py", line 39, in extract_feat
    voxel_features, feature_coors = self.voxel_encoder(voxels, coors)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/mmdetection3d/mmdet3d/models/voxel_encoders/pillar_encoder.py", line 301, in forward
    voxel_feats, voxel_coors = self.pfn_scatter(point_feats, coors)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 112, in forward
    voxel, voxel_coor = self.forward_single(
  File "/home/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 90, in forward_single
    voxels, voxel_coors, num_points = dynamic_scatter(
  File "/home/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 37, in forward
    results = dynamic_point_to_voxel_forward(points, coors, voxel_size,
RuntimeError: CUDA error: invalid configuration argument

**Comment by Tai-Wang** [comment]
Please refer to #306 .

**Comment by Tai-Wang** [comment]
Close due to duplication.
