### ISSUE TITLE
Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by ktro2828** [open-mmlab/mmdetection3d#425]
I run  `tools/train.py`, then I got this error,

```
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmdet3d.datasets import build_dataset
  File "/home/leus/autoware/mmdetection3d/mmdet3d/datasets/__init__.py", line 1, in <module>
    from mmdet.datasets.builder import build_dataloader
  File "/home/leus/.local/share/virtualenvs/mmdetection3d-rnRHe6mf/lib/python3.8/site-packages/mmdet/datasets/__init__.py", line 2, in <module>
    from .cityscapes import CityscapesDataset
  File "/home/leus/.local/share/virtualenvs/mmdetection3d-rnRHe6mf/lib/python3.8/site-packages/mmdet/datasets/cityscapes.py", line 12, in <module>
    import pycocotools.mask as maskUtils
  File "/home/leus/.local/share/virtualenvs/mmdetection3d-rnRHe6mf/lib/python3.8/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
from this issue https://github.com/open-mmlab/mmdetection3d/issues/301, I tried
```
pip uninstall pycocotools
pip uninstall mmpycocotools
pip install mmpycocotools
```
but it doesn't work...

__My environment__

- cuda=10.2
- Python==3.8
- torch==1.7.0
- mmcv-full==1.3.0
- mmdet==2.11.0
- mmdet3d==0.12.0
- mmpycocotools==12.0.3

can anyone help me??

**Comment by ktro2828** [comment]
I found that I got error with Python==3.8.8 although got no error with Python==3.6.9

**Comment by ZhangYu1ing** [comment]
Did you get this error when you run tools/create_data.py?

**Comment by ktro2828** [comment]
Yes, I got this error with python3.8.8, when I run tools/create_data.py

**Comment by pigtigger** [comment]
i got this erro with python3.7 ,did you figure it out?
