### ISSUE TITLE
Eorr while building mmdet3d

### ISSUE THREAD

**Issue by Latha-13** [open-mmlab/mmdetection3d#544]
RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /home/shubham-k/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shubham-k/TSRevathi/AI/mmdetection3d-master/setup.py'"'"'; __file__='"'"'/home/shubham-k/TSRevathi/AI/mmdetection3d-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-qs6tpw5a'

I have correctly build the mmcv mmdet and mmsegmentation but still this error occurs can i have some solution to solve this issue. This error i got when im building the mmdetection3d in my local system. When i tried to build the mmdetection3d in google collab there was no error.

Thank you

**Comment by wHao-Wu** [comment]
Hi, @Latha-13 

Have you checked whether the cuda environment is compatible with pytorch version in your local system? Besides, can you provide more error information about compiling mmdet3d?

**Comment by Latha-13** [comment]
Running setup.py develop for mmdet3d
    Running command /home/shubham-k/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/setup.py'"'"'; __file__='"'"'/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    creating mmdet3d.egg-info
    writing mmdet3d.egg-info/PKG-INFO
    writing dependency_links to mmdet3d.egg-info/dependency_links.txt
    writing requirements to mmdet3d.egg-info/requires.txt
    writing top-level names to mmdet3d.egg-info/top_level.txt
    writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
    reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'mmdet3d/model_zoo.yml'
    warning: no files found matching '*.py' under directory 'mmdet3d/configs'
    warning: no files found matching '*.yml' under directory 'mmdet3d/configs'
    warning: no files found matching '*.sh' under directory 'mmdet3d/tools'
    warning: no files found matching '*.py' under directory 'mmdet3d/tools'
    warning: no files found matching '*.png' under directory 'mmdet3d/demo'
    warning: no files found matching '*.jpg' under directory 'mmdet3d/demo'
    warning: no files found matching '*.bin' under directory 'mmdet3d/demo'
    warning: no files found matching '*.pkl' under directory 'mmdet3d/demo'
    warning: no files found matching '*.py' under directory 'mmdet3d/demo'
    writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
    running build_ext
    building 'mmdet3d.ops.spconv.sparse_conv_ext' extension
    creating /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build
    creating /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7
    creating /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d
    creating /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops
    creating /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv
    creating /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src
    Emitting ninja build file /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/7] c++ -MMD -MF /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o.d -pthread -B /home/shubham-k/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
    FAILED: /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o
    c++ -MMD -MF /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o.d -pthread -B /home/shubham-k/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include/torch_utils.h:17:0,
                     from /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include/spconv/spconv_ops.h:22,
                     from /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/indice.cc:17:
    /home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: No such file or directory
     #include <cublas_v2.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    [2/7] c++ -MMD -MF /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o.d -pthread -B /home/shubham-k/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/all.cc -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
    FAILED: /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o
    c++ -MMD -MF /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o.d -pthread -B /home/shubham-k/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/all.cc -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include/torch_utils.h:17:0,
                     from /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include/spconv/fused_spconv_ops.h:22,
                     from /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/all.cc:16:
    /home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: No such file or directory
     #include <cublas_v2.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    [3/7] c++ -MMD -MF /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering.o.d -pthread -B /home/shubham-k/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/reordering.cc -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    [4/7] c++ -MMD -MF /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool.o.d -pthread -B /home/shubham-k/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/maxpool.cc -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    [5/7] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/reordering_cuda.cu -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61
    [6/7] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/indice_cuda.cu -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61
    [7/7] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shubham-k/anaconda3/envs/open-mmlab/include/python3.7m -c -c /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/mmdet3d/ops/spconv/src/maxpool_cuda.cu -o /home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
        env=env)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/setup.py", line 254, in <module>
        zip_safe=False)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
        build_ext.build_extensions(self)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /home/shubham-k/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/setup.py'"'"'; __file__='"'"'/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 400, in run
    pycompile=options.compile,
  File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 88, in install_given_reqs
    pycompile=pycompile,
  File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 774, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 258, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/shubham-k/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/setup.py'"'"'; __file__='"'"'/home/shubham-k/TSRevathi/AI/mmdetction-3D/mmdetection-2.11.0/mmdetection3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-2z57r6w4'


Yes i have installed 
pytorch==1.7.1 
torchvision==0.8.2
torchaudio==0.7.2 
cudatoolkit=10.1

**Comment by wHao-Wu** [comment]
According to your environment setting (pytorch, torchvision, cuda, etc), I have install the mmcv, mmdet, mmseg, mmdet3d successfully. So I wonder whether you have installed the mmdet3d once and want to reinstall the mmdet3d again in a different environment. If so, please refer to [instructions](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#install-mmdetection3d) to clear all the files in the `build/`

```shell
pip uninstall mmdet3d
rm -rf ./build
find . -name "*.so" | xargs rm
```
Then you can try to reinstall the mmdet and mmdet3d.

**Comment by Latha-13** [comment]
only when I tried to build mmdet3d this error occurs. I haven't installed mmdet3d once. I tried mmdetection that is up running in my local system. This mmdetection3d alone isn't working I have all the prequisities installed in my system this particular error occurs when I tired to execute the command
        git clone https://github.com/open-mmlab/mmdetection3d.git
        cd mmdetection3d
        pip install -v -e .

**Comment by Tai-Wang** [comment]
It seems that there is still something wrong or incompatible with your cuda related environment. The core error in your report is:
```
/home/shubham-k/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: No such file or directory
#include <cublas_v2.h>
^~~~~~~~~~~~~
compilation terminated.
```
Could you successfully build mmdet or mmcv-full (instead of mmcv-lite) from source? Please also double check the environment and run `python mmdet3d/utils/collect_env.py`  to provide more information about it.
