### ISSUE TITLE
package version conflict for tensorboard and others in CUDA10.2 CUDNN7.6.5 in installation

### ISSUE THREAD

**Issue by gujiaqivadin** [open-mmlab/mmdetection3d#560]
I follow the given markdown file to install mmdetection/mmsegmentation successfully. But  finally in  mmdetection3d, I run into some problems in the version of some packages. I also try to change my torch version to 1.5/1.7, but the same problem still occurs. 

**Reproduction**
1. What command or script did you run?

After I install mmdetection and mmsegmentation successfully, i ran the folloing script in mmdetection3d and got some problems. 
``` 
pip install -v -e .
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
kitti

**Environment**
The environment is cuda10.2 cudnn7.6.5 torch1.8.1 torchvision0.9.1, gcc5.4.0. The mmdetection2.11.0, mmsegmentation0.13.0, mmcv-full1.3.4.
Here is my installed packages after runnning ' pip list' :

```
Package            Version             Location
------------------ ------------------- ----------------------------------------
addict             2.4.0
certifi            2020.12.5
cycler             0.10.0
Cython             0.29.23
importlib-metadata 4.0.1
kiwisolver         1.3.1
matplotlib         3.4.2
mkl-fft            1.3.0
mkl-random         1.2.1
mkl-service        2.3.0
mmcv-full          1.3.4
mmdet              2.11.0              /home/xxx/project/mmdetection
mmpycocotools      12.0.3
mmsegmentation     0.13.0              /home//project/mmsegmentation
numpy              1.20.2
olefile            0.46
opencv-python      4.5.2.52
Pillow             8.2.0
pip                21.0.1
prettytable        2.1.0
pyparsing          2.4.7
python-dateutil    2.8.1
PyYAML             5.4.1
setuptools         52.0.0.post20210125
six                1.15.0
terminaltables     3.1.0
torch              1.8.1
torchvision        0.9.1
typing-extensions  3.7.4.3
wcwidth            0.2.5
wheel              0.36.2
yapf               0.31.0
zipp               3.4.1
```

**Error traceback**

```
Collecting scikit-image
  Created temporary directory: /tmp/pip-unpack-2j_gakcw
  http://pypi.doubanio.com:80 "GET /packages/fe/01/3a830f3df578ea3ed94ee7fd9f91e85c3dec2431d8548ab1c91869e51450/scikit_image-0.18.1-cp37-cp37m-manylinux1_x86_64.whl HTTP/1.1" 200 29198649
  Downloading http://pypi.doubanio.com/packages/fe/01/3a830f3df578ea3ed94ee7fd9f91e85c3dec2431d8548ab1c91869e51450/scikit_image-0.18.1-cp37-cp37m-manylinux1_x86_64.whl (29.2 MB)
     |████████████████████████████████| 29.2 MB 1.4 MB/s
  Added scikit-image from http://pypi.doubanio.com/packages/fe/01/3a830f3df578ea3ed94ee7fd9f91e85c3dec2431d8548ab1c91869e51450/scikit_image-0.18.1-cp37-cp37m-manylinux1_x86_64.whl#sha256=1256017c513e8e1b8b9da73e5fd1e605d0077bbbc8e5c8d6c2cab36400131c6c (from mmdet3d==0.13.0) to build tracker '/tmp/pip-req-tracker-77irv0tf'
  Removed scikit-image from http://pypi.doubanio.com/packages/fe/01/3a830f3df578ea3ed94ee7fd9f91e85c3dec2431d8548ab1c91869e51450/scikit_image-0.18.1-cp37-cp37m-manylinux1_x86_64.whl#sha256=1256017c513e8e1b8b9da73e5fd1e605d0077bbbc8e5c8d6c2cab36400131c6c (from mmdet3d==0.13.0) from build tracker '/tmp/pip-req-tracker-77irv0tf'
1 location(s) to search for versions of tensorboard:
* http://pypi.douban.com/simple/tensorboard/
Fetching project page and analyzing links: http://pypi.douban.com/simple/tensorboard/
Getting page http://pypi.douban.com/simple/tensorboard/
Found index url http://pypi.douban.com/simple
http://pypi.douban.com:80 "GET /simple/tensorboard/ HTTP/1.1" 200 1011
Given no hashes to check 0 links for project 'tensorboard': discarding no candidates
ERROR: Could not find a version that satisfies the requirement tensorboard (from mmdet3d)
ERROR: No matching distribution found for tensorboard
Exception information:
Traceback (most recent call last):
  File "/home/gujiaqi.gjq/anaconda3/envs/mmcv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/gujiaqi.gjq/anaconda3/envs/mmcv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/gujiaqi.gjq/anaconda3/envs/mmcv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 357, in resolve
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('tensorboard'), parent=EditableCandidate('file:///home/gujiaqi.gjq/project/mmdetection3d'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gujiaqi.gjq/anaconda3/envs/mmcv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/gujiaqi.gjq/anaconda3/envs/mmcv/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/gujiaqi.gjq/anaconda3/envs/mmcv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/gujiaqi.gjq/anaconda3/envs/mmcv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for tensorboard
Removed build tracker: '/tmp/pip-req-tracker-77irv0tf'

```

I also tried to install tensorboard use 'conda install' mannully, but new package version problem related to lyft sdk still occurs. 

```
The conflict is caused by:
    lyft-dataset-sdk 0.0.8 depends on tqdm>=4.25.0
    lyft-dataset-sdk 0.0.7 depends on tqdm>=4.25.0
    lyft-dataset-sdk 0.0.6 depends on tqdm>=4.25.0
    lyft-dataset-sdk 0.0.5 depends on tqdm>=4.25.0
    lyft-dataset-sdk 0.0.4 depends on tqdm>=4.25.0
    lyft-dataset-sdk 0.0.3 depends on tqdm>=4.25.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by THU17cyz** [comment]
Hi @gujiaqivadin , what is your python version? Can you refer to this [page](https://stackoverflow.com/questions/48720833/could-not-find-a-version-that-satisfies-the-requirement-tensorflow) and see if it's a conflict caused by the python version?

**Comment by gujiaqivadin** [comment]
And I tried python3.6, this conflict still existes. @THU17cyz @Tai-Wang Hhhhelp.

**Comment by Tai-Wang** [comment]
For your reference, my environment with cuda 10.2 has these related packages with the following versions:
```
lyft-dataset-sdk          0.0.8                    pypi_0    pypi
nuscenes-devkit           1.0.5                    pypi_0    pypi
pytorch                   1.5.0           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch
tensorboard               2.2.2                    pypi_0    pypi
tqdm                      4.47.0                   pypi_0    pypi
```
