### ISSUE TITLE
Training the lyft dataset error!

### ISSUE THREAD

**Issue by luoxiaoliaolan** [open-mmlab/mmdetection3d#561]
Hi !     
      First, according to the content prompted by this repo, I completed the configuration of the environment.
      Second,  I downloaded the lyft dataset，and used ‘tools/create_data.py’to preprocess this dataset. After preprocessing, I got several pkl files：lyft_infos_test.pkl、lyft_infos_train.pkl、lyft_infos_val.pkl and several json files: lyft_infos_train.coco.json、lyft_infos_val.coco.json.
     My training command is `python tools/train.py /home/lyb/DataServer/upload_tool/Project/mmdetection3d-master/configs/pointpillars/hv_pointpillars_fpn_sbn-all_2x8_2x_lyft-3d.py --work-dir /home/lyb/DataServer/upload_tool/Project/mmdetection3d-master/train_dir`
     When I try to use this framework to train the lyft dataset, I encountered this error：
`Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 218, in main
    meta=meta)
  File "/home/lyb/DataServer/upload_tool/Project/mmdetection3d-master/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/lyb/DataServer/upload_tool/Project/mmdetection-2.11.0/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lyb/Project/mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lyb/DataServer/upload_tool/Project/mmdetection3d-master/mmdet3d/datasets/custom_3d.py", line 378, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/lyb/DataServer/upload_tool/Project/mmdetection3d-master/mmdet3d/datasets/custom_3d.py", line 153, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/home/lyb/DataServer/upload_tool/Project/mmdetection-2.11.0/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/lyb/DataServer/upload_tool/Project/mmdetection3d-master/mmdet3d/datasets/pipelines/loading.py", line 409, in __call__
    points = points.reshape(-1, self.load_dim)
ValueError: cannot reshape array of size 265728 into shape (5)
`
    It's strange that the training process has been started for a while, and the training iteration has already started. I think it may be because of the feature dimension of a certain data loaded during the training process，but it is difficult for me to find which data has the problem.
  Could you tell me in more detail how to solve this problem?  I thought of using the “try....except..”  to avoid the termination of training due to this problem, but I am not sure where in the code should be used.
                   Looking forward to your reply, thank you very much！

**Comment by Tai-Wang** [comment]
That's a problem about the raw data provided by Lyft. We are just prepared to add a trouble shooting issue for it. Please refer to the PR #546 .

**Comment by Tai-Wang** [comment]
#546 has been merged, then you can refer to this [file](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/lyft_data_fixer.py) and new instructions about data preparation for Lyft in the [doc](https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html).

**Comment by luoxiaoliaolan** [comment]
Thanks a lot! I have resolved this problem. Looking forward to you posting more tutorials on mmdetection3D!
