### ISSUE TITLE
 cannot import name 'build' from 'mmdet.models.builder' 

### ISSUE THREAD

**Issue by selmadeac** [open-mmlab/mmdetection3d#562]
Hi! I get this error when I try to train a model.

Traceback (most recent call last):
  File "/home/selma/workspace/mmdetection3d/tools/train.py", line 17, in <module>
    from mmdet3d.models import build_detector
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/backbones/__init__.py", line 3, in <module>
    from .nostem_regnet import NoStemRegNet
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/backbones/nostem_regnet.py", line 2, in <module>
    from ..builder import BACKBONES
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/builder.py", line 3, in <module>
    from mmdet.models.builder import (BACKBONES, DETECTORS, HEADS, LOSSES, NECKS,
**ImportError: cannot import name 'build' from 'mmdet.models.builder' (/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/builder.py)**

my env is:
torchvision               0.9.0                
open3d                    0.12.0           
opencv-python             4.5.2.52         
mmcv-full                 1.3.4                  
mmdet                     2.12.0               
mmdet3d                   0.12.0                
mmsegmentation         0.13.0              
cudatoolkit 		11.1
numpy                     1.19.5 
python                    3.7.10 
pytorch                   1.8.0

**Comment by selmadeac** [comment]
Thank you for your response!

**Comment by selmadeac** [comment]
it worked!
