### ISSUE TITLE
resume-from and load-from (no load-from in tools/train.sh)

### ISSUE THREAD

**Issue by yaodongC** [open-mmlab/mmdetection3d#570]
Hi! In the official doc (/docs/1_exist_data_model.md), the difference between 'resume-from' and 'load-from' option is explained in detail. However, I did not find the '--load-from' option in the 'tools/train.py' file. And trying to use this option in 'tools/dist_train.sh'  as suggested in the doc results in failure as well. 
Could you please provide more detail on where '--load-from' option is used?

**Comment by Wuziyi616** [comment]
You can use `--cfg-options` to add some args that is not listed in `train.py` (see [here](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/train.py#58-L67)). An example is like:
```
python tools/train.py xxx --cfg-options "--load-from path/to/weight"
```
You can also add the `load_from` parameter in the config file you use. An example is [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/imvotenet/imvotenet_stage2_16x8_sunrgbd-3d-10class.py#L260).

**Comment by Joaovsky** [comment]
Hi there,

 python tools/train.py configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py --cfg-options 'load-from=home/mola/data/virtual_kitti_1_3_1/training/EXP2/mvx_iii_ep15/epoch_15.pth'
Traceback (most recent call last):
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value="'optimizer'", context=('\n', (2, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/lib2to3/pgen2/parse.py", line 162, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value="'optimizer'", context=('\n', (2, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 131, in ParseCodeToTree
    raise e
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 129, in ParseCodeToTree
    ast.parse(code)
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 2
    'optimizer': dict(
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 179, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump
    f.write(self.pretty_text)
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:2:1: invalid syntax

I got this error when trying to fine tune MVX model I pre-trained.

How did you solve this issue? Did you had it in the first place?

**Comment by Joaovsky** [comment]
done
