### ISSUE TITLE
KeyError: 'image_path'

### ISSUE THREAD

**Issue by Jsijon** [open-mmlab/mmdetection3d#59]
when i try to train with this command:
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py

i get the error bellow:

Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 155, in main
{'image_idx': '006740', 'image_shape': array([ 375, 1242], dtype=int32)}
    train_detector(
  File "/home/john/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/john/anaconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/john/anaconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/john/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/john/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/john/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/john/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/john/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/john/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/john/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/john/mmdetection/mmdet/datasets/dataset_wrappers.py", line 78, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/john/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 293, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/john/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 146, in prepare_train_data
    input_dict = self.get_data_info(index)
  File "/home/john/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 111, in get_data_info
    info['image']['image_path'])
KeyError: 'image_path'

**Comment by Tai-Wang** [comment]
Please follow the template for "error report" to describe your issue.

From the current error message, I think you can first check whether the procedure of generating info is successful. It seems that 'image_path' is not included in your info.

**Comment by Jsijon** [comment]
1. What command or script did you run?
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No

3. What dataset did you use?
Kitti

4. Enviroment information
 sys.platform: linux
Python: 3.8.3 (default, Jul  2 2020, 16:21:59) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce GTX 1650 SUPER
GCC: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.3.0
MMCV: 1.0.5
MMDetection: 2.3.0
MMDetection3D: 0.5.0+5f7b31c
MMDetection3D Compiler: GCC 9.3
MMDetection3D CUDA Compiler: 10.1

More information:
[image_path] key is not in the dictionary, 
i can't find where the info dictionary is created to investigate more, what happened.
Can't you locate for me in which py the dict info is created?

Thank you

**Comment by Tai-Wang** [comment]
You need to create data info at first for data loading. For more details, please refer to our [documentation](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#prepare-datasets), where you can see how to run create_data.py with several arguments when preparing info for different dataset.

**Comment by Jsijon** [comment]
it seems to work after creating data info. thanks

**Comment by Li-Whasaka** [comment]
> it seems to work after creating data info. thanks

Hi，How did you solve it?
