### ISSUE TITLE
MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#603]
**Notice**

There are several common situations in the reimplementation issues as below
1. Reimplement a model in the model zoo using the provided configs
2. Reimplement a model in the model zoo on other dataset (e.g., custom datasets)
3. Reimplement a custom model but all the components are implemented in MMDetection3D
4. Reimplement a custom model with new modules implemented by yourself

There are several things to do for different cases as below.
- For case 1 & 3, please follow the steps in the following sections thus we could help to quick identify the issue.
- For case 2 & 4, please understand that we are not able to do much help here because we usually do not know the full code and the users should be responsible to the code they write.
- One suggestion for case 2 & 4 is that the users should first check whether the bug lies in the self-implemted code or the original code. For example, users can first make sure that the same model runs well on supported datasets. If you still need help, please describe what you have done and what you obtain in the issue, and follow the steps in the following sections and try as clear as possible so that we can better help you.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The issue has not been fixed in the latest version.

**Describe the issue**

I want to train the second. But one GPU has not enough memory. I made an error using multiple GPUs for training.
2021-05-30 23:17:13,824 - mmdet - INFO - Start running, host: erkang@tg-platform-iaaas004.nullmax.lan, work_dir: /home/erkang/work/mmlab1/mmdetection3d/work_dirs/hv_second_secfpn_6x8_80e_kitti-3d-3class
2021-05-30 23:17:13,825 - mmdet - INFO - workflow: [('train', 1)], max: 40 epochs
Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 218, in main
    meta=meta)
  File "/home/erkang/work/mmlab1/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 55, in train_step
    ('MMDataParallel only supports single GPU training, if you need to'
AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

**Reproduction**
1. What command or script did you run?

```
python tools/train.py configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py --gpu-ids 6 7
```

2. What config dir you run?

```
configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
No
4. What dataset did you use?
kitti
**Environment**
1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
fatal: Not a git repository (or any of the parent directories): .git
sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.2
OpenCV: 4.5.2
MMCV: 1.3.5
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.11.0
MMSegmentation: 0.13.0
MMDetection3D: 0.13.0+
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Results**

If applicable, paste the related results here, e.g., what you expect and what you get.

```
A placeholder for results comparison
```

**Issue fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Wuziyi616** [comment]
Please use `tools/dist_train.py` for multi-gpu training. We provide script `tools/dist_train.sh` for easy usage. See our docs [here](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html#train-with-multiple-gpus).

**Comment by qfwysw** [comment]
2021-05-31 09:57:06,020 - mmdet - INFO - workflow: [('train', 1)], max: 40 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 222, in <module>
    main()
  File "./tools/train.py", line 218, in main
    meta=meta)
  File "/home/erkang/work/mmlab1/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 51, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/home/erkang/work/mmlab1/mmdetection3d/mmdet3d/models/detectors/base.py", line 58, in forward
    return self.forward_train(**kwargs)
  File "/home/erkang/work/mmlab1/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 89, in forward_train
    x = self.extract_feat(points, img_metas)
  File "/home/erkang/work/mmlab1/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 46, in extract_feat
    x = self.neck(x)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/home/erkang/work/mmlab1/mmdetection3d/mmdet3d/models/necks/second_fpn.py", line 89, in forward
    out = torch.cat(ups, dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 414.00 MiB (GPU 1; 10.76 GiB total capacity; 3.47 GiB already allocated; 371.44 MiB free; 3.58 GiB reserved in total by PyTorch)

**Comment by qfwysw** [comment]
I think one GPU can't load all the data, so even multiple GPUs can't train.
![image](https://user-images.githubusercontent.com/53482524/120129740-164a8f00-c1f7-11eb-8d74-92985945e6d6.png)

**Comment by qfwysw** [comment]
Traceback (most recent call last):
  File "./tools/train.py", line 222, in <module>
    main()
  File "./tools/train.py", line 218, in main
    meta=meta)
  File "/home/erkang/work/mmlab1/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 414.00 MiB (GPU 0; 10.76 GiB total capacity; 4.75 GiB already allocated; 265.44 MiB free; 5.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "./tools/train.py", line 222, in <module>
    main()
  File "./tools/train.py", line 218, in main
    meta=meta)
  File "/home/erkang/work/mmlab1/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 414.00 MiB (GPU 3; 10.76 GiB total capacity; 4.76 GiB already allocated; 255.44 MiB free; 5.32 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/erkang/miniconda3/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/erkang/miniconda3/envs/mmlab/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by Wuziyi616** [comment]
That's strange, because according to MVX-Net's [page](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/mvxnet/README.md), it only takes 6.7 GB memory per card. What command do you use? BTW, can you download our pre-trained weight to see if you can test it successfully (so that we can check if your environment is correct)?

**Comment by qfwysw** [comment]
I'm sorry for slow response. It's ok that I used the checkpoint. But I still fail to train the model.
The commend: CUDA_VISIBLE_DEVICES=6,7 PORT=29500 ./tools/dist_train.sh configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py 2
#####################################################################
(mmlab) erkang@tg-platform-iaaas004:~/work/mmlab1/mmdetection3d$ CUDA_VISIBLE_DEVICES=6,7 PORT=29500 ./tools/dist_test.sh configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py  hv_second_secfpn_6x8_80e_kitti-3d-3class_20200620_230238-9208083a.pth 2 --eval mAP
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Use load_from_local loader
Use load_from_local loader
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3770/3769, 30.6 task/s, elapsed: 123s, ETA:     0s
Converting prediction to KITTI format
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3769/3769, 372.1 task/s, elapsed: 10s, ETA:     0s
Result is saved to /tmp/tmp5jtsa8ih/results.pkl.

Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:69.7338, 63.9623, 60.5021
bev  AP:68.4904, 62.1143, 56.4856
3d   AP:63.6988, 58.3152, 52.4050
aos  AP:61.31, 56.29, 53.15
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:69.7338, 63.9623, 60.5021
bev  AP:78.5849, 76.4132, 70.6600
3d   AP:78.5821, 76.3980, 70.3593
aos  AP:61.31, 56.29, 53.15
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:84.1005, 73.6341, 71.7605
bev  AP:82.4623, 68.8043, 65.5102
3d   AP:79.2228, 64.9277, 60.6362
aos  AP:83.36, 71.87, 70.07
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:84.1005, 73.6341, 71.7605
bev  AP:84.2537, 72.3342, 69.8203
3d   AP:84.2347, 72.2970, 69.7915
aos  AP:83.36, 71.87, 70.07
Car AP@0.70, 0.70, 0.70:
bbox AP:98.1839, 89.7606, 88.7837
bev  AP:89.6905, 87.4570, 85.4865
3d   AP:87.4561, 76.7569, 74.1302
aos  AP:97.70, 88.73, 87.34
Car AP@0.70, 0.50, 0.50:
bbox AP:98.1839, 89.7606, 88.7837
bev  AP:98.4400, 90.1218, 89.6270
3d   AP:98.3329, 90.0209, 89.4035
aos  AP:97.70, 88.73, 87.34

Overall AP@easy, moderate, hard:
bbox AP:84.0061, 75.7857, 73.6821
bev  AP:80.2144, 72.7919, 69.1608
3d   AP:76.7926, 66.6666, 62.3905
aos  AP:80.79, 72.30, 70.19

{'KITTI/Pedestrian_3D_easy_strict': 63.69884152652578, 'KITTI/Pedestrian_BEV_easy_strict': 68.49040600922008, 'KITTI/Pedestrian_2D_easy_strict': 69.73381314342772, 'KITTI/Pedestrian_3D_moderate_strict': 58.31524381181663, 'KITTI/Pedestrian_BEV_moderate_strict': 62.11434516431644, 'KITTI/Pedestrian_2D_moderate_strict': 63.96234463025826, 'KITTI/Pedestrian_3D_hard_strict': 52.40502332844205, 'KITTI/Pedestrian_BEV_hard_strict': 56.48558260076981, 'KITTI/Pedestrian_2D_hard_strict': 60.50210782089006, 'KITTI/Pedestrian_3D_easy_loose': 78.58205826728224, 'KITTI/Pedestrian_BEV_easy_loose': 78.58486830459239, 'KITTI/Pedestrian_2D_easy_loose': 69.73381314342772, 'KITTI/Pedestrian_3D_moderate_loose': 76.39797609600035, 'KITTI/Pedestrian_BEV_moderate_loose': 76.4132081938468, 'KITTI/Pedestrian_2D_moderate_loose': 63.96234463025826, 'KITTI/Pedestrian_3D_hard_loose': 70.35929206132681, 'KITTI/Pedestrian_BEV_hard_loose': 70.6600459805845, 'KITTI/Pedestrian_2D_hard_loose': 60.50210782089006, 'KITTI/Cyclist_3D_easy_strict': 79.22280316336372, 'KITTI/Cyclist_BEV_easy_strict': 82.46232583724039, 'KITTI/Cyclist_2D_easy_strict': 84.10050176199667, 'KITTI/Cyclist_3D_moderate_strict': 64.92773820579798, 'KITTI/Cyclist_BEV_moderate_strict': 68.8043262822328, 'KITTI/Cyclist_2D_moderate_strict': 73.63413010634102, 'KITTI/Cyclist_3D_hard_strict': 60.63622320371695, 'KITTI/Cyclist_BEV_hard_strict': 65.51017345501509, 'KITTI/Cyclist_2D_hard_strict': 71.76048343850024, 'KITTI/Cyclist_3D_easy_loose': 84.23466934050089, 'KITTI/Cyclist_BEV_easy_loose': 84.25371542404314, 'KITTI/Cyclist_2D_easy_loose': 84.10050176199667, 'KITTI/Cyclist_3D_moderate_loose': 72.29697883600147, 'KITTI/Cyclist_BEV_moderate_loose': 72.33418805849016, 'KITTI/Cyclist_2D_moderate_loose': 73.63413010634102, 'KITTI/Cyclist_3D_hard_loose': 69.7914541040776, 'KITTI/Cyclist_BEV_hard_loose': 69.82031095964592, 'KITTI/Cyclist_2D_hard_loose': 71.76048343850024, 'KITTI/Car_3D_easy_strict': 87.45610724795893, 'KITTI/Car_BEV_easy_strict': 89.69046011671303, 'KITTI/Car_2D_easy_strict': 98.18389028596552, 'KITTI/Car_3D_moderate_strict': 76.75689210664453, 'KITTI/Car_BEV_moderate_strict': 87.45702960861706, 'KITTI/Car_2D_moderate_strict': 89.76058109581083, 'KITTI/Car_3D_hard_strict': 74.13015065869207, 'KITTI/Car_BEV_hard_strict': 85.4865455582404, 'KITTI/Car_2D_hard_strict': 88.78373491728972, 'KITTI/Car_3D_easy_loose': 98.33288257217502, 'KITTI/Car_BEV_easy_loose': 98.4400221898542, 'KITTI/Car_2D_easy_loose': 98.18389028596552, 'KITTI/Car_3D_moderate_loose': 90.02090501786836, 'KITTI/Car_BEV_moderate_loose': 90.12184507731126, 'KITTI/Car_2D_moderate_loose': 89.76058109581083, 'KITTI/Car_3D_hard_loose': 89.40349529357029, 'KITTI/Car_BEV_hard_loose': 89.62702775979791, 'KITTI/Car_2D_hard_loose': 88.78373491728972, 'KITTI/Overall_3D_easy': 76.79258397928281, 'KITTI/Overall_BEV_easy': 80.21439732105783, 'KITTI/Overall_2D_easy': 84.00606839712997, 'KITTI/Overall_3D_moderate': 66.66662470808637, 'KITTI/Overall_BEV_moderate': 72.7919003517221, 'KITTI/Overall_2D_moderate': 75.78568527747004, 'KITTI/Overall_3D_hard': 62.39046573028369, 'KITTI/Overall_BEV_hard': 69.1607672046751, 'KITTI/Overall_2D_hard': 73.68210872556001}

**Comment by Wuziyi616** [comment]
I tried with your command and everything works well on Titan XP GPU, which is 1GB larger than 2080Ti. That may be the problem. Can you try lowering the batch size to 5 and have a try? Simple add `data = dict(samples_per_gpu=5)` in the config file will do this.

**Comment by qfwysw** [comment]
Thanks for your help. It works!

**Comment by Wuziyi616** [comment]
Glad it helps. But I would like to point out that, training with smaller batch size and less number of GPUs will make the model performance worse. You can consider using the linear learning rate scaling strategy. For example, if our config is `6x8` (batch_size x num_GPUs) and you use `5x2`, you may need to divide the lr by 4. Just a small suggestion :)

**Comment by qfwysw** [comment]
Thank you for your reminding. I will pay attention to this problem.
