### ISSUE TITLE
Training Pointpillars on Waymo dataset

### ISSUE THREAD

**Issue by selmadeac** [open-mmlab/mmdetection3d#613]
Hi!

I have successfully converted Waymo dataset format to kitti format.
I am trying to train pointpillars on waymo using the following command:
```
python ./tools/train.py ./configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car.py
--work-dir
./tmp
--gpu-ids
0
```

However I get the following error:
2021-06-02 17:40:16,307 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
[libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 3.8.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-py2-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.8.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-py2-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)

Also, I have noticed that inside the config file, there is only model settings and no dataset settings so I appended inside the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car.py the code from file waymoD5-3d-car.py.
If I do not do this, nothing happends.

**Comment by Tai-Wang** [comment]
We have added the dataset config by inheriting the `waymoD5-3d-car.py` [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car.py#L3). Please see more details about the config system in our [tutorial](https://mmdetection3d.readthedocs.io/en/latest/tutorials/config.html).

**Comment by selmadeac** [comment]
Ohh, thank you for your reply! I have deleted my modifications. I understand the usage of the config files better now. However, the error:
what(): This program was compiled against version 3.8.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.0). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "bazel-out/k8-py2-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
Is still occurring...

**Comment by selmadeac** [comment]
I have reinstalled the framework and installed protobuf 3.8.0. The previous error was solved. However new problems emerge. 
```

Traceback (most recent call last):
  File "./tools/train.py", line 222, in <module>
    main()
  File "./tools/train.py", line 218, in main
    meta=meta)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/detectors/base.py", line 58, in forward
    return self.forward_train(**kwargs)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 273, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 207, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 196, in extract_pts_feat
    img_feats, img_metas)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 182, in new_func
    return old_func(*args, **kwargs)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/voxel_encoders/voxel_encoder.py", line 444, in forward
    voxel_feats = vfe(voxel_feats)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/models/voxel_encoders/utils.py", line 86, in forward
    x = self.norm(x.permute(0, 2, 1).contiguous()).permute(0, 2,
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 182, in new_func
    return old_func(*args, **kwargs)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/ops/norm.py", line 57, in forward
    if dist.get_world_size() == 1 or not self.training:
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 711, in get_world_size
    return _get_group_size(group)
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 263, in _get_group_size
    default_pg = _get_default_group()
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.


```

**Comment by Wuziyi616** [comment]
You need to use dist_train because MVX-Net uses SyncBN. Please refer to `tools/dist_train.py` for distributed training. (You can do so even if you only have one GPU)

**Comment by selmadeac** [comment]
Thank you very much! it works now!
