### ISSUE TITLE
Occasionally evaluation error during training

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmdetection3d#674]
Hi, I am training mmdet3d on a docker machine. However, I met this problem occasionally, and sometimes, it runs normally. I have no idea why this happens, could you help me with this problem?
```
2021-06-24 15:05:30,889 - mmdet - INFO - Saving checkpoint at 15 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3776/3769, 106.3 task/s, elapsed: 36s, ETA:     0sTraceback (most recent call last):
  File "./tools/train.py", line 204, in <module>
    main()
  File "./tools/train.py", line 200, in main
    meta=meta)
  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 276, in after_train_epoch
    gpu_collect=self.gpu_collect)
  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/mmdet/apis/test.py", line 113, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/mmdet/apis/test.py", line 156, in collect_results_cpu
    shutil.rmtree(tmpdir)
  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/shutil.py", line 498, in rmtree
    onerror(os.rmdir, path, sys.exc_info())  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/shutil.py", line 496, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/nfs/chenzehui/code/2d3d_fusion/work_dirs/voxel_dynamic_kitti/.eval_hook'
Traceback (most recent call last):
  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()  File "/nfs/chenzehui/others/miniconda3/envs/mmdet3d/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main    cmd=cmd)
subprocess.CalledProcessError: Command '['/nfs/chenzehui/others/miniconda3/envs/mmdet3d/bin/python', '-u', './tools/train.py', '--local_rank=7', 'voxel_cfg/voxel_dynamic_kitti.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Comment by Dinghow** [comment]
dddd

**Comment by Tai-Wang** [comment]
What's your training setting? How many samples per gpu and how many gpus are used? I guess there is something wrong with the evaluation hook, so you can also create an issue in mmdetection and ask some help from the community.

**Comment by zehuichen123** [comment]
This problem is related to my dev-machine, not mmdet3d code. Sorry for the bother, I will close this issue.
