### ISSUE TITLE
An error occurred while creating Scannetv2 data

### ISSUE THREAD

**Issue by xiaobaishu0097** [open-mmlab/mmdetection3d#676]
@Wuziyi616  I am trying to create the Scannet dataset as required, but an error occurred when I operate ```python tools/create_data.py scannet --root-path ./data/scannet --out-dir ./data/scannet --extra-tag scannet```. Here is the error message:
```
scannet info test file is saved to ./data/scannet/scannet_infos_test.pkl
Traceback (most recent call last):
  File "tools/create_data.py", line 300, in <module>
    workers=args.workers)
  File "tools/create_data.py", line 134, in scannet_data_prep
    root_path, info_prefix, out_dir, workers=workers)
  File "/scratch1/du014/Auxiliary_Code/mmdetection3d/tools/data_converter/indoor_converter.py", line 87, in create_indoor_info_file
    train_dataset.get_seg_infos()
  File "/scratch1/du014/Auxiliary_Code/mmdetection3d/tools/data_converter/scannet_data_utils.py", line 204, in get_seg_infos
    scene_idxs, label_weight = self.get_scene_idxs_and_label_weight()
  File "/scratch1/du014/Auxiliary_Code/mmdetection3d/tools/data_converter/scannet_data_utils.py", line 247, in get_scene_idxs_and_label_weight
    scene_idxs.extend([idx] * round(sample_prob[idx] * num_iter))
TypeError: can't multiply sequence by non-int of type 'numpy.float64'
```

My environment:
- cuda 10.2
- python 3.6
- mmcv-full 1.3.7
- mmdet 2.11.0
- mmdet3d 0.14.0
- mmsegmentation 0.14.0
- numpy 1.18.0

Can anyone help me????

**Comment by Wuziyi616** [comment]
It's very strange because `round()` should convert the value to `int`. Maybe you can change it to `scene_idxs.extend([idx] * int(round(sample_prob[idx] * num_iter)))` and have a try?

**Comment by filaPro** [comment]
Hi @Wuziyi616,
I'm also meeting this bug. The thing is `type(round(np.float64)) == np.float64`. Should we reopen this and fix?

**Comment by Wuziyi616** [comment]
Yes of course! Can you kindly fix it in a one line PR? Thanks!
