### ISSUE TITLE
"an illegal memory access was encountered" in SparseConv.

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection3d#679]
**Describe the bug**
I build a simple model with DynamicVFE and SparseEncoder as follows:
``` 
# A simplified forward function.

# mmdet3d.ops.voxel.voxelize, max_points = -1
points, coords = self.voxelize(points_list)

# DynamicVFE
voxel_feature, voxel_coords = self.voxel_encoder(points, coords)

# SparseEncoder in mmdet3d/models/middle_encoders/sparse_encoder.py
inst_feature_map = self.sparse_encoder(voxel_feature, voxel_coords, len(points_list)) 
```
The params is 
```
        class VoxelEncoder:
            last_voxel_feat_dim = 128
            init_params = dict(
                 in_channels=3,
                 feat_channels=[64, 64, last_voxel_feat_dim],
                 with_distance=False,
                 with_cluster_center=True,
                 with_voxel_center=True,
                 voxel_size=(0.2, 0.2, 0.5),
                 point_cloud_range=(-20, -20, -3, 20, 20, 3),
                 norm_params= {'eps':1e-4, 'momentum':0.01},
                 mode='max',
                 return_point_feats=False
            )

        class SparseEncoder:
            init_params = dict(
                 in_channels=128,
                 sparse_shape=[10, 512, 512],
                 order=('conv', 'norm', 'act'),
                 norm_cfg=dict(type='BN1d', eps=1e-3, momentum=0.01),
                 base_channels=16,
                 output_channels=64,
                 encoder_channels=((16, ), (32, 32, 32), (64, 64, 64), (64, 64,
                                                                        64)),
                 encoder_paddings=((1, ), (1, 1, 1), (1, 1, 1), ((0, 1, 1), 1,
                                                                 1)),
                 block_type='conv_module'
            )
```
And I got following error:
**Error traceback**

```
Traceback (most recent call last):
  File "scripts/train.py", line 53, in <module>
    train(parse_args())
  File "scripts/train.py", line 38, in train
    train_model(model, optimizer, loader, sampler, lr_scheduler, cfg, logger)
  File "Det-torch/rangedetr/utils/training_utils.py", line 58, in train_model
    loss_dict, output_dict = model(input_dict)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "Det-torch/rangedetr/models/sparse_detector.py", line 27, in forward
    output = self.get_loss(input_dict)
  File "Det-torch/rangedetr/models/sparse_detector.py", line 34, in get_loss
    output = self.get_network_output(input_dict)
  File "Det-torch/rangedetr/models/sparse_detector.py", line 66, in get_network_output
    inst_feature_map = self.sparse_encoder(voxel_feature, voxel_coords, len(points_list))
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "Det-torch/rangedetr/models/sparse_encoder.py", line 134, in forward
    x = self.conv_input(input_sp_tensor)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "mmdetection3d/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "mmdetection3d/mmdet3d/ops/spconv/conv.py", line 186, in forward
    outids.shape[0])
  File "mmdetection3d/mmdet3d/ops/spconv/functional.py", line 65, in forward
    indice_pair_num, num_activate_out, False, True)
  File "mmdetection3d/mmdet3d/ops/spconv/ops.py", line 119, in indice_conv
    int(subm))
RuntimeError: CUDA error: an illegal memory access was encountered (copy_kernel_cuda at /pytorch/aten/src/ATen/native/cuda/Copy.cu:180)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f40cc796193 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x56e3912 (0x7f40d24d4912 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x1a2a41d (0x7f40ce81b41d in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x1a266ff (0x7f40ce8176ff in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #4: at::native::copy_(at::Tensor&, at::Tensor const&, bool) + 0x3e (0x7f40ce819bee in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x436ecb8 (0x7f40d115fcb8 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x199af9d (0x7f40ce78bf9d in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x1cb836d (0x7f40ceaa936d in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #8: at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool, c10::optional<c10::MemoryFormat>) + 0x245 (0x7f40ceaaa6f5 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #9: <unknown function> + 0x1ffdb9a (0x7f40cedeeb9a in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #10: <unknown function> + 0x3ce3866 (0x7f40d0ad4866 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #11: <unknown function> + 0x20485e2 (0x7f40cee395e2 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #12: <unknown function> + 0x215fe (0x7f40b08605fe in mmdetection3d/mmdet3d/ops/spconv/sparse_conv_ext.cpython-36m-x86_64-linux-gnu.so)
frame #13: at::Tensor spconv::indiceConv<float>(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long, long, long) + 0x18a (0x7f40b087df6a in mmdetection3d/mmdet3d/ops/spconv/sparse_conv_ext.cpython-36m-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x504ff (0x7f40b088f4ff in mmdetection3d/mmdet3d/ops/spconv/sparse_conv_ext.cpython-36m-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x5076e (0x7f40b088f76e in mmdetection3d/mmdet3d/ops/spconv/sparse_conv_ext.cpython-36m-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x4e050 (0x7f40b088d050 in mmdetection3d/mmdet3d/ops/spconv/sparse_conv_ext.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #27: THPFunction_apply(_object*, _object*) + 0xa8f (0x7f4117d7a82f in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch_python.so)



```
Even though I set `shuffle = False` in data sampler, this error seems still non-deterministic.

**Environment**
sys.platform: linux
Python: 3.6.8 (default, Jul  2 2019, 13:27:03) [GCC 5.4.0 20160609]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.1.0
MMCV: 1.2.7
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.0
MMDetection: 2.10.0
MMDetection3D: 0.11.0+
@Tai-Wang

**Comment by Tai-Wang** [comment]
Please refer to this [comment](https://github.com/open-mmlab/mmdetection3d/issues/382#issuecomment-810831507) for the way to compute the `sparse_shape`.
