### ISSUE TITLE
Making an MVXNet Nuscenes config

### ISSUE THREAD

**Issue by abdelrahman-osama** [open-mmlab/mmdetection3d#684]
I am experiencing the following error after modifying the config file for mvx to work on Nuscenes dataset:

`Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 218, in main
    meta=meta)
  File "/home/abdelrahman/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/abdelrahman/mmdetection3d/mmdet3d/models/detectors/base.py", line 58, in forward
    return self.forward_train(**kwargs)
  File "/home/abdelrahman/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 279, in forward_train
    gt_bboxes_ignore)
  File "/home/abdelrahman/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 316, in forward_pts_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/abdelrahman/mmdetection3d/mmdet3d/models/dense_heads/shape_aware_head.py", line 341, in loss
    num_total_samples=num_total_samples)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/abdelrahman/mmdetection3d/mmdet3d/models/dense_heads/shape_aware_head.py", line 248, in loss_single
    bbox_targets = bbox_targets.reshape(-1, self.box_code_size)
RuntimeError: shape '[-1, 7]' is invalid for input of size 1843200`

Any idea what would be the problem?

**Comment by abdelrahman-osama** [comment]
I solved the issue by adding the code size as an input parameter to the bbox coder: 
`bbox_coder=dict(type='DeltaXYZWLHRBBoxCoder', code_size=9),`

Set it to 9 if you're using NuScenes, its default value is 7 for Kitti
