### ISSUE TITLE
MVXNet on Nuscenes Evaluation Error

### ISSUE THREAD

**Issue by abdelrahman-osama** [open-mmlab/mmdetection3d#693]
I get the following error in the evaluation set on my modified config file of MVXNet for NuScenes:

2021-07-01 02:29:53,169 - mmdet - INFO - Epoch [1][28050/28130] lr: 3.000e-03, eta: 6 days, 6:12:25, time: 0.474, data_time: 0.005, memory: 4176, loss_cls: 0.0000, loss_bbox: 0.0000, loss_dir: 0.0000, loss: 0.0000, grad_norm: 0.0000
2021-07-01 02:30:17,652 - mmdet - INFO - Epoch [1][28100/28130] lr: 3.000e-03, eta: 6 days, 6:11:54, time: 0.490, data_time: 0.005, memory: 4176, loss_cls: 0.0566, loss_bbox: 0.0832, loss_dir: 0.0001, loss: 0.1399, grad_norm: 0.3583
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 5.4 task/s, elapsed: 1117s, ETA:     0s
Formating bboxes of pts_bbox
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 7938.6 task/s, elapsed: 1s, ETA:     0ss
Results writes to /tmp/tmplpqijguy/results/pts_bbox/results_nusc.json
Evaluating bboxes of pts_bbox
Evaluation Parameters: <nuscenes.nuscenes.NuScenes object at 0x7f3fcc50f610> <nuscenes.eval.detection.data_classes.DetectionConfig object at 0x7f3fc155a710> /tmp/tmplpqijguy/results/pts_bbox/results_nusc.json val /tmp/tmplpqijguy/results/pts_bbox
Traceback (most recent call last):
  File "tools/train.py", line 222, in <module>
    main()
  File "tools/train.py", line 218, in main
    meta=meta)
  File "/home/abdelrahman/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 147, in after_train_epoch
    key_score = self.evaluate(runner, results)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 177, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/abdelrahman/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 515, in evaluate
    ret_dict = self._evaluate_single(result_files[name])
  File "/home/abdelrahman/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 412, in _evaluate_single
    verbose=False)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/nuscenes/eval/detection/evaluate.py", line 94, in __init__
    self.pred_boxes = filter_eval_boxes(nusc, self.pred_boxes, self.cfg.class_range, verbose=verbose)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/nuscenes/eval/common/loaders.py", line 219, in filter_eval_boxes
    class_field = _get_box_class_field(eval_boxes)
  File "/home/abdelrahman/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/nuscenes/eval/common/loaders.py", line 283, in _get_box_class_field
    raise Exception('Error: Invalid box type: %s' % box)
Exception: Error: Invalid box type: None

Any idea where would be the problem?

**Comment by Tai-Wang** [comment]
It seems your loss is unexpectedly low, and thus possibly your output can be strange (there is no reasonable boxes). You can check this problem by setting breakpoints when evaluation to have a look at the outputs and further check the training settings (like the data infos, batch size and learning rates).

**Comment by abdelrahman-osama** [comment]
I figured out the problem. The order of classes in the class_names array was not aligned with the anchor_list order.

**Comment by drilistbox** [comment]
> I figured out the problem. The order of classes in the class_names array was not aligned with the anchor_list order.

Hi, I encounter the same problem above. Where did you change to make the program right?

**Comment by Joaovsky** [comment]
Hey, I'm trying to run MVXnet on nuscenes dataset. I set code_size=9 and replaced the dataset settings that were adequate to kitti so that they could be compatible with nuscenes instead, as well as the the training test,evaluation pipeline and data dictionary. However, I still have this problem when training MVXnet on nuscenes: AssertionError: channel size mismatch.

Can you show me your modified config of MVXnet nuscenes-compatible?

**Comment by pradi-02** [comment]
> I figured out the problem. The order of classes in the class_names array was not aligned with the anchor_list order.

I am also encountering the same problem above. Could you please tell us where the change was made?

**Comment by pradi-02** [comment]
> > I figured out the problem. The order of classes in the class_names array was not aligned with the anchor_list order.
> 
> I am also encountering the same problem above. Could you please tell us where the change was made?

Changed the function _get_box_class_field()
By commenting out the exception and commenting class_field = 'detection_name' instead.
The type of the box is the same but it isnt recognized.
