### ISSUE TITLE
when I compile mmdet3d with "pip install -v -e .", got an error like this

### ISSUE THREAD

**Issue by s1mpleee** [open-mmlab/mmdetection3d#763]
```
    RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /home/adas/anaconda3/envs/mm/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/media/adas/ubuntu3/open-mmlab/mmdetection3d/setup.py'"'"'; __file__='"'"'/media/adas/ubuntu3/open-mmlab/mmdetection3d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/adas/anaconda3/envs/mm/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/adas/anaconda3/envs/mm/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/adas/anaconda3/envs/mm/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 402, in run
    pycompile=options.compile,
  File "/home/adas/anaconda3/envs/mm/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 85, in install_given_reqs
    pycompile=pycompile,
  File "/home/adas/anaconda3/envs/mm/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 773, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/adas/anaconda3/envs/mm/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 46, in install_editable
    cwd=unpacked_source_directory,
  File "/home/adas/anaconda3/envs/mm/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/adas/anaconda3/envs/mm/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/media/adas/ubuntu3/open-mmlab/mmdetection3d/setup.py'"'"'; __file__='"'"'/media/adas/ubuntu3/open-mmlab/mmdetection3d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-fmag9_t2'

```

**Comment by s1mpleee** [comment]
by the way, I can't compile mmcv from source, so I use "pip install mmcv-full" instead,is that problem related to this error

**Comment by Roywangj** [comment]
excuse, i have met the same error.  may i ask how do you solve this issue? Thank you!
