### ISSUE TITLE
I have problem with create_data.py

### ISSUE THREAD

**Issue by mqm-slice** [open-mmlab/mmdetection3d#772]
(open-mmlab) warcraft@warcraft-MS-7A94:/datasets/mqmdatasets/projects/mmdetection3d$ python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
Traceback (most recent call last):
  File "tools/create_data.py", line 5, in <module>
    from tools.data_converter import kitti_converter as kitti
  File "/datasets/mqmdatasets/projects/mmdetection3d/tools/data_converter/kitti_converter.py", line 7, in <module>
    from mmdet3d.core.bbox import box_np_ops
  File "/datasets/mqmdatasets/projects/mmdetection3d/mmdet3d/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/datasets/mqmdatasets/projects/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 1, in <module>
    from mmdet.core.anchor import build_anchor_generator
  File "/home/warcraft/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/__init__.py", line 4, in <module>
    from .mask import *  # noqa: F401, F403
  File "/home/warcraft/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/warcraft/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
  File "/home/warcraft/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

I have reinstall the vitural environment several times 

there is some key packages 

(open-mmlab) warcraft@warcraft-MS-7A94:/datasets/mqmdatasets/projects/mmdetection3d$ conda list numpy
c# packages in environment at /home/warcraft/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
numpy                     1.18.0                   pypi_0    pypi
(open-mmlab) warcraft@warcraft-MS-7A94:/datasets/mqmdatasets/projects/mmdetection3d$ conda list numba
# packages in environment at /home/warcraft/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
numba                     0.48.0                   pypi_0    pypi
(open-mmlab) warcraft@warcraft-MS-7A94:/datasets/mqmdatasets/projects/mmdetection3d$ conda list mmdet
# packages in environment at /home/warcraft/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
mmdet                     2.14.0                   pypi_0    pypi
mmdet3d                   0.15.0                    dev_0    <develop>
(open-mmlab) warcraft@warcraft-MS-7A94:/datasets/mqmdatasets/projects/mmdetection3d$ conda list mmcv
# packages in environment at /home/warcraft/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
mmcv-full                 1.3.8                    pypi_0    pypi

**Comment by filaPro** [comment]
You can probably follow these 2 [lines](https://github.com/open-mmlab/mmdetection3d/blob/master/docker/Dockerfile#L29-L30) and replace `pycocotools` with `mmpycocotools`. `Dockerfile` is for sure valid right now.

**Comment by Wuziyi616** [comment]
The newest version of MMDet3D now supports `pycocotools` instead of `mmpycocotools`, we may need to update Dockerfile. @mqm-slice you can try uninstalling `mmpycocotools` and then downgrade `pycocotools` to `2.0.1`?
