### ISSUE TITLE
The error incurred when running test.py in centepoint.

### ISSUE THREAD

**Issue by rockywind** [open-mmlab/mmdetection3d#781]
The error is below.
`Use load_from_local loader
[                                                  ] 0/6019, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 214, in <module>
    main()
  File "tools/test.py", line 184, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/apis/test.py", line 38, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/models/detectors/base.py", line 60, in forward
    return self.forward_test(**kwargs)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/models/detectors/base.py", line 41, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 404, in simple_test
    points, img=img, img_metas=img_metas)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 207, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/models/detectors/centerpoint.py", line 43, in extract_pts_feat
    x = self.pts_middle_encoder(voxel_features, coors, batch_size)
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/models/middle_encoders/sparse_encoder.py", line 112, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/CN/zizhang.wu/anaconda3/envs/mm_imvoxelnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/ops/spconv/conv.py", line 168, in forward
    grid=input.grid)
  File "/newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/ops/spconv/ops.py", line 94, in get_indice_pairs
    int(transpose))
RuntimeError: /newnfs/zzwu/08_3d_code/mmdetection3d/mmdet3d/ops/spconv/src/indice_cuda.cu 124
cuda execution failed with error 2
`

**Comment by Wuziyi616** [comment]
Hummm, very strange. Are you sure you have compiled mmdet3d correctly? Can you successfully run some of our demo?

**Comment by Tai-Wang** [comment]
Close due to inactivity.
