### ISSUE TITLE
RuntimeError: CUDA error: invalid device function 段错误 (核心已转储)

### ISSUE THREAD

**Issue by scar-on** [open-mmlab/mmdetection3d#789]
**The following error occurred while running demo**
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 41, in <module>
    main()
  File "demo/pcd_demo.py", line 28, in main
    result, data = inference_detector(model, args.pcd)
  File "/home/cdutzj/scar/mmdetection3d/mmdet3d/apis/inference.py", line 115, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/base.py", line 60, in forward
    return self.forward_test(**kwargs)
  File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/base.py", line 41, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 99, in simple_test
    x = self.extract_feat(points, img_metas)
  File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 41, in extract_feat
    voxels, num_points, coors = self.voxelize(points)
  File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 56, in voxelize
    res_voxels, res_coors, res_num_points = self.voxel_layer(res)
  File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cdutzj/scar/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 113, in forward
    self.max_num_points, max_voxels)
  File "/home/cdutzj/scar/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 53, in forward
    coors_range, max_points, max_voxels, 3)
RuntimeError: CUDA error: invalid device function
段错误 (核心已转储)
**My compilation environment is**
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.5.0
TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.5.3
MMCV: 1.3.9
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.0
MMDetection: 2.14.0
MMSegmentation: 0.15.0
MMDetection3D: 0.15.0+1b2e64c
**My mailbox**
（1597763078@qq.com）

**Comment by Wuziyi616** [comment]
Humm, very strange. Can you successfully run other demos? Such as the VoteNet one described in the demo docs?

**Comment by Tai-Wang** [comment]
Close due to inactivity.
