### ISSUE TITLE
RuntimeError: mmdet3d/ops/spconv/src/indice_cuda.cu 124

### ISSUE THREAD

**Issue by BeyondXie** [open-mmlab/mmdetection3d#929]
When I tried the demo, some problems arose,I tried many times to reinstall mmdet3d but it still had this problem.

/home/y202729/tools/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmdet/core/anchor/builder.py:16: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 44, in <module>
    main()
  File "demo/pcd_demo.py", line 31, in main
    result, data = inference_detector(model, args.pcd)
  File "/home/y202729/mmdetection3d/mmdet3d/apis/inference.py", line 116, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/home/y202729/tools/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y202729/tools/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/y202729/mmdetection3d/mmdet3d/models/detectors/base.py", line 61, in forward
    return self.forward_test(**kwargs)
  File "/home/y202729/mmdetection3d/mmdet3d/models/detectors/base.py", line 42, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/home/y202729/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 100, in simple_test
    x = self.extract_feat(points, img_metas)
  File "/home/y202729/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 45, in extract_feat
    x = self.middle_encoder(voxel_features, coors, batch_size)
  File "/home/y202729/tools/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y202729/tools/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/y202729/mmdetection3d/mmdet3d/models/middle_encoders/sparse_encoder.py", line 113, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/y202729/tools/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y202729/mmdetection3d/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/y202729/tools/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y202729/mmdetection3d/mmdet3d/ops/spconv/conv.py", line 168, in forward
    grid=input.grid)
  File "/home/y202729/mmdetection3d/mmdet3d/ops/spconv/ops.py", line 94, in get_indice_pairs
    int(transpose))
RuntimeError: mmdet3d/ops/spconv/src/indice_cuda.cu 124
cuda execution failed with error 2

**Comment by Tai-Wang** [comment]
Please refer to #21 and #37 for possible solutions. Please follow the template for "error report" to redescribe your issue if necessary.
