### ISSUE TITLE
load images from six cameras and stack them

### ISSUE THREAD

**Issue by DFLyan** [open-mmlab/mmdetection3d#936]
Based on the config of FCOS3D, I want to use all six cameras' RGB images of dataset “nuscenes”  as the input of the network.  Then, I just simply use the "LoadMultiViewImageFromFiles" or "LoadMultiChannelImageFromFiles" instead of "LoadImageFromFileMono3D" in the pipeline, but it doesn't work. There are several errors. Which stage should I change or rewrite? In the load of the pipeline or create_data.py in the data preparation, or other functions? Thanks!

**Comment by ZwwWayne** [comment]
Could you use the `error template` to post details of your errors?

**Comment by DFLyan** [comment]
> Could you use the `error template` to post details of your errors?

When I use the function "LoadMultiViewImageFromFiles", the error is:

Traceback (most recent call last):
  File "./tools/train.py", line 224, in <module>
    main()
  File "./tools/train.py", line 220, in main
    meta=meta)
  File "/data1/jwchen/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/data1/jwchen/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 44, in __call__
    filename = results['img_filename']
KeyError: 'img_filename'

Traceback (most recent call last):
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/data1/jwchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/data1/jwchen/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/fvd/fvd.py', '--launcher', 'pytorch', '--work-dir', 'fvd']' returned non-zero exit status 1.

\
I debug the code and find that the filename in the result is only one. 
![image](https://user-images.githubusercontent.com/27199157/133634416-56e8cfe2-058a-49c5-83b7-fe52cdf7d145.png)

So there will be no two or more images stacked. It may be caused when converting the formate of the dataset "nuscenes" into coco.json, I think. The convert function now is likely just for the monocular 3D object detection. I mean, for multiview RGB inputs, the construction of coco.json may need to be changed slightly.
Or any other advice from you. Thanks!

**Comment by tojimahammatov** [comment]
@DFLyan  hello. I guess you can probably refer to [this issue](https://github.com/open-mmlab/mmdetection3d/pull/611). I have also faced this problem before and solved on my own similar as above link.
