### ISSUE TITLE
cuda error 9 in spconv/src/reordering_cuda.cu with larger batch size

### ISSUE THREAD

**Issue by flaxsh** [open-mmlab/mmdetection3d#945]
**Describe the bug**
When running training with larger batch sizes execution crashes in 
/mmdetection3d/mmdet3d/ops/spconv/src/reordering_cuda.cu with "cuda errror 9" and no further information given.
Works with batch size <=6 but crashes with >=8.
From nvidia-smi it doesn't seem like the GPU is out of memory: "```GPU( 24271MiB / 32510MiB)) ```"

I what steps could I take to debug this issue? What could cause this error?
Thanks in advance!

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/path/to/my/config.py  --work-dir /foo```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes; Yes
3. What dataset did you use?
NuScenes

**Environment**
Environment is based on the nvidia-pytorch container: nvcr.io/nvidia/pytorch:21.02-py3
```
sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29373293_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.8.0a0+52ea372
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.2
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.1
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.2, CUDNN_VERSION=8.1.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0a0
OpenCV: 4.4.0
MMCV: 1.3.7
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: not available
MMDetection: 2.11.0
MMSegmentation: 0.13.0
MMDetection3D: 0.14.0+
```

**Error traceback**
```
Traceback (most recent call last):
  File "tools/train.py", line 235, in <module>
    main(parse_args())
  File "tools/train.py", line 223, in main
    train_model(
  File "/mmdetection3d/mmdet3d/apis/train.py", line 43, in train_model
    raise exception
  File "/opt/conda/lib/python3.8/site-packages/mmdet/apis/train.py", line 171, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/conda/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 51, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 126, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/mmdetection3d/mmdet3d/models/detectors/centerpoint_sequential.py", line 99, in forward
    pts_feats = self.extract_pts_feat(points)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 126, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/mmdetection3d/mmdet3d/models/detectors/centerpoint.py", line 43, in extract_pts_feat
    x = self.pts_middle_encoder(voxel_features, coors, batch_size)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 126, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/mmdetection3d/mmdet3d/models/middle_encoders/sparse_encoder.py", line 112, in forward
    x = self.conv_input(input_sp_tensor)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmdetection3d/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmdetection3d/mmdet3d/ops/spconv/conv.py", line 186, in forward
    out_features = Fsp.indice_subm_conv(features, weight,
  File "/mmdetection3d/mmdet3d/ops/spconv/functional.py", line 64, in forward
    return ops.indice_conv(features, filters, indice_pairs,
  File "/mmdetection3d/mmdet3d/ops/spconv/ops.py", line 120, in indice_conv
    return sparse_conv_ext.indice_conv_half(features, filters,
RuntimeError: /mmdetection3d/mmdet3d/ops/spconv/src/reordering_cuda.cu 114
cuda execution failed with error 9
```

**Comment by Tai-Wang** [comment]
What config do you use? Please show the specific related settings.

**Comment by DeppMeng** [comment]
Exact the same issue. I use one Tesla A100 GPU with 80G memory. It works fine with batch-size 16 but the error occurs with batch-size 24. The GPU memory at that time is about 60G.

**Comment by HuangDihe** [comment]
Exact the same issue. I use one Tesla V100 GPU with 32G memory.  The error occurs when the number of voxels is large.
