### ISSUE TITLE
Out of memory when running model.cuda()

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection3d#947]
I got a strange problem when training SECOND and PointPillars:
```
Traceback (most recent call last):
  File "tools/train.py", line 243, in <module>
    main()
  File "tools/train.py", line 227, in main
    meta=meta)
  File "mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mmdet/apis/train.py", line 79, in train_detector
    model.cuda(),
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
```
The OOM error is raised when moving the model to GPU (model.cuda()). There is no GPU resources competition.
Since I use the standard training config, it is impossible to produce such a model large enough to consume ~11 GB of memory.
The issue seems related to the running environment, because it disappears after switching to another server (with the same image).
Though it is solved, I have no idea for the real reasons. I can't understand it at all.
Does anyone know the reasons?

**Comment by Tai-Wang** [comment]
Please provide more information following the issue template for reimplementation and also your used config. The current cues are far not enough for us to help you find the reason.

**Comment by Abyssaledge** [comment]
@Tai-Wang Thanks for reply. I find this issue is not related to MMDetection3D. A simple code snippet can reproduce this error.
```
>>> import torch
>>> torch.rand(1).cuda(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
>>> torch.rand(1).cuda(1)
tensor([0.7275], device='cuda:1')
``` 
It seems that this issue is not related to MMDetection3D, so I close this issue. You are definitely welcome to comment on [this strange problem](https://discuss.pytorch.org/t/out-of-memory-when-running-model-cuda/132480).
